#define ID                               1
#define COMMA                            2
#define EQUALS                           3
#define LPAREN                           4
#define RPAREN                           5
#define NULLVAL                          6
#define OPEN                             7
#define XCLOSE                           8
#define XCREATE                          9
#define INSERT_TUPLE                    10
#define XDECLARE                        11
#define INDEX                           12
#define ON                              13
#define USING                           14
#define XBUILD                          15
#define INDICES                         16
#define UNIQUE                          17
#define XTOAST                          18
#define OBJ_ID                          19
#define XBOOTSTRAP                      20
#define XSHARED_RELATION                21
#define XROWTYPE_OID                    22
#define XFORCE                          23
#define XNOT                            24
#define XNULL                           25
