var topics =
[
    [ "Conflict Types", "group__conflict__types.html", "group__conflict__types" ],
    [ "Conflict Set", "group__conflict__set.html", "group__conflict__set" ],
    [ "Conflict Detection", "group__conflict__detect.html", "group__conflict__detect" ],
    [ "Multi-Grammar Conflict Detection", "group__multi__grammar.html", "group__multi__grammar" ],
    [ "ConflictPoint Lifecycle", "group__conflict__point__api.html", "group__conflict__point__api" ],
    [ "MultiGrammarConflictResult Lifecycle", "group__multi__conflict__result.html", "group__multi__conflict__result" ],
    [ "Multi-Grammar Conflict Detection API", "group__multi__detect__api.html", "group__multi__detect__api" ],
    [ "Strategy Identifiers", "group__strat__ids.html", "group__strat__ids" ],
    [ "Strategy Result", "group__strat__result.html", "group__strat__result" ],
    [ "Strategy VTable", "group__strat__vtable.html", "group__strat__vtable" ],
    [ "Disambiguation Context", "group__disambig__ctx.html", "group__disambig__ctx" ],
    [ "Disambiguation API", "group__disambig__api.html", "group__disambig__api" ],
    [ "Grammar Extension Metadata (Execution)", "group__exec__ext__meta.html", "group__exec__ext__meta" ],
    [ "Execution Policy Enum", "group__exec__policy__enum.html", "group__exec__policy__enum" ],
    [ "Execution Result", "group__exec__result.html", "group__exec__result" ],
    [ "Parser Handle", "group__exec__parser__handle.html", "group__exec__parser__handle" ],
    [ "Parser Execution Callback", "group__exec__callback.html", "group__exec__callback" ],
    [ "Execution Policy Configuration", "group__exec__config.html", "group__exec__config" ],
    [ "Execution Policy API", "group__exec__api.html", "group__exec__api" ],
    [ "Disambiguation Strategies", "group__disambig__strategy.html", "group__disambig__strategy" ],
    [ "Execution Policies", "group__exec__policy.html", "group__exec__policy" ],
    [ "Oracle Callback", "group__oracle__cb.html", "group__oracle__cb" ],
    [ "Extension Metadata", "group__ext__metadata.html", "group__ext__metadata" ],
    [ "Registry Handle", "group__registry__handle.html", "group__registry__handle" ],
    [ "Topological Order Result", "group__ext__order.html", "group__ext__order" ],
    [ "Registry API", "group__registry__api.html", "group__registry__api" ],
    [ "Grammar Modes", "group__grammar__modes.html", "group__grammar__modes" ],
    [ "Context Entry", "group__ctx__entry.html", "group__ctx__entry" ],
    [ "Mode Registration", "group__mode__info.html", "group__mode__info" ],
    [ "Context Stack Handle", "group__ctx__stack.html", "group__ctx__stack" ],
    [ "Context Switch Callback", "group__ctx__switch__cb.html", "group__ctx__switch__cb" ],
    [ "Grammar Context API", "group__grammar__ctx__api.html", "group__grammar__ctx__api" ],
    [ "Snapshot API", "group__snapshot__api.html", "group__snapshot__api" ],
    [ "Parse Context API", "group__parse__ctx__api.html", "group__parse__ctx__api" ],
    [ "JIT Compilation API", "group__jit__api.html", "group__jit__api" ],
    [ "Extension Initialization API", "group__ext__init.html", "group__ext__init" ],
    [ "Fork Status", "group__fork__status.html", "group__fork__status" ],
    [ "Cloned Parser State", "group__cloned__state.html", "group__cloned__state" ],
    [ "ParseFork", "group__parse__fork.html", "group__parse__fork" ],
    [ "Fork ID Generation", "group__fork__id.html", "group__fork__id" ],
    [ "Cloning API", "group__clone__api.html", "group__clone__api" ],
    [ "Fork Lifecycle", "group__fork__lifecycle.html", "group__fork__lifecycle" ],
    [ "Fork State Access", "group__fork__access.html", "group__fork__access" ],
    [ "Fork Set Management", "group__fork__set.html", "group__fork__set" ],
    [ "Convenience Macro for Generated Parsers", "group__fork__macro.html", "group__fork__macro" ],
    [ "Plugin Handle", "group__plugin__handle.html", "group__plugin__handle" ],
    [ "Plugin Capability Flags", "group__plugin__caps.html", "group__plugin__caps" ],
    [ "Plugin Version", "group__plugin__version.html", "group__plugin__version" ],
    [ "Plugin Interface", "group__plugin__interface.html", "group__plugin__interface" ],
    [ "Dynamic Plugin Entry Point", "group__plugin__entry.html", "group__plugin__entry" ],
    [ "Manager Configuration", "group__manager__config.html", "group__manager__config" ],
    [ "Manager Status Codes", "group__manager__status.html", "group__manager__status" ],
    [ "Manager Handle", "group__manager__handle.html", "group__manager__handle" ],
    [ "Manager Lifecycle", "group__manager__lifecycle.html", "group__manager__lifecycle" ],
    [ "Plugin Loading", "group__plugin__loading.html", "group__plugin__loading" ],
    [ "Active Parser Management", "group__active__parser.html", "group__active__parser" ],
    [ "Plugin Enumeration and Introspection", "group__plugin__introspection.html", "group__plugin__introspection" ],
    [ "Hot-Swap Support", "group__hot__swap.html", "group__hot__swap" ],
    [ "Version Compatibility Utilities", "group__version__utils.html", "group__version__utils" ],
    [ "Plugin Validation and Introspection Utilities", "group__plugin__validation.html", "group__plugin__validation" ]
];