#define NULL_CONST                       1
#define INTEGER_CONST                    2
#define MAXINT_PLUS_ONE_CONST            3
#define DOUBLE_CONST                     4
#define BOOLEAN_CONST                    5
#define VARIABLE                         6
#define FUNCTION                         7
#define AND_OP                           8
#define OR_OP                            9
#define NOT_OP                          10
#define NE_OP                           11
#define LE_OP                           12
#define GE_OP                           13
#define LS_OP                           14
#define RS_OP                           15
#define IS_OP                           16
#define ISNULL_OP                       17
#define NOTNULL_OP                      18
#define CASE_KW                         19
#define WHEN_KW                         20
#define THEN_KW                         21
#define ELSE_KW                         22
#define END_KW                          23
#define PLUS                            24
#define MINUS                           25
#define STAR                            26
#define SLASH                           27
#define PERCENT                         28
#define LT                              29
#define GT                              30
#define EQ                              31
#define AMP                             32
#define PIPE                            33
#define HASH                            34
#define TILDE                           35
#define LPAREN                          36
#define RPAREN                          37
#define COMMA                           38
#define UNARY                           39
