#define TO_P                             1
#define NULL_P                           2
#define TRUE_P                           3
#define FALSE_P                          4
#define IS_P                             5
#define UNKNOWN_P                        6
#define EXISTS_P                         7
#define IDENT_P                          8
#define STRING_P                         9
#define NUMERIC_P                       10
#define INT_P                           11
#define VARIABLE_P                      12
#define OR_P                            13
#define AND_P                           14
#define NOT_P                           15
#define LESS_P                          16
#define LESSEQUAL_P                     17
#define EQUAL_P                         18
#define NOTEQUAL_P                      19
#define GREATEREQUAL_P                  20
#define GREATER_P                       21
#define ANY_P                           22
#define STRICT_P                        23
#define LAX_P                           24
#define LAST_P                          25
#define STARTS_P                        26
#define WITH_P                          27
#define LIKE_REGEX_P                    28
#define FLAG_P                          29
#define ABS_P                           30
#define SIZE_P                          31
#define TYPE_P                          32
#define FLOOR_P                         33
#define DOUBLE_P                        34
#define CEILING_P                       35
#define KEYVALUE_P                      36
#define DATETIME_P                      37
#define BIGINT_P                        38
#define BOOLEAN_P                       39
#define DATE_P                          40
#define DECIMAL_P                       41
#define INTEGER_P                       42
#define NUMBER_P                        43
#define STRINGFUNC_P                    44
#define TIME_P                          45
#define TIME_TZ_P                       46
#define TIMESTAMP_P                     47
#define TIMESTAMP_TZ_P                  48
#define DOLLAR                          49
#define AT                              50
#define DOT                             51
#define LBRACKET                        52
#define RBRACKET                        53
#define LBRACE                          54
#define RBRACE                          55
#define LPAREN                          56
#define RPAREN                          57
#define QUESTION                        58
#define COMMA                           59
#define STAR                            60
#define COLON                           61
#define PLUS                            62
#define MINUS                           63
#define SLASH                           64
#define PERCENT                         65
#define UMINUS                          66
