#define SCONST                           1
#define IDENT                            2
#define UCONST                           3
#define RECPTR                           4
#define K_BASE_BACKUP                    5
#define K_IDENTIFY_SYSTEM                6
#define K_READ_REPLICATION_SLOT          7
#define K_SHOW                           8
#define K_START_REPLICATION              9
#define K_CREATE_REPLICATION_SLOT       10
#define K_DROP_REPLICATION_SLOT         11
#define K_ALTER_REPLICATION_SLOT        12
#define K_TIMELINE_HISTORY              13
#define K_WAIT                          14
#define K_TIMELINE                      15
#define K_PHYSICAL                      16
#define K_LOGICAL                       17
#define K_SLOT                          18
#define K_RESERVE_WAL                   19
#define K_TEMPORARY                     20
#define K_TWO_PHASE                     21
#define K_EXPORT_SNAPSHOT               22
#define K_NOEXPORT_SNAPSHOT             23
#define K_USE_SNAPSHOT                  24
#define K_UPLOAD_MANIFEST               25
#define LPAREN                          26
#define RPAREN                          27
#define COMMA                           28
#define SEMI                            29
#define DOT                             30
