var searchData=
[
  ['machine_20construction_0',['State Machine Construction',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md234',1,'']]],
  ['macro_20for_20generated_20parsers_1',['Convenience Macro for Generated Parsers',['../group__fork__macro.html',1,'']]],
  ['major_2',['major',['../struct_lime_plugin_version.html#a3b4c9442844f88c6256bc47e3bb927c9',1,'LimePluginVersion']]],
  ['make_20cmake_3',['Option 3: Generator + Extension Framework (Make / CMake)',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md43',1,'']]],
  ['makefile_4',['Makefile',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md44',1,'']]],
  ['mallocs_5',['Pattern B: Stack-allocated parser (zero mallocs)',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md55',1,'']]],
  ['management_6',['Management',['../group__active__parser.html',1,'Active Parser Management'],['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md540',1,'Dependency Management'],['../group__fork__set.html',1,'Fork Set Management'],['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md109',1,'Memory Management'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md389',1,'Memory Management'],['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md511',1,'Memory Management']]],
  ['manager_7',['Snapshot Lifecycle Under the Manager',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md513',1,'']]],
  ['manager_20configuration_8',['Manager Configuration',['../group__manager__config.html',1,'']]],
  ['manager_20handle_9',['Manager Handle',['../group__manager__handle.html',1,'']]],
  ['manager_20lifecycle_10',['Manager Lifecycle',['../group__manager__lifecycle.html',1,'']]],
  ['manager_20status_20codes_11',['Manager Status Codes',['../group__manager__status.html',1,'']]],
  ['mapping_12',['Directive Mapping',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md426',1,'']]],
  ['mapping_20yacc_20specific_13',['Directive Mapping (Yacc-Specific)',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___y_a_c_c.html#autotoc_md449',1,'']]],
  ['markdown_20yaml_20format_14',['From Markdown + YAML Format',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md535',1,'']]],
  ['matrix_15',['Feature Comparison Matrix',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md401',1,'']]],
  ['matters_16',['Extension ordering matters',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md303',1,'']]],
  ['matters_20most_17',['Why Tokenizer JIT Matters Most',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md478',1,'']]],
  ['max_5fexecutions_18',['max_executions',['../struct_execution_policy_config.html#ae9564cbc4148c2e5a4362a623a07e4b0',1,'ExecutionPolicyConfig']]],
  ['max_5fforks_19',['max_forks',['../struct_parse_fork_set.html#aa5c973e1b744beee3a7c8228e4d5f98f',1,'ParseForkSet']]],
  ['max_5fplugins_20',['max_plugins',['../struct_parser_manager_config.html#a775d7344111eefd724955adf676e4b53',1,'ParserManagerConfig']]],
  ['mcjit_20legacy_21',['MCJIT (Legacy)',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md473',1,'']]],
  ['mcjit_20vs_20orcjit_20migration_22',['MCJIT vs OrcJIT Migration',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md472',1,'']]],
  ['measuring_20extension_20overhead_23',['Measuring Extension Overhead',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md393',1,'']]],
  ['mechanisms_24',['Synchronization Mechanisms',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md107',1,'']]],
  ['memory_25',['Memory',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md351',1,'Per-Extension Memory'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md352',1,'Per-Fork Memory'],['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md314',1,'Snapshot Memory']]],
  ['memory_20budget_26',['Aggregate Memory Budget',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md353',1,'']]],
  ['memory_20budget_20guide_27',['Memory Budget Guide',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md332',1,'']]],
  ['memory_20management_28',['Memory Management',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md109',1,'Memory Management'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md389',1,'Memory Management'],['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md511',1,'Memory Management']]],
  ['memory_20optimization_29',['Memory Optimization',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md336',1,'']]],
  ['memory_20overhead_30',['Memory Overhead',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md350',1,'']]],
  ['memory_20overhead_20per_20extension_31',['Memory Overhead Per Extension',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md327',1,'']]],
  ['memory_20profiling_32',['Memory Profiling',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md395',1,'']]],
  ['memory_20usage_33',['Memory Usage',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md423',1,'']]],
  ['menhir_34',['Lime vs Menhir',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md412',1,'']]],
  ['menhir_20when_20you_20need_3a_35',['Use Menhir when you need:',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md418',1,'']]],
  ['meson_36',['Option 2: Generator + Extension Framework (Meson)',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md40',1,'']]],
  ['meson_20subproject_37',['As a Meson subproject',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md41',1,'']]],
  ['metadata_38',['Extension Metadata',['../group__ext__metadata.html',1,'']]],
  ['metadata_20block_39',['Metadata Block',['../md_docs_2_l_i_t_e_r_a_t_e___f_o_r_m_a_t.html#autotoc_md561',1,'']]],
  ['metadata_20execution_40',['Grammar Extension Metadata (Execution)',['../group__exec__ext__meta.html',1,'']]],
  ['metadata_20validation_41',['Module Metadata Validation',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md543',1,'']]],
  ['metrics_20to_20compare_42',['Key Metrics to Compare',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md394',1,'']]],
  ['mid_20rule_20actions_43',['Mid-Rule Actions',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md433',1,'']]],
  ['migrating_20from_20bison_20to_20lime_44',['Migrating from Bison to Lime',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html',1,'']]],
  ['migrating_20from_20yacc_20to_20lime_45',['Migrating from Yacc to Lime',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___y_a_c_c.html',1,'']]],
  ['migration_46',['MCJIT vs OrcJIT Migration',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md472',1,'']]],
  ['migration_20checklist_47',['Quick Migration Checklist',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___y_a_c_c.html#autotoc_md453',1,'']]],
  ['migration_20guide_48',['Migration Guide',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md534',1,'']]],
  ['migration_20path_49',['Migration Path',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md475',1,'']]],
  ['migration_20paths_50',['Migration Paths',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md419',1,'']]],
  ['minimal_51',['Keep modifications minimal',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md296',1,'']]],
  ['minor_52',['minor',['../struct_lime_plugin_version.html#ab0f82e66c3318b23c7c5af593f9cb1a3',1,'LimePluginVersion']]],
  ['mod_5fadd_5frule_53',['Adding Grammar Rules (&lt;span class=&quot;tt&quot;&gt;MOD_ADD_RULE&lt;/span&gt;)',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md278',1,'']]],
  ['mod_5fadd_5ftoken_54',['Adding Tokens (&lt;span class=&quot;tt&quot;&gt;MOD_ADD_TOKEN&lt;/span&gt;)',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md277',1,'']]],
  ['mod_5fadd_5ftype_55',['Adding Non-Terminal Types (&lt;span class=&quot;tt&quot;&gt;MOD_ADD_TYPE&lt;/span&gt;)',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md280',1,'']]],
  ['mod_5findex_5fa_56',['mod_index_a',['../struct_conflict.html#ab164bad1b812deffae5b46aaa830a0dd',1,'Conflict']]],
  ['mod_5findex_5fb_57',['mod_index_b',['../struct_conflict.html#ae55bca2da147ce2d6cfa22f63190a27e',1,'Conflict']]],
  ['mod_5fmodify_5fprecedence_58',['Modifying Precedence (&lt;span class=&quot;tt&quot;&gt;MOD_MODIFY_PRECEDENCE&lt;/span&gt;)',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md279',1,'']]],
  ['mod_5fremove_5frule_59',['Removing Rules (&lt;span class=&quot;tt&quot;&gt;MOD_REMOVE_RULE&lt;/span&gt;)',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md281',1,'']]],
  ['mode_60',['mode',['../struct_grammar_context_entry.html#ae75966e7e93d61a5c9173202986c03a9',1,'GrammarContextEntry::mode'],['../struct_grammar_mode_info.html#a6f108470c59093785e0f4dc1e1747a30',1,'GrammarModeInfo::mode']]],
  ['mode_20registration_61',['Mode Registration',['../group__mode__info.html',1,'']]],
  ['mode_5fcount_5f_62',['MODE_COUNT_',['../group__grammar__modes.html#ggac879c49c0a97d7abdd1b5f5bf8903290abd78c0decaaa4a2ca88be610438d2060',1,'grammar_context.h']]],
  ['mode_5fcustom_63',['MODE_CUSTOM',['../group__grammar__modes.html#ggac879c49c0a97d7abdd1b5f5bf8903290a39886566586698864e02d93e0df1d173',1,'grammar_context.h']]],
  ['mode_5fedn_64',['MODE_EDN',['../group__grammar__modes.html#ggac879c49c0a97d7abdd1b5f5bf8903290ae19222ddeffa6f07113b0f77bcbd4173',1,'grammar_context.h']]],
  ['mode_5fjson_65',['MODE_JSON',['../group__grammar__modes.html#ggac879c49c0a97d7abdd1b5f5bf8903290a6594df426998c58e8cf3410dfcd03c2c',1,'grammar_context.h']]],
  ['mode_5fname_66',['mode_name',['../struct_grammar_context_entry.html#aa032092e638133bee7d8c7c91969cab3',1,'GrammarContextEntry']]],
  ['mode_5fsql_67',['MODE_SQL',['../group__grammar__modes.html#ggac879c49c0a97d7abdd1b5f5bf8903290a69ee5eb82fd407c4506b5f85904ed150',1,'grammar_context.h']]],
  ['mode_5fxpath_68',['MODE_XPATH',['../group__grammar__modes.html#ggac879c49c0a97d7abdd1b5f5bf8903290abf3e49ed77512dce35bd714d6de8eff9',1,'grammar_context.h']]],
  ['mode_5fxquery_69',['MODE_XQUERY',['../group__grammar__modes.html#ggac879c49c0a97d7abdd1b5f5bf8903290ad234fd10691b6f53eb75a462618f0370',1,'grammar_context.h']]],
  ['model_70',['Model',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md501',1,'Concurrency Model'],['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md110',1,'Ownership Model'],['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___y_a_c_c.html#autotoc_md446',1,'Parser Model']]],
  ['modes_71',['Modes',['../group__grammar__modes.html',1,'Grammar Modes'],['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md322',1,'JIT Compilation Modes']]],
  ['modification_72',['Copy-on-Write Modification',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md87',1,'']]],
  ['modification_20types_73',['Grammar Modification Types',['../md_docs_2_a_p_i.html#autotoc_md172',1,'']]],
  ['modifications_74',['Modifications',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md95',1,'Grammar Modifications'],['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md276',1,'Grammar Modifications']]],
  ['modifications_75',['modifications',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md300',1,'Free dynamically allocated modifications'],['../struct_grammar_extension_metadata.html#aadef9fb59331417ca90a1e827642220d',1,'GrammarExtensionMetadata::modifications']]],
  ['modifications_20array_76',['Step 1: Define the modifications array',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md288',1,'']]],
  ['modifications_20minimal_77',['Keep modifications minimal',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md296',1,'']]],
  ['modifying_20precedence_20mod_5fmodify_5fprecedence_78',['Modifying Precedence (&lt;span class=&quot;tt&quot;&gt;MOD_MODIFY_PRECEDENCE&lt;/span&gt;)',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md279',1,'']]],
  ['modular_20grammar_20examples_20pg_5fmodular_79',['PostgreSQL Modular Grammar (&lt;span class=&quot;tt&quot;&gt;examples/pg_modular/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md64',1,'']]],
  ['module_20composition_80',['Module Composition',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md530',1,'']]],
  ['module_20foo_20requires_20bar_20which_20is_20not_20available_81',['&quot;Module &apos;foo&apos; requires &apos;bar&apos;, which is not available&quot;',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md547',1,'']]],
  ['module_20format_82',['Lime Module Format',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html',1,'']]],
  ['module_20identity_83',['Module Identity',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md525',1,'']]],
  ['module_20metadata_20validation_84',['Module Metadata Validation',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md543',1,'']]],
  ['module_20organization_85',['Module Organization',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md538',1,'']]],
  ['module_20system_86',['Module System',['../md_docs_2_c_o_n_c_e_p_t_s.html#autotoc_md36',1,'']]],
  ['module_5fname_87',['&quot;Unknown declaration keyword: %module_name&quot;',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md546',1,'']]],
  ['modules_88',['&quot;Cyclic dependency detected among modules&quot;',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md548',1,'']]],
  ['mongodb_89',['MongoDB Query Language (&lt;span class=&quot;tt&quot;&gt;examples/mongodb/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md75',1,'']]],
  ['mongodb_20query_20language_20examples_20mongodb_90',['MongoDB Query Language (&lt;span class=&quot;tt&quot;&gt;examples/mongodb/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md75',1,'']]],
  ['monolithic_20grammar_91',['From Monolithic Grammar',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md536',1,'']]],
  ['most_92',['Most',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md316',1,'When SIMD Helps Most'],['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md478',1,'Why Tokenizer JIT Matters Most']]],
  ['motivation_93',['Motivation',['../index.html#autotoc_md2',1,'']]],
  ['multi_20grammar_20conflict_20detection_94',['Multi-Grammar Conflict Detection',['../group__multi__grammar.html',1,'']]],
  ['multi_20grammar_20conflict_20detection_20api_95',['Multi-Grammar Conflict Detection API',['../group__multi__detect__api.html',1,'']]],
  ['multi_5fconflict_5fresult_5fcreate_96',['multi_conflict_result_create',['../group__multi__conflict__result.html#ga4f8c11a66a5074647c287fc88f962bbf',1,'conflict.h']]],
  ['multi_5fconflict_5fresult_5fdestroy_97',['multi_conflict_result_destroy',['../group__multi__conflict__result.html#gafd0a3ffd87f24c1873ac03e806eac04b',1,'conflict.h']]],
  ['multigrammarconflictresult_98',['MultiGrammarConflictResult',['../struct_multi_grammar_conflict_result.html',1,'']]],
  ['multigrammarconflictresult_20lifecycle_99',['MultiGrammarConflictResult Lifecycle',['../group__multi__conflict__result.html',1,'']]],
  ['multiple_20extensions_100',['Multiple Extensions',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md331',1,'']]]
];
