var searchData=
[
  ['a_20and_20b_0',['&quot;Symbol &apos;X&apos; is exported by both &apos;A&apos; and &apos;B&apos;&quot;',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md549',1,'']]],
  ['a_20driver_1',['Writing a Driver',['../md_docs_2_g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md21',1,'']]],
  ['a_20meson_20subproject_2',['As a Meson subproject',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md41',1,'']]],
  ['a_20shift_20reduce_20example_3',['A Shift-Reduce Example',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md205',1,'']]],
  ['a_20system_20library_4',['As a system library',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md42',1,'']]],
  ['a_3a_20allocate_20once_20reset_20between_20parses_5',['Pattern A: Allocate once, reset between parses',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md54',1,'']]],
  ['abi_20versioning_6',['ABI Versioning',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md494',1,'']]],
  ['acceleration_7',['SIMD Acceleration',['../md_docs_2_a_p_i.html#autotoc_md147',1,'']]],
  ['access_8',['Access',['../group__fork__access.html',1,'Fork State Access'],['../md_docs_2_a_p_i.html#autotoc_md135',1,'Snapshot-Indirected Table Access']]],
  ['acknowledgements_9',['Acknowledgements',['../index.html#autotoc_md14',1,'']]],
  ['action_20table_20compression_10',['Action Table Compression',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md268',1,'']]],
  ['action_20table_20jit_11',['Tokenizer JIT vs Action Table JIT',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md481',1,'']]],
  ['action_20table_20layout_12',['Action Table Layout',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md90',1,'']]],
  ['action_20table_20lookups_13',['Speedup from JIT on Action Table Lookups',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md460',1,'']]],
  ['action_20table_20packing_20acttab_14',['Action Table Packing (acttab)',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md250',1,'']]],
  ['action_20types_15',['Conflict Action Types',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md245',1,'']]],
  ['actions_16',['Mid-Rule Actions',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md433',1,'']]],
  ['active_20conflicts_17',['With Extensions (Active Conflicts)',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md358',1,'']]],
  ['active_20parser_20and_20hot_20swap_18',['Active Parser and Hot-Swap',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md503',1,'']]],
  ['active_20parser_20management_19',['Active Parser Management',['../group__active__parser.html',1,'']]],
  ['active_20plugin_20',['Setting the Active Plugin',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md504',1,'']]],
  ['acttab_21',['Action Table Packing (acttab)',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md250',1,'']]],
  ['add_5ftoken_22',['add_token',['../md_docs_2_a_p_i.html#autotoc_md155',1,'']]],
  ['adding_20grammar_20rules_20mod_5fadd_5frule_23',['Adding Grammar Rules (&lt;span class=&quot;tt&quot;&gt;MOD_ADD_RULE&lt;/span&gt;)',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md278',1,'']]],
  ['adding_20non_20terminal_20types_20mod_5fadd_5ftype_24',['Adding Non-Terminal Types (&lt;span class=&quot;tt&quot;&gt;MOD_ADD_TYPE&lt;/span&gt;)',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md280',1,'']]],
  ['adding_20tokens_20mod_5fadd_5ftoken_25',['Adding Tokens (&lt;span class=&quot;tt&quot;&gt;MOD_ADD_TOKEN&lt;/span&gt;)',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md277',1,'']]],
  ['adds_26',['What the extension adds',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md287',1,'']]],
  ['advanced_20topics_27',['Advanced Topics',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md550',1,'']]],
  ['aggregate_20memory_20budget_28',['Aggregate Memory Budget',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md353',1,'']]],
  ['ahead_20lr_29',['LALR(1) &amp;ndash; Look-Ahead LR',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md210',1,'']]],
  ['algorithm_30',['Algorithm',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md88',1,'LALR(1) Algorithm'],['../md_docs_2_a_l_g_o_r_i_t_h_m.html',1,'LALR(1) Parsing Algorithm'],['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md249',1,'Lookup Algorithm']]],
  ['allocate_20once_20reset_20between_20parses_31',['Pattern A: Allocate once, reset between parses',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md54',1,'']]],
  ['allocated_20modifications_32',['Free dynamically allocated modifications',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md300',1,'']]],
  ['allocated_20parser_20zero_20mallocs_33',['Pattern B: Stack-allocated parser (zero mallocs)',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md55',1,'']]],
  ['allocation_20and_20reuse_34',['Parser Allocation and Reuse',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md53',1,'']]],
  ['allocation_20strategy_35',['Allocation Strategy',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md111',1,'']]],
  ['among_20modules_36',['&quot;Cyclic dependency detected among modules&quot;',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md548',1,'']]],
  ['analysis_37',['Cost-Benefit Analysis',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md459',1,'']]],
  ['analysis_20for_20lime_20parser_20generator_38',['JIT Compilation Analysis for Lime Parser Generator',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html',1,'']]],
  ['analysis_20with_20extensions_39',['Break-Even Analysis with Extensions',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md372',1,'']]],
  ['and_20b_40',['&quot;Symbol &apos;X&apos; is exported by both &apos;A&apos; and &apos;B&apos;&quot;',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md549',1,'']]],
  ['and_20hot_20swap_41',['Active Parser and Hot-Swap',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md503',1,'']]],
  ['and_20integration_42',['Code Generation and Integration',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md403',1,'']]],
  ['and_20introspection_43',['Plugin Enumeration and Introspection',['../group__plugin__introspection.html',1,'']]],
  ['and_20introspection_20utilities_44',['Plugin Validation and Introspection Utilities',['../group__plugin__validation.html',1,'']]],
  ['and_20parsers_45',['Grammars and Parsers',['../md_docs_2_c_o_n_c_e_p_t_s.html#autotoc_md26',1,'']]],
  ['and_20parsing_46',['Grammar and Parsing',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md402',1,'']]],
  ['and_20performance_47',['NDEBUG and Performance',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md56',1,'']]],
  ['and_20reuse_48',['Parser Allocation and Reuse',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md53',1,'']]],
  ['and_20thread_20safety_49',['Copy-on-Write and Thread Safety',['../md_docs_2_c_o_n_c_e_p_t_s.html#autotoc_md33',1,'']]],
  ['and_20tooling_50',['Build and Tooling',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md407',1,'']]],
  ['antlr_51',['Lime vs ANTLR',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md411',1,'']]],
  ['antlr_20when_20you_20need_3a_52',['Use ANTLR when you need:',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md417',1,'']]],
  ['aot_20compilation_20lime_20j_53',['AOT Compilation (&lt;span class=&quot;tt&quot;&gt;lime -j&lt;/span&gt;)',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md468',1,'']]],
  ['aot_20vs_20runtime_20jit_54',['AOT vs Runtime JIT',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md467',1,'']]],
  ['api_55',['API',['../group__clone__api.html',1,'Cloning API'],['../group__disambig__api.html',1,'Disambiguation API'],['../group__exec__api.html',1,'Execution Policy API'],['../md_docs_2_a_p_i.html#autotoc_md166',1,'Extension API'],['../group__ext__init.html',1,'Extension Initialization API'],['../group__grammar__ctx__api.html',1,'Grammar Context API'],['../group__jit__api.html',1,'JIT Compilation API'],['../md_docs_2_a_p_i.html#autotoc_md175',1,'JIT Compilation API'],['../md_docs_2_a_p_i.html#autotoc_md182',1,'JIT Policy API'],['../group__multi__detect__api.html',1,'Multi-Grammar Conflict Detection API'],['../group__parse__ctx__api.html',1,'Parse Context API'],['../md_docs_2_a_p_i.html#autotoc_md128',1,'Parse Context API'],['../group__registry__api.html',1,'Registry API'],['../md_docs_2_a_p_i.html#autotoc_md158',1,'SIMD Character Classification API'],['../group__snapshot__api.html',1,'Snapshot API'],['../md_docs_2_a_p_i.html#autotoc_md121',1,'Snapshot API'],['../md_docs_2_a_p_i.html#autotoc_md149',1,'Token Table API'],['../md_docs_2_a_p_i.html#autotoc_md137',1,'Tokenizer API']]],
  ['api_20parser_20h_56',['High-Level API (parser.h)',['../md_docs_2_a_p_i.html#autotoc_md167',1,'']]],
  ['api_20reference_57',['Extensible SQL Parser &amp;ndash; API Reference',['../md_docs_2_a_p_i.html',1,'']]],
  ['api_20src_20extension_20h_58',['Internal Registry API (src/extension.h)',['../md_docs_2_a_p_i.html#autotoc_md168',1,'']]],
  ['appendix_3a_20data_20structure_20sizes_59',['Appendix: Data Structure Sizes',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md397',1,'']]],
  ['applied_60',['How Extensions Are Applied',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md293',1,'']]],
  ['approach_61',['Lime&apos;s Approach',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md218',1,'']]],
  ['architecture_62',['Architecture',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html',1,'Architecture'],['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md102',1,'Architecture'],['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md84',1,'Copy-on-Write Snapshot Architecture']]],
  ['architecture_20overview_63',['Architecture Overview',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md342',1,'Architecture Overview'],['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md490',1,'Architecture Overview']]],
  ['are_20applied_64',['How Extensions Are Applied',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md293',1,'']]],
  ['arm_20only_65',['classify_simd_neon (ARM only)',['../md_docs_2_a_p_i.html#autotoc_md164',1,'']]],
  ['array_66',['Step 1: Define the modifications array',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md288',1,'']]],
  ['arrays_67',['The Five Arrays',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md248',1,'']]],
  ['as_20a_20meson_20subproject_68',['As a Meson subproject',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md41',1,'']]],
  ['as_20a_20system_20library_69',['As a system library',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md42',1,'']]],
  ['assigned_20token_20codes_70',['Use auto-assigned token codes',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md297',1,'']]],
  ['assignment_71',['Handle Assignment',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md502',1,'']]],
  ['at_20build_20time_72',['Generating Parsers at Build Time',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md49',1,'']]],
  ['auto_20assigned_20token_20codes_73',['Use auto-assigned token codes',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md297',1,'']]],
  ['auto_5fjit_74',['auto_jit',['../struct_parser_manager_config.html#af01d22ed79852db08ecbffa7cfb2c814',1,'ParserManagerConfig']]],
  ['available_75',['JIT Performance (When LLVM Available)',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md320',1,'']]],
  ['available_76',['&quot;Module &apos;foo&apos; requires &apos;bar&apos;, which is not available&quot;',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md547',1,'']]],
  ['avoiding_20symbol_20collisions_77',['Avoiding Symbol Collisions',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md50',1,'']]]
];
