var searchData=
[
  ['re_20exporting_20symbols_0',['Re-exporting Symbols',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md552',1,'']]],
  ['reading_1',['Reading',['../md_docs_2_c_o_n_c_e_p_t_s.html#autotoc_md37',1,'Further Reading'],['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md58',1,'Further Reading']]],
  ['recommendation_2',['Recommendation',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md470',1,'']]],
  ['recommendations_3',['Recommendations',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md384',1,'Performance Tuning Recommendations'],['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md328',1,'Recommendations']]],
  ['recommended_4',['OrcJIT (Recommended)',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md474',1,'']]],
  ['recommended_20configuration_5',['Recommended Configuration',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md483',1,'']]],
  ['recovery_6',['Error Recovery',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md257',1,'']]],
  ['reduce_20example_7',['A Shift-Reduce Example',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md205',1,'']]],
  ['reduce_20reduce_20resolution_8',['Reduce/Reduce Resolution',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md244',1,'']]],
  ['reduce_20resolution_9',['Reduce/Reduce Resolution',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md244',1,'']]],
  ['reduction_10',['Conflict Reduction',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md388',1,'']]],
  ['reentrancy_11',['Reentrancy',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___y_a_c_c.html#autotoc_md447',1,'']]],
  ['reference_12',['Reference',['../md_docs_2_a_p_i.html#autotoc_md186',1,'Data Structures Reference'],['../md_docs_2_a_p_i.html',1,'Extensible SQL Parser &amp;ndash; API Reference'],['../md_docs_2_l_i_t_e_r_a_t_e___f_o_r_m_a_t.html#autotoc_md573',1,'Tool Reference']]],
  ['reference_20card_13',['Quick Reference Card',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md443',1,'']]],
  ['references_14',['References',['../index.html#autotoc_md16',1,'References'],['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md264',1,'References'],['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md555',1,'References']]],
  ['registration_15',['Registration',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md272',1,'1. Registration'],['../md_docs_2_a_p_i.html#autotoc_md199',1,'Extension Registration'],['../group__mode__info.html',1,'Mode Registration']]],
  ['registration_20function_16',['Step 4: Convenience registration function',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md291',1,'']]],
  ['registry_17',['Registry',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md345',1,'Extension Registry'],['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md499',1,'Plugin Registry']]],
  ['registry_20api_18',['Registry API',['../group__registry__api.html',1,'']]],
  ['registry_20api_20src_20extension_20h_19',['Internal Registry API (src/extension.h)',['../md_docs_2_a_p_i.html#autotoc_md168',1,'']]],
  ['registry_20functions_20',['Registry Functions',['../md_docs_2_a_p_i.html#autotoc_md171',1,'']]],
  ['registry_20handle_21',['Registry Handle',['../group__registry__handle.html',1,'']]],
  ['related_20tools_22',['Related Tools',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md267',1,'']]],
  ['remove_5ftokens_5fby_5fextension_23',['remove_tokens_by_extension',['../md_docs_2_a_p_i.html#autotoc_md156',1,'']]],
  ['removing_20rules_20mod_5fremove_5frule_24',['Removing Rules (&lt;span class=&quot;tt&quot;&gt;MOD_REMOVE_RULE&lt;/span&gt;)',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md281',1,'']]],
  ['reordering_25',['State Reordering',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md251',1,'']]],
  ['replication_26',['Replication Protocol (&lt;span class=&quot;tt&quot;&gt;examples/replication/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md70',1,'']]],
  ['replication_20config_20examples_20syncrep_27',['Synchronous Replication Config (&lt;span class=&quot;tt&quot;&gt;examples/syncrep/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md69',1,'']]],
  ['replication_20protocol_20examples_20replication_28',['Replication Protocol (&lt;span class=&quot;tt&quot;&gt;examples/replication/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md70',1,'']]],
  ['reporttable_29',['Step 10: ReportTable',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md232',1,'']]],
  ['reproduction_30',['Benchmark Reproduction',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md391',1,'']]],
  ['required_31',['get_modifications (required)',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md283',1,'']]],
  ['required_20callbacks_32',['Required Callbacks',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md492',1,'']]],
  ['required_20fields_33',['Required Fields',['../md_docs_2_l_i_t_e_r_a_t_e___f_o_r_m_a_t.html#autotoc_md562',1,'']]],
  ['requires_20bar_20which_20is_20not_20available_34',['&quot;Module &apos;foo&apos; requires &apos;bar&apos;, which is not available&quot;',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md547',1,'']]],
  ['reset_20between_20parses_35',['Pattern A: Allocate once, reset between parses',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md54',1,'']]],
  ['resolution_36',['Resolution',['../md_docs_2_a_p_i.html#autotoc_md173',1,'Conflict Resolution'],['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md241',1,'Conflict Resolution'],['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md243',1,'Precedence-Based Resolution'],['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md244',1,'Reduce/Reduce Resolution']]],
  ['resolve_37',['resolve',['../struct_disambiguation_strategy_v_table.html#a6c1609ace2ea51ec34e3f5a18f04436d',1,'DisambiguationStrategyVTable']]],
  ['resolve_20strategy_38',['Fork-Resolve Strategy',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md367',1,'']]],
  ['resolve_5fconflicts_39',['resolve_conflicts',['../group__conflict__detect.html#gaee8377eaefd6d02f061675cb98daa3ae',1,'conflict.h']]],
  ['resolved_40',['resolved',['../struct_conflict.html#acf69a2ce6747df1ce8c1e3765a867bc1',1,'Conflict']]],
  ['resortstates_41',['Step 9: ResortStates',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md231',1,'']]],
  ['result_42',['Result',['../group__exec__result.html',1,'Execution Result'],['../group__strat__result.html',1,'Strategy Result'],['../group__ext__order.html',1,'Topological Order Result']]],
  ['result_43',['result',['../struct_execution_result.html#aa39e2a39c254b0f2e8a05ede412fea47',1,'ExecutionResult']]],
  ['reuse_44',['Parser Allocation and Reuse',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md53',1,'']]],
  ['rule_20actions_45',['Mid-Rule Actions',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md433',1,'']]],
  ['rule_20level_20conflicts_46',['Rule-Level Conflicts',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md362',1,'']]],
  ['rule_20not_20taking_20effect_47',['Grammar rule not taking effect',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md307',1,'']]],
  ['rule_20overhead_48',['Tiebreaker Rule Overhead',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md382',1,'']]],
  ['rule_20syntax_49',['Rule Syntax',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md428',1,'']]],
  ['rule_20syntax_20translation_50',['Rule Syntax Translation',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___y_a_c_c.html#autotoc_md450',1,'']]],
  ['rule_5fconflicts_51',['rule_conflicts',['../struct_multi_grammar_conflict_result.html#aa7f92de13ec77f606899646256816d2b',1,'MultiGrammarConflictResult']]],
  ['rules_52',['Rules',['../md_docs_2_l_i_t_e_r_a_t_e___f_o_r_m_a_t.html#autotoc_md567',1,'Content Rules'],['../md_docs_2_l_i_t_e_r_a_t_e___f_o_r_m_a_t.html#autotoc_md564',1,'Naming Rules'],['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md512',1,'Ownership Rules']]],
  ['rules_20mod_5fadd_5frule_53',['Adding Grammar Rules (&lt;span class=&quot;tt&quot;&gt;MOD_ADD_RULE&lt;/span&gt;)',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md278',1,'']]],
  ['rules_20mod_5fremove_5frule_54',['Removing Rules (&lt;span class=&quot;tt&quot;&gt;MOD_REMOVE_RULE&lt;/span&gt;)',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md281',1,'']]],
  ['running_20benchmarks_55',['Running Benchmarks',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md337',1,'']]],
  ['running_20the_20parser_20benchmark_20suite_56',['Running the Parser Benchmark Suite',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md392',1,'']]],
  ['runtime_57',['Generated Parser Runtime',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md254',1,'']]],
  ['runtime_20costs_58',['Per-Token Runtime Costs',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md325',1,'']]],
  ['runtime_20dispatch_59',['Runtime Dispatch',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md105',1,'']]],
  ['runtime_20extensibility_60',['Runtime Extensibility',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md406',1,'']]],
  ['runtime_20extension_20loading_61',['Runtime Extension Loading',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md48',1,'']]],
  ['runtime_20jit_62',['Runtime JIT',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md467',1,'AOT vs Runtime JIT'],['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md469',1,'Runtime JIT']]],
  ['runtime_20parsing_20performance_63',['Runtime Parsing Performance',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md262',1,'']]]
];
