var searchData=
[
  ['generated_20parser_20runtime_0',['Generated Parser Runtime',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md254',1,'']]],
  ['generated_20parser_20symbols_1',['Generated parser symbols',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md51',1,'']]],
  ['generated_20parsers_2',['Convenience Macro for Generated Parsers',['../group__fork__macro.html',1,'']]],
  ['generating_20parsers_20at_20build_20time_3',['Generating Parsers at Build Time',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md49',1,'']]],
  ['generation_4',['Fork ID Generation',['../group__fork__id.html',1,'']]],
  ['generation_20and_20integration_5',['Code Generation and Integration',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md403',1,'']]],
  ['generator_6',['Generator',['../md_docs_2_g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md19',1,'Building the Generator'],['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html',1,'JIT Compilation Analysis for Lime Parser Generator'],['../index.html',1,'Lime Parser Generator']]],
  ['generator_20comparison_20guide_7',['Parser Generator Comparison Guide',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html',1,'']]],
  ['generator_20extension_20framework_20make_20cmake_8',['Option 3: Generator + Extension Framework (Make / CMake)',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md43',1,'']]],
  ['generator_20extension_20framework_20meson_9',['Option 2: Generator + Extension Framework (Meson)',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md40',1,'']]],
  ['generator_20only_20no_20extension_20framework_10',['Option 1: Generator Only (No Extension Framework)',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md39',1,'']]],
  ['get_5fabi_5fmajor_11',['get_abi_major',['../struct_lime_parser_plugin.html#a75a770fb6a0b448da2d97e5f55e3a528',1,'LimeParserPlugin']]],
  ['get_5fabi_5fminor_12',['get_abi_minor',['../struct_lime_parser_plugin.html#a83335580006640a64ea0d1192967aa2b',1,'LimeParserPlugin']]],
  ['get_5fcapabilities_13',['get_capabilities',['../struct_lime_parser_plugin.html#a489abf5c6e8c73473b91ded9107dd82b',1,'LimeParserPlugin']]],
  ['get_5fclassify_5ffunc_14',['get_classify_func',['../md_docs_2_a_p_i.html#autotoc_md161',1,'']]],
  ['get_5fmodifications_20required_15',['get_modifications (required)',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md283',1,'']]],
  ['get_5fname_16',['get_name',['../struct_lime_parser_plugin.html#a16f6683892142b165824ab631387367f',1,'LimeParserPlugin']]],
  ['get_5fversion_17',['get_version',['../struct_lime_parser_plugin.html#adbcaa0b0a1c7502e060300d4b6c98fe1',1,'LimeParserPlugin']]],
  ['getting_20started_18',['Getting Started',['../md_docs_2_g_e_t_t_i_n_g___s_t_a_r_t_e_d.html',1,'']]],
  ['glrparser_19',['GLRParser',['../struct_g_l_r_parser.html',1,'']]],
  ['goals_20',['Goals',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md488',1,'Goals'],['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md489',1,'Non-Goals']]],
  ['gotchas_21',['Common Gotchas',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md442',1,'']]],
  ['goto_20function_22',['GOTO Function',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md237',1,'']]],
  ['graceful_20degradation_23',['Graceful Degradation',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md103',1,'']]],
  ['gracefully_24',['Handle conflicts gracefully',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md299',1,'']]],
  ['grammar_25',['Grammar',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md536',1,'From Monolithic Grammar'],['../md_docs_2_g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md20',1,'Your First Grammar']]],
  ['grammar_20and_20parsing_26',['Grammar and Parsing',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md402',1,'']]],
  ['grammar_20conflict_20detection_27',['Multi-Grammar Conflict Detection',['../group__multi__grammar.html',1,'']]],
  ['grammar_20conflict_20detection_20api_28',['Multi-Grammar Conflict Detection API',['../group__multi__detect__api.html',1,'']]],
  ['grammar_20context_20api_29',['Grammar Context API',['../group__grammar__ctx__api.html',1,'']]],
  ['grammar_20examples_20pg_30',['PostgreSQL Full Grammar (&lt;span class=&quot;tt&quot;&gt;examples/pg/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md63',1,'']]],
  ['grammar_20examples_20pg_5fmodular_31',['PostgreSQL Modular Grammar (&lt;span class=&quot;tt&quot;&gt;examples/pg_modular/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md64',1,'']]],
  ['grammar_20extension_20metadata_20execution_32',['Grammar Extension Metadata (Execution)',['../group__exec__ext__meta.html',1,'']]],
  ['grammar_20format_20examples_20literate_33',['Literate Grammar Format (&lt;span class=&quot;tt&quot;&gt;examples/literate/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md78',1,'']]],
  ['grammar_20format_20specification_34',['Literate Grammar Format Specification',['../md_docs_2_l_i_t_e_r_a_t_e___f_o_r_m_a_t.html',1,'']]],
  ['grammar_20modes_35',['Grammar Modes',['../group__grammar__modes.html',1,'']]],
  ['grammar_20modification_20types_36',['Grammar Modification Types',['../md_docs_2_a_p_i.html#autotoc_md172',1,'']]],
  ['grammar_20modifications_37',['Grammar Modifications',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md95',1,'Grammar Modifications'],['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md276',1,'Grammar Modifications']]],
  ['grammar_20rule_20not_20taking_20effect_38',['Grammar rule not taking effect',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md307',1,'']]],
  ['grammar_20rules_20mod_5fadd_5frule_39',['Adding Grammar Rules (&lt;span class=&quot;tt&quot;&gt;MOD_ADD_RULE&lt;/span&gt;)',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md278',1,'']]],
  ['grammar_20size_40',['JIT Compilation Cost by Grammar Size',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md373',1,'']]],
  ['grammar_20syntax_20differences_41',['Grammar Syntax Differences',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md427',1,'']]],
  ['grammar_5fcontext_2eh_42',['grammar_context.h',['../grammar__context_8h.html',1,'']]],
  ['grammar_5fcontext_5fclose_5fbracket_43',['grammar_context_close_bracket',['../group__grammar__ctx__api.html#gacdca8dc0c1e3e36b445ee9eb6f98d53c',1,'grammar_context.h']]],
  ['grammar_5fcontext_5fcreate_44',['grammar_context_create',['../group__grammar__ctx__api.html#ga26bb20fcb43b746a5a7f3e67cc0f0036',1,'grammar_context.h']]],
  ['grammar_5fcontext_5fcurrent_5fmode_45',['grammar_context_current_mode',['../group__grammar__ctx__api.html#ga32fc6347944cc9523f2dcba89eb18763',1,'grammar_context.h']]],
  ['grammar_5fcontext_5fcurrent_5fsnapshot_46',['grammar_context_current_snapshot',['../group__grammar__ctx__api.html#ga56febb6cde1f6b6199abb12bd1329149',1,'grammar_context.h']]],
  ['grammar_5fcontext_5fdepth_47',['grammar_context_depth',['../group__grammar__ctx__api.html#gab3dd699224dd716c7e24fd9b130f7610',1,'grammar_context.h']]],
  ['grammar_5fcontext_5fdestroy_48',['grammar_context_destroy',['../group__grammar__ctx__api.html#ga42121159b63be436cedf9a056e2f721b',1,'grammar_context.h']]],
  ['grammar_5fcontext_5fdetect_5fexit_49',['grammar_context_detect_exit',['../group__grammar__ctx__api.html#ga47e882a5931bd358ff1843bf5a3d3982',1,'grammar_context.h']]],
  ['grammar_5fcontext_5fdetect_5fswitch_50',['grammar_context_detect_switch',['../group__grammar__ctx__api.html#gaf7e6ca75ed1f3a8d16cf3065a136d8de',1,'grammar_context.h']]],
  ['grammar_5fcontext_5fis_5froot_5fonly_51',['grammar_context_is_root_only',['../group__grammar__ctx__api.html#ga6507bbb0d508ed5070d0de02762698f3',1,'grammar_context.h']]],
  ['grammar_5fcontext_5fopen_5fbracket_52',['grammar_context_open_bracket',['../group__grammar__ctx__api.html#gae4759f9b92a0da094bf61a81ad350e73',1,'grammar_context.h']]],
  ['grammar_5fcontext_5fpop_53',['grammar_context_pop',['../group__grammar__ctx__api.html#ga1ba1e4f09e379f1b0ccf277955f769ff',1,'grammar_context.h']]],
  ['grammar_5fcontext_5fpush_54',['grammar_context_push',['../group__grammar__ctx__api.html#ga8b698918b1a4a81cbc876cdad1e25aa6',1,'grammar_context.h']]],
  ['grammar_5fcontext_5fregister_5fmode_55',['grammar_context_register_mode',['../group__grammar__ctx__api.html#ga7904d62416f2ba815c95f93c61b93099',1,'grammar_context.h']]],
  ['grammar_5fcontext_5fset_5fswitch_5fcallback_56',['grammar_context_set_switch_callback',['../group__grammar__ctx__api.html#ga7cbab6e7ce73f21f1b143ea4ea169e84',1,'grammar_context.h']]],
  ['grammar_5fname_57',['grammar_name',['../struct_lime_context.html#ab18c1d38af115ebd3f4631baa1f694d3',1,'LimeContext']]],
  ['grammarcontextentry_58',['GrammarContextEntry',['../struct_grammar_context_entry.html',1,'']]],
  ['grammarcontextstack_59',['GrammarContextStack',['../group__ctx__stack.html#ga22b423837bd1c80b1e55916066b1d0ad',1,'grammar_context.h']]],
  ['grammarextensionmetadata_60',['GrammarExtensionMetadata',['../struct_grammar_extension_metadata.html',1,'']]],
  ['grammarmode_61',['GrammarMode',['../group__grammar__modes.html#gac879c49c0a97d7abdd1b5f5bf8903290',1,'grammar_context.h']]],
  ['grammarmodeinfo_62',['GrammarModeInfo',['../struct_grammar_mode_info.html',1,'']]],
  ['grammars_20and_20parsers_63',['Grammars and Parsers',['../md_docs_2_c_o_n_c_e_p_t_s.html#autotoc_md26',1,'']]],
  ['grow_20too_20large_64',['Parser tables grow too large',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md309',1,'']]],
  ['gssnode_65',['GSSNode',['../struct_g_s_s_node.html',1,'']]],
  ['guarantee_66',['Hot-Swap Guarantee',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md505',1,'']]],
  ['guide_67',['Guide',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html',1,'Extension Development Guide'],['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md332',1,'Memory Budget Guide'],['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md534',1,'Migration Guide'],['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html',1,'Parser Generator Comparison Guide']]],
  ['guide_20examples_20lime_5fpostgres_68',['PostgreSQL Integration Guide (&lt;span class=&quot;tt&quot;&gt;examples/lime_postgres/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md80',1,'']]]
];
