var searchData=
[
  ['of_20conflicts_0',['Types of Conflicts',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md242',1,'']]],
  ['of_20contents_1',['of Contents',['../md_docs_2_a_p_i.html#autotoc_md117',1,'Table of Contents'],['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md202',1,'Table of Contents'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md340',1,'Table of Contents']]],
  ['on_20action_20table_20lookups_2',['Speedup from JIT on Action Table Lookups',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md460',1,'']]],
  ['on_20extension_20load_3',['JIT Invalidation on Extension Load',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md371',1,'']]],
  ['on_20write_20and_20thread_20safety_4',['Copy-on-Write and Thread Safety',['../md_docs_2_c_o_n_c_e_p_t_s.html#autotoc_md33',1,'']]],
  ['on_20write_20modification_5',['Copy-on-Write Modification',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md87',1,'']]],
  ['on_20write_20snapshot_20architecture_6',['Copy-on-Write Snapshot Architecture',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md84',1,'']]],
  ['on_5fconflict_20optional_7',['on_conflict (optional)',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md284',1,'']]],
  ['on_5funload_8',['Segmentation fault in on_unload',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md308',1,'']]],
  ['on_5funload_20optional_9',['on_unload (optional)',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md285',1,'']]],
  ['once_20reset_20between_20parses_10',['Pattern A: Allocate once, reset between parses',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md54',1,'']]],
  ['one_20time_11',['Loading Costs (One-Time)',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md324',1,'']]],
  ['only_12',['only',['../md_docs_2_a_p_i.html#autotoc_md163',1,'classify_simd_avx2 (x86_64 only)'],['../md_docs_2_a_p_i.html#autotoc_md164',1,'classify_simd_neon (ARM only)']]],
  ['only_20no_20extension_20framework_13',['Option 1: Generator Only (No Extension Framework)',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md39',1,'']]],
  ['operations_14',['Snapshot Operations',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md313',1,'']]],
  ['optimization_15',['Optimization',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md336',1,'Memory Optimization'],['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md477',1,'Tokenizer JIT - Highest Value Optimization']]],
  ['option_201_3a_20generator_20only_20no_20extension_20framework_16',['Option 1: Generator Only (No Extension Framework)',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md39',1,'']]],
  ['option_202_3a_20generator_20extension_20framework_20meson_17',['Option 2: Generator + Extension Framework (Meson)',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md40',1,'']]],
  ['option_203_3a_20generator_20extension_20framework_20make_20cmake_18',['Option 3: Generator + Extension Framework (Make / CMake)',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md43',1,'']]],
  ['optional_19',['optional',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md284',1,'on_conflict (optional)'],['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md285',1,'on_unload (optional)']]],
  ['optional_20callbacks_20',['Optional Callbacks',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md493',1,'']]],
  ['optional_20dependencies_21',['Optional Dependencies',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md553',1,'']]],
  ['optional_20fields_22',['Optional Fields',['../md_docs_2_l_i_t_e_r_a_t_e___f_o_r_m_a_t.html#autotoc_md563',1,'']]],
  ['oracle_23',['oracle',['../struct_grammar_extension_metadata.html#a4bf8bcf74c1f777defc2c418fcada5d3',1,'GrammarExtensionMetadata']]],
  ['oracle_20callback_24',['Oracle Callback',['../group__oracle__cb.html',1,'']]],
  ['oracle_20disambiguation_20examples_20llm_5foracle_25',['LLM Oracle Disambiguation (&lt;span class=&quot;tt&quot;&gt;examples/llm_oracle/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md77',1,'']]],
  ['oraclecallback_26',['OracleCallback',['../group__oracle__cb.html#ga1e3202f12134a0e943476ceefa75afb5',1,'extension_registry.h']]],
  ['oraclecontext_27',['OracleContext',['../struct_oracle_context.html',1,'']]],
  ['orcjit_20migration_28',['MCJIT vs OrcJIT Migration',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md472',1,'']]],
  ['orcjit_20recommended_29',['OrcJIT (Recommended)',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md474',1,'']]],
  ['order_20result_30',['Topological Order Result',['../group__ext__order.html',1,'']]],
  ['ordering_20matters_31',['Extension ordering matters',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md303',1,'']]],
  ['organization_32',['Module Organization',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md538',1,'']]],
  ['original_20bison_20bootparse_20y_20excerpt_33',['Original Bison (bootparse.y excerpt)',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md439',1,'']]],
  ['output_34',['Composed Output',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md533',1,'']]],
  ['output_20format_35',['Output Format',['../md_docs_2_l_i_t_e_r_a_t_e___f_o_r_m_a_t.html#autotoc_md571',1,'']]],
  ['over_20yacc_20bison_36',['Why Lime over Yacc/Bison?',['../index.html#autotoc_md3',1,'']]],
  ['overhead_37',['Overhead',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md323',1,'Extension Overhead'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md393',1,'Measuring Extension Overhead'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md350',1,'Memory Overhead'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md382',1,'Tiebreaker Rule Overhead']]],
  ['overhead_20breakdown_38',['Component Overhead Breakdown',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md344',1,'']]],
  ['overhead_20per_20extension_39',['Memory Overhead Per Extension',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md327',1,'']]],
  ['overview_40',['Overview',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md342',1,'Architecture Overview'],['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md490',1,'Architecture Overview'],['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md83',1,'Component Overview'],['../index.html#autotoc_md1',1,'Overview'],['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md82',1,'Overview'],['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md270',1,'Overview'],['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md400',1,'Overview'],['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md455',1,'Overview'],['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md521',1,'Overview'],['../md_docs_2_l_i_t_e_r_a_t_e___f_o_r_m_a_t.html#autotoc_md559',1,'Overview']]],
  ['ownership_20model_41',['Ownership Model',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md110',1,'']]],
  ['ownership_20rules_42',['Ownership Rules',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md512',1,'']]]
];
