var searchData=
[
  ['data_20structure_0',['Data Structure',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md500',1,'']]],
  ['data_20structure_20sizes_1',['Appendix: Data Structure Sizes',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md397',1,'']]],
  ['data_20structures_20reference_2',['Data Structures Reference',['../md_docs_2_a_p_i.html#autotoc_md186',1,'']]],
  ['datalog_3',['Datalog/EDN (&lt;span class=&quot;tt&quot;&gt;examples/datalog/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md76',1,'']]],
  ['datalog_20edn_20examples_20datalog_4',['Datalog/EDN (&lt;span class=&quot;tt&quot;&gt;examples/datalog/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md76',1,'']]],
  ['decision_20tree_5',['Deployment Decision Tree',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md486',1,'']]],
  ['declaration_20keyword_3a_20module_5fname_6',['&quot;Unknown declaration keyword: %module_name&quot;',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md546',1,'']]],
  ['declarations_7',['Declarations',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md429',1,'Token Declarations'],['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md430',1,'Type Declarations']]],
  ['default_20thresholds_8',['Default Thresholds',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md484',1,'']]],
  ['define_20the_20extensioninfo_20descriptor_9',['Step 3: Define the ExtensionInfo descriptor',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md290',1,'']]],
  ['define_20the_20modifications_20array_10',['Step 1: Define the modifications array',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md288',1,'']]],
  ['degradation_11',['Graceful Degradation',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md103',1,'']]],
  ['dependencies_12',['Dependencies',['../md_docs_2_l_i_t_e_r_a_t_e___f_o_r_m_a_t.html#autotoc_md569',1,'Cyclic Dependencies'],['../index.html#autotoc_md12',1,'Dependencies'],['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md526',1,'Dependencies'],['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md553',1,'Optional Dependencies']]],
  ['dependency_20detected_20among_20modules_13',['&quot;Cyclic dependency detected among modules&quot;',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md548',1,'']]],
  ['dependency_20management_14',['Dependency Management',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md540',1,'']]],
  ['deployment_20decision_20tree_15',['Deployment Decision Tree',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md486',1,'']]],
  ['depth_16',['depth',['../struct_grammar_context_entry.html#a11e19de9d21f4dd618710a165f624634',1,'GrammarContextEntry']]],
  ['description_17',['description',['../struct_conflict.html#a43551830b89d6dc0f3b88bb517ef7110',1,'Conflict::description'],['../struct_conflict_point.html#aef8e0e915b841b354b420bfda52dcde5',1,'ConflictPoint::description']]],
  ['descriptor_18',['Step 3: Define the ExtensionInfo descriptor',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md290',1,'']]],
  ['deserialize_5fsnapshot_19',['deserialize_snapshot',['../struct_lime_parser_plugin.html#ae8b9fc6b153594cca6eec9ef8d0b23fc',1,'LimeParserPlugin']]],
  ['design_20',['Design',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md92',1,'Design'],['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html',1,'Parser Plugin Design']]],
  ['destroy_21',['destroy',['../struct_disambiguation_strategy_v_table.html#a316b994e984425e81104d19a6c23011e',1,'DisambiguationStrategyVTable::destroy'],['../struct_lime_parser_plugin.html#a891bed38f2b4aa84bfb2e161e236f750',1,'LimeParserPlugin::destroy']]],
  ['destroy_5ftoken_5ftable_22',['destroy_token_table',['../md_docs_2_a_p_i.html#autotoc_md153',1,'']]],
  ['detailed_20comparisons_23',['Detailed Comparisons',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md408',1,'']]],
  ['detect_5fall_5fmulti_5fgrammar_5fconflicts_24',['detect_all_multi_grammar_conflicts',['../group__multi__detect__api.html#gaa861434ea59292552bb6d5d1f97bc554',1,'conflict.h']]],
  ['detect_5fconflict_25',['detect_conflict',['../group__multi__detect__api.html#gaa0d9ca046afba5926b872452ddf5da6f',1,'conflict.h']]],
  ['detect_5fconflicts_26',['detect_conflicts',['../group__conflict__detect.html#ga8f9ae48af0bda7e7ed199b540170e057',1,'conflict.h']]],
  ['detect_5frule_5fconflicts_27',['detect_rule_conflicts',['../group__multi__detect__api.html#ga4b5a7d55f868310cb587b11bedfe2793',1,'conflict.h']]],
  ['detect_5fsemantic_5fconflicts_28',['detect_semantic_conflicts',['../group__multi__detect__api.html#gacdf3ad2c8488d014a16472dfa7ec80ef',1,'conflict.h']]],
  ['detect_5ftoken_5fconflicts_29',['detect_token_conflicts',['../group__multi__detect__api.html#ga2f789b8c51b6999908441467bc9fae0f',1,'conflict.h']]],
  ['detected_20among_20modules_30',['&quot;Cyclic dependency detected among modules&quot;',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md548',1,'']]],
  ['detection_31',['Detection',['../group__conflict__detect.html',1,'Conflict Detection'],['../md_docs_2_c_o_n_c_e_p_t_s.html#autotoc_md30',1,'Conflict Detection'],['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md96',1,'Conflict Detection'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md346',1,'Conflict Detection'],['../md_docs_2_l_i_t_e_r_a_t_e___f_o_r_m_a_t.html#autotoc_md570',1,'Duplicate Detection'],['../group__multi__grammar.html',1,'Multi-Grammar Conflict Detection']]],
  ['detection_20api_32',['Multi-Grammar Conflict Detection API',['../group__multi__detect__api.html',1,'']]],
  ['detection_20types_33',['Conflict Detection Types',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md294',1,'']]],
  ['development_34',['Extension Development',['../index.html#autotoc_md9',1,'']]],
  ['development_20guide_35',['Extension Development Guide',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html',1,'']]],
  ['dialect_20extensions_20contrib_36',['SQL Dialect Extensions (&lt;span class=&quot;tt&quot;&gt;contrib/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md79',1,'']]],
  ['differences_37',['Grammar Syntax Differences',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md427',1,'']]],
  ['differences_20from_20yacc_38',['Key Differences from Yacc',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___y_a_c_c.html#autotoc_md445',1,'']]],
  ['differences_20from_20yacc_20bison_39',['Key Differences from Yacc/Bison',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md219',1,'']]],
  ['directive_20format_40',['Why Directive Format?',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md522',1,'']]],
  ['directive_20mapping_41',['Directive Mapping',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md426',1,'']]],
  ['directive_20mapping_20yacc_20specific_42',['Directive Mapping (Yacc-Specific)',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___y_a_c_c.html#autotoc_md449',1,'']]],
  ['directive_20syntax_43',['Directive Syntax',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md524',1,'']]],
  ['directory_20layout_44',['Directory Layout',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md115',1,'']]],
  ['disambig_5fcontext_45',['DISAMBIG_CONTEXT',['../group__disambig__strategy.html#gga8eca7cbd950b2677cbbae73d04289cb6ac702df7e3066a1e0592ab5199c4404fa',1,'extension_registry.h']]],
  ['disambig_5ffork_5fresolve_46',['DISAMBIG_FORK_RESOLVE',['../group__disambig__strategy.html#gga8eca7cbd950b2677cbbae73d04289cb6a3a93a13c79d01846766d372a6a50393d',1,'extension_registry.h']]],
  ['disambig_5fnone_47',['DISAMBIG_NONE',['../group__disambig__strategy.html#gga8eca7cbd950b2677cbbae73d04289cb6afbad9ebf287d491f6f1e77cdc6c89020',1,'extension_registry.h']]],
  ['disambig_5foracle_48',['DISAMBIG_ORACLE',['../group__disambig__strategy.html#gga8eca7cbd950b2677cbbae73d04289cb6a3863db516f03bb0ed0ac9373cde3ed9e',1,'extension_registry.h']]],
  ['disambig_5fpriority_49',['DISAMBIG_PRIORITY',['../group__disambig__strategy.html#gga8eca7cbd950b2677cbbae73d04289cb6af1064e998cfa2dd3d220425c5520cdfc',1,'extension_registry.h']]],
  ['disambiguation_20api_50',['Disambiguation API',['../group__disambig__api.html',1,'']]],
  ['disambiguation_20context_51',['Disambiguation Context',['../group__disambig__ctx.html',1,'']]],
  ['disambiguation_20examples_20llm_5foracle_52',['LLM Oracle Disambiguation (&lt;span class=&quot;tt&quot;&gt;examples/llm_oracle/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md77',1,'']]],
  ['disambiguation_20framework_53',['Disambiguation Framework',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md347',1,'']]],
  ['disambiguation_20strategies_54',['Disambiguation Strategies',['../group__disambig__strategy.html',1,'Disambiguation Strategies'],['../md_docs_2_c_o_n_c_e_p_t_s.html#autotoc_md31',1,'Disambiguation Strategies'],['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md326',1,'Disambiguation Strategies']]],
  ['disambiguation_20strategy_20performance_55',['Disambiguation Strategy Performance',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md365',1,'']]],
  ['disambiguation_20strategy_20selection_56',['Disambiguation Strategy Selection',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md386',1,'']]],
  ['disambiguation_2eh_57',['disambiguation.h',['../disambiguation_8h.html',1,'']]],
  ['disambiguation_5fcreate_58',['disambiguation_create',['../group__disambig__api.html#ga95bae05db969294d0385e4e367a25cdc',1,'disambiguation.h']]],
  ['disambiguation_5fcreate_5fcustom_59',['disambiguation_create_custom',['../group__disambig__api.html#gaa634cf8c444d72fb444185dae4f93135',1,'disambiguation.h']]],
  ['disambiguation_5fdestroy_60',['disambiguation_destroy',['../group__disambig__api.html#gaafef41bc2073cb5ced490834ca1188f9',1,'disambiguation.h']]],
  ['disambiguation_5fget_5fstrategy_61',['disambiguation_get_strategy',['../group__disambig__api.html#gac0c6a1b94c92ca22373f1c88c8ad6be8',1,'disambiguation.h']]],
  ['disambiguation_5fresolve_62',['disambiguation_resolve',['../group__disambig__api.html#ga8b7b1ebbb9a66a39a90c2cc9b9ac1bcf',1,'disambiguation.h']]],
  ['disambiguation_5fstrategy_5fname_63',['disambiguation_strategy_name',['../group__disambig__api.html#ga9f3146d3c88ee9ab43b7195355cc5e3d',1,'disambiguation.h']]],
  ['disambiguation_5fupdate_64',['disambiguation_update',['../group__disambig__api.html#gad1b9bf0f98e5e8c864aa388e81ceaa28',1,'disambiguation.h']]],
  ['disambiguationcontext_65',['DisambiguationContext',['../group__disambig__ctx.html#ga5997e40251a6dc35353abe15ed02aa47',1,'disambiguation.h']]],
  ['disambiguationstrategy_66',['DisambiguationStrategy',['../group__disambig__strategy.html#ga8eca7cbd950b2677cbbae73d04289cb6',1,'extension_registry.h']]],
  ['disambiguationstrategyvtable_67',['DisambiguationStrategyVTable',['../struct_disambiguation_strategy_v_table.html',1,'']]],
  ['dispatch_68',['Runtime Dispatch',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md105',1,'']]],
  ['documentation_69',['Documentation',['../index.html#autotoc_md6',1,'']]],
  ['downgrade_20flow_70',['Upgrade / Downgrade Flow',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md509',1,'']]],
  ['doxygen_71',['Doxygen',['../index.html#autotoc_md7',1,'']]],
  ['driven_20baseline_72',['Interpreted (Table-Driven) Baseline',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md319',1,'']]],
  ['driver_73',['Writing a Driver',['../md_docs_2_g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md21',1,'']]],
  ['duplicate_20detection_74',['Duplicate Detection',['../md_docs_2_l_i_t_e_r_a_t_e___f_o_r_m_a_t.html#autotoc_md570',1,'']]],
  ['dynamic_20loading_75',['Dynamic Loading',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md495',1,'']]],
  ['dynamic_20plugin_20entry_20point_76',['Dynamic Plugin Entry Point',['../group__plugin__entry.html',1,'']]],
  ['dynamically_20allocated_20modifications_77',['Free dynamically allocated modifications',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md300',1,'']]]
];
