var searchData=
[
  ['s_20approach_0',['Lime&apos;s Approach',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md218',1,'']]],
  ['safety_1',['Safety',['../md_docs_2_c_o_n_c_e_p_t_s.html#autotoc_md33',1,'Copy-on-Write and Thread Safety'],['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md106',1,'Thread Safety'],['../md_docs_2_a_p_i.html#autotoc_md193',1,'Thread Safety']]],
  ['safety_2',['Thread safety',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md302',1,'']]],
  ['safety_20checklist_3',['Thread Safety Checklist',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md57',1,'']]],
  ['savings_4',['Space Savings',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md252',1,'']]],
  ['scaling_20behavior_5',['Scaling Behavior',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md329',1,'Scaling Behavior'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md375',1,'Scaling Behavior']]],
  ['scaling_20summary_6',['Scaling Summary',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md380',1,'']]],
  ['segmentation_20fault_20in_20on_5funload_7',['Segmentation fault in on_unload',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md308',1,'']]],
  ['selection_8',['Disambiguation Strategy Selection',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md386',1,'']]],
  ['semantic_20level_20conflicts_9',['Semantic-Level Conflicts',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md363',1,'']]],
  ['semantic_5fconflicts_10',['semantic_conflicts',['../struct_multi_grammar_conflict_result.html#a176b8a87e8b8b7740b39fd1d34747079',1,'MultiGrammarConflictResult']]],
  ['semantic_5fresult_11',['semantic_result',['../struct_parse_fork.html#a975362357eb2ea95166a7908f6c67570',1,'ParseFork']]],
  ['semver_12',['SemVer',['../struct_sem_ver.html',1,'']]],
  ['serialize_5fsnapshot_13',['serialize_snapshot',['../struct_lime_parser_plugin.html#af2307e46ef565076f5812312ee6dbfa7',1,'LimeParserPlugin']]],
  ['session_14',['Parse Session',['../md_docs_2_a_p_i.html#autotoc_md198',1,'']]],
  ['session_20isolation_15',['Session Isolation',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md506',1,'']]],
  ['set_16',['Conflict Set',['../group__conflict__set.html',1,'']]],
  ['set_20management_17',['Fork Set Management',['../group__fork__set.html',1,'']]],
  ['setting_20the_20active_20plugin_18',['Setting the Active Plugin',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md504',1,'']]],
  ['shared_20library_20plugins_19',['Shared Library Plugins',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md496',1,'']]],
  ['shift_20reduce_20example_20',['A Shift-Reduce Example',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md205',1,'']]],
  ['should_5fexecute_21',['should_execute',['../struct_grammar_extension_metadata.html#adeb45d60cc3d757e09179fda14fc7e36',1,'GrammarExtensionMetadata']]],
  ['simd_20acceleration_22',['SIMD Acceleration',['../md_docs_2_a_p_i.html#autotoc_md147',1,'']]],
  ['simd_20character_20classification_23',['SIMD Character Classification',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md315',1,'']]],
  ['simd_20character_20classification_20api_24',['SIMD Character Classification API',['../md_docs_2_a_p_i.html#autotoc_md158',1,'']]],
  ['simd_20helps_20least_25',['When SIMD Helps Least',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md317',1,'']]],
  ['simd_20helps_20most_26',['When SIMD Helps Most',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md316',1,'']]],
  ['simd_20tokenization_27',['SIMD Tokenization',['../md_docs_2_c_o_n_c_e_p_t_s.html#autotoc_md34',1,'SIMD Tokenization'],['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md97',1,'SIMD Tokenization']]],
  ['simple_20lr_28',['SLR(1) &amp;ndash; Simple LR',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md209',1,'']]],
  ['size_29',['JIT Compilation Cost by Grammar Size',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md373',1,'']]],
  ['sizes_30',['Appendix: Data Structure Sizes',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md397',1,'']]],
  ['slr_201_20ndash_20simple_20lr_31',['SLR(1) &amp;ndash; Simple LR',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md209',1,'']]],
  ['snapshot_32',['snapshot',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md298',1,'Inspect the base snapshot'],['../struct_grammar_context_entry.html#a6ec8418e79e799c51afba652c313d241',1,'GrammarContextEntry::snapshot'],['../struct_grammar_mode_info.html#afc9dcbf7f7e34ef74cf49077de9e0beb',1,'GrammarModeInfo::snapshot'],['../struct_parse_fork.html#a16f50d0f4febc37f7062525b93b891c2',1,'ParseFork::snapshot']]],
  ['snapshot_20api_33',['Snapshot API',['../group__snapshot__api.html',1,'Snapshot API'],['../md_docs_2_a_p_i.html#autotoc_md121',1,'Snapshot API']]],
  ['snapshot_20architecture_34',['Copy-on-Write Snapshot Architecture',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md84',1,'']]],
  ['snapshot_20h_35',['ParserSnapshot (src/snapshot.h)',['../md_docs_2_a_p_i.html#autotoc_md187',1,'']]],
  ['snapshot_20indirected_20table_20access_36',['Snapshot-Indirected Table Access',['../md_docs_2_a_p_i.html#autotoc_md135',1,'']]],
  ['snapshot_20integration_37',['Snapshot Integration',['../md_docs_2_a_p_i.html#autotoc_md180',1,'']]],
  ['snapshot_20lifecycle_38',['Snapshot Lifecycle',['../md_docs_2_a_p_i.html#autotoc_md197',1,'']]],
  ['snapshot_20lifecycle_20under_20the_20manager_39',['Snapshot Lifecycle Under the Manager',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md513',1,'']]],
  ['snapshot_20memory_40',['Snapshot Memory',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md314',1,'']]],
  ['snapshot_20operations_41',['Snapshot Operations',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md313',1,'']]],
  ['snapshots_42',['Snapshots',['../md_docs_2_c_o_n_c_e_p_t_s.html#autotoc_md27',1,'']]],
  ['space_20complexity_43',['Space Complexity',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md261',1,'']]],
  ['space_20savings_44',['Space Savings',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md252',1,'']]],
  ['specific_45',['Directive Mapping (Yacc-Specific)',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___y_a_c_c.html#autotoc_md449',1,'']]],
  ['specification_46',['Literate Grammar Format Specification',['../md_docs_2_l_i_t_e_r_a_t_e___f_o_r_m_a_t.html',1,'']]],
  ['speedup_20from_20jit_20on_20action_20table_20lookups_47',['Speedup from JIT on Action Table Lookups',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md460',1,'']]],
  ['sql_20dialect_20extensions_20contrib_48',['SQL Dialect Extensions (&lt;span class=&quot;tt&quot;&gt;contrib/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md79',1,'']]],
  ['sql_20parser_20ndash_20api_20reference_49',['Extensible SQL Parser &amp;ndash; API Reference',['../md_docs_2_a_p_i.html',1,'']]],
  ['src_20extension_20h_50',['Internal Registry API (src/extension.h)',['../md_docs_2_a_p_i.html#autotoc_md168',1,'']]],
  ['src_20snapshot_20h_51',['ParserSnapshot (src/snapshot.h)',['../md_docs_2_a_p_i.html#autotoc_md187',1,'']]],
  ['stack_20allocated_20parser_20zero_20mallocs_52',['Pattern B: Stack-allocated parser (zero mallocs)',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md55',1,'']]],
  ['stack_20handle_53',['Context Stack Handle',['../group__ctx__stack.html',1,'']]],
  ['stack_5fcapacity_54',['stack_capacity',['../struct_cloned_parser_state.html#a4b20e1a530817bc57c2f40f7bfa1380b',1,'ClonedParserState']]],
  ['stack_5fdata_55',['stack_data',['../struct_cloned_parser_state.html#a92e75ea26f236a594830bcd37a6c1774',1,'ClonedParserState']]],
  ['stack_5fdepth_56',['stack_depth',['../struct_cloned_parser_state.html#adcbd12fb59fe3accf2ea6f12324f6425',1,'ClonedParserState']]],
  ['stack_5fis_5finline_57',['stack_is_inline',['../struct_cloned_parser_state.html#abce8e780e2489f889e61267e6567cd17',1,'ClonedParserState']]],
  ['stack_5fsize_58',['stack_size',['../struct_cloned_parser_state.html#a492cb4718a1d424a39d45248dd46ab44',1,'ClonedParserState']]],
  ['start_59',['Quick Start',['../index.html#autotoc_md4',1,'']]],
  ['start_5foffset_60',['start_offset',['../struct_grammar_context_entry.html#aedbd279154b97ebef678856650bbf0a3',1,'GrammarContextEntry']]],
  ['started_61',['Getting Started',['../md_docs_2_g_e_t_t_i_n_g___s_t_a_r_t_e_d.html',1,'']]],
  ['state_62',['State',['../group__cloned__state.html',1,'Cloned Parser State'],['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md255',1,'Parser State']]],
  ['state_63',['state',['../struct_lime_context.html#ac53e6722bfc349b3ccb9cb427c4d1e51',1,'LimeContext::state'],['../struct_conflict_point.html#aa25ff9154c5d816996faafb4a74b000d',1,'ConflictPoint::state'],['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md301',1,'Use user_data for state']]],
  ['state_20access_64',['Fork State Access',['../group__fork__access.html',1,'']]],
  ['state_20identity_65',['State Identity',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md238',1,'']]],
  ['state_20machine_20construction_66',['State Machine Construction',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md234',1,'']]],
  ['state_20reordering_67',['State Reordering',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md251',1,'']]],
  ['state_5fdata_68',['state_data',['../struct_cloned_parser_state.html#a7e4cfebd1546eafcaa0eda36c48f11c0',1,'ClonedParserState']]],
  ['state_5fsize_69',['state_size',['../struct_cloned_parser_state.html#a00e7199579b4bfc621eead43d8fa164d',1,'ClonedParserState']]],
  ['static_20plugins_70',['Static Plugins',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md497',1,'']]],
  ['status_71',['Fork Status',['../group__fork__status.html',1,'']]],
  ['status_72',['status',['../struct_parse_fork.html#ad5bc33305aa2daddc7f706528b976ee8',1,'ParseFork']]],
  ['status_20codes_73',['Manager Status Codes',['../group__manager__status.html',1,'']]],
  ['step_2010_3a_20reporttable_74',['Step 10: ReportTable',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md232',1,'']]],
  ['step_201_3a_20define_20the_20modifications_20array_75',['Step 1: Define the modifications array',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md288',1,'']]],
  ['step_201_3a_20parse_76',['Step 1: Parse',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md223',1,'']]],
  ['step_202_3a_20findruleprecedences_77',['Step 2: FindRulePrecedences',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md224',1,'']]],
  ['step_202_3a_20implement_20the_20callbacks_78',['Step 2: Implement the callbacks',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md289',1,'']]],
  ['step_203_3a_20define_20the_20extensioninfo_20descriptor_79',['Step 3: Define the ExtensionInfo descriptor',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md290',1,'']]],
  ['step_203_3a_20findfirstsets_80',['Step 3: FindFirstSets',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md225',1,'']]],
  ['step_204_3a_20convenience_20registration_20function_81',['Step 4: Convenience registration function',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md291',1,'']]],
  ['step_204_3a_20findstates_82',['Step 4: FindStates',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md226',1,'']]],
  ['step_205_3a_20findlinks_83',['Step 5: FindLinks',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md227',1,'']]],
  ['step_206_3a_20findfollowsets_84',['Step 6: FindFollowSets',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md228',1,'']]],
  ['step_207_3a_20findactions_85',['Step 7: FindActions',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md229',1,'']]],
  ['step_208_3a_20compresstables_86',['Step 8: CompressTables',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md230',1,'']]],
  ['step_209_3a_20resortstates_87',['Step 9: ResortStates',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md231',1,'']]],
  ['step_20pipeline_88',['The 10-Step Pipeline',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md222',1,'']]],
  ['steps_89',['Next Steps',['../md_docs_2_g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md24',1,'']]],
  ['stop_5fon_5ferror_90',['stop_on_error',['../struct_execution_policy_config.html#a49e668534f2f8aa22d7d9826cdfd3508',1,'ExecutionPolicyConfig']]],
  ['strat_5fbayesian_91',['STRAT_BAYESIAN',['../group__strat__ids.html#gga521a48a44c0ca8862a0935ad1324716bae1dc836d9943779d45c1e25ef5dbc305',1,'disambiguation.h']]],
  ['strat_5fcustom_92',['STRAT_CUSTOM',['../group__strat__ids.html#gga521a48a44c0ca8862a0935ad1324716bab80f1090b1b9895d684e9dbacb2dea21',1,'disambiguation.h']]],
  ['strat_5ffork_5fresolve_93',['STRAT_FORK_RESOLVE',['../group__strat__ids.html#gga521a48a44c0ca8862a0935ad1324716ba0cc3d5e55b0dbc3113512ca10ba5f2d8',1,'disambiguation.h']]],
  ['strat_5fllm_94',['STRAT_LLM',['../group__strat__ids.html#gga521a48a44c0ca8862a0935ad1324716baabddd3dec996ef9369cebd231ff214fb',1,'disambiguation.h']]],
  ['strat_5fpriority_95',['STRAT_PRIORITY',['../group__strat__ids.html#gga521a48a44c0ca8862a0935ad1324716ba8de80da030e99067e5e3daa7d5a6f4b4',1,'disambiguation.h']]],
  ['strategies_96',['Strategies',['../group__disambig__strategy.html',1,'Disambiguation Strategies'],['../md_docs_2_c_o_n_c_e_p_t_s.html#autotoc_md31',1,'Disambiguation Strategies'],['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md326',1,'Disambiguation Strategies']]],
  ['strategy_97',['Strategy',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md111',1,'Allocation Strategy'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md367',1,'Fork-Resolve Strategy'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md366',1,'Priority Strategy']]],
  ['strategy_98',['strategy',['../struct_grammar_extension_metadata.html#a10d90b2fb0673d0288d5afc01d0d260a',1,'GrammarExtensionMetadata']]],
  ['strategy_20comparison_99',['Strategy Comparison',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md368',1,'']]],
  ['strategy_20identifiers_100',['Strategy Identifiers',['../group__strat__ids.html',1,'']]],
  ['strategy_20performance_101',['Disambiguation Strategy Performance',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md365',1,'']]],
  ['strategy_20result_102',['Strategy Result',['../group__strat__result.html',1,'']]],
  ['strategy_20selection_103',['Disambiguation Strategy Selection',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md386',1,'']]],
  ['strategy_20vtable_104',['Strategy VTable',['../group__strat__vtable.html',1,'']]],
  ['strategy_5fresult_5fcleanup_105',['strategy_result_cleanup',['../group__strat__result.html#ga3d0be4cc0fad21fa33a747e8f08424d8',1,'disambiguation.h']]],
  ['strategy_5fresult_5finit_106',['strategy_result_init',['../group__strat__result.html#gaaba950e9dfad608e59d5e0102d259c4b',1,'disambiguation.h']]],
  ['strategyresult_107',['StrategyResult',['../struct_strategy_result.html',1,'']]],
  ['structure_108',['Structure',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md500',1,'Data Structure'],['../md_docs_2_l_i_t_e_r_a_t_e___f_o_r_m_a_t.html#autotoc_md560',1,'File Structure']]],
  ['structure_20sizes_109',['Appendix: Data Structure Sizes',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md397',1,'']]],
  ['structures_20reference_110',['Data Structures Reference',['../md_docs_2_a_p_i.html#autotoc_md186',1,'']]],
  ['subproject_111',['As a Meson subproject',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md41',1,'']]],
  ['subsystem_20parsers_112',['PostgreSQL Subsystem Parsers',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md65',1,'']]],
  ['suite_113',['Running the Parser Benchmark Suite',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md392',1,'']]],
  ['summary_114',['Scaling Summary',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md380',1,'']]],
  ['support_115',['Hot-Swap Support',['../group__hot__swap.html',1,'']]],
  ['swap_116',['Active Parser and Hot-Swap',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md503',1,'']]],
  ['swap_20guarantee_117',['Hot-Swap Guarantee',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md505',1,'']]],
  ['swap_20support_118',['Hot-Swap Support',['../group__hot__swap.html',1,'']]],
  ['switch_20callback_119',['Context Switch Callback',['../group__ctx__switch__cb.html',1,'']]],
  ['symbol_20collisions_120',['Avoiding Symbol Collisions',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md50',1,'']]],
  ['symbol_20x_20is_20exported_20by_20both_20a_20and_20b_121',['&quot;Symbol &apos;X&apos; is exported by both &apos;A&apos; and &apos;B&apos;&quot;',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md549',1,'']]],
  ['symbols_122',['Re-exporting Symbols',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md552',1,'']]],
  ['symbols_123',['symbols',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md51',1,'Generated parser symbols'],['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md52',1,'Library (extension framework) symbols']]],
  ['synchronization_20mechanisms_124',['Synchronization Mechanisms',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md107',1,'']]],
  ['synchronous_20replication_20config_20examples_20syncrep_125',['Synchronous Replication Config (&lt;span class=&quot;tt&quot;&gt;examples/syncrep/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md69',1,'']]],
  ['syncrep_126',['Synchronous Replication Config (&lt;span class=&quot;tt&quot;&gt;examples/syncrep/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md69',1,'']]],
  ['syntax_127',['Syntax',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md524',1,'Directive Syntax'],['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md428',1,'Rule Syntax']]],
  ['syntax_20differences_128',['Grammar Syntax Differences',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md427',1,'']]],
  ['syntax_20translation_129',['Rule Syntax Translation',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___y_a_c_c.html#autotoc_md450',1,'']]],
  ['system_130',['System',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md112',1,'Build System'],['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md91',1,'Extension System'],['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md515',1,'Extension System'],['../md_docs_2_c_o_n_c_e_p_t_s.html#autotoc_md36',1,'Module System']]],
  ['system_20changes_131',['Build System Changes',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md434',1,'']]],
  ['system_20library_132',['As a system library',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md42',1,'']]],
  ['systems_133',['Integration with Existing Systems',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md514',1,'']]]
];
