var searchData=
[
  ['b_0',['&quot;Symbol &apos;X&apos; is exported by both &apos;A&apos; and &apos;B&apos;&quot;',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md549',1,'']]],
  ['b_3a_20stack_20allocated_20parser_20zero_20mallocs_1',['Pattern B: Stack-allocated parser (zero mallocs)',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md55',1,'']]],
  ['bar_20which_20is_20not_20available_2',['&quot;Module &apos;foo&apos; requires &apos;bar&apos;, which is not available&quot;',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md547',1,'']]],
  ['base_20snapshot_3',['Inspect the base snapshot',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md298',1,'']]],
  ['based_20keyword_20classifier_4',['Trie-Based Keyword Classifier',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md479',1,'']]],
  ['based_20resolution_5',['Precedence-Based Resolution',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md243',1,'']]],
  ['baseline_6',['Interpreted (Table-Driven) Baseline',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md319',1,'']]],
  ['baseline_20no_20extensions_7',['Baseline (No Extensions)',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md356',1,'']]],
  ['basic_20tokenization_8',['Basic Tokenization',['../md_docs_2_a_p_i.html#autotoc_md196',1,'']]],
  ['behavior_9',['Behavior',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md329',1,'Scaling Behavior'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md375',1,'Scaling Behavior']]],
  ['benchmark_20reproduction_10',['Benchmark Reproduction',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md391',1,'']]],
  ['benchmark_20suite_11',['Running the Parser Benchmark Suite',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md392',1,'']]],
  ['benchmarks_12',['Benchmarks',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md420',1,'Performance Benchmarks'],['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md337',1,'Running Benchmarks']]],
  ['beneficial_13',['Beneficial',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md464',1,'When JIT Is Beneficial'],['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md465',1,'When JIT Is Not Beneficial']]],
  ['benefit_20analysis_14',['Cost-Benefit Analysis',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md459',1,'']]],
  ['best_20practices_15',['Best Practices',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md295',1,'Best Practices'],['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md537',1,'Best Practices']]],
  ['between_20parses_16',['Pattern A: Allocate once, reset between parses',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md54',1,'']]],
  ['bison_17',['Bison',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md219',1,'Key Differences from Yacc/Bison'],['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md410',1,'Lime vs Bison'],['../index.html#autotoc_md3',1,'Why Lime over Yacc/Bison?']]],
  ['bison_20bootparse_20y_20excerpt_18',['Original Bison (bootparse.y excerpt)',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md439',1,'']]],
  ['bison_20build_19',['Bison Build',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md435',1,'']]],
  ['bison_20to_20lime_20',['Migrating from Bison to Lime',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html',1,'']]],
  ['bison_20when_20you_20need_3a_21',['Use Bison when you need:',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md416',1,'']]],
  ['bison_20yacc_22',['Comparison to Bison/Yacc',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md523',1,'']]],
  ['bki_20parser_20examples_20bootstrap_23',['Bootstrap (BKI) Parser (&lt;span class=&quot;tt&quot;&gt;examples/bootstrap/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md67',1,'']]],
  ['block_24',['Metadata Block',['../md_docs_2_l_i_t_e_r_a_t_e___f_o_r_m_a_t.html#autotoc_md561',1,'']]],
  ['blocks_25',['Code Blocks',['../md_docs_2_l_i_t_e_r_a_t_e___f_o_r_m_a_t.html#autotoc_md566',1,'']]],
  ['boot_5fgrammar_20lime_20excerpt_26',['Converted Lime (boot_grammar.lime excerpt)',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md440',1,'']]],
  ['bootparse_20y_20excerpt_27',['Original Bison (bootparse.y excerpt)',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md439',1,'']]],
  ['bootstrap_28',['Bootstrap (BKI) Parser (&lt;span class=&quot;tt&quot;&gt;examples/bootstrap/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md67',1,'']]],
  ['bootstrap_20bki_20parser_20examples_20bootstrap_29',['Bootstrap (BKI) Parser (&lt;span class=&quot;tt&quot;&gt;examples/bootstrap/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md67',1,'']]],
  ['bootstrap_20parser_30',['Worked Example: PostgreSQL Bootstrap Parser',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md438',1,'']]],
  ['both_20a_20and_20b_31',['&quot;Symbol &apos;X&apos; is exported by both &apos;A&apos; and &apos;B&apos;&quot;',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md549',1,'']]],
  ['break_20even_20analysis_20with_20extensions_32',['Break-Even Analysis with Extensions',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md372',1,'']]],
  ['break_20even_20point_33',['Break-Even Point',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md462',1,'']]],
  ['breakdown_34',['Breakdown',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md344',1,'Component Overhead Breakdown'],['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md457',1,'Parse Time Breakdown']]],
  ['budget_35',['Aggregate Memory Budget',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md353',1,'']]],
  ['budget_20guide_36',['Memory Budget Guide',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md332',1,'']]],
  ['build_37',['Build',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md435',1,'Bison Build'],['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md436',1,'Lime Build']]],
  ['build_20and_20tooling_38',['Build and Tooling',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md407',1,'']]],
  ['build_20system_39',['Build System',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md112',1,'']]],
  ['build_20system_20changes_40',['Build System Changes',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md434',1,'']]],
  ['build_20targets_41',['Build Targets',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md113',1,'']]],
  ['build_20time_42',['Generating Parsers at Build Time',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md49',1,'']]],
  ['building_20the_20extension_20framework_43',['Building the Extension Framework',['../md_docs_2_g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md22',1,'']]],
  ['building_20the_20generator_44',['Building the Generator',['../md_docs_2_g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md19',1,'']]],
  ['by_20both_20a_20and_20b_45',['&quot;Symbol &apos;X&apos; is exported by both &apos;A&apos; and &apos;B&apos;&quot;',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md549',1,'']]],
  ['by_20grammar_20size_46',['JIT Compilation Cost by Grammar Size',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md373',1,'']]]
];
