var searchData=
[
  ['each_20tool_0',['When to Use Each Tool',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md413',1,'']]],
  ['edn_20examples_20datalog_1',['Datalog/EDN (&lt;span class=&quot;tt&quot;&gt;examples/datalog/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md76',1,'']]],
  ['effect_2',['Grammar rule not taking effect',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md307',1,'']]],
  ['entry_3',['Context Entry',['../group__ctx__entry.html',1,'']]],
  ['entry_20point_4',['Dynamic Plugin Entry Point',['../group__plugin__entry.html',1,'']]],
  ['enum_5',['Execution Policy Enum',['../group__exec__policy__enum.html',1,'']]],
  ['enumeration_20and_20introspection_6',['Plugin Enumeration and Introspection',['../group__plugin__introspection.html',1,'']]],
  ['error_7',['error',['../struct_execution_result.html#a62028cf35f5a682a0b4d99066cfc1825',1,'ExecutionResult']]],
  ['error_20handling_8',['Error Handling',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md404',1,'Error Handling'],['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md432',1,'Error Handling'],['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md510',1,'Error Handling']]],
  ['error_20handling_20conventions_9',['Error Handling Conventions',['../md_docs_2_a_p_i.html#autotoc_md191',1,'']]],
  ['error_20recovery_10',['Error Recovery',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md257',1,'']]],
  ['error_5fcount_11',['error_count',['../struct_parse_fork.html#af9da43f3a9eeba891977effc12de2ab0',1,'ParseFork']]],
  ['even_20analysis_20with_20extensions_12',['Break-Even Analysis with Extensions',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md372',1,'']]],
  ['even_20point_13',['Break-Even Point',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md462',1,'']]],
  ['example_14',['Example',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md205',1,'A Shift-Reduce Example'],['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md239',1,'Complete Example'],['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md529',1,'Complete Example'],['../md_docs_2_l_i_t_e_r_a_t_e___f_o_r_m_a_t.html#autotoc_md572',1,'Example']]],
  ['example_15',['Compiling the example',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md292',1,'']]],
  ['example_3a_20plugin_20implementation_16',['Example: Plugin Implementation',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md518',1,'']]],
  ['example_3a_20postgresql_20bootstrap_20parser_17',['Worked Example: PostgreSQL Bootstrap Parser',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md438',1,'']]],
  ['examples_18',['Examples',['../md_docs_2_e_x_a_m_p_l_e_s.html',1,'Examples'],['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md556',1,'Examples'],['../md_docs_2_a_p_i.html#autotoc_md195',1,'Usage Examples']]],
  ['examples_20bootstrap_19',['Bootstrap (BKI) Parser (&lt;span class=&quot;tt&quot;&gt;examples/bootstrap/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md67',1,'']]],
  ['examples_20calc_20',['Calculator (&lt;span class=&quot;tt&quot;&gt;examples/calc/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md60',1,'']]],
  ['examples_20datalog_21',['Datalog/EDN (&lt;span class=&quot;tt&quot;&gt;examples/datalog/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md76',1,'']]],
  ['examples_20isolation_22',['Isolation Test Parser (&lt;span class=&quot;tt&quot;&gt;examples/isolation/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md68',1,'']]],
  ['examples_20jsonb_5fextension_20c_23',['JSONB Extension (&lt;span class=&quot;tt&quot;&gt;examples/jsonb_extension.c&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md61',1,'']]],
  ['examples_20jsonpath_24',['JSONPath (&lt;span class=&quot;tt&quot;&gt;examples/jsonpath/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md72',1,'']]],
  ['examples_20lime_5fpostgres_25',['PostgreSQL Integration Guide (&lt;span class=&quot;tt&quot;&gt;examples/lime_postgres/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md80',1,'']]],
  ['examples_20literate_26',['Literate Grammar Format (&lt;span class=&quot;tt&quot;&gt;examples/literate/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md78',1,'']]],
  ['examples_20llm_5foracle_27',['LLM Oracle Disambiguation (&lt;span class=&quot;tt&quot;&gt;examples/llm_oracle/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md77',1,'']]],
  ['examples_20mongodb_28',['MongoDB Query Language (&lt;span class=&quot;tt&quot;&gt;examples/mongodb/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md75',1,'']]],
  ['examples_20pg_29',['PostgreSQL Full Grammar (&lt;span class=&quot;tt&quot;&gt;examples/pg/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md63',1,'']]],
  ['examples_20pg_5fmodular_30',['PostgreSQL Modular Grammar (&lt;span class=&quot;tt&quot;&gt;examples/pg_modular/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md64',1,'']]],
  ['examples_20pgbench_31',['pgbench Expressions (&lt;span class=&quot;tt&quot;&gt;examples/pgbench/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md66',1,'']]],
  ['examples_20plugin_5ftemplate_32',['Plugin Template (&lt;span class=&quot;tt&quot;&gt;examples/plugin_template/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md62',1,'']]],
  ['examples_20replication_33',['Replication Protocol (&lt;span class=&quot;tt&quot;&gt;examples/replication/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md70',1,'']]],
  ['examples_20syncrep_34',['Synchronous Replication Config (&lt;span class=&quot;tt&quot;&gt;examples/syncrep/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md69',1,'']]],
  ['examples_20xpath_35',['XPath 1.0 (&lt;span class=&quot;tt&quot;&gt;examples/xpath/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md73',1,'']]],
  ['examples_20xquery_36',['XQuery 1.0 (&lt;span class=&quot;tt&quot;&gt;examples/xquery/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md74',1,'']]],
  ['excerpt_37',['excerpt',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md440',1,'Converted Lime (boot_grammar.lime excerpt)'],['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md439',1,'Original Bison (bootparse.y excerpt)']]],
  ['exec_5fall_38',['EXEC_ALL',['../group__exec__policy__enum.html#ggabb9b083e3cf53f9b637f5d20bc969ebaa6c8c3a9803065a4e7fe33f76b0adbd47',1,'execution_policy.h']]],
  ['exec_5fchain_39',['EXEC_CHAIN',['../group__exec__policy__enum.html#ggabb9b083e3cf53f9b637f5d20bc969ebaa5adc695d3a20c36097e584bad108a964',1,'execution_policy.h']]],
  ['exec_5fconditional_40',['EXEC_CONDITIONAL',['../group__exec__policy__enum.html#ggabb9b083e3cf53f9b637f5d20bc969ebaa6c240e2f38872f7756f4ed34f2c5faa5',1,'execution_policy.h']]],
  ['exec_5ffirst_5fonly_41',['EXEC_FIRST_ONLY',['../group__exec__policy__enum.html#ggabb9b083e3cf53f9b637f5d20bc969ebaa57a42f97093d3de1c9a1bac88665a25c',1,'execution_policy.h']]],
  ['exec_5flazy_42',['EXEC_LAZY',['../group__exec__policy.html#gga55b6f6efa9d95995f40fae2c4e396dcda92a8231c78cdb515e246c77f64ba6642',1,'extension_registry.h']]],
  ['exec_5fparallel_43',['EXEC_PARALLEL',['../group__exec__policy.html#gga55b6f6efa9d95995f40fae2c4e396dcda0b246e4ee5d6e4a9225d38f0bd2a9aa8',1,'extension_registry.h']]],
  ['exec_5fpipeline_44',['EXEC_PIPELINE',['../group__exec__policy.html#gga55b6f6efa9d95995f40fae2c4e396dcdad9cd985effd4017687aaf55bf778da8d',1,'extension_registry.h']]],
  ['exec_5fsequential_45',['EXEC_SEQUENTIAL',['../group__exec__policy.html#gga55b6f6efa9d95995f40fae2c4e396dcda7cad1a92fbffe04e8066b547e8b05db3',1,'extension_registry.h']]],
  ['execute_5ffirst_5fonly_46',['execute_first_only',['../group__exec__api.html#gad6a9abc25dbeadb2c428c2762d97a4c9',1,'execution_policy.h']]],
  ['execute_5ffn_47',['execute_fn',['../struct_execution_policy_config.html#a1253dc1dc0527a327bc62397e5a7f4e6',1,'ExecutionPolicyConfig']]],
  ['execute_5fsemantic_5factions_48',['execute_semantic_actions',['../group__exec__api.html#ga35037e1a434c4414b16d8a1b439326c4',1,'execution_policy.h']]],
  ['execution_49',['Grammar Extension Metadata (Execution)',['../group__exec__ext__meta.html',1,'']]],
  ['execution_20callback_50',['Parser Execution Callback',['../group__exec__callback.html',1,'']]],
  ['execution_20policies_51',['Execution Policies',['../group__exec__policy.html',1,'Execution Policies'],['../md_docs_2_c_o_n_c_e_p_t_s.html#autotoc_md32',1,'Execution Policies']]],
  ['execution_20policy_20api_52',['Execution Policy API',['../group__exec__api.html',1,'']]],
  ['execution_20policy_20configuration_53',['Execution Policy Configuration',['../group__exec__config.html',1,'']]],
  ['execution_20policy_20enum_54',['Execution Policy Enum',['../group__exec__policy__enum.html',1,'']]],
  ['execution_20result_55',['Execution Result',['../group__exec__result.html',1,'']]],
  ['execution_5fpolicy_2eh_56',['execution_policy.h',['../execution__policy_8h.html',1,'']]],
  ['execution_5fpolicy_5fconfig_5finit_57',['execution_policy_config_init',['../group__exec__api.html#ga7f575bfb9480d1f9ff61a5677a350033',1,'execution_policy.h']]],
  ['execution_5fpolicy_5fname_58',['execution_policy_name',['../group__exec__api.html#gaa0a4385adcf15377df50173a0fbdf6df',1,'execution_policy.h']]],
  ['execution_5fresults_5ffree_59',['execution_results_free',['../group__exec__api.html#gaa758b88e5de5b06d77813039936a90a2',1,'execution_policy.h']]],
  ['executionpolicy_60',['ExecutionPolicy',['../group__exec__policy.html#ga55b6f6efa9d95995f40fae2c4e396dcd',1,'extension_registry.h']]],
  ['executionpolicyconfig_61',['ExecutionPolicyConfig',['../struct_execution_policy_config.html',1,'']]],
  ['executionresult_62',['ExecutionResult',['../struct_execution_result.html',1,'']]],
  ['existing_20systems_63',['Integration with Existing Systems',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md514',1,'']]],
  ['exit_5ftoken_64',['exit_token',['../struct_grammar_mode_info.html#ab3c2c295f447d194053d575f0c88ac87',1,'GrammarModeInfo']]],
  ['expected_20performance_65',['Expected Performance',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md480',1,'']]],
  ['explanation_66',['explanation',['../struct_strategy_result.html#a58e37f57e0e12b41b48ae68c2645fb96',1,'StrategyResult']]],
  ['exported_20by_20both_20a_20and_20b_67',['&quot;Symbol &apos;X&apos; is exported by both &apos;A&apos; and &apos;B&apos;&quot;',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md549',1,'']]],
  ['exporting_20symbols_68',['Re-exporting Symbols',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md552',1,'']]],
  ['exports_69',['Exports',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md527',1,'']]],
  ['expressions_20examples_20pgbench_70',['pgbench Expressions (&lt;span class=&quot;tt&quot;&gt;examples/pgbench/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md66',1,'']]],
  ['ext_5fid_71',['ext_id',['../struct_lime_context.html#a040da8fcf594c51bb8ff57a247ddd2ae',1,'LimeContext']]],
  ['ext_5fid_5fa_72',['ext_id_a',['../struct_conflict.html#a93b0199b1ce09bb0bf44b64f922c4ee9',1,'Conflict']]],
  ['ext_5fid_5fb_73',['ext_id_b',['../struct_conflict.html#acc3056db31c9abb5474799235215f093',1,'Conflict']]],
  ['extensibility_74',['Runtime Extensibility',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md406',1,'']]],
  ['extensible_20sql_20parser_20ndash_20api_20reference_75',['Extensible SQL Parser &amp;ndash; API Reference',['../md_docs_2_a_p_i.html',1,'']]],
  ['extension_76',['Extension',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md376',1,'1 Extension'],['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md286',1,'Complete Walkthrough: JSONB Extension'],['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md327',1,'Memory Overhead Per Extension']]],
  ['extension_20adds_77',['What the extension adds',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md287',1,'']]],
  ['extension_20api_78',['Extension API',['../md_docs_2_a_p_i.html#autotoc_md166',1,'']]],
  ['extension_20callbacks_79',['Extension Callbacks',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md94',1,'Extension Callbacks'],['../md_docs_2_a_p_i.html#autotoc_md170',1,'Extension Callbacks']]],
  ['extension_20development_80',['Extension Development',['../index.html#autotoc_md9',1,'']]],
  ['extension_20development_20guide_81',['Extension Development Guide',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html',1,'']]],
  ['extension_20examples_20jsonb_5fextension_20c_82',['JSONB Extension (&lt;span class=&quot;tt&quot;&gt;examples/jsonb_extension.c&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md61',1,'']]],
  ['extension_20fails_20to_20load_83',['Extension fails to load',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md305',1,'']]],
  ['extension_20framework_84',['Extension Framework',['../md_docs_2_g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md22',1,'Building the Extension Framework'],['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md39',1,'Option 1: Generator Only (No Extension Framework)']]],
  ['extension_20framework_20make_20cmake_85',['Option 3: Generator + Extension Framework (Make / CMake)',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md43',1,'']]],
  ['extension_20framework_20meson_86',['Option 2: Generator + Extension Framework (Meson)',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md40',1,'']]],
  ['extension_20framework_20performance_20characteristics_87',['Extension Framework Performance Characteristics',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html',1,'']]],
  ['extension_20framework_20symbols_88',['Library (extension framework) symbols',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md52',1,'']]],
  ['extension_20h_89',['Internal Registry API (src/extension.h)',['../md_docs_2_a_p_i.html#autotoc_md168',1,'']]],
  ['extension_20initialization_20api_90',['Extension Initialization API',['../group__ext__init.html',1,'']]],
  ['extension_20lifecycle_91',['Extension Lifecycle',['../md_docs_2_c_o_n_c_e_p_t_s.html#autotoc_md29',1,'Extension Lifecycle'],['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md93',1,'Extension Lifecycle'],['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md271',1,'Extension Lifecycle']]],
  ['extension_20load_92',['JIT Invalidation on Extension Load',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md371',1,'']]],
  ['extension_20loading_93',['Extension Loading',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md385',1,'Extension Loading'],['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md48',1,'Runtime Extension Loading']]],
  ['extension_20memory_94',['Per-Extension Memory',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md351',1,'']]],
  ['extension_20metadata_95',['Extension Metadata',['../group__ext__metadata.html',1,'']]],
  ['extension_20metadata_20execution_96',['Grammar Extension Metadata (Execution)',['../group__exec__ext__meta.html',1,'']]],
  ['extension_20ordering_20matters_97',['Extension ordering matters',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md303',1,'']]],
  ['extension_20overhead_98',['Extension Overhead',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md323',1,'Extension Overhead'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md393',1,'Measuring Extension Overhead']]],
  ['extension_20registration_99',['Extension Registration',['../md_docs_2_a_p_i.html#autotoc_md199',1,'']]],
  ['extension_20registry_100',['Extension Registry',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md345',1,'']]],
  ['extension_20system_101',['Extension System',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md91',1,'Extension System'],['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md515',1,'Extension System']]],
  ['extension_5fid_102',['extension_id',['../struct_grammar_extension_metadata.html#a8736ae69907cceea97146bc825221ec7',1,'GrammarExtensionMetadata::extension_id'],['../struct_execution_result.html#afaadc11c6b1194cb46f336a036bdb8ab',1,'ExecutionResult::extension_id']]],
  ['extension_5fname_103',['extension_name',['../struct_oracle_context.html#a8ef774dc460b3ce05b3c26a4418da254',1,'OracleContext']]],
  ['extension_5forder_5fdestroy_104',['extension_order_destroy',['../group__ext__order.html#ga57bc065743797e4e662b1d2a718b9953',1,'extension_registry.h']]],
  ['extension_5fregistry_2eh_105',['extension_registry.h',['../extension__registry_8h.html',1,'']]],
  ['extension_5fregistry_5fcheck_5fdependencies_106',['extension_registry_check_dependencies',['../group__registry__api.html#ga3cc3af719d23971bdf8a5a77c18ecc20',1,'extension_registry.h']]],
  ['extension_5fregistry_5fcount_107',['extension_registry_count',['../group__registry__api.html#ga706ad75c8b2bbdd6093caf927516c86e',1,'extension_registry.h']]],
  ['extension_5fregistry_5fcreate_108',['extension_registry_create',['../group__registry__api.html#gabdb471d2f940b45aaca6d0f45adfafac',1,'extension_registry.h']]],
  ['extension_5fregistry_5fdestroy_109',['extension_registry_destroy',['../group__registry__api.html#gaa3f84fea99126571b668b53bec27aeee',1,'extension_registry.h']]],
  ['extension_5fregistry_5ffind_110',['extension_registry_find',['../group__registry__api.html#gaed75b7e39749cc577565e7adc3328437',1,'extension_registry.h']]],
  ['extension_5fregistry_5fforeach_111',['extension_registry_foreach',['../group__registry__api.html#ga1f3c2f4a74c99708d0daa1318d7eab51',1,'extension_registry.h']]],
  ['extension_5fregistry_5fget_5forder_112',['extension_registry_get_order',['../group__registry__api.html#gad2e1195c1f21fd2352dad0a69a29b5b0',1,'extension_registry.h']]],
  ['extension_5fregistry_5fregister_113',['extension_registry_register',['../group__registry__api.html#ga1fc0eb667fe538e57f800ec0fc1a0a87',1,'extension_registry.h']]],
  ['extension_5fregistry_5funregister_114',['extension_registry_unregister',['../group__registry__api.html#ga3e292d3cf6718250439a3b6ec3a350e2',1,'extension_registry.h']]],
  ['extensioninfo_20descriptor_115',['Step 3: Define the ExtensionInfo descriptor',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md290',1,'']]],
  ['extensionorder_116',['ExtensionOrder',['../struct_extension_order.html',1,'']]],
  ['extensionregistry_117',['ExtensionRegistry',['../group__registry__handle.html#gaea46be4a7141df97a37536dabd527447',1,'extension_registry.h']]],
  ['extensions_118',['Extensions',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md378',1,'10 Extensions'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md377',1,'5 Extensions'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md379',1,'50 Extensions'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md356',1,'Baseline (No Extensions)'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md372',1,'Break-Even Analysis with Extensions'],['../md_docs_2_c_o_n_c_e_p_t_s.html#autotoc_md28',1,'Extensions'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md370',1,'JIT Interaction with Extensions'],['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md331',1,'Multiple Extensions']]],
  ['extensions_20active_20conflicts_119',['With Extensions (Active Conflicts)',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md358',1,'']]],
  ['extensions_20are_20applied_120',['How Extensions Are Applied',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md293',1,'']]],
  ['extensions_20contrib_121',['SQL Dialect Extensions (&lt;span class=&quot;tt&quot;&gt;contrib/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md79',1,'']]],
  ['extensions_20no_20conflicts_122',['With Extensions (No Conflicts)',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md357',1,'']]],
  ['extensionvisitorfn_123',['ExtensionVisitorFn',['../group__registry__api.html#gaefe10270a5c4adc15807c426507a1621',1,'extension_registry.h']]]
];
