var searchData=
[
  ['walkthrough_3a_20jsonb_20extension_0',['Complete Walkthrough: JSONB Extension',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md286',1,'']]],
  ['what_20changed_1',['What Changed',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md441',1,'']]],
  ['what_20the_20extension_20adds_2',['What the extension adds',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md287',1,'']]],
  ['when_20jit_20is_20beneficial_3',['When JIT Is Beneficial',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md464',1,'']]],
  ['when_20jit_20is_20not_20beneficial_4',['When JIT Is Not Beneficial',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md465',1,'']]],
  ['when_20llvm_20available_5',['JIT Performance (When LLVM Available)',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md320',1,'']]],
  ['when_20simd_20helps_20least_6',['When SIMD Helps Least',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md317',1,'']]],
  ['when_20simd_20helps_20most_7',['When SIMD Helps Most',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md316',1,'']]],
  ['when_20to_20tune_8',['When to Tune',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md485',1,'']]],
  ['when_20to_20use_20each_20tool_9',['When to Use Each Tool',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md413',1,'']]],
  ['when_20you_20need_3a_10',['when you need:',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md417',1,'Use ANTLR when you need:'],['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md416',1,'Use Bison when you need:'],['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md414',1,'Use Lime when you need:'],['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md418',1,'Use Menhir when you need:'],['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md415',1,'Use Yacc when you need:']]],
  ['which_20is_20not_20available_11',['&quot;Module &apos;foo&apos; requires &apos;bar&apos;, which is not available&quot;',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md547',1,'']]],
  ['why_20directive_20format_12',['Why Directive Format?',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md522',1,'']]],
  ['why_20lalr_201_13',['Why LALR(1)?',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md216',1,'']]],
  ['why_20lime_20over_20yacc_20bison_14',['Why Lime over Yacc/Bison?',['../index.html#autotoc_md3',1,'']]],
  ['why_20tokenizer_20jit_20matters_20most_15',['Why Tokenizer JIT Matters Most',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md478',1,'']]],
  ['winning_5fcontexts_16',['winning_contexts',['../struct_strategy_result.html#a3883c2aacb5df9c905c4beba2bb58547',1,'StrategyResult']]],
  ['wins_17',['Quick Wins',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md334',1,'']]],
  ['with_20existing_20systems_18',['Integration with Existing Systems',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md514',1,'']]],
  ['with_20extensions_19',['with Extensions',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md372',1,'Break-Even Analysis with Extensions'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md370',1,'JIT Interaction with Extensions']]],
  ['with_20extensions_20active_20conflicts_20',['With Extensions (Active Conflicts)',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md358',1,'']]],
  ['with_20extensions_20no_20conflicts_21',['With Extensions (No Conflicts)',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md357',1,'']]],
  ['with_20policy_22',['JIT Compilation with Policy',['../md_docs_2_a_p_i.html#autotoc_md200',1,'']]],
  ['with_20prec_23',['Precedence with prec',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md431',1,'']]],
  ['worked_20example_3a_20postgresql_20bootstrap_20parser_24',['Worked Example: PostgreSQL Bootstrap Parser',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md438',1,'']]],
  ['works_25',['Works',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md265',1,'Foundational Works'],['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md532',1,'How Composition Works']]],
  ['write_20and_20thread_20safety_26',['Copy-on-Write and Thread Safety',['../md_docs_2_c_o_n_c_e_p_t_s.html#autotoc_md33',1,'']]],
  ['write_20modification_27',['Copy-on-Write Modification',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md87',1,'']]],
  ['write_20snapshot_20architecture_28',['Copy-on-Write Snapshot Architecture',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md84',1,'']]],
  ['writing_20a_20driver_29',['Writing a Driver',['../md_docs_2_g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md21',1,'']]]
];
