var searchData=
[
  ['c_0',['c',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md61',1,'JSONB Extension (&lt;span class=&quot;tt&quot;&gt;examples/jsonb_extension.c&lt;/span&gt;)'],['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md89',1,'Processing Pipeline (in &lt;span class=&quot;tt&quot;&gt;lime.c&lt;/span&gt;)']]],
  ['calc_1',['Calculator (&lt;span class=&quot;tt&quot;&gt;examples/calc/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md60',1,'']]],
  ['calculator_20examples_20calc_2',['Calculator (&lt;span class=&quot;tt&quot;&gt;examples/calc/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md60',1,'']]],
  ['callback_3',['Callback',['../group__ctx__switch__cb.html',1,'Context Switch Callback'],['../group__oracle__cb.html',1,'Oracle Callback'],['../group__exec__callback.html',1,'Parser Execution Callback']]],
  ['callbacks_4',['Callbacks',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md94',1,'Extension Callbacks'],['../md_docs_2_a_p_i.html#autotoc_md170',1,'Extension Callbacks'],['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md282',1,'Implementing Callbacks'],['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md493',1,'Optional Callbacks'],['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md492',1,'Required Callbacks']]],
  ['callbacks_5',['Step 2: Implement the callbacks',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md289',1,'']]],
  ['candidate_5fcount_6',['candidate_count',['../struct_oracle_context.html#af527c26ad6d43f4e769bab4b5078ec67',1,'OracleContext']]],
  ['candidate_5flabels_7',['candidate_labels',['../struct_oracle_context.html#a71b7b6a2ddb2089aa0eb0426a2a17c76',1,'OracleContext']]],
  ['canonical_20lr_201_8',['Canonical LR(1)',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md211',1,'']]],
  ['capabilities_9',['Capabilities',['../md_docs_2_l_i_t_e_r_a_t_e___f_o_r_m_a_t.html#autotoc_md565',1,'']]],
  ['capabilities_10',['capabilities',['../struct_lime_plugin_info.html#a9b6aaeb91168a1c469d6f39301a799f3',1,'LimePluginInfo']]],
  ['capability_20flags_11',['Plugin Capability Flags',['../group__plugin__caps.html',1,'']]],
  ['capacity_12',['capacity',['../struct_conflict_set.html#a1d748cb8b43e691ab547ef3a848608b7',1,'ConflictSet::capacity'],['../struct_conflict_point.html#af3f9009ec7edd4f26078d728ec675258',1,'ConflictPoint::capacity'],['../struct_multi_grammar_conflict_result.html#a57a9ac211a33d4f9ad0dc69b916ee786',1,'MultiGrammarConflictResult::capacity'],['../struct_parse_fork_set.html#a23330cedea8897e9d4d5f14d9f0e32b3',1,'ParseForkSet::capacity']]],
  ['card_13',['Quick Reference Card',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md443',1,'']]],
  ['changed_14',['What Changed',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md441',1,'']]],
  ['changes_15',['Build System Changes',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md434',1,'']]],
  ['character_20classification_16',['Character Classification',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md98',1,'Character Classification'],['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md315',1,'SIMD Character Classification']]],
  ['character_20classification_20api_17',['SIMD Character Classification API',['../md_docs_2_a_p_i.html#autotoc_md158',1,'']]],
  ['characteristics_18',['Characteristics',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html',1,'Extension Framework Performance Characteristics'],['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html',1,'Performance Characteristics'],['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md259',1,'Performance Characteristics']]],
  ['checklist_19',['Checklist',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___y_a_c_c.html#autotoc_md453',1,'Quick Migration Checklist'],['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md57',1,'Thread Safety Checklist']]],
  ['checks_20',['Plugin Version Checks',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md508',1,'']]],
  ['classification_21',['Classification',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md98',1,'Character Classification'],['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md315',1,'SIMD Character Classification']]],
  ['classification_20api_22',['SIMD Character Classification API',['../md_docs_2_a_p_i.html#autotoc_md158',1,'']]],
  ['classifier_23',['Trie-Based Keyword Classifier',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md479',1,'']]],
  ['classify_5fscalar_24',['classify_scalar',['../md_docs_2_a_p_i.html#autotoc_md162',1,'']]],
  ['classify_5fsimd_5favx2_20x86_5f64_20only_25',['classify_simd_avx2 (x86_64 only)',['../md_docs_2_a_p_i.html#autotoc_md163',1,'']]],
  ['classify_5fsimd_5fneon_20arm_20only_26',['classify_simd_neon (ARM only)',['../md_docs_2_a_p_i.html#autotoc_md164',1,'']]],
  ['cleanup_27',['4. Cleanup',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md275',1,'']]],
  ['clone_5fparser_5fstate_28',['clone_parser_state',['../group__clone__api.html#ga8abc6613050bb08d109ece39fc3a98a0',1,'parser_fork.h']]],
  ['cloned_20parser_20state_29',['Cloned Parser State',['../group__cloned__state.html',1,'']]],
  ['cloned_5fparser_5fstate_5fdestroy_30',['cloned_parser_state_destroy',['../group__clone__api.html#gafd92d3f3bbc2eef51c9f717e42ac3908',1,'parser_fork.h']]],
  ['cloned_5fstate_31',['cloned_state',['../struct_parse_fork.html#a9126af5ad9772adcc0fe4cfca57c4c20',1,'ParseFork']]],
  ['clonedparserstate_32',['ClonedParserState',['../struct_cloned_parser_state.html',1,'']]],
  ['cloning_20api_33',['Cloning API',['../group__clone__api.html',1,'']]],
  ['closure_34',['Closure',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md236',1,'']]],
  ['cmake_35',['CMake',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md45',1,'CMake'],['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md43',1,'Option 3: Generator + Extension Framework (Make / CMake)']]],
  ['code_20blocks_36',['Code Blocks',['../md_docs_2_l_i_t_e_r_a_t_e___f_o_r_m_a_t.html#autotoc_md566',1,'']]],
  ['code_20generation_20and_20integration_37',['Code Generation and Integration',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md403',1,'']]],
  ['codes_38',['Codes',['../group__manager__status.html',1,'Manager Status Codes'],['../md_docs_2_a_p_i.html#autotoc_md189',1,'Token Type Codes']]],
  ['codes_39',['Use auto-assigned token codes',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md297',1,'']]],
  ['collisions_40',['Avoiding Symbol Collisions',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md50',1,'']]],
  ['common_20gotchas_41',['Common Gotchas',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md442',1,'']]],
  ['compare_42',['Key Metrics to Compare',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md394',1,'']]],
  ['comparison_43',['Comparison',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md212',1,'Comparison'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md360',1,'Conflict Type Comparison'],['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md424',1,'License Comparison'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md368',1,'Strategy Comparison']]],
  ['comparison_20guide_44',['Parser Generator Comparison Guide',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html',1,'']]],
  ['comparison_20matrix_45',['Feature Comparison Matrix',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md401',1,'']]],
  ['comparison_20table_46',['Comparison Table',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md215',1,'']]],
  ['comparison_20to_20bison_20yacc_47',['Comparison to Bison/Yacc',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md523',1,'']]],
  ['comparisons_48',['Detailed Comparisons',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md408',1,'']]],
  ['compatibility_49',['Version Compatibility',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md507',1,'']]],
  ['compatibility_20notes_50',['Compatibility Notes',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___y_a_c_c.html#autotoc_md452',1,'']]],
  ['compatibility_20utilities_51',['Version Compatibility Utilities',['../group__version__utils.html',1,'']]],
  ['compilation_52',['Compilation',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md114',1,'Conditional Compilation'],['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md554',1,'Conditional Compilation'],['../md_docs_2_c_o_n_c_e_p_t_s.html#autotoc_md35',1,'JIT Compilation'],['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md318',1,'JIT Compilation'],['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md516',1,'JIT Compilation']]],
  ['compilation_20analysis_20for_20lime_20parser_20generator_53',['JIT Compilation Analysis for Lime Parser Generator',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html',1,'']]],
  ['compilation_20api_54',['Compilation API',['../group__jit__api.html',1,'JIT Compilation API'],['../md_docs_2_a_p_i.html#autotoc_md175',1,'JIT Compilation API']]],
  ['compilation_20cost_55',['Compilation Cost',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md461',1,'']]],
  ['compilation_20cost_20by_20grammar_20size_56',['JIT Compilation Cost by Grammar Size',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md373',1,'']]],
  ['compilation_20lime_20j_57',['AOT Compilation (&lt;span class=&quot;tt&quot;&gt;lime -j&lt;/span&gt;)',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md468',1,'']]],
  ['compilation_20modes_58',['JIT Compilation Modes',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md322',1,'']]],
  ['compilation_20trigger_59',['Compilation Trigger',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md104',1,'']]],
  ['compilation_20with_20policy_60',['JIT Compilation with Policy',['../md_docs_2_a_p_i.html#autotoc_md200',1,'']]],
  ['compiling_20the_20example_61',['Compiling the example',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md292',1,'']]],
  ['complete_20example_62',['Complete Example',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md239',1,'Complete Example'],['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md529',1,'Complete Example']]],
  ['complete_20walkthrough_3a_20jsonb_20extension_63',['Complete Walkthrough: JSONB Extension',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md286',1,'']]],
  ['complexity_64',['Complexity',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md261',1,'Space Complexity'],['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md260',1,'Time Complexity']]],
  ['component_20overhead_20breakdown_65',['Component Overhead Breakdown',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md344',1,'']]],
  ['component_20overview_66',['Component Overview',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md83',1,'']]],
  ['compose_67',['Using lime-compose',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md531',1,'']]],
  ['composed_20output_68',['Composed Output',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md533',1,'']]],
  ['composition_69',['Module Composition',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md530',1,'']]],
  ['composition_20process_70',['Composition Process',['../md_docs_2_l_i_t_e_r_a_t_e___f_o_r_m_a_t.html#autotoc_md568',1,'']]],
  ['composition_20validation_71',['Composition Validation',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md544',1,'']]],
  ['composition_20works_72',['How Composition Works',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md532',1,'']]],
  ['compression_73',['Compression',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md268',1,'Action Table Compression'],['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md247',1,'Table Compression']]],
  ['compresstables_74',['Step 8: CompressTables',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md230',1,'']]],
  ['concepts_75',['Concepts',['../md_docs_2_c_o_n_c_e_p_t_s.html',1,'']]],
  ['concurrency_20model_76',['Concurrency Model',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md501',1,'']]],
  ['concurrent_20parsers_77',['Concurrent Parsers',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md330',1,'']]],
  ['conditional_20compilation_78',['Conditional Compilation',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md114',1,'Conditional Compilation'],['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md554',1,'Conditional Compilation']]],
  ['confidence_79',['confidence',['../struct_strategy_result.html#ae33db46a6e2e6df2c63716e17138f226',1,'StrategyResult']]],
  ['config_20examples_20syncrep_80',['Synchronous Replication Config (&lt;span class=&quot;tt&quot;&gt;examples/syncrep/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md69',1,'']]],
  ['configuration_81',['Configuration',['../group__exec__config.html',1,'Execution Policy Configuration'],['../group__manager__config.html',1,'Manager Configuration'],['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md483',1,'Recommended Configuration']]],
  ['configurations_20items_82',['Configurations (Items)',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md235',1,'']]],
  ['conflict_83',['Conflict',['../struct_conflict.html',1,'']]],
  ['conflict_20action_20types_84',['Conflict Action Types',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md245',1,'']]],
  ['conflict_20detection_85',['Conflict Detection',['../group__conflict__detect.html',1,'Conflict Detection'],['../md_docs_2_c_o_n_c_e_p_t_s.html#autotoc_md30',1,'Conflict Detection'],['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md96',1,'Conflict Detection'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md346',1,'Conflict Detection'],['../group__multi__grammar.html',1,'Multi-Grammar Conflict Detection']]],
  ['conflict_20detection_20api_86',['Multi-Grammar Conflict Detection API',['../group__multi__detect__api.html',1,'']]],
  ['conflict_20detection_20types_87',['Conflict Detection Types',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md294',1,'']]],
  ['conflict_20reduction_88',['Conflict Reduction',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md388',1,'']]],
  ['conflict_20resolution_89',['Conflict Resolution',['../md_docs_2_a_p_i.html#autotoc_md173',1,'Conflict Resolution'],['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md241',1,'Conflict Resolution']]],
  ['conflict_20set_90',['Conflict Set',['../group__conflict__set.html',1,'']]],
  ['conflict_20type_20comparison_91',['Conflict Type Comparison',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md360',1,'']]],
  ['conflict_20types_92',['Conflict Types',['../group__conflict__types.html',1,'']]],
  ['conflict_2eh_93',['conflict.h',['../conflict_8h.html',1,'']]],
  ['conflict_5fdescription_94',['conflict_description',['../struct_oracle_context.html#a62ea8ed17b758367fde4f79b843cc731',1,'OracleContext']]],
  ['conflict_5fduplicate_5frule_95',['CONFLICT_DUPLICATE_RULE',['../group__conflict__types.html#gga004b7b03871e3e677442025ce670bf0ea2abb6a8192dc2e0bea0618bcb1527c31',1,'conflict.h']]],
  ['conflict_5flevel_5frule_96',['CONFLICT_LEVEL_RULE',['../group__multi__grammar.html#ggab04657e12edf9c78929042eb41bfbe8cad7651fa3fe5d5add3dbd06f1dfca6e2b',1,'conflict.h']]],
  ['conflict_5flevel_5fsemantic_97',['CONFLICT_LEVEL_SEMANTIC',['../group__multi__grammar.html#ggab04657e12edf9c78929042eb41bfbe8ca02d879f5f3cde5ec6b4c116e0ffb6a3a',1,'conflict.h']]],
  ['conflict_5flevel_5ftoken_98',['CONFLICT_LEVEL_TOKEN',['../group__multi__grammar.html#ggab04657e12edf9c78929042eb41bfbe8ca2f929a602715d63268d2650fc187e72e',1,'conflict.h']]],
  ['conflict_5fpoint_5fadd_5fcontext_99',['conflict_point_add_context',['../group__conflict__point__api.html#gaff2ee01cad3f04172e16d4b500ab8a39',1,'conflict.h']]],
  ['conflict_5fpoint_5fdestroy_100',['conflict_point_destroy',['../group__conflict__point__api.html#gae9899ebc758c8b440fb6ab6fb687ef8b',1,'conflict.h']]],
  ['conflict_5fpoint_5finit_101',['conflict_point_init',['../group__conflict__point__api.html#ga071e5cb71f1bb6bdb1a200633404820a',1,'conflict.h']]],
  ['conflict_5fprecedence_5fclash_102',['CONFLICT_PRECEDENCE_CLASH',['../group__conflict__types.html#gga004b7b03871e3e677442025ce670bf0ea8aca94e00cff19843f4260ff54a37ad0',1,'conflict.h']]],
  ['conflict_5freduce_5freduce_103',['CONFLICT_REDUCE_REDUCE',['../group__conflict__types.html#gga004b7b03871e3e677442025ce670bf0eaa384acb7026d5b9ab43be5c1b50c6457',1,'conflict.h']]],
  ['conflict_5fset_5fadd_104',['conflict_set_add',['../group__conflict__set.html#gaf6ecb87552664cbe1ebac87a6985dd0c',1,'conflict.h']]],
  ['conflict_5fset_5fcreate_105',['conflict_set_create',['../group__conflict__set.html#ga7464287a55c078b19e177e1cef5d5b5c',1,'conflict.h']]],
  ['conflict_5fset_5fdestroy_106',['conflict_set_destroy',['../group__conflict__set.html#ga2413f70a5b65eb560757de7714f32cd3',1,'conflict.h']]],
  ['conflict_5fset_5funresolved_5fcount_107',['conflict_set_unresolved_count',['../group__conflict__set.html#ga3b47113c9cb870e1ce5ce9e651f77837',1,'conflict.h']]],
  ['conflict_5fshift_5freduce_108',['CONFLICT_SHIFT_REDUCE',['../group__conflict__types.html#gga004b7b03871e3e677442025ce670bf0ea47d507750fb8eac987222b9f63b209ee',1,'conflict.h']]],
  ['conflict_5fthreshold_109',['conflict_threshold',['../struct_grammar_extension_metadata.html#a7c62c1d23f3996dd03fe478187bc3e4d',1,'GrammarExtensionMetadata']]],
  ['conflict_5ftoken_5fcollision_110',['CONFLICT_TOKEN_COLLISION',['../group__conflict__types.html#gga004b7b03871e3e677442025ce670bf0eae59d6739ca7f881fb08aa343e6c390a9',1,'conflict.h']]],
  ['conflictlevel_111',['ConflictLevel',['../group__multi__grammar.html#gab04657e12edf9c78929042eb41bfbe8c',1,'conflict.h']]],
  ['conflictpoint_112',['ConflictPoint',['../struct_conflict_point.html',1,'']]],
  ['conflictpoint_20lifecycle_113',['ConflictPoint Lifecycle',['../group__conflict__point__api.html',1,'']]],
  ['conflicts_114',['Conflicts',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md362',1,'Rule-Level Conflicts'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md363',1,'Semantic-Level Conflicts'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md361',1,'Token-Level Conflicts'],['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md242',1,'Types of Conflicts'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md358',1,'With Extensions (Active Conflicts)'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md357',1,'With Extensions (No Conflicts)']]],
  ['conflicts_115',['conflicts',['../struct_conflict_set.html#aa9c618e3033ae39a703de0762dc0c3df',1,'ConflictSet::conflicts'],['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md306',1,'Token conflicts']]],
  ['conflicts_20gracefully_116',['Handle conflicts gracefully',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md299',1,'']]],
  ['conflicts_5fwith_117',['conflicts_with',['../struct_grammar_extension_metadata.html#ae030e91e0a7af980cc42d3e1b4512176',1,'GrammarExtensionMetadata']]],
  ['conflictset_118',['ConflictSet',['../struct_conflict_set.html',1,'']]],
  ['conflicttype_119',['ConflictType',['../group__conflict__types.html#ga004b7b03871e3e677442025ce670bf0e',1,'conflict.h']]],
  ['considerations_120',['Future Considerations',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md519',1,'']]],
  ['constraints_121',['Version Constraints',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md551',1,'']]],
  ['construction_122',['State Machine Construction',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md234',1,'']]],
  ['content_20rules_123',['Content Rules',['../md_docs_2_l_i_t_e_r_a_t_e___f_o_r_m_a_t.html#autotoc_md567',1,'']]],
  ['contents_124',['Contents',['../md_docs_2_a_p_i.html#autotoc_md117',1,'Table of Contents'],['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md202',1,'Table of Contents'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md340',1,'Table of Contents']]],
  ['context_125',['Disambiguation Context',['../group__disambig__ctx.html',1,'']]],
  ['context_20api_126',['Context API',['../group__grammar__ctx__api.html',1,'Grammar Context API'],['../group__parse__ctx__api.html',1,'Parse Context API'],['../md_docs_2_a_p_i.html#autotoc_md128',1,'Parse Context API']]],
  ['context_20entry_127',['Context Entry',['../group__ctx__entry.html',1,'']]],
  ['context_20stack_20handle_128',['Context Stack Handle',['../group__ctx__stack.html',1,'']]],
  ['context_20switch_20callback_129',['Context Switch Callback',['../group__ctx__switch__cb.html',1,'']]],
  ['contexts_130',['contexts',['../struct_conflict_point.html#ad03eb75e05634c2590657c5293c4b2a7',1,'ConflictPoint']]],
  ['contextswitchcallback_131',['ContextSwitchCallback',['../group__ctx__switch__cb.html#gafa958ad16aa483f44ad9bd4a73b75d62',1,'grammar_context.h']]],
  ['contrib_132',['SQL Dialect Extensions (&lt;span class=&quot;tt&quot;&gt;contrib/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md79',1,'']]],
  ['contributing_133',['Contributing',['../index.html#autotoc_md13',1,'']]],
  ['convenience_20macro_20for_20generated_20parsers_134',['Convenience Macro for Generated Parsers',['../group__fork__macro.html',1,'']]],
  ['convenience_20registration_20function_135',['Step 4: Convenience registration function',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md291',1,'']]],
  ['conventions_136',['Conventions',['../md_docs_2_a_p_i.html#autotoc_md191',1,'Error Handling Conventions'],['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md539',1,'Naming Conventions']]],
  ['converted_20lime_20boot_5fgrammar_20lime_20excerpt_137',['Converted Lime (boot_grammar.lime excerpt)',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md440',1,'']]],
  ['copy_20on_20write_20and_20thread_20safety_138',['Copy-on-Write and Thread Safety',['../md_docs_2_c_o_n_c_e_p_t_s.html#autotoc_md33',1,'']]],
  ['copy_20on_20write_20modification_139',['Copy-on-Write Modification',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md87',1,'']]],
  ['copy_20on_20write_20snapshot_20architecture_140',['Copy-on-Write Snapshot Architecture',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md84',1,'']]],
  ['cost_141',['Compilation Cost',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md461',1,'']]],
  ['cost_20benefit_20analysis_142',['Cost-Benefit Analysis',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md459',1,'']]],
  ['cost_20by_20grammar_20size_143',['JIT Compilation Cost by Grammar Size',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md373',1,'']]],
  ['cost_20per_20token_144',['CPU Cost Per Token',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md355',1,'']]],
  ['costs_145',['Per-Token Runtime Costs',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md325',1,'']]],
  ['costs_20one_20time_146',['Loading Costs (One-Time)',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md324',1,'']]],
  ['count_147',['count',['../struct_conflict_set.html#aec138c0cc8197f00563e0cf5be085229',1,'ConflictSet::count'],['../struct_extension_order.html#a7dd522e54b5dd81bb0c56ad331fe816d',1,'ExtensionOrder::count'],['../struct_parse_fork_set.html#a7044a65267a7ad6d9a511c0994a12bde',1,'ParseForkSet::count']]],
  ['cpu_20cost_20per_20token_148',['CPU Cost Per Token',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md355',1,'']]],
  ['create_5fsnapshot_149',['create_snapshot',['../struct_lime_parser_plugin.html#a1a3852740edf42c56db96784ff34a2f9',1,'LimeParserPlugin']]],
  ['create_5ftoken_5ftable_150',['create_token_table',['../md_docs_2_a_p_i.html#autotoc_md152',1,'']]],
  ['cyclic_20dependencies_151',['Cyclic Dependencies',['../md_docs_2_l_i_t_e_r_a_t_e___f_o_r_m_a_t.html#autotoc_md569',1,'']]],
  ['cyclic_20dependency_20detected_20among_20modules_152',['&quot;Cyclic dependency detected among modules&quot;',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md548',1,'']]]
];
