var searchData=
[
  ['id_20generation_0',['Fork ID Generation',['../group__fork__id.html',1,'']]],
  ['identifiers_1',['Strategy Identifiers',['../group__strat__ids.html',1,'']]],
  ['identity_2',['Identity',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md525',1,'Module Identity'],['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md238',1,'State Identity']]],
  ['implement_20the_20callbacks_3',['Step 2: Implement the callbacks',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md289',1,'']]],
  ['implementation_4',['Example: Plugin Implementation',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md518',1,'']]],
  ['implementation_20tiers_5',['Implementation Tiers',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md99',1,'']]],
  ['implementing_20callbacks_6',['Implementing Callbacks',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md282',1,'']]],
  ['imports_7',['Imports',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md528',1,'']]],
  ['in_20lime_20c_8',['Processing Pipeline (in &lt;span class=&quot;tt&quot;&gt;lime.c&lt;/span&gt;)',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md89',1,'']]],
  ['in_20on_5funload_9',['Segmentation fault in on_unload',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md308',1,'']]],
  ['in_20your_20project_10',['Integrating Lime in Your Project',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html',1,'']]],
  ['indirected_20table_20access_11',['Snapshot-Indirected Table Access',['../md_docs_2_a_p_i.html#autotoc_md135',1,'']]],
  ['init_12',['init',['../struct_disambiguation_strategy_v_table.html#ab418098d5220932913683a053f945780',1,'DisambiguationStrategyVTable::init'],['../struct_lime_parser_plugin.html#ac31d962c853742535effb5e1aaebc02f',1,'LimeParserPlugin::init']]],
  ['initialization_20api_13',['Extension Initialization API',['../group__ext__init.html',1,'']]],
  ['inspect_20the_20base_20snapshot_14',['Inspect the base snapshot',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md298',1,'']]],
  ['integrating_20lime_20in_20your_20project_15',['Integrating Lime in Your Project',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html',1,'']]],
  ['integration_16',['Integration',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md403',1,'Code Generation and Integration'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md387',1,'JIT Integration'],['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md101',1,'LLVM JIT Integration'],['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___y_a_c_c.html#autotoc_md448',1,'No yylex Integration'],['../md_docs_2_a_p_i.html#autotoc_md180',1,'Snapshot Integration']]],
  ['integration_20guide_20examples_20lime_5fpostgres_17',['PostgreSQL Integration Guide (&lt;span class=&quot;tt&quot;&gt;examples/lime_postgres/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md80',1,'']]],
  ['integration_20with_20existing_20systems_18',['Integration with Existing Systems',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md514',1,'']]],
  ['interaction_20with_20extensions_19',['JIT Interaction with Extensions',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md370',1,'']]],
  ['interface_20',['Interface',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md437',1,'Parser Interface'],['../group__plugin__interface.html',1,'Plugin Interface']]],
  ['interface_20limeparserplugin_21',['Plugin Interface (&lt;span class=&quot;tt&quot;&gt;LimeParserPlugin&lt;/span&gt;)',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md491',1,'']]],
  ['internal_20registry_20api_20src_20extension_20h_22',['Internal Registry API (src/extension.h)',['../md_docs_2_a_p_i.html#autotoc_md168',1,'']]],
  ['internal_20terminology_23',['Internal Terminology',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md220',1,'']]],
  ['interpreted_20table_20driven_20baseline_24',['Interpreted (Table-Driven) Baseline',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md319',1,'']]],
  ['introduction_20to_20lr_20parsing_25',['Introduction to LR Parsing',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md204',1,'']]],
  ['introspection_26',['Plugin Enumeration and Introspection',['../group__plugin__introspection.html',1,'']]],
  ['introspection_20utilities_27',['Plugin Validation and Introspection Utilities',['../group__plugin__validation.html',1,'']]],
  ['invalidation_20on_20extension_20load_28',['JIT Invalidation on Extension Load',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md371',1,'']]],
  ['invariants_29',['Key Invariants',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md108',1,'']]],
  ['is_20beneficial_30',['When JIT Is Beneficial',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md464',1,'']]],
  ['is_20exported_20by_20both_20a_20and_20b_31',['&quot;Symbol &apos;X&apos; is exported by both &apos;A&apos; and &apos;B&apos;&quot;',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md549',1,'']]],
  ['is_20not_20available_32',['&quot;Module &apos;foo&apos; requires &apos;bar&apos;, which is not available&quot;',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md547',1,'']]],
  ['is_20not_20beneficial_33',['When JIT Is Not Beneficial',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md465',1,'']]],
  ['is_5factive_34',['is_active',['../struct_lime_plugin_info.html#a73d1f242882b17658b2c7d6a2e1aca01',1,'LimePluginInfo']]],
  ['is_5fdynamic_35',['is_dynamic',['../struct_lime_plugin_info.html#afab0d16bd01b3a5c8e9fca3a5d6f6f68',1,'LimePluginInfo']]],
  ['isolation_36',['Session Isolation',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md506',1,'']]],
  ['isolation_37',['Isolation Test Parser (&lt;span class=&quot;tt&quot;&gt;examples/isolation/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md68',1,'']]],
  ['isolation_20test_20parser_20examples_20isolation_38',['Isolation Test Parser (&lt;span class=&quot;tt&quot;&gt;examples/isolation/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md68',1,'']]],
  ['items_39',['Configurations (Items)',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md235',1,'']]]
];
