var searchData=
[
  ['data_20structure_0',['Data Structure',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md500',1,'']]],
  ['data_20structure_20sizes_1',['Appendix: Data Structure Sizes',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md397',1,'']]],
  ['data_20structures_20reference_2',['Data Structures Reference',['../md_docs_2_a_p_i.html#autotoc_md186',1,'']]],
  ['datalog_3',['Datalog/EDN (&lt;span class=&quot;tt&quot;&gt;examples/datalog/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md76',1,'']]],
  ['datalog_20edn_20examples_20datalog_4',['Datalog/EDN (&lt;span class=&quot;tt&quot;&gt;examples/datalog/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md76',1,'']]],
  ['decision_20tree_5',['Deployment Decision Tree',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md486',1,'']]],
  ['declaration_20keyword_3a_20module_5fname_6',['&quot;Unknown declaration keyword: %module_name&quot;',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md546',1,'']]],
  ['declarations_7',['Declarations',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md429',1,'Token Declarations'],['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md430',1,'Type Declarations']]],
  ['default_20thresholds_8',['Default Thresholds',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md484',1,'']]],
  ['define_20the_20extensioninfo_20descriptor_9',['Step 3: Define the ExtensionInfo descriptor',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md290',1,'']]],
  ['define_20the_20modifications_20array_10',['Step 1: Define the modifications array',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md288',1,'']]],
  ['degradation_11',['Graceful Degradation',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md103',1,'']]],
  ['dependencies_12',['Dependencies',['../md_docs_2_l_i_t_e_r_a_t_e___f_o_r_m_a_t.html#autotoc_md569',1,'Cyclic Dependencies'],['../index.html#autotoc_md12',1,'Dependencies'],['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md526',1,'Dependencies'],['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md553',1,'Optional Dependencies']]],
  ['dependency_20detected_20among_20modules_13',['&quot;Cyclic dependency detected among modules&quot;',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md548',1,'']]],
  ['dependency_20management_14',['Dependency Management',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md540',1,'']]],
  ['deployment_20decision_20tree_15',['Deployment Decision Tree',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md486',1,'']]],
  ['descriptor_16',['Step 3: Define the ExtensionInfo descriptor',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md290',1,'']]],
  ['design_17',['Design',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md92',1,'Design'],['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html',1,'Parser Plugin Design']]],
  ['destroy_5ftoken_5ftable_18',['destroy_token_table',['../md_docs_2_a_p_i.html#autotoc_md153',1,'']]],
  ['detailed_20comparisons_19',['Detailed Comparisons',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md408',1,'']]],
  ['detected_20among_20modules_20',['&quot;Cyclic dependency detected among modules&quot;',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md548',1,'']]],
  ['detection_21',['Detection',['../md_docs_2_c_o_n_c_e_p_t_s.html#autotoc_md30',1,'Conflict Detection'],['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md96',1,'Conflict Detection'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md346',1,'Conflict Detection'],['../md_docs_2_l_i_t_e_r_a_t_e___f_o_r_m_a_t.html#autotoc_md570',1,'Duplicate Detection']]],
  ['detection_20types_22',['Conflict Detection Types',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md294',1,'']]],
  ['development_23',['Extension Development',['../index.html#autotoc_md9',1,'']]],
  ['development_20guide_24',['Extension Development Guide',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html',1,'']]],
  ['dialect_20extensions_20contrib_25',['SQL Dialect Extensions (&lt;span class=&quot;tt&quot;&gt;contrib/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md79',1,'']]],
  ['differences_26',['Grammar Syntax Differences',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md427',1,'']]],
  ['differences_20from_20yacc_27',['Key Differences from Yacc',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___y_a_c_c.html#autotoc_md445',1,'']]],
  ['differences_20from_20yacc_20bison_28',['Key Differences from Yacc/Bison',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md219',1,'']]],
  ['directive_20format_29',['Why Directive Format?',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md522',1,'']]],
  ['directive_20mapping_30',['Directive Mapping',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md426',1,'']]],
  ['directive_20mapping_20yacc_20specific_31',['Directive Mapping (Yacc-Specific)',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___y_a_c_c.html#autotoc_md449',1,'']]],
  ['directive_20syntax_32',['Directive Syntax',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md524',1,'']]],
  ['directory_20layout_33',['Directory Layout',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md115',1,'']]],
  ['disambiguation_20examples_20llm_5foracle_34',['LLM Oracle Disambiguation (&lt;span class=&quot;tt&quot;&gt;examples/llm_oracle/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md77',1,'']]],
  ['disambiguation_20framework_35',['Disambiguation Framework',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md347',1,'']]],
  ['disambiguation_20strategies_36',['Disambiguation Strategies',['../md_docs_2_c_o_n_c_e_p_t_s.html#autotoc_md31',1,'Disambiguation Strategies'],['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md326',1,'Disambiguation Strategies']]],
  ['disambiguation_20strategy_20performance_37',['Disambiguation Strategy Performance',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md365',1,'']]],
  ['disambiguation_20strategy_20selection_38',['Disambiguation Strategy Selection',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md386',1,'']]],
  ['dispatch_39',['Runtime Dispatch',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md105',1,'']]],
  ['documentation_40',['Documentation',['../index.html#autotoc_md6',1,'']]],
  ['downgrade_20flow_41',['Upgrade / Downgrade Flow',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md509',1,'']]],
  ['doxygen_42',['Doxygen',['../index.html#autotoc_md7',1,'']]],
  ['driven_20baseline_43',['Interpreted (Table-Driven) Baseline',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md319',1,'']]],
  ['driver_44',['Writing a Driver',['../md_docs_2_g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md21',1,'']]],
  ['duplicate_20detection_45',['Duplicate Detection',['../md_docs_2_l_i_t_e_r_a_t_e___f_o_r_m_a_t.html#autotoc_md570',1,'']]],
  ['dynamic_20loading_46',['Dynamic Loading',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md495',1,'']]],
  ['dynamically_20allocated_20modifications_47',['Free dynamically allocated modifications',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md300',1,'']]]
];
