var searchData=
[
  ['re_20exporting_20symbols_0',['Re-exporting Symbols',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md552',1,'']]],
  ['reading_1',['Reading',['../md_docs_2_c_o_n_c_e_p_t_s.html#autotoc_md37',1,'Further Reading'],['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md58',1,'Further Reading']]],
  ['recommendation_2',['Recommendation',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md470',1,'']]],
  ['recommendations_3',['Recommendations',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md384',1,'Performance Tuning Recommendations'],['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md328',1,'Recommendations']]],
  ['recommended_4',['OrcJIT (Recommended)',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md474',1,'']]],
  ['recommended_20configuration_5',['Recommended Configuration',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md483',1,'']]],
  ['recovery_6',['Error Recovery',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md257',1,'']]],
  ['reduce_20example_7',['A Shift-Reduce Example',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md205',1,'']]],
  ['reduce_20reduce_20resolution_8',['Reduce/Reduce Resolution',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md244',1,'']]],
  ['reduce_20resolution_9',['Reduce/Reduce Resolution',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md244',1,'']]],
  ['reduction_10',['Conflict Reduction',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md388',1,'']]],
  ['reentrancy_11',['Reentrancy',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___y_a_c_c.html#autotoc_md447',1,'']]],
  ['reference_12',['Reference',['../md_docs_2_a_p_i.html#autotoc_md186',1,'Data Structures Reference'],['../md_docs_2_a_p_i.html',1,'Extensible SQL Parser &amp;ndash; API Reference'],['../md_docs_2_l_i_t_e_r_a_t_e___f_o_r_m_a_t.html#autotoc_md573',1,'Tool Reference']]],
  ['reference_20card_13',['Quick Reference Card',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md443',1,'']]],
  ['references_14',['References',['../index.html#autotoc_md16',1,'References'],['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md264',1,'References'],['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md555',1,'References']]],
  ['registration_15',['Registration',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md272',1,'1. Registration'],['../md_docs_2_a_p_i.html#autotoc_md199',1,'Extension Registration']]],
  ['registration_20function_16',['Step 4: Convenience registration function',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md291',1,'']]],
  ['registry_17',['Registry',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md345',1,'Extension Registry'],['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md499',1,'Plugin Registry']]],
  ['registry_20api_20src_20extension_20h_18',['Internal Registry API (src/extension.h)',['../md_docs_2_a_p_i.html#autotoc_md168',1,'']]],
  ['registry_20functions_19',['Registry Functions',['../md_docs_2_a_p_i.html#autotoc_md171',1,'']]],
  ['related_20tools_20',['Related Tools',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md267',1,'']]],
  ['remove_5ftokens_5fby_5fextension_21',['remove_tokens_by_extension',['../md_docs_2_a_p_i.html#autotoc_md156',1,'']]],
  ['removing_20rules_20mod_5fremove_5frule_22',['Removing Rules (&lt;span class=&quot;tt&quot;&gt;MOD_REMOVE_RULE&lt;/span&gt;)',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md281',1,'']]],
  ['reordering_23',['State Reordering',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md251',1,'']]],
  ['replication_24',['Replication Protocol (&lt;span class=&quot;tt&quot;&gt;examples/replication/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md70',1,'']]],
  ['replication_20config_20examples_20syncrep_25',['Synchronous Replication Config (&lt;span class=&quot;tt&quot;&gt;examples/syncrep/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md69',1,'']]],
  ['replication_20protocol_20examples_20replication_26',['Replication Protocol (&lt;span class=&quot;tt&quot;&gt;examples/replication/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md70',1,'']]],
  ['reporttable_27',['Step 10: ReportTable',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md232',1,'']]],
  ['reproduction_28',['Benchmark Reproduction',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md391',1,'']]],
  ['required_29',['get_modifications (required)',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md283',1,'']]],
  ['required_20callbacks_30',['Required Callbacks',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md492',1,'']]],
  ['required_20fields_31',['Required Fields',['../md_docs_2_l_i_t_e_r_a_t_e___f_o_r_m_a_t.html#autotoc_md562',1,'']]],
  ['requires_20bar_20which_20is_20not_20available_32',['&quot;Module &apos;foo&apos; requires &apos;bar&apos;, which is not available&quot;',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md547',1,'']]],
  ['reset_20between_20parses_33',['Pattern A: Allocate once, reset between parses',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md54',1,'']]],
  ['resolution_34',['Resolution',['../md_docs_2_a_p_i.html#autotoc_md173',1,'Conflict Resolution'],['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md241',1,'Conflict Resolution'],['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md243',1,'Precedence-Based Resolution'],['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md244',1,'Reduce/Reduce Resolution']]],
  ['resolve_20strategy_35',['Fork-Resolve Strategy',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md367',1,'']]],
  ['resortstates_36',['Step 9: ResortStates',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md231',1,'']]],
  ['reuse_37',['Parser Allocation and Reuse',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md53',1,'']]],
  ['rule_20actions_38',['Mid-Rule Actions',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md433',1,'']]],
  ['rule_20level_20conflicts_39',['Rule-Level Conflicts',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md362',1,'']]],
  ['rule_20not_20taking_20effect_40',['Grammar rule not taking effect',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md307',1,'']]],
  ['rule_20overhead_41',['Tiebreaker Rule Overhead',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md382',1,'']]],
  ['rule_20syntax_42',['Rule Syntax',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md428',1,'']]],
  ['rule_20syntax_20translation_43',['Rule Syntax Translation',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___y_a_c_c.html#autotoc_md450',1,'']]],
  ['rules_44',['Rules',['../md_docs_2_l_i_t_e_r_a_t_e___f_o_r_m_a_t.html#autotoc_md567',1,'Content Rules'],['../md_docs_2_l_i_t_e_r_a_t_e___f_o_r_m_a_t.html#autotoc_md564',1,'Naming Rules'],['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md512',1,'Ownership Rules']]],
  ['rules_20mod_5fadd_5frule_45',['Adding Grammar Rules (&lt;span class=&quot;tt&quot;&gt;MOD_ADD_RULE&lt;/span&gt;)',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md278',1,'']]],
  ['rules_20mod_5fremove_5frule_46',['Removing Rules (&lt;span class=&quot;tt&quot;&gt;MOD_REMOVE_RULE&lt;/span&gt;)',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md281',1,'']]],
  ['running_20benchmarks_47',['Running Benchmarks',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md337',1,'']]],
  ['running_20the_20parser_20benchmark_20suite_48',['Running the Parser Benchmark Suite',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md392',1,'']]],
  ['runtime_49',['Generated Parser Runtime',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md254',1,'']]],
  ['runtime_20costs_50',['Per-Token Runtime Costs',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md325',1,'']]],
  ['runtime_20dispatch_51',['Runtime Dispatch',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md105',1,'']]],
  ['runtime_20extensibility_52',['Runtime Extensibility',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md406',1,'']]],
  ['runtime_20extension_20loading_53',['Runtime Extension Loading',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md48',1,'']]],
  ['runtime_20jit_54',['Runtime JIT',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md467',1,'AOT vs Runtime JIT'],['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md469',1,'Runtime JIT']]],
  ['runtime_20parsing_20performance_55',['Runtime Parsing Performance',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md262',1,'']]]
];
