var searchData=
[
  ['machine_20construction_0',['State Machine Construction',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md234',1,'']]],
  ['make_20cmake_1',['Option 3: Generator + Extension Framework (Make / CMake)',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md43',1,'']]],
  ['makefile_2',['Makefile',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md44',1,'']]],
  ['mallocs_3',['Pattern B: Stack-allocated parser (zero mallocs)',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md55',1,'']]],
  ['management_4',['Management',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md540',1,'Dependency Management'],['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md109',1,'Memory Management'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md389',1,'Memory Management'],['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md511',1,'Memory Management']]],
  ['manager_5',['Snapshot Lifecycle Under the Manager',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md513',1,'']]],
  ['mapping_6',['Directive Mapping',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md426',1,'']]],
  ['mapping_20yacc_20specific_7',['Directive Mapping (Yacc-Specific)',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___y_a_c_c.html#autotoc_md449',1,'']]],
  ['markdown_20yaml_20format_8',['From Markdown + YAML Format',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md535',1,'']]],
  ['matrix_9',['Feature Comparison Matrix',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md401',1,'']]],
  ['matters_10',['Extension ordering matters',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md303',1,'']]],
  ['matters_20most_11',['Why Tokenizer JIT Matters Most',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md478',1,'']]],
  ['mcjit_20legacy_12',['MCJIT (Legacy)',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md473',1,'']]],
  ['mcjit_20vs_20orcjit_20migration_13',['MCJIT vs OrcJIT Migration',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md472',1,'']]],
  ['measuring_20extension_20overhead_14',['Measuring Extension Overhead',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md393',1,'']]],
  ['mechanisms_15',['Synchronization Mechanisms',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md107',1,'']]],
  ['memory_16',['Memory',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md351',1,'Per-Extension Memory'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md352',1,'Per-Fork Memory'],['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md314',1,'Snapshot Memory']]],
  ['memory_20budget_17',['Aggregate Memory Budget',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md353',1,'']]],
  ['memory_20budget_20guide_18',['Memory Budget Guide',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md332',1,'']]],
  ['memory_20management_19',['Memory Management',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md109',1,'Memory Management'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md389',1,'Memory Management'],['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md511',1,'Memory Management']]],
  ['memory_20optimization_20',['Memory Optimization',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md336',1,'']]],
  ['memory_20overhead_21',['Memory Overhead',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md350',1,'']]],
  ['memory_20overhead_20per_20extension_22',['Memory Overhead Per Extension',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md327',1,'']]],
  ['memory_20profiling_23',['Memory Profiling',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md395',1,'']]],
  ['memory_20usage_24',['Memory Usage',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md423',1,'']]],
  ['menhir_25',['Lime vs Menhir',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md412',1,'']]],
  ['menhir_20when_20you_20need_3a_26',['Use Menhir when you need:',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md418',1,'']]],
  ['meson_27',['Option 2: Generator + Extension Framework (Meson)',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md40',1,'']]],
  ['meson_20subproject_28',['As a Meson subproject',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md41',1,'']]],
  ['metadata_20block_29',['Metadata Block',['../md_docs_2_l_i_t_e_r_a_t_e___f_o_r_m_a_t.html#autotoc_md561',1,'']]],
  ['metadata_20validation_30',['Module Metadata Validation',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md543',1,'']]],
  ['metrics_20to_20compare_31',['Key Metrics to Compare',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md394',1,'']]],
  ['mid_20rule_20actions_32',['Mid-Rule Actions',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md433',1,'']]],
  ['migrating_20from_20bison_20to_20lime_33',['Migrating from Bison to Lime',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html',1,'']]],
  ['migrating_20from_20yacc_20to_20lime_34',['Migrating from Yacc to Lime',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___y_a_c_c.html',1,'']]],
  ['migration_35',['MCJIT vs OrcJIT Migration',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md472',1,'']]],
  ['migration_20checklist_36',['Quick Migration Checklist',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___y_a_c_c.html#autotoc_md453',1,'']]],
  ['migration_20guide_37',['Migration Guide',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md534',1,'']]],
  ['migration_20path_38',['Migration Path',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md475',1,'']]],
  ['migration_20paths_39',['Migration Paths',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md419',1,'']]],
  ['minimal_40',['Keep modifications minimal',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md296',1,'']]],
  ['mod_5fadd_5frule_41',['Adding Grammar Rules (&lt;span class=&quot;tt&quot;&gt;MOD_ADD_RULE&lt;/span&gt;)',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md278',1,'']]],
  ['mod_5fadd_5ftoken_42',['Adding Tokens (&lt;span class=&quot;tt&quot;&gt;MOD_ADD_TOKEN&lt;/span&gt;)',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md277',1,'']]],
  ['mod_5fadd_5ftype_43',['Adding Non-Terminal Types (&lt;span class=&quot;tt&quot;&gt;MOD_ADD_TYPE&lt;/span&gt;)',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md280',1,'']]],
  ['mod_5fmodify_5fprecedence_44',['Modifying Precedence (&lt;span class=&quot;tt&quot;&gt;MOD_MODIFY_PRECEDENCE&lt;/span&gt;)',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md279',1,'']]],
  ['mod_5fremove_5frule_45',['Removing Rules (&lt;span class=&quot;tt&quot;&gt;MOD_REMOVE_RULE&lt;/span&gt;)',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md281',1,'']]],
  ['model_46',['Model',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md501',1,'Concurrency Model'],['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md110',1,'Ownership Model'],['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___y_a_c_c.html#autotoc_md446',1,'Parser Model']]],
  ['modes_47',['JIT Compilation Modes',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md322',1,'']]],
  ['modification_48',['Copy-on-Write Modification',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md87',1,'']]],
  ['modification_20types_49',['Grammar Modification Types',['../md_docs_2_a_p_i.html#autotoc_md172',1,'']]],
  ['modifications_50',['Modifications',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md95',1,'Grammar Modifications'],['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md276',1,'Grammar Modifications']]],
  ['modifications_51',['Free dynamically allocated modifications',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md300',1,'']]],
  ['modifications_20array_52',['Step 1: Define the modifications array',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md288',1,'']]],
  ['modifications_20minimal_53',['Keep modifications minimal',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md296',1,'']]],
  ['modifying_20precedence_20mod_5fmodify_5fprecedence_54',['Modifying Precedence (&lt;span class=&quot;tt&quot;&gt;MOD_MODIFY_PRECEDENCE&lt;/span&gt;)',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md279',1,'']]],
  ['modular_20grammar_20examples_20pg_5fmodular_55',['PostgreSQL Modular Grammar (&lt;span class=&quot;tt&quot;&gt;examples/pg_modular/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md64',1,'']]],
  ['module_20composition_56',['Module Composition',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md530',1,'']]],
  ['module_20foo_20requires_20bar_20which_20is_20not_20available_57',['&quot;Module &apos;foo&apos; requires &apos;bar&apos;, which is not available&quot;',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md547',1,'']]],
  ['module_20format_58',['Lime Module Format',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html',1,'']]],
  ['module_20identity_59',['Module Identity',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md525',1,'']]],
  ['module_20metadata_20validation_60',['Module Metadata Validation',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md543',1,'']]],
  ['module_20organization_61',['Module Organization',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md538',1,'']]],
  ['module_20system_62',['Module System',['../md_docs_2_c_o_n_c_e_p_t_s.html#autotoc_md36',1,'']]],
  ['module_5fname_63',['&quot;Unknown declaration keyword: %module_name&quot;',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md546',1,'']]],
  ['modules_64',['&quot;Cyclic dependency detected among modules&quot;',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md548',1,'']]],
  ['mongodb_65',['MongoDB Query Language (&lt;span class=&quot;tt&quot;&gt;examples/mongodb/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md75',1,'']]],
  ['mongodb_20query_20language_20examples_20mongodb_66',['MongoDB Query Language (&lt;span class=&quot;tt&quot;&gt;examples/mongodb/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md75',1,'']]],
  ['monolithic_20grammar_67',['From Monolithic Grammar',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md536',1,'']]],
  ['most_68',['Most',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md316',1,'When SIMD Helps Most'],['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md478',1,'Why Tokenizer JIT Matters Most']]],
  ['motivation_69',['Motivation',['../index.html#autotoc_md2',1,'']]],
  ['multiple_20extensions_70',['Multiple Extensions',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md331',1,'']]]
];
