var searchData=
[
  ['c_0',['c',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md61',1,'JSONB Extension (&lt;span class=&quot;tt&quot;&gt;examples/jsonb_extension.c&lt;/span&gt;)'],['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md89',1,'Processing Pipeline (in &lt;span class=&quot;tt&quot;&gt;lime.c&lt;/span&gt;)']]],
  ['calc_1',['Calculator (&lt;span class=&quot;tt&quot;&gt;examples/calc/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md60',1,'']]],
  ['calculator_20examples_20calc_2',['Calculator (&lt;span class=&quot;tt&quot;&gt;examples/calc/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md60',1,'']]],
  ['callbacks_3',['Callbacks',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md94',1,'Extension Callbacks'],['../md_docs_2_a_p_i.html#autotoc_md170',1,'Extension Callbacks'],['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md282',1,'Implementing Callbacks'],['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md493',1,'Optional Callbacks'],['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md492',1,'Required Callbacks']]],
  ['callbacks_4',['Step 2: Implement the callbacks',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md289',1,'']]],
  ['canonical_20lr_201_5',['Canonical LR(1)',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md211',1,'']]],
  ['capabilities_6',['Capabilities',['../md_docs_2_l_i_t_e_r_a_t_e___f_o_r_m_a_t.html#autotoc_md565',1,'']]],
  ['card_7',['Quick Reference Card',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md443',1,'']]],
  ['changed_8',['What Changed',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md441',1,'']]],
  ['changes_9',['Build System Changes',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md434',1,'']]],
  ['character_20classification_10',['Character Classification',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md98',1,'Character Classification'],['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md315',1,'SIMD Character Classification']]],
  ['character_20classification_20api_11',['SIMD Character Classification API',['../md_docs_2_a_p_i.html#autotoc_md158',1,'']]],
  ['characteristics_12',['Characteristics',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html',1,'Extension Framework Performance Characteristics'],['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html',1,'Performance Characteristics'],['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md259',1,'Performance Characteristics']]],
  ['checklist_13',['Checklist',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___y_a_c_c.html#autotoc_md453',1,'Quick Migration Checklist'],['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md57',1,'Thread Safety Checklist']]],
  ['checks_14',['Plugin Version Checks',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md508',1,'']]],
  ['classification_15',['Classification',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md98',1,'Character Classification'],['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md315',1,'SIMD Character Classification']]],
  ['classification_20api_16',['SIMD Character Classification API',['../md_docs_2_a_p_i.html#autotoc_md158',1,'']]],
  ['classifier_17',['Trie-Based Keyword Classifier',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md479',1,'']]],
  ['classify_5fscalar_18',['classify_scalar',['../md_docs_2_a_p_i.html#autotoc_md162',1,'']]],
  ['classify_5fsimd_5favx2_20x86_5f64_20only_19',['classify_simd_avx2 (x86_64 only)',['../md_docs_2_a_p_i.html#autotoc_md163',1,'']]],
  ['classify_5fsimd_5fneon_20arm_20only_20',['classify_simd_neon (ARM only)',['../md_docs_2_a_p_i.html#autotoc_md164',1,'']]],
  ['cleanup_21',['4. Cleanup',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md275',1,'']]],
  ['closure_22',['Closure',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md236',1,'']]],
  ['cmake_23',['CMake',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md45',1,'CMake'],['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md43',1,'Option 3: Generator + Extension Framework (Make / CMake)']]],
  ['code_20blocks_24',['Code Blocks',['../md_docs_2_l_i_t_e_r_a_t_e___f_o_r_m_a_t.html#autotoc_md566',1,'']]],
  ['code_20generation_20and_20integration_25',['Code Generation and Integration',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md403',1,'']]],
  ['codes_26',['Token Type Codes',['../md_docs_2_a_p_i.html#autotoc_md189',1,'']]],
  ['codes_27',['Use auto-assigned token codes',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md297',1,'']]],
  ['collisions_28',['Avoiding Symbol Collisions',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md50',1,'']]],
  ['common_20gotchas_29',['Common Gotchas',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md442',1,'']]],
  ['compare_30',['Key Metrics to Compare',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md394',1,'']]],
  ['comparison_31',['Comparison',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md212',1,'Comparison'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md360',1,'Conflict Type Comparison'],['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md424',1,'License Comparison'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md368',1,'Strategy Comparison']]],
  ['comparison_20guide_32',['Parser Generator Comparison Guide',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html',1,'']]],
  ['comparison_20matrix_33',['Feature Comparison Matrix',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md401',1,'']]],
  ['comparison_20table_34',['Comparison Table',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md215',1,'']]],
  ['comparison_20to_20bison_20yacc_35',['Comparison to Bison/Yacc',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md523',1,'']]],
  ['comparisons_36',['Detailed Comparisons',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md408',1,'']]],
  ['compatibility_37',['Version Compatibility',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md507',1,'']]],
  ['compatibility_20notes_38',['Compatibility Notes',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___y_a_c_c.html#autotoc_md452',1,'']]],
  ['compilation_39',['Compilation',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md114',1,'Conditional Compilation'],['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md554',1,'Conditional Compilation'],['../md_docs_2_c_o_n_c_e_p_t_s.html#autotoc_md35',1,'JIT Compilation'],['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md318',1,'JIT Compilation'],['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md516',1,'JIT Compilation']]],
  ['compilation_20analysis_20for_20lime_20parser_20generator_40',['JIT Compilation Analysis for Lime Parser Generator',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html',1,'']]],
  ['compilation_20api_41',['JIT Compilation API',['../md_docs_2_a_p_i.html#autotoc_md175',1,'']]],
  ['compilation_20cost_42',['Compilation Cost',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md461',1,'']]],
  ['compilation_20cost_20by_20grammar_20size_43',['JIT Compilation Cost by Grammar Size',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md373',1,'']]],
  ['compilation_20lime_20j_44',['AOT Compilation (&lt;span class=&quot;tt&quot;&gt;lime -j&lt;/span&gt;)',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md468',1,'']]],
  ['compilation_20modes_45',['JIT Compilation Modes',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md322',1,'']]],
  ['compilation_20trigger_46',['Compilation Trigger',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md104',1,'']]],
  ['compilation_20with_20policy_47',['JIT Compilation with Policy',['../md_docs_2_a_p_i.html#autotoc_md200',1,'']]],
  ['compiling_20the_20example_48',['Compiling the example',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md292',1,'']]],
  ['complete_20example_49',['Complete Example',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md239',1,'Complete Example'],['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md529',1,'Complete Example']]],
  ['complete_20walkthrough_3a_20jsonb_20extension_50',['Complete Walkthrough: JSONB Extension',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md286',1,'']]],
  ['complexity_51',['Complexity',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md261',1,'Space Complexity'],['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md260',1,'Time Complexity']]],
  ['component_20overhead_20breakdown_52',['Component Overhead Breakdown',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md344',1,'']]],
  ['component_20overview_53',['Component Overview',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md83',1,'']]],
  ['compose_54',['Using lime-compose',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md531',1,'']]],
  ['composed_20output_55',['Composed Output',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md533',1,'']]],
  ['composition_56',['Module Composition',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md530',1,'']]],
  ['composition_20process_57',['Composition Process',['../md_docs_2_l_i_t_e_r_a_t_e___f_o_r_m_a_t.html#autotoc_md568',1,'']]],
  ['composition_20validation_58',['Composition Validation',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md544',1,'']]],
  ['composition_20works_59',['How Composition Works',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md532',1,'']]],
  ['compression_60',['Compression',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md268',1,'Action Table Compression'],['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md247',1,'Table Compression']]],
  ['compresstables_61',['Step 8: CompressTables',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md230',1,'']]],
  ['concepts_62',['Concepts',['../md_docs_2_c_o_n_c_e_p_t_s.html',1,'']]],
  ['concurrency_20model_63',['Concurrency Model',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md501',1,'']]],
  ['concurrent_20parsers_64',['Concurrent Parsers',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md330',1,'']]],
  ['conditional_20compilation_65',['Conditional Compilation',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md114',1,'Conditional Compilation'],['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md554',1,'Conditional Compilation']]],
  ['config_20examples_20syncrep_66',['Synchronous Replication Config (&lt;span class=&quot;tt&quot;&gt;examples/syncrep/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md69',1,'']]],
  ['configuration_67',['Recommended Configuration',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md483',1,'']]],
  ['configurations_20items_68',['Configurations (Items)',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md235',1,'']]],
  ['conflict_20action_20types_69',['Conflict Action Types',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md245',1,'']]],
  ['conflict_20detection_70',['Conflict Detection',['../md_docs_2_c_o_n_c_e_p_t_s.html#autotoc_md30',1,'Conflict Detection'],['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md96',1,'Conflict Detection'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md346',1,'Conflict Detection']]],
  ['conflict_20detection_20types_71',['Conflict Detection Types',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md294',1,'']]],
  ['conflict_20reduction_72',['Conflict Reduction',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md388',1,'']]],
  ['conflict_20resolution_73',['Conflict Resolution',['../md_docs_2_a_p_i.html#autotoc_md173',1,'Conflict Resolution'],['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md241',1,'Conflict Resolution']]],
  ['conflict_20type_20comparison_74',['Conflict Type Comparison',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md360',1,'']]],
  ['conflicts_75',['Conflicts',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md362',1,'Rule-Level Conflicts'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md363',1,'Semantic-Level Conflicts'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md361',1,'Token-Level Conflicts'],['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md242',1,'Types of Conflicts'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md358',1,'With Extensions (Active Conflicts)'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md357',1,'With Extensions (No Conflicts)']]],
  ['conflicts_76',['Token conflicts',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md306',1,'']]],
  ['conflicts_20gracefully_77',['Handle conflicts gracefully',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md299',1,'']]],
  ['considerations_78',['Future Considerations',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md519',1,'']]],
  ['constraints_79',['Version Constraints',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md551',1,'']]],
  ['construction_80',['State Machine Construction',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md234',1,'']]],
  ['content_20rules_81',['Content Rules',['../md_docs_2_l_i_t_e_r_a_t_e___f_o_r_m_a_t.html#autotoc_md567',1,'']]],
  ['contents_82',['Contents',['../md_docs_2_a_p_i.html#autotoc_md117',1,'Table of Contents'],['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md202',1,'Table of Contents'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md340',1,'Table of Contents']]],
  ['context_20api_83',['Parse Context API',['../md_docs_2_a_p_i.html#autotoc_md128',1,'']]],
  ['contrib_84',['SQL Dialect Extensions (&lt;span class=&quot;tt&quot;&gt;contrib/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md79',1,'']]],
  ['contributing_85',['Contributing',['../index.html#autotoc_md13',1,'']]],
  ['convenience_20registration_20function_86',['Step 4: Convenience registration function',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md291',1,'']]],
  ['conventions_87',['Conventions',['../md_docs_2_a_p_i.html#autotoc_md191',1,'Error Handling Conventions'],['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md539',1,'Naming Conventions']]],
  ['converted_20lime_20boot_5fgrammar_20lime_20excerpt_88',['Converted Lime (boot_grammar.lime excerpt)',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md440',1,'']]],
  ['copy_20on_20write_20and_20thread_20safety_89',['Copy-on-Write and Thread Safety',['../md_docs_2_c_o_n_c_e_p_t_s.html#autotoc_md33',1,'']]],
  ['copy_20on_20write_20modification_90',['Copy-on-Write Modification',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md87',1,'']]],
  ['copy_20on_20write_20snapshot_20architecture_91',['Copy-on-Write Snapshot Architecture',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md84',1,'']]],
  ['cost_92',['Compilation Cost',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md461',1,'']]],
  ['cost_20benefit_20analysis_93',['Cost-Benefit Analysis',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md459',1,'']]],
  ['cost_20by_20grammar_20size_94',['JIT Compilation Cost by Grammar Size',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md373',1,'']]],
  ['cost_20per_20token_95',['CPU Cost Per Token',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md355',1,'']]],
  ['costs_96',['Per-Token Runtime Costs',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md325',1,'']]],
  ['costs_20one_20time_97',['Loading Costs (One-Time)',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md324',1,'']]],
  ['cpu_20cost_20per_20token_98',['CPU Cost Per Token',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md355',1,'']]],
  ['create_5ftoken_5ftable_99',['create_token_table',['../md_docs_2_a_p_i.html#autotoc_md152',1,'']]],
  ['cyclic_20dependencies_100',['Cyclic Dependencies',['../md_docs_2_l_i_t_e_r_a_t_e___f_o_r_m_a_t.html#autotoc_md569',1,'']]],
  ['cyclic_20dependency_20detected_20among_20modules_101',['&quot;Cyclic dependency detected among modules&quot;',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md548',1,'']]]
];
