var searchData=
[
  ['each_20tool_0',['When to Use Each Tool',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md413',1,'']]],
  ['edn_20examples_20datalog_1',['Datalog/EDN (&lt;span class=&quot;tt&quot;&gt;examples/datalog/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md76',1,'']]],
  ['effect_2',['Grammar rule not taking effect',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md307',1,'']]],
  ['error_20handling_3',['Error Handling',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md404',1,'Error Handling'],['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md432',1,'Error Handling'],['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md510',1,'Error Handling']]],
  ['error_20handling_20conventions_4',['Error Handling Conventions',['../md_docs_2_a_p_i.html#autotoc_md191',1,'']]],
  ['error_20recovery_5',['Error Recovery',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md257',1,'']]],
  ['even_20analysis_20with_20extensions_6',['Break-Even Analysis with Extensions',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md372',1,'']]],
  ['even_20point_7',['Break-Even Point',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md462',1,'']]],
  ['example_8',['Example',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md205',1,'A Shift-Reduce Example'],['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md239',1,'Complete Example'],['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md529',1,'Complete Example'],['../md_docs_2_l_i_t_e_r_a_t_e___f_o_r_m_a_t.html#autotoc_md572',1,'Example']]],
  ['example_9',['Compiling the example',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md292',1,'']]],
  ['example_3a_20plugin_20implementation_10',['Example: Plugin Implementation',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md518',1,'']]],
  ['example_3a_20postgresql_20bootstrap_20parser_11',['Worked Example: PostgreSQL Bootstrap Parser',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md438',1,'']]],
  ['examples_12',['Examples',['../md_docs_2_e_x_a_m_p_l_e_s.html',1,'Examples'],['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md556',1,'Examples'],['../md_docs_2_a_p_i.html#autotoc_md195',1,'Usage Examples']]],
  ['examples_20bootstrap_13',['Bootstrap (BKI) Parser (&lt;span class=&quot;tt&quot;&gt;examples/bootstrap/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md67',1,'']]],
  ['examples_20calc_14',['Calculator (&lt;span class=&quot;tt&quot;&gt;examples/calc/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md60',1,'']]],
  ['examples_20datalog_15',['Datalog/EDN (&lt;span class=&quot;tt&quot;&gt;examples/datalog/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md76',1,'']]],
  ['examples_20isolation_16',['Isolation Test Parser (&lt;span class=&quot;tt&quot;&gt;examples/isolation/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md68',1,'']]],
  ['examples_20jsonb_5fextension_20c_17',['JSONB Extension (&lt;span class=&quot;tt&quot;&gt;examples/jsonb_extension.c&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md61',1,'']]],
  ['examples_20jsonpath_18',['JSONPath (&lt;span class=&quot;tt&quot;&gt;examples/jsonpath/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md72',1,'']]],
  ['examples_20lime_5fpostgres_19',['PostgreSQL Integration Guide (&lt;span class=&quot;tt&quot;&gt;examples/lime_postgres/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md80',1,'']]],
  ['examples_20literate_20',['Literate Grammar Format (&lt;span class=&quot;tt&quot;&gt;examples/literate/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md78',1,'']]],
  ['examples_20llm_5foracle_21',['LLM Oracle Disambiguation (&lt;span class=&quot;tt&quot;&gt;examples/llm_oracle/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md77',1,'']]],
  ['examples_20mongodb_22',['MongoDB Query Language (&lt;span class=&quot;tt&quot;&gt;examples/mongodb/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md75',1,'']]],
  ['examples_20pg_23',['PostgreSQL Full Grammar (&lt;span class=&quot;tt&quot;&gt;examples/pg/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md63',1,'']]],
  ['examples_20pg_5fmodular_24',['PostgreSQL Modular Grammar (&lt;span class=&quot;tt&quot;&gt;examples/pg_modular/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md64',1,'']]],
  ['examples_20pgbench_25',['pgbench Expressions (&lt;span class=&quot;tt&quot;&gt;examples/pgbench/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md66',1,'']]],
  ['examples_20plugin_5ftemplate_26',['Plugin Template (&lt;span class=&quot;tt&quot;&gt;examples/plugin_template/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md62',1,'']]],
  ['examples_20replication_27',['Replication Protocol (&lt;span class=&quot;tt&quot;&gt;examples/replication/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md70',1,'']]],
  ['examples_20syncrep_28',['Synchronous Replication Config (&lt;span class=&quot;tt&quot;&gt;examples/syncrep/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md69',1,'']]],
  ['examples_20xpath_29',['XPath 1.0 (&lt;span class=&quot;tt&quot;&gt;examples/xpath/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md73',1,'']]],
  ['examples_20xquery_30',['XQuery 1.0 (&lt;span class=&quot;tt&quot;&gt;examples/xquery/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md74',1,'']]],
  ['excerpt_31',['excerpt',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md440',1,'Converted Lime (boot_grammar.lime excerpt)'],['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md439',1,'Original Bison (bootparse.y excerpt)']]],
  ['execution_20policies_32',['Execution Policies',['../md_docs_2_c_o_n_c_e_p_t_s.html#autotoc_md32',1,'']]],
  ['existing_20systems_33',['Integration with Existing Systems',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md514',1,'']]],
  ['expected_20performance_34',['Expected Performance',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md480',1,'']]],
  ['exported_20by_20both_20a_20and_20b_35',['&quot;Symbol &apos;X&apos; is exported by both &apos;A&apos; and &apos;B&apos;&quot;',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md549',1,'']]],
  ['exporting_20symbols_36',['Re-exporting Symbols',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md552',1,'']]],
  ['exports_37',['Exports',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md527',1,'']]],
  ['expressions_20examples_20pgbench_38',['pgbench Expressions (&lt;span class=&quot;tt&quot;&gt;examples/pgbench/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md66',1,'']]],
  ['extensibility_39',['Runtime Extensibility',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md406',1,'']]],
  ['extensible_20sql_20parser_20ndash_20api_20reference_40',['Extensible SQL Parser &amp;ndash; API Reference',['../md_docs_2_a_p_i.html',1,'']]],
  ['extension_41',['Extension',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md376',1,'1 Extension'],['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md286',1,'Complete Walkthrough: JSONB Extension'],['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md327',1,'Memory Overhead Per Extension']]],
  ['extension_20adds_42',['What the extension adds',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md287',1,'']]],
  ['extension_20api_43',['Extension API',['../md_docs_2_a_p_i.html#autotoc_md166',1,'']]],
  ['extension_20callbacks_44',['Extension Callbacks',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md94',1,'Extension Callbacks'],['../md_docs_2_a_p_i.html#autotoc_md170',1,'Extension Callbacks']]],
  ['extension_20development_45',['Extension Development',['../index.html#autotoc_md9',1,'']]],
  ['extension_20development_20guide_46',['Extension Development Guide',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html',1,'']]],
  ['extension_20examples_20jsonb_5fextension_20c_47',['JSONB Extension (&lt;span class=&quot;tt&quot;&gt;examples/jsonb_extension.c&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md61',1,'']]],
  ['extension_20fails_20to_20load_48',['Extension fails to load',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md305',1,'']]],
  ['extension_20framework_49',['Extension Framework',['../md_docs_2_g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md22',1,'Building the Extension Framework'],['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md39',1,'Option 1: Generator Only (No Extension Framework)']]],
  ['extension_20framework_20make_20cmake_50',['Option 3: Generator + Extension Framework (Make / CMake)',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md43',1,'']]],
  ['extension_20framework_20meson_51',['Option 2: Generator + Extension Framework (Meson)',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md40',1,'']]],
  ['extension_20framework_20performance_20characteristics_52',['Extension Framework Performance Characteristics',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html',1,'']]],
  ['extension_20framework_20symbols_53',['Library (extension framework) symbols',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md52',1,'']]],
  ['extension_20h_54',['Internal Registry API (src/extension.h)',['../md_docs_2_a_p_i.html#autotoc_md168',1,'']]],
  ['extension_20lifecycle_55',['Extension Lifecycle',['../md_docs_2_c_o_n_c_e_p_t_s.html#autotoc_md29',1,'Extension Lifecycle'],['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md93',1,'Extension Lifecycle'],['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md271',1,'Extension Lifecycle']]],
  ['extension_20load_56',['JIT Invalidation on Extension Load',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md371',1,'']]],
  ['extension_20loading_57',['Extension Loading',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md385',1,'Extension Loading'],['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md48',1,'Runtime Extension Loading']]],
  ['extension_20memory_58',['Per-Extension Memory',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md351',1,'']]],
  ['extension_20ordering_20matters_59',['Extension ordering matters',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md303',1,'']]],
  ['extension_20overhead_60',['Extension Overhead',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md323',1,'Extension Overhead'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md393',1,'Measuring Extension Overhead']]],
  ['extension_20registration_61',['Extension Registration',['../md_docs_2_a_p_i.html#autotoc_md199',1,'']]],
  ['extension_20registry_62',['Extension Registry',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md345',1,'']]],
  ['extension_20system_63',['Extension System',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md91',1,'Extension System'],['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md515',1,'Extension System']]],
  ['extensioninfo_20descriptor_64',['Step 3: Define the ExtensionInfo descriptor',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md290',1,'']]],
  ['extensions_65',['Extensions',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md378',1,'10 Extensions'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md377',1,'5 Extensions'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md379',1,'50 Extensions'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md356',1,'Baseline (No Extensions)'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md372',1,'Break-Even Analysis with Extensions'],['../md_docs_2_c_o_n_c_e_p_t_s.html#autotoc_md28',1,'Extensions'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md370',1,'JIT Interaction with Extensions'],['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md331',1,'Multiple Extensions']]],
  ['extensions_20active_20conflicts_66',['With Extensions (Active Conflicts)',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md358',1,'']]],
  ['extensions_20are_20applied_67',['How Extensions Are Applied',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md293',1,'']]],
  ['extensions_20contrib_68',['SQL Dialect Extensions (&lt;span class=&quot;tt&quot;&gt;contrib/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md79',1,'']]],
  ['extensions_20no_20conflicts_69',['With Extensions (No Conflicts)',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md357',1,'']]]
];
