var searchData=
[
  ['fails_20to_20load_0',['Extension fails to load',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md305',1,'']]],
  ['family_1',['The LR Parsing Family',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md207',1,'']]],
  ['fault_20in_20on_5funload_2',['Segmentation fault in on_unload',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md308',1,'']]],
  ['feature_20comparison_20matrix_3',['Feature Comparison Matrix',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md401',1,'']]],
  ['fields_4',['Fields',['../md_docs_2_l_i_t_e_r_a_t_e___f_o_r_m_a_t.html#autotoc_md563',1,'Optional Fields'],['../md_docs_2_l_i_t_e_r_a_t_e___f_o_r_m_a_t.html#autotoc_md562',1,'Required Fields']]],
  ['file_20layout_5',['File Layout',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md541',1,'']]],
  ['file_20structure_6',['File Structure',['../md_docs_2_l_i_t_e_r_a_t_e___f_o_r_m_a_t.html#autotoc_md560',1,'']]],
  ['findactions_7',['Step 7: FindActions',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md229',1,'']]],
  ['findfirstsets_8',['Step 3: FindFirstSets',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md225',1,'']]],
  ['findfollowsets_9',['Step 6: FindFollowSets',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md228',1,'']]],
  ['findlinks_10',['Step 5: FindLinks',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md227',1,'']]],
  ['findruleprecedences_11',['Step 2: FindRulePrecedences',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md224',1,'']]],
  ['findstates_12',['Step 4: FindStates',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md226',1,'']]],
  ['first_20grammar_13',['Your First Grammar',['../md_docs_2_g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md20',1,'']]],
  ['five_20arrays_14',['The Five Arrays',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md248',1,'']]],
  ['flags_15',['Useful Flags',['../md_docs_2_g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md23',1,'']]],
  ['flow_16',['Upgrade / Downgrade Flow',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md509',1,'']]],
  ['foo_20requires_20bar_20which_20is_20not_20available_17',['&quot;Module &apos;foo&apos; requires &apos;bar&apos;, which is not available&quot;',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md547',1,'']]],
  ['for_20lime_20parser_20generator_18',['JIT Compilation Analysis for Lime Parser Generator',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html',1,'']]],
  ['for_20state_19',['Use user_data for state',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md301',1,'']]],
  ['fork_20memory_20',['Per-Fork Memory',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md352',1,'']]],
  ['fork_20resolve_20strategy_21',['Fork-Resolve Strategy',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md367',1,'']]],
  ['forking_22',['Parser Forking',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md348',1,'']]],
  ['format_23',['Format',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md535',1,'From Markdown + YAML Format'],['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html',1,'Lime Module Format'],['../md_docs_2_l_i_t_e_r_a_t_e___f_o_r_m_a_t.html#autotoc_md571',1,'Output Format'],['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md522',1,'Why Directive Format?']]],
  ['format_20examples_20literate_24',['Literate Grammar Format (&lt;span class=&quot;tt&quot;&gt;examples/literate/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md78',1,'']]],
  ['format_20specification_25',['Literate Grammar Format Specification',['../md_docs_2_l_i_t_e_r_a_t_e___f_o_r_m_a_t.html',1,'']]],
  ['foundational_20works_26',['Foundational Works',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md265',1,'']]],
  ['framework_27',['Framework',['../md_docs_2_g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md22',1,'Building the Extension Framework'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md347',1,'Disambiguation Framework'],['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md39',1,'Option 1: Generator Only (No Extension Framework)']]],
  ['framework_20make_20cmake_28',['Option 3: Generator + Extension Framework (Make / CMake)',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md43',1,'']]],
  ['framework_20meson_29',['Option 2: Generator + Extension Framework (Meson)',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md40',1,'']]],
  ['framework_20performance_20characteristics_30',['Extension Framework Performance Characteristics',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html',1,'']]],
  ['framework_20symbols_31',['Library (extension framework) symbols',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md52',1,'']]],
  ['free_20dynamically_20allocated_20modifications_32',['Free dynamically allocated modifications',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md300',1,'']]],
  ['from_20bison_20to_20lime_33',['Migrating from Bison to Lime',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html',1,'']]],
  ['from_20jit_20on_20action_20table_20lookups_34',['Speedup from JIT on Action Table Lookups',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md460',1,'']]],
  ['from_20markdown_20yaml_20format_35',['From Markdown + YAML Format',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md535',1,'']]],
  ['from_20monolithic_20grammar_36',['From Monolithic Grammar',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md536',1,'']]],
  ['from_20yacc_37',['Key Differences from Yacc',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___y_a_c_c.html#autotoc_md445',1,'']]],
  ['from_20yacc_20bison_38',['Key Differences from Yacc/Bison',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md219',1,'']]],
  ['from_20yacc_20to_20lime_39',['Migrating from Yacc to Lime',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___y_a_c_c.html',1,'']]],
  ['full_20grammar_20examples_20pg_40',['PostgreSQL Full Grammar (&lt;span class=&quot;tt&quot;&gt;examples/pg/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md63',1,'']]],
  ['function_41',['GOTO Function',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md237',1,'']]],
  ['function_42',['Step 4: Convenience registration function',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md291',1,'']]],
  ['functions_43',['Functions',['../md_docs_2_a_p_i.html#autotoc_md123',1,'Functions'],['../md_docs_2_a_p_i.html#autotoc_md130',1,'Functions'],['../md_docs_2_a_p_i.html#autotoc_md139',1,'Functions'],['../md_docs_2_a_p_i.html#autotoc_md151',1,'Functions'],['../md_docs_2_a_p_i.html#autotoc_md160',1,'Functions'],['../md_docs_2_a_p_i.html#autotoc_md177',1,'Functions'],['../md_docs_2_a_p_i.html#autotoc_md184',1,'Functions'],['../md_docs_2_a_p_i.html#autotoc_md171',1,'Registry Functions']]],
  ['further_20reading_44',['Further Reading',['../md_docs_2_c_o_n_c_e_p_t_s.html#autotoc_md37',1,'Further Reading'],['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md58',1,'Further Reading']]],
  ['future_20considerations_45',['Future Considerations',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md519',1,'']]]
];
