var searchData=
[
  ['s_20approach_0',['Lime&apos;s Approach',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md218',1,'']]],
  ['safety_1',['Safety',['../md_docs_2_c_o_n_c_e_p_t_s.html#autotoc_md33',1,'Copy-on-Write and Thread Safety'],['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md106',1,'Thread Safety'],['../md_docs_2_a_p_i.html#autotoc_md193',1,'Thread Safety']]],
  ['safety_2',['Thread safety',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md302',1,'']]],
  ['safety_20checklist_3',['Thread Safety Checklist',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md57',1,'']]],
  ['savings_4',['Space Savings',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md252',1,'']]],
  ['scaling_20behavior_5',['Scaling Behavior',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md329',1,'Scaling Behavior'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md375',1,'Scaling Behavior']]],
  ['scaling_20summary_6',['Scaling Summary',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md380',1,'']]],
  ['segmentation_20fault_20in_20on_5funload_7',['Segmentation fault in on_unload',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md308',1,'']]],
  ['selection_8',['Disambiguation Strategy Selection',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md386',1,'']]],
  ['semantic_20level_20conflicts_9',['Semantic-Level Conflicts',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md363',1,'']]],
  ['session_10',['Parse Session',['../md_docs_2_a_p_i.html#autotoc_md198',1,'']]],
  ['session_20isolation_11',['Session Isolation',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md506',1,'']]],
  ['setting_20the_20active_20plugin_12',['Setting the Active Plugin',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md504',1,'']]],
  ['shared_20library_20plugins_13',['Shared Library Plugins',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md496',1,'']]],
  ['shift_20reduce_20example_14',['A Shift-Reduce Example',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md205',1,'']]],
  ['simd_20acceleration_15',['SIMD Acceleration',['../md_docs_2_a_p_i.html#autotoc_md147',1,'']]],
  ['simd_20character_20classification_16',['SIMD Character Classification',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md315',1,'']]],
  ['simd_20character_20classification_20api_17',['SIMD Character Classification API',['../md_docs_2_a_p_i.html#autotoc_md158',1,'']]],
  ['simd_20helps_20least_18',['When SIMD Helps Least',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md317',1,'']]],
  ['simd_20helps_20most_19',['When SIMD Helps Most',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md316',1,'']]],
  ['simd_20tokenization_20',['SIMD Tokenization',['../md_docs_2_c_o_n_c_e_p_t_s.html#autotoc_md34',1,'SIMD Tokenization'],['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md97',1,'SIMD Tokenization']]],
  ['simple_20lr_21',['SLR(1) &amp;ndash; Simple LR',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md209',1,'']]],
  ['size_22',['JIT Compilation Cost by Grammar Size',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md373',1,'']]],
  ['sizes_23',['Appendix: Data Structure Sizes',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md397',1,'']]],
  ['slr_201_20ndash_20simple_20lr_24',['SLR(1) &amp;ndash; Simple LR',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md209',1,'']]],
  ['snapshot_25',['Inspect the base snapshot',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md298',1,'']]],
  ['snapshot_20api_26',['Snapshot API',['../md_docs_2_a_p_i.html#autotoc_md121',1,'']]],
  ['snapshot_20architecture_27',['Copy-on-Write Snapshot Architecture',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md84',1,'']]],
  ['snapshot_20h_28',['ParserSnapshot (src/snapshot.h)',['../md_docs_2_a_p_i.html#autotoc_md187',1,'']]],
  ['snapshot_20indirected_20table_20access_29',['Snapshot-Indirected Table Access',['../md_docs_2_a_p_i.html#autotoc_md135',1,'']]],
  ['snapshot_20integration_30',['Snapshot Integration',['../md_docs_2_a_p_i.html#autotoc_md180',1,'']]],
  ['snapshot_20lifecycle_31',['Snapshot Lifecycle',['../md_docs_2_a_p_i.html#autotoc_md197',1,'']]],
  ['snapshot_20lifecycle_20under_20the_20manager_32',['Snapshot Lifecycle Under the Manager',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md513',1,'']]],
  ['snapshot_20memory_33',['Snapshot Memory',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md314',1,'']]],
  ['snapshot_20operations_34',['Snapshot Operations',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md313',1,'']]],
  ['snapshots_35',['Snapshots',['../md_docs_2_c_o_n_c_e_p_t_s.html#autotoc_md27',1,'']]],
  ['space_20complexity_36',['Space Complexity',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md261',1,'']]],
  ['space_20savings_37',['Space Savings',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md252',1,'']]],
  ['specific_38',['Directive Mapping (Yacc-Specific)',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___y_a_c_c.html#autotoc_md449',1,'']]],
  ['specification_39',['Literate Grammar Format Specification',['../md_docs_2_l_i_t_e_r_a_t_e___f_o_r_m_a_t.html',1,'']]],
  ['speedup_20from_20jit_20on_20action_20table_20lookups_40',['Speedup from JIT on Action Table Lookups',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md460',1,'']]],
  ['sql_20dialect_20extensions_20contrib_41',['SQL Dialect Extensions (&lt;span class=&quot;tt&quot;&gt;contrib/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md79',1,'']]],
  ['sql_20parser_20ndash_20api_20reference_42',['Extensible SQL Parser &amp;ndash; API Reference',['../md_docs_2_a_p_i.html',1,'']]],
  ['src_20extension_20h_43',['Internal Registry API (src/extension.h)',['../md_docs_2_a_p_i.html#autotoc_md168',1,'']]],
  ['src_20snapshot_20h_44',['ParserSnapshot (src/snapshot.h)',['../md_docs_2_a_p_i.html#autotoc_md187',1,'']]],
  ['stack_20allocated_20parser_20zero_20mallocs_45',['Pattern B: Stack-allocated parser (zero mallocs)',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md55',1,'']]],
  ['start_46',['Quick Start',['../index.html#autotoc_md4',1,'']]],
  ['started_47',['Getting Started',['../md_docs_2_g_e_t_t_i_n_g___s_t_a_r_t_e_d.html',1,'']]],
  ['state_48',['Parser State',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md255',1,'']]],
  ['state_49',['Use user_data for state',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md301',1,'']]],
  ['state_20identity_50',['State Identity',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md238',1,'']]],
  ['state_20machine_20construction_51',['State Machine Construction',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md234',1,'']]],
  ['state_20reordering_52',['State Reordering',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md251',1,'']]],
  ['static_20plugins_53',['Static Plugins',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md497',1,'']]],
  ['step_2010_3a_20reporttable_54',['Step 10: ReportTable',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md232',1,'']]],
  ['step_201_3a_20define_20the_20modifications_20array_55',['Step 1: Define the modifications array',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md288',1,'']]],
  ['step_201_3a_20parse_56',['Step 1: Parse',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md223',1,'']]],
  ['step_202_3a_20findruleprecedences_57',['Step 2: FindRulePrecedences',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md224',1,'']]],
  ['step_202_3a_20implement_20the_20callbacks_58',['Step 2: Implement the callbacks',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md289',1,'']]],
  ['step_203_3a_20define_20the_20extensioninfo_20descriptor_59',['Step 3: Define the ExtensionInfo descriptor',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md290',1,'']]],
  ['step_203_3a_20findfirstsets_60',['Step 3: FindFirstSets',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md225',1,'']]],
  ['step_204_3a_20convenience_20registration_20function_61',['Step 4: Convenience registration function',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md291',1,'']]],
  ['step_204_3a_20findstates_62',['Step 4: FindStates',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md226',1,'']]],
  ['step_205_3a_20findlinks_63',['Step 5: FindLinks',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md227',1,'']]],
  ['step_206_3a_20findfollowsets_64',['Step 6: FindFollowSets',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md228',1,'']]],
  ['step_207_3a_20findactions_65',['Step 7: FindActions',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md229',1,'']]],
  ['step_208_3a_20compresstables_66',['Step 8: CompressTables',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md230',1,'']]],
  ['step_209_3a_20resortstates_67',['Step 9: ResortStates',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md231',1,'']]],
  ['step_20pipeline_68',['The 10-Step Pipeline',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md222',1,'']]],
  ['steps_69',['Next Steps',['../md_docs_2_g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md24',1,'']]],
  ['strategies_70',['Strategies',['../md_docs_2_c_o_n_c_e_p_t_s.html#autotoc_md31',1,'Disambiguation Strategies'],['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md326',1,'Disambiguation Strategies']]],
  ['strategy_71',['Strategy',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md111',1,'Allocation Strategy'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md367',1,'Fork-Resolve Strategy'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md366',1,'Priority Strategy']]],
  ['strategy_20comparison_72',['Strategy Comparison',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md368',1,'']]],
  ['strategy_20performance_73',['Disambiguation Strategy Performance',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md365',1,'']]],
  ['strategy_20selection_74',['Disambiguation Strategy Selection',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md386',1,'']]],
  ['structure_75',['Structure',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md500',1,'Data Structure'],['../md_docs_2_l_i_t_e_r_a_t_e___f_o_r_m_a_t.html#autotoc_md560',1,'File Structure']]],
  ['structure_20sizes_76',['Appendix: Data Structure Sizes',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md397',1,'']]],
  ['structures_20reference_77',['Data Structures Reference',['../md_docs_2_a_p_i.html#autotoc_md186',1,'']]],
  ['subproject_78',['As a Meson subproject',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md41',1,'']]],
  ['subsystem_20parsers_79',['PostgreSQL Subsystem Parsers',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md65',1,'']]],
  ['suite_80',['Running the Parser Benchmark Suite',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md392',1,'']]],
  ['summary_81',['Scaling Summary',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md380',1,'']]],
  ['swap_82',['Active Parser and Hot-Swap',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md503',1,'']]],
  ['swap_20guarantee_83',['Hot-Swap Guarantee',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md505',1,'']]],
  ['symbol_20collisions_84',['Avoiding Symbol Collisions',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md50',1,'']]],
  ['symbol_20x_20is_20exported_20by_20both_20a_20and_20b_85',['&quot;Symbol &apos;X&apos; is exported by both &apos;A&apos; and &apos;B&apos;&quot;',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md549',1,'']]],
  ['symbols_86',['Re-exporting Symbols',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md552',1,'']]],
  ['symbols_87',['symbols',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md51',1,'Generated parser symbols'],['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md52',1,'Library (extension framework) symbols']]],
  ['synchronization_20mechanisms_88',['Synchronization Mechanisms',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md107',1,'']]],
  ['synchronous_20replication_20config_20examples_20syncrep_89',['Synchronous Replication Config (&lt;span class=&quot;tt&quot;&gt;examples/syncrep/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md69',1,'']]],
  ['syncrep_90',['Synchronous Replication Config (&lt;span class=&quot;tt&quot;&gt;examples/syncrep/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md69',1,'']]],
  ['syntax_91',['Syntax',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md524',1,'Directive Syntax'],['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md428',1,'Rule Syntax']]],
  ['syntax_20differences_92',['Grammar Syntax Differences',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md427',1,'']]],
  ['syntax_20translation_93',['Rule Syntax Translation',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___y_a_c_c.html#autotoc_md450',1,'']]],
  ['system_94',['System',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md112',1,'Build System'],['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md91',1,'Extension System'],['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md515',1,'Extension System'],['../md_docs_2_c_o_n_c_e_p_t_s.html#autotoc_md36',1,'Module System']]],
  ['system_20changes_95',['Build System Changes',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md434',1,'']]],
  ['system_20library_96',['As a system library',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md42',1,'']]],
  ['systems_97',['Integration with Existing Systems',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md514',1,'']]]
];
