var searchData=
[
  ['table_0',['Table',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md215',1,'Comparison Table'],['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md100',1,'Token Table']]],
  ['table_20access_1',['Snapshot-Indirected Table Access',['../md_docs_2_a_p_i.html#autotoc_md135',1,'']]],
  ['table_20api_2',['Token Table API',['../md_docs_2_a_p_i.html#autotoc_md149',1,'']]],
  ['table_20compression_3',['Table Compression',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md268',1,'Action Table Compression'],['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md247',1,'Table Compression']]],
  ['table_20driven_20baseline_4',['Interpreted (Table-Driven) Baseline',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md319',1,'']]],
  ['table_20jit_5',['Tokenizer JIT vs Action Table JIT',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md481',1,'']]],
  ['table_20layout_6',['Action Table Layout',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md90',1,'']]],
  ['table_20lookups_7',['Speedup from JIT on Action Table Lookups',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md460',1,'']]],
  ['table_20of_20contents_8',['Table of Contents',['../md_docs_2_a_p_i.html#autotoc_md117',1,'Table of Contents'],['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md202',1,'Table of Contents'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md340',1,'Table of Contents']]],
  ['table_20packing_20acttab_9',['Action Table Packing (acttab)',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md250',1,'']]],
  ['table_20performance_10',['Token Table Performance',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md312',1,'']]],
  ['tables_20grow_20too_20large_11',['Parser tables grow too large',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md309',1,'']]],
  ['taking_20effect_12',['Grammar rule not taking effect',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md307',1,'']]],
  ['targets_13',['Build Targets',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md113',1,'']]],
  ['template_20examples_20plugin_5ftemplate_14',['Plugin Template (&lt;span class=&quot;tt&quot;&gt;examples/plugin_template/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md62',1,'']]],
  ['terminal_20types_20mod_5fadd_5ftype_15',['Adding Non-Terminal Types (&lt;span class=&quot;tt&quot;&gt;MOD_ADD_TYPE&lt;/span&gt;)',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md280',1,'']]],
  ['terminology_16',['Internal Terminology',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md220',1,'']]],
  ['test_20parser_20examples_20isolation_17',['Isolation Test Parser (&lt;span class=&quot;tt&quot;&gt;examples/isolation/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md68',1,'']]],
  ['testing_18',['Testing',['../index.html#autotoc_md11',1,'']]],
  ['textbooks_19',['Textbooks',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md266',1,'']]],
  ['the_2010_20step_20pipeline_20',['The 10-Step Pipeline',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md222',1,'']]],
  ['the_20active_20plugin_21',['Setting the Active Plugin',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md504',1,'']]],
  ['the_20base_20snapshot_22',['Inspect the base snapshot',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md298',1,'']]],
  ['the_20callbacks_23',['Step 2: Implement the callbacks',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md289',1,'']]],
  ['the_20example_24',['Compiling the example',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md292',1,'']]],
  ['the_20extension_20adds_25',['What the extension adds',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md287',1,'']]],
  ['the_20extension_20framework_26',['Building the Extension Framework',['../md_docs_2_g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md22',1,'']]],
  ['the_20extensioninfo_20descriptor_27',['Step 3: Define the ExtensionInfo descriptor',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md290',1,'']]],
  ['the_20five_20arrays_28',['The Five Arrays',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md248',1,'']]],
  ['the_20generator_29',['Building the Generator',['../md_docs_2_g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md19',1,'']]],
  ['the_20lr_20parsing_20family_30',['The LR Parsing Family',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md207',1,'']]],
  ['the_20manager_31',['Snapshot Lifecycle Under the Manager',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md513',1,'']]],
  ['the_20modifications_20array_32',['Step 1: Define the modifications array',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md288',1,'']]],
  ['the_20parser_20benchmark_20suite_33',['Running the Parser Benchmark Suite',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md392',1,'']]],
  ['thread_20safety_34',['Thread Safety',['../md_docs_2_c_o_n_c_e_p_t_s.html#autotoc_md33',1,'Copy-on-Write and Thread Safety'],['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md106',1,'Thread Safety'],['../md_docs_2_a_p_i.html#autotoc_md193',1,'Thread Safety']]],
  ['thread_20safety_35',['Thread safety',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md302',1,'']]],
  ['thread_20safety_20checklist_36',['Thread Safety Checklist',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md57',1,'']]],
  ['thresholds_37',['Default Thresholds',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md484',1,'']]],
  ['throughput_38',['Throughput',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md311',1,'Tokenizer Throughput'],['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md422',1,'Tokenizer Throughput']]],
  ['tiebreaker_20rule_20overhead_39',['Tiebreaker Rule Overhead',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md382',1,'']]],
  ['tiers_40',['Implementation Tiers',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md99',1,'']]],
  ['time_41',['Time',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md49',1,'Generating Parsers at Build Time'],['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md324',1,'Loading Costs (One-Time)']]],
  ['time_20breakdown_42',['Parse Time Breakdown',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md457',1,'']]],
  ['time_20complexity_43',['Time Complexity',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md260',1,'']]],
  ['to_20bison_20yacc_44',['Comparison to Bison/Yacc',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md523',1,'']]],
  ['to_20compare_45',['Key Metrics to Compare',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md394',1,'']]],
  ['to_20lime_46',['to Lime',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html',1,'Migrating from Bison to Lime'],['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___y_a_c_c.html',1,'Migrating from Yacc to Lime']]],
  ['to_20load_47',['Extension fails to load',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md305',1,'']]],
  ['to_20lr_20parsing_48',['Introduction to LR Parsing',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md204',1,'']]],
  ['to_20tune_49',['When to Tune',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md485',1,'']]],
  ['to_20use_20each_20tool_50',['When to Use Each Tool',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md413',1,'']]],
  ['token_51',['CPU Cost Per Token',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md355',1,'']]],
  ['token_20codes_52',['Use auto-assigned token codes',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md297',1,'']]],
  ['token_20conflicts_53',['Token conflicts',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md306',1,'']]],
  ['token_20declarations_54',['Token Declarations',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md429',1,'']]],
  ['token_20level_20conflicts_55',['Token-Level Conflicts',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md361',1,'']]],
  ['token_20runtime_20costs_56',['Per-Token Runtime Costs',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md325',1,'']]],
  ['token_20table_57',['Token Table',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md100',1,'']]],
  ['token_20table_20api_58',['Token Table API',['../md_docs_2_a_p_i.html#autotoc_md149',1,'']]],
  ['token_20table_20performance_59',['Token Table Performance',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md312',1,'']]],
  ['token_20type_20codes_60',['Token Type Codes',['../md_docs_2_a_p_i.html#autotoc_md189',1,'']]],
  ['tokenization_61',['Tokenization',['../md_docs_2_a_p_i.html#autotoc_md196',1,'Basic Tokenization'],['../md_docs_2_c_o_n_c_e_p_t_s.html#autotoc_md34',1,'SIMD Tokenization'],['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md97',1,'SIMD Tokenization']]],
  ['tokenizer_62',['Tokenizer',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md517',1,'']]],
  ['tokenizer_20api_63',['Tokenizer API',['../md_docs_2_a_p_i.html#autotoc_md137',1,'']]],
  ['tokenizer_20jit_20highest_20value_20optimization_64',['Tokenizer JIT - Highest Value Optimization',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md477',1,'']]],
  ['tokenizer_20jit_20matters_20most_65',['Why Tokenizer JIT Matters Most',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md478',1,'']]],
  ['tokenizer_20jit_20vs_20action_20table_20jit_66',['Tokenizer JIT vs Action Table JIT',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md481',1,'']]],
  ['tokenizer_20throughput_67',['Tokenizer Throughput',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md311',1,'Tokenizer Throughput'],['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md422',1,'Tokenizer Throughput']]],
  ['tokenizer_5fcolumn_68',['tokenizer_column',['../md_docs_2_a_p_i.html#autotoc_md146',1,'']]],
  ['tokenizer_5fcreate_69',['tokenizer_create',['../md_docs_2_a_p_i.html#autotoc_md140',1,'']]],
  ['tokenizer_5fdestroy_70',['tokenizer_destroy',['../md_docs_2_a_p_i.html#autotoc_md141',1,'']]],
  ['tokenizer_5fline_71',['tokenizer_line',['../md_docs_2_a_p_i.html#autotoc_md145',1,'']]],
  ['tokenizer_5fnext_72',['tokenizer_next',['../md_docs_2_a_p_i.html#autotoc_md142',1,'']]],
  ['tokenizer_5fpeek_73',['tokenizer_peek',['../md_docs_2_a_p_i.html#autotoc_md143',1,'']]],
  ['tokenizer_5fposition_74',['tokenizer_position',['../md_docs_2_a_p_i.html#autotoc_md144',1,'']]],
  ['tokens_20mod_5fadd_5ftoken_75',['Adding Tokens (&lt;span class=&quot;tt&quot;&gt;MOD_ADD_TOKEN&lt;/span&gt;)',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md277',1,'']]],
  ['too_20large_76',['Parser tables grow too large',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md309',1,'']]],
  ['tool_77',['When to Use Each Tool',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md413',1,'']]],
  ['tool_20reference_78',['Tool Reference',['../md_docs_2_l_i_t_e_r_a_t_e___f_o_r_m_a_t.html#autotoc_md573',1,'']]],
  ['tooling_79',['Build and Tooling',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md407',1,'']]],
  ['tools_80',['Related Tools',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md267',1,'']]],
  ['topics_81',['Advanced Topics',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md550',1,'']]],
  ['translation_82',['Rule Syntax Translation',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___y_a_c_c.html#autotoc_md450',1,'']]],
  ['tree_83',['Deployment Decision Tree',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md486',1,'']]],
  ['trie_20based_20keyword_20classifier_84',['Trie-Based Keyword Classifier',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md479',1,'']]],
  ['trigger_85',['Compilation Trigger',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md104',1,'']]],
  ['troubleshooting_86',['Troubleshooting',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md304',1,'Troubleshooting'],['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md545',1,'Troubleshooting']]],
  ['tune_87',['When to Tune',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md485',1,'']]],
  ['tuning_88',['Tuning',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md335',1,'JIT Tuning'],['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md333',1,'Performance Tuning']]],
  ['tuning_20recommendations_89',['Performance Tuning Recommendations',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md384',1,'']]],
  ['type_20codes_90',['Token Type Codes',['../md_docs_2_a_p_i.html#autotoc_md189',1,'']]],
  ['type_20comparison_91',['Conflict Type Comparison',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md360',1,'']]],
  ['type_20declarations_92',['Type Declarations',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md430',1,'']]],
  ['types_93',['Types',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md245',1,'Conflict Action Types'],['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md294',1,'Conflict Detection Types'],['../md_docs_2_a_p_i.html#autotoc_md172',1,'Grammar Modification Types'],['../md_docs_2_a_p_i.html#autotoc_md122',1,'Types'],['../md_docs_2_a_p_i.html#autotoc_md129',1,'Types'],['../md_docs_2_a_p_i.html#autotoc_md138',1,'Types'],['../md_docs_2_a_p_i.html#autotoc_md150',1,'Types'],['../md_docs_2_a_p_i.html#autotoc_md159',1,'Types'],['../md_docs_2_a_p_i.html#autotoc_md169',1,'Types'],['../md_docs_2_a_p_i.html#autotoc_md176',1,'Types'],['../md_docs_2_a_p_i.html#autotoc_md183',1,'Types']]],
  ['types_20mod_5fadd_5ftype_94',['Adding Non-Terminal Types (&lt;span class=&quot;tt&quot;&gt;MOD_ADD_TYPE&lt;/span&gt;)',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md280',1,'']]],
  ['types_20of_20conflicts_95',['Types of Conflicts',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md242',1,'']]]
];
