var searchData=
[
  ['lalr_201_0',['Why LALR(1)?',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md216',1,'']]],
  ['lalr_201_20algorithm_1',['LALR(1) Algorithm',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md88',1,'']]],
  ['lalr_201_20ndash_20look_20ahead_20lr_2',['LALR(1) &amp;ndash; Look-Ahead LR',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md210',1,'']]],
  ['lalr_201_20parsing_20algorithm_3',['LALR(1) Parsing Algorithm',['../md_docs_2_a_l_g_o_r_i_t_h_m.html',1,'']]],
  ['lalr_201_20vs_20ll_20k_20parsing_4',['LALR(1) vs LL(k) Parsing',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md214',1,'']]],
  ['language_20examples_20mongodb_5',['MongoDB Query Language (&lt;span class=&quot;tt&quot;&gt;examples/mongodb/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md75',1,'']]],
  ['language_20parsers_6',['Query Language Parsers',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md71',1,'']]],
  ['large_7',['Parser tables grow too large',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md309',1,'']]],
  ['latency_8',['Parse Latency',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md421',1,'']]],
  ['layout_9',['Layout',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md90',1,'Action Table Layout'],['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md115',1,'Directory Layout'],['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md541',1,'File Layout'],['../index.html#autotoc_md5',1,'Project Layout']]],
  ['least_10',['When SIMD Helps Least',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md317',1,'']]],
  ['legacy_11',['MCJIT (Legacy)',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md473',1,'']]],
  ['level_20api_20parser_20h_12',['High-Level API (parser.h)',['../md_docs_2_a_p_i.html#autotoc_md167',1,'']]],
  ['level_20conflicts_13',['Level Conflicts',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md362',1,'Rule-Level Conflicts'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md363',1,'Semantic-Level Conflicts'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md361',1,'Token-Level Conflicts']]],
  ['level_20jit_5fcontext_20h_14',['Low-Level (jit_context.h)',['../md_docs_2_a_p_i.html#autotoc_md179',1,'']]],
  ['level_20parser_20h_15',['High-Level (parser.h)',['../md_docs_2_a_p_i.html#autotoc_md178',1,'']]],
  ['library_16',['As a system library',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md42',1,'']]],
  ['library_20extension_20framework_20symbols_17',['Library (extension framework) symbols',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md52',1,'']]],
  ['library_20plugins_18',['Shared Library Plugins',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md496',1,'']]],
  ['library_20version_19',['Library Version',['../md_docs_2_a_p_i.html#autotoc_md119',1,'']]],
  ['license_20',['License',['../index.html#autotoc_md15',1,'']]],
  ['license_20comparison_21',['License Comparison',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md424',1,'']]],
  ['lifecycle_22',['Lifecycle',['../md_docs_2_c_o_n_c_e_p_t_s.html#autotoc_md29',1,'Extension Lifecycle'],['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md93',1,'Extension Lifecycle'],['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md271',1,'Extension Lifecycle'],['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md86',1,'Lifecycle'],['../md_docs_2_a_p_i.html#autotoc_md197',1,'Snapshot Lifecycle']]],
  ['lifecycle_20under_20the_20manager_23',['Snapshot Lifecycle Under the Manager',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md513',1,'']]],
  ['lime_24',['Lime',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html',1,'Migrating from Bison to Lime'],['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___y_a_c_c.html',1,'Migrating from Yacc to Lime']]],
  ['lime_20boot_5fgrammar_20lime_20excerpt_25',['Converted Lime (boot_grammar.lime excerpt)',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md440',1,'']]],
  ['lime_20build_26',['Lime Build',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md436',1,'']]],
  ['lime_20c_27',['Processing Pipeline (in &lt;span class=&quot;tt&quot;&gt;lime.c&lt;/span&gt;)',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md89',1,'']]],
  ['lime_20compose_28',['Using lime-compose',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md531',1,'']]],
  ['lime_20excerpt_29',['Converted Lime (boot_grammar.lime excerpt)',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md440',1,'']]],
  ['lime_20in_20your_20project_30',['Integrating Lime in Your Project',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html',1,'']]],
  ['lime_20j_31',['AOT Compilation (&lt;span class=&quot;tt&quot;&gt;lime -j&lt;/span&gt;)',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md468',1,'']]],
  ['lime_20module_20format_32',['Lime Module Format',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html',1,'']]],
  ['lime_20over_20yacc_20bison_33',['Why Lime over Yacc/Bison?',['../index.html#autotoc_md3',1,'']]],
  ['lime_20parser_20generator_34',['Lime Parser Generator',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html',1,'JIT Compilation Analysis for Lime Parser Generator'],['../index.html',1,'Lime Parser Generator']]],
  ['lime_20s_20approach_35',['Lime&apos;s Approach',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md218',1,'']]],
  ['lime_20vs_20antlr_36',['Lime vs ANTLR',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md411',1,'']]],
  ['lime_20vs_20bison_37',['Lime vs Bison',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md410',1,'']]],
  ['lime_20vs_20menhir_38',['Lime vs Menhir',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md412',1,'']]],
  ['lime_20vs_20yacc_39',['Lime vs Yacc',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md409',1,'']]],
  ['lime_20when_20you_20need_3a_40',['Use Lime when you need:',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md414',1,'']]],
  ['lime_5fpostgres_41',['PostgreSQL Integration Guide (&lt;span class=&quot;tt&quot;&gt;examples/lime_postgres/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md80',1,'']]],
  ['lime_5fsnapshot_5facquire_42',['lime_snapshot_acquire',['../md_docs_2_a_p_i.html#autotoc_md125',1,'']]],
  ['lime_5fsnapshot_5fcreate_43',['lime_snapshot_create',['../md_docs_2_a_p_i.html#autotoc_md124',1,'']]],
  ['lime_5fsnapshot_5frelease_44',['lime_snapshot_release',['../md_docs_2_a_p_i.html#autotoc_md126',1,'']]],
  ['limeparserplugin_45',['Plugin Interface (&lt;span class=&quot;tt&quot;&gt;LimeParserPlugin&lt;/span&gt;)',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md491',1,'']]],
  ['linking_46',['Linking',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md46',1,'']]],
  ['literate_47',['Literate Grammar Format (&lt;span class=&quot;tt&quot;&gt;examples/literate/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md78',1,'']]],
  ['literate_20grammar_20format_20examples_20literate_48',['Literate Grammar Format (&lt;span class=&quot;tt&quot;&gt;examples/literate/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md78',1,'']]],
  ['literate_20grammar_20format_20specification_49',['Literate Grammar Format Specification',['../md_docs_2_l_i_t_e_r_a_t_e___f_o_r_m_a_t.html',1,'']]],
  ['ll_20k_20parsing_50',['LALR(1) vs LL(k) Parsing',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md214',1,'']]],
  ['llm_20oracle_20disambiguation_20examples_20llm_5foracle_51',['LLM Oracle Disambiguation (&lt;span class=&quot;tt&quot;&gt;examples/llm_oracle/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md77',1,'']]],
  ['llm_5foracle_52',['LLM Oracle Disambiguation (&lt;span class=&quot;tt&quot;&gt;examples/llm_oracle/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md77',1,'']]],
  ['llvm_20available_53',['JIT Performance (When LLVM Available)',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md320',1,'']]],
  ['llvm_20jit_20integration_54',['LLVM JIT Integration',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md101',1,'']]],
  ['load_55',['JIT Invalidation on Extension Load',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md371',1,'']]],
  ['load_56',['Extension fails to load',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md305',1,'']]],
  ['loading_57',['Loading',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md273',1,'2. Loading'],['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md495',1,'Dynamic Loading'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md385',1,'Extension Loading'],['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md48',1,'Runtime Extension Loading']]],
  ['loading_20costs_20one_20time_58',['Loading Costs (One-Time)',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md324',1,'']]],
  ['look_20ahead_20lr_59',['LALR(1) &amp;ndash; Look-Ahead LR',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md210',1,'']]],
  ['lookup_20algorithm_60',['Lookup Algorithm',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md249',1,'']]],
  ['lookup_5ftoken_61',['lookup_token',['../md_docs_2_a_p_i.html#autotoc_md154',1,'']]],
  ['lookups_62',['Speedup from JIT on Action Table Lookups',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md460',1,'']]],
  ['loop_63',['Parse Loop',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md256',1,'']]],
  ['low_20level_20jit_5fcontext_20h_64',['Low-Level (jit_context.h)',['../md_docs_2_a_p_i.html#autotoc_md179',1,'']]],
  ['lr_65',['LR',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md210',1,'LALR(1) &amp;ndash; Look-Ahead LR'],['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md209',1,'SLR(1) &amp;ndash; Simple LR']]],
  ['lr_200_66',['LR(0)',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md208',1,'']]],
  ['lr_201_67',['Canonical LR(1)',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md211',1,'']]],
  ['lr_20parsing_68',['Introduction to LR Parsing',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md204',1,'']]],
  ['lr_20parsing_20family_69',['The LR Parsing Family',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md207',1,'']]]
];
