var searchData=
[
  ['identity_0',['Identity',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md525',1,'Module Identity'],['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md238',1,'State Identity']]],
  ['implement_20the_20callbacks_1',['Step 2: Implement the callbacks',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md289',1,'']]],
  ['implementation_2',['Example: Plugin Implementation',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md518',1,'']]],
  ['implementation_20tiers_3',['Implementation Tiers',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md99',1,'']]],
  ['implementing_20callbacks_4',['Implementing Callbacks',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md282',1,'']]],
  ['imports_5',['Imports',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md528',1,'']]],
  ['in_20lime_20c_6',['Processing Pipeline (in &lt;span class=&quot;tt&quot;&gt;lime.c&lt;/span&gt;)',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md89',1,'']]],
  ['in_20on_5funload_7',['Segmentation fault in on_unload',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md308',1,'']]],
  ['in_20your_20project_8',['Integrating Lime in Your Project',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html',1,'']]],
  ['indirected_20table_20access_9',['Snapshot-Indirected Table Access',['../md_docs_2_a_p_i.html#autotoc_md135',1,'']]],
  ['inspect_20the_20base_20snapshot_10',['Inspect the base snapshot',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md298',1,'']]],
  ['integrating_20lime_20in_20your_20project_11',['Integrating Lime in Your Project',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html',1,'']]],
  ['integration_12',['Integration',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md403',1,'Code Generation and Integration'],['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md387',1,'JIT Integration'],['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md101',1,'LLVM JIT Integration'],['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___y_a_c_c.html#autotoc_md448',1,'No yylex Integration'],['../md_docs_2_a_p_i.html#autotoc_md180',1,'Snapshot Integration']]],
  ['integration_20guide_20examples_20lime_5fpostgres_13',['PostgreSQL Integration Guide (&lt;span class=&quot;tt&quot;&gt;examples/lime_postgres/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md80',1,'']]],
  ['integration_20with_20existing_20systems_14',['Integration with Existing Systems',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md514',1,'']]],
  ['interaction_20with_20extensions_15',['JIT Interaction with Extensions',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md370',1,'']]],
  ['interface_16',['Parser Interface',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md437',1,'']]],
  ['interface_20limeparserplugin_17',['Plugin Interface (&lt;span class=&quot;tt&quot;&gt;LimeParserPlugin&lt;/span&gt;)',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md491',1,'']]],
  ['internal_20registry_20api_20src_20extension_20h_18',['Internal Registry API (src/extension.h)',['../md_docs_2_a_p_i.html#autotoc_md168',1,'']]],
  ['internal_20terminology_19',['Internal Terminology',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md220',1,'']]],
  ['interpreted_20table_20driven_20baseline_20',['Interpreted (Table-Driven) Baseline',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md319',1,'']]],
  ['introduction_20to_20lr_20parsing_21',['Introduction to LR Parsing',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md204',1,'']]],
  ['invalidation_20on_20extension_20load_22',['JIT Invalidation on Extension Load',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md371',1,'']]],
  ['invariants_23',['Key Invariants',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md108',1,'']]],
  ['is_20beneficial_24',['When JIT Is Beneficial',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md464',1,'']]],
  ['is_20exported_20by_20both_20a_20and_20b_25',['&quot;Symbol &apos;X&apos; is exported by both &apos;A&apos; and &apos;B&apos;&quot;',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md549',1,'']]],
  ['is_20not_20available_26',['&quot;Module &apos;foo&apos; requires &apos;bar&apos;, which is not available&quot;',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md547',1,'']]],
  ['is_20not_20beneficial_27',['When JIT Is Not Beneficial',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md465',1,'']]],
  ['isolation_28',['Session Isolation',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md506',1,'']]],
  ['isolation_29',['Isolation Test Parser (&lt;span class=&quot;tt&quot;&gt;examples/isolation/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md68',1,'']]],
  ['isolation_20test_20parser_20examples_20isolation_30',['Isolation Test Parser (&lt;span class=&quot;tt&quot;&gt;examples/isolation/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md68',1,'']]],
  ['items_31',['Configurations (Items)',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md235',1,'']]]
];
