var searchData=
[
  ['j_0',['AOT Compilation (&lt;span class=&quot;tt&quot;&gt;lime -j&lt;/span&gt;)',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md468',1,'']]],
  ['jit_1',['JIT',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md467',1,'AOT vs Runtime JIT'],['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md469',1,'Runtime JIT'],['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md481',1,'Tokenizer JIT vs Action Table JIT']]],
  ['jit_20compilation_2',['JIT Compilation',['../md_docs_2_c_o_n_c_e_p_t_s.html#autotoc_md35',1,'JIT Compilation'],['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md318',1,'JIT Compilation'],['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md516',1,'JIT Compilation']]],
  ['jit_20compilation_20analysis_20for_20lime_20parser_20generator_3',['JIT Compilation Analysis for Lime Parser Generator',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html',1,'']]],
  ['jit_20compilation_20api_4',['JIT Compilation API',['../md_docs_2_a_p_i.html#autotoc_md175',1,'']]],
  ['jit_20compilation_20cost_20by_20grammar_20size_5',['JIT Compilation Cost by Grammar Size',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md373',1,'']]],
  ['jit_20compilation_20modes_6',['JIT Compilation Modes',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md322',1,'']]],
  ['jit_20compilation_20with_20policy_7',['JIT Compilation with Policy',['../md_docs_2_a_p_i.html#autotoc_md200',1,'']]],
  ['jit_20highest_20value_20optimization_8',['Tokenizer JIT - Highest Value Optimization',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md477',1,'']]],
  ['jit_20integration_9',['JIT Integration',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md387',1,'JIT Integration'],['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md101',1,'LLVM JIT Integration']]],
  ['jit_20interaction_20with_20extensions_10',['JIT Interaction with Extensions',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md370',1,'']]],
  ['jit_20invalidation_20on_20extension_20load_11',['JIT Invalidation on Extension Load',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md371',1,'']]],
  ['jit_20is_20beneficial_12',['When JIT Is Beneficial',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md464',1,'']]],
  ['jit_20is_20not_20beneficial_13',['When JIT Is Not Beneficial',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md465',1,'']]],
  ['jit_20matters_20most_14',['Why Tokenizer JIT Matters Most',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md478',1,'']]],
  ['jit_20on_20action_20table_20lookups_15',['Speedup from JIT on Action Table Lookups',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md460',1,'']]],
  ['jit_20performance_20when_20llvm_20available_16',['JIT Performance (When LLVM Available)',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md320',1,'']]],
  ['jit_20policy_17',['JIT Policy',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md321',1,'']]],
  ['jit_20policy_20api_18',['JIT Policy API',['../md_docs_2_a_p_i.html#autotoc_md182',1,'']]],
  ['jit_20tuning_19',['JIT Tuning',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md335',1,'']]],
  ['jit_20vs_20action_20table_20jit_20',['Tokenizer JIT vs Action Table JIT',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md481',1,'']]],
  ['jit_5fcontext_20h_21',['Low-Level (jit_context.h)',['../md_docs_2_a_p_i.html#autotoc_md179',1,'']]],
  ['jsonb_20extension_22',['Complete Walkthrough: JSONB Extension',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md286',1,'']]],
  ['jsonb_20extension_20examples_20jsonb_5fextension_20c_23',['JSONB Extension (&lt;span class=&quot;tt&quot;&gt;examples/jsonb_extension.c&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md61',1,'']]],
  ['jsonb_5fextension_20c_24',['JSONB Extension (&lt;span class=&quot;tt&quot;&gt;examples/jsonb_extension.c&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md61',1,'']]],
  ['jsonpath_25',['JSONPath (&lt;span class=&quot;tt&quot;&gt;examples/jsonpath/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md72',1,'']]],
  ['jsonpath_20examples_20jsonpath_26',['JSONPath (&lt;span class=&quot;tt&quot;&gt;examples/jsonpath/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md72',1,'']]]
];
