var searchData=
[
  ['generated_20parser_20runtime_0',['Generated Parser Runtime',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md254',1,'']]],
  ['generated_20parser_20symbols_1',['Generated parser symbols',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md51',1,'']]],
  ['generating_20parsers_20at_20build_20time_2',['Generating Parsers at Build Time',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md49',1,'']]],
  ['generation_20and_20integration_3',['Code Generation and Integration',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md403',1,'']]],
  ['generator_4',['Generator',['../md_docs_2_g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md19',1,'Building the Generator'],['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html',1,'JIT Compilation Analysis for Lime Parser Generator'],['../index.html',1,'Lime Parser Generator']]],
  ['generator_20comparison_20guide_5',['Parser Generator Comparison Guide',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html',1,'']]],
  ['generator_20extension_20framework_20make_20cmake_6',['Option 3: Generator + Extension Framework (Make / CMake)',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md43',1,'']]],
  ['generator_20extension_20framework_20meson_7',['Option 2: Generator + Extension Framework (Meson)',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md40',1,'']]],
  ['generator_20only_20no_20extension_20framework_8',['Option 1: Generator Only (No Extension Framework)',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md39',1,'']]],
  ['get_5fclassify_5ffunc_9',['get_classify_func',['../md_docs_2_a_p_i.html#autotoc_md161',1,'']]],
  ['get_5fmodifications_20required_10',['get_modifications (required)',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md283',1,'']]],
  ['getting_20started_11',['Getting Started',['../md_docs_2_g_e_t_t_i_n_g___s_t_a_r_t_e_d.html',1,'']]],
  ['goals_12',['Goals',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md488',1,'Goals'],['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md489',1,'Non-Goals']]],
  ['gotchas_13',['Common Gotchas',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md442',1,'']]],
  ['goto_20function_14',['GOTO Function',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md237',1,'']]],
  ['graceful_20degradation_15',['Graceful Degradation',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md103',1,'']]],
  ['gracefully_16',['Handle conflicts gracefully',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md299',1,'']]],
  ['grammar_17',['Grammar',['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md536',1,'From Monolithic Grammar'],['../md_docs_2_g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md20',1,'Your First Grammar']]],
  ['grammar_20and_20parsing_18',['Grammar and Parsing',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md402',1,'']]],
  ['grammar_20examples_20pg_19',['PostgreSQL Full Grammar (&lt;span class=&quot;tt&quot;&gt;examples/pg/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md63',1,'']]],
  ['grammar_20examples_20pg_5fmodular_20',['PostgreSQL Modular Grammar (&lt;span class=&quot;tt&quot;&gt;examples/pg_modular/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md64',1,'']]],
  ['grammar_20format_20examples_20literate_21',['Literate Grammar Format (&lt;span class=&quot;tt&quot;&gt;examples/literate/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md78',1,'']]],
  ['grammar_20format_20specification_22',['Literate Grammar Format Specification',['../md_docs_2_l_i_t_e_r_a_t_e___f_o_r_m_a_t.html',1,'']]],
  ['grammar_20modification_20types_23',['Grammar Modification Types',['../md_docs_2_a_p_i.html#autotoc_md172',1,'']]],
  ['grammar_20modifications_24',['Grammar Modifications',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md95',1,'Grammar Modifications'],['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md276',1,'Grammar Modifications']]],
  ['grammar_20rule_20not_20taking_20effect_25',['Grammar rule not taking effect',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md307',1,'']]],
  ['grammar_20rules_20mod_5fadd_5frule_26',['Adding Grammar Rules (&lt;span class=&quot;tt&quot;&gt;MOD_ADD_RULE&lt;/span&gt;)',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md278',1,'']]],
  ['grammar_20size_27',['JIT Compilation Cost by Grammar Size',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md373',1,'']]],
  ['grammar_20syntax_20differences_28',['Grammar Syntax Differences',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md427',1,'']]],
  ['grammars_20and_20parsers_29',['Grammars and Parsers',['../md_docs_2_c_o_n_c_e_p_t_s.html#autotoc_md26',1,'']]],
  ['grow_20too_20large_30',['Parser tables grow too large',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md309',1,'']]],
  ['guarantee_31',['Hot-Swap Guarantee',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md505',1,'']]],
  ['guide_32',['Guide',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html',1,'Extension Development Guide'],['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md332',1,'Memory Budget Guide'],['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md534',1,'Migration Guide'],['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html',1,'Parser Generator Comparison Guide']]],
  ['guide_20examples_20lime_5fpostgres_33',['PostgreSQL Integration Guide (&lt;span class=&quot;tt&quot;&gt;examples/lime_postgres/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md80',1,'']]]
];
