var searchData=
[
  ['packing_20acttab_0',['Action Table Packing (acttab)',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md250',1,'']]],
  ['parse_1',['Step 1: Parse',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md223',1,'']]],
  ['parse_20context_20api_2',['Parse Context API',['../md_docs_2_a_p_i.html#autotoc_md128',1,'']]],
  ['parse_20latency_3',['Parse Latency',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md421',1,'']]],
  ['parse_20loop_4',['Parse Loop',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md256',1,'']]],
  ['parse_20session_5',['Parse Session',['../md_docs_2_a_p_i.html#autotoc_md198',1,'']]],
  ['parse_20time_20breakdown_6',['Parse Time Breakdown',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md457',1,'']]],
  ['parse_5fbegin_7',['parse_begin',['../md_docs_2_a_p_i.html#autotoc_md131',1,'']]],
  ['parse_5fend_8',['parse_end',['../md_docs_2_a_p_i.html#autotoc_md133',1,'']]],
  ['parse_5fget_5fsnapshot_9',['parse_get_snapshot',['../md_docs_2_a_p_i.html#autotoc_md134',1,'']]],
  ['parse_5ftoken_10',['parse_token',['../md_docs_2_a_p_i.html#autotoc_md132',1,'']]],
  ['parser_11',['Worked Example: PostgreSQL Bootstrap Parser',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md438',1,'']]],
  ['parser_20allocation_20and_20reuse_12',['Parser Allocation and Reuse',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md53',1,'']]],
  ['parser_20and_20hot_20swap_13',['Active Parser and Hot-Swap',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md503',1,'']]],
  ['parser_20benchmark_20suite_14',['Running the Parser Benchmark Suite',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md392',1,'']]],
  ['parser_20examples_20bootstrap_15',['Bootstrap (BKI) Parser (&lt;span class=&quot;tt&quot;&gt;examples/bootstrap/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md67',1,'']]],
  ['parser_20examples_20isolation_16',['Isolation Test Parser (&lt;span class=&quot;tt&quot;&gt;examples/isolation/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md68',1,'']]],
  ['parser_20forking_17',['Parser Forking',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md348',1,'']]],
  ['parser_20generator_18',['Parser Generator',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html',1,'JIT Compilation Analysis for Lime Parser Generator'],['../index.html',1,'Lime Parser Generator']]],
  ['parser_20generator_20comparison_20guide_19',['Parser Generator Comparison Guide',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html',1,'']]],
  ['parser_20h_20',['parser h',['../md_docs_2_a_p_i.html#autotoc_md178',1,'High-Level (parser.h)'],['../md_docs_2_a_p_i.html#autotoc_md167',1,'High-Level API (parser.h)']]],
  ['parser_20interface_21',['Parser Interface',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md437',1,'']]],
  ['parser_20model_22',['Parser Model',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___y_a_c_c.html#autotoc_md446',1,'']]],
  ['parser_20ndash_20api_20reference_23',['Extensible SQL Parser &amp;ndash; API Reference',['../md_docs_2_a_p_i.html',1,'']]],
  ['parser_20plugin_20design_24',['Parser Plugin Design',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html',1,'']]],
  ['parser_20runtime_25',['Generated Parser Runtime',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md254',1,'']]],
  ['parser_20state_26',['Parser State',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md255',1,'']]],
  ['parser_20symbols_27',['Generated parser symbols',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md51',1,'']]],
  ['parser_20tables_20grow_20too_20large_28',['Parser tables grow too large',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md309',1,'']]],
  ['parser_20zero_20mallocs_29',['Pattern B: Stack-allocated parser (zero mallocs)',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md55',1,'']]],
  ['parsers_30',['Parsers',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md330',1,'Concurrent Parsers'],['../md_docs_2_c_o_n_c_e_p_t_s.html#autotoc_md26',1,'Grammars and Parsers'],['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md65',1,'PostgreSQL Subsystem Parsers'],['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md71',1,'Query Language Parsers']]],
  ['parsers_20at_20build_20time_31',['Generating Parsers at Build Time',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md49',1,'']]],
  ['parsersnapshot_32',['ParserSnapshot',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md85',1,'']]],
  ['parsersnapshot_20src_20snapshot_20h_33',['ParserSnapshot (src/snapshot.h)',['../md_docs_2_a_p_i.html#autotoc_md187',1,'']]],
  ['parses_34',['Pattern A: Allocate once, reset between parses',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md54',1,'']]],
  ['parsing_35',['Parsing',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md402',1,'Grammar and Parsing'],['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md204',1,'Introduction to LR Parsing'],['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md214',1,'LALR(1) vs LL(k) Parsing']]],
  ['parsing_20algorithm_36',['LALR(1) Parsing Algorithm',['../md_docs_2_a_l_g_o_r_i_t_h_m.html',1,'']]],
  ['parsing_20family_37',['The LR Parsing Family',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md207',1,'']]],
  ['parsing_20performance_38',['Runtime Parsing Performance',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md262',1,'']]],
  ['path_39',['Migration Path',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md475',1,'']]],
  ['paths_40',['Migration Paths',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md419',1,'']]],
  ['pattern_20a_3a_20allocate_20once_20reset_20between_20parses_41',['Pattern A: Allocate once, reset between parses',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md54',1,'']]],
  ['pattern_20b_3a_20stack_20allocated_20parser_20zero_20mallocs_42',['Pattern B: Stack-allocated parser (zero mallocs)',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md55',1,'']]],
  ['per_20extension_43',['Memory Overhead Per Extension',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md327',1,'']]],
  ['per_20extension_20memory_44',['Per-Extension Memory',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md351',1,'']]],
  ['per_20fork_20memory_45',['Per-Fork Memory',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md352',1,'']]],
  ['per_20token_46',['CPU Cost Per Token',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md355',1,'']]],
  ['per_20token_20runtime_20costs_47',['Per-Token Runtime Costs',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md325',1,'']]],
  ['performance_48',['Performance',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md365',1,'Disambiguation Strategy Performance'],['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md480',1,'Expected Performance'],['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md56',1,'NDEBUG and Performance'],['../index.html#autotoc_md10',1,'Performance'],['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md405',1,'Performance'],['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md262',1,'Runtime Parsing Performance'],['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md312',1,'Token Table Performance']]],
  ['performance_20benchmarks_49',['Performance Benchmarks',['../md_docs_2_c_o_m_p_a_r_i_s_o_n.html#autotoc_md420',1,'']]],
  ['performance_20characteristics_50',['Performance Characteristics',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html',1,'Extension Framework Performance Characteristics'],['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html',1,'Performance Characteristics'],['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md259',1,'Performance Characteristics']]],
  ['performance_20tuning_51',['Performance Tuning',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md333',1,'']]],
  ['performance_20tuning_20recommendations_52',['Performance Tuning Recommendations',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md384',1,'']]],
  ['performance_20when_20llvm_20available_53',['JIT Performance (When LLVM Available)',['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md320',1,'']]],
  ['pg_54',['PostgreSQL Full Grammar (&lt;span class=&quot;tt&quot;&gt;examples/pg/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md63',1,'']]],
  ['pg_5fmodular_55',['PostgreSQL Modular Grammar (&lt;span class=&quot;tt&quot;&gt;examples/pg_modular/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md64',1,'']]],
  ['pgbench_56',['pgbench Expressions (&lt;span class=&quot;tt&quot;&gt;examples/pgbench/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md66',1,'']]],
  ['pgbench_20expressions_20examples_20pgbench_57',['pgbench Expressions (&lt;span class=&quot;tt&quot;&gt;examples/pgbench/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md66',1,'']]],
  ['pipeline_58',['The 10-Step Pipeline',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md222',1,'']]],
  ['pipeline_20in_20lime_20c_59',['Processing Pipeline (in &lt;span class=&quot;tt&quot;&gt;lime.c&lt;/span&gt;)',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md89',1,'']]],
  ['plugin_60',['Setting the Active Plugin',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md504',1,'']]],
  ['plugin_20design_61',['Parser Plugin Design',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html',1,'']]],
  ['plugin_20implementation_62',['Example: Plugin Implementation',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md518',1,'']]],
  ['plugin_20interface_20limeparserplugin_63',['Plugin Interface (&lt;span class=&quot;tt&quot;&gt;LimeParserPlugin&lt;/span&gt;)',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md491',1,'']]],
  ['plugin_20registry_64',['Plugin Registry',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md499',1,'']]],
  ['plugin_20template_20examples_20plugin_5ftemplate_65',['Plugin Template (&lt;span class=&quot;tt&quot;&gt;examples/plugin_template/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md62',1,'']]],
  ['plugin_20version_20checks_66',['Plugin Version Checks',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md508',1,'']]],
  ['plugin_5ftemplate_67',['Plugin Template (&lt;span class=&quot;tt&quot;&gt;examples/plugin_template/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md62',1,'']]],
  ['plugins_68',['Plugins',['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md496',1,'Shared Library Plugins'],['../md_docs_2_p_a_r_s_e_r___p_l_u_g_i_n___d_e_s_i_g_n.html#autotoc_md497',1,'Static Plugins']]],
  ['point_69',['Break-Even Point',['../md_docs_2_j_i_t___a_n_a_l_y_s_i_s.html#autotoc_md462',1,'']]],
  ['policies_70',['Execution Policies',['../md_docs_2_c_o_n_c_e_p_t_s.html#autotoc_md32',1,'']]],
  ['policy_71',['Policy',['../md_docs_2_a_p_i.html#autotoc_md200',1,'JIT Compilation with Policy'],['../md_docs_2_p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md321',1,'JIT Policy']]],
  ['policy_20api_72',['JIT Policy API',['../md_docs_2_a_p_i.html#autotoc_md182',1,'']]],
  ['postgresql_20bootstrap_20parser_73',['Worked Example: PostgreSQL Bootstrap Parser',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md438',1,'']]],
  ['postgresql_20full_20grammar_20examples_20pg_74',['PostgreSQL Full Grammar (&lt;span class=&quot;tt&quot;&gt;examples/pg/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md63',1,'']]],
  ['postgresql_20integration_20guide_20examples_20lime_5fpostgres_75',['PostgreSQL Integration Guide (&lt;span class=&quot;tt&quot;&gt;examples/lime_postgres/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md80',1,'']]],
  ['postgresql_20modular_20grammar_20examples_20pg_5fmodular_76',['PostgreSQL Modular Grammar (&lt;span class=&quot;tt&quot;&gt;examples/pg_modular/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md64',1,'']]],
  ['postgresql_20subsystem_20parsers_77',['PostgreSQL Subsystem Parsers',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md65',1,'']]],
  ['practices_78',['Practices',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md295',1,'Best Practices'],['../md_docs_2_m_o_d_u_l_e___f_o_r_m_a_t.html#autotoc_md537',1,'Best Practices']]],
  ['prec_79',['Precedence with prec',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md431',1,'']]],
  ['precedence_20based_20resolution_80',['Precedence-Based Resolution',['../md_docs_2_a_l_g_o_r_i_t_h_m.html#autotoc_md243',1,'']]],
  ['precedence_20mod_5fmodify_5fprecedence_81',['Modifying Precedence (&lt;span class=&quot;tt&quot;&gt;MOD_MODIFY_PRECEDENCE&lt;/span&gt;)',['../md_docs_2_e_x_t_e_n_s_i_o_n_s.html#autotoc_md279',1,'']]],
  ['precedence_20with_20prec_82',['Precedence with prec',['../md_docs_2_m_i_g_r_a_t_i_o_n___f_r_o_m___b_i_s_o_n.html#autotoc_md431',1,'']]],
  ['prerequisites_83',['Prerequisites',['../md_docs_2_g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md18',1,'']]],
  ['priority_20strategy_84',['Priority Strategy',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md366',1,'']]],
  ['process_85',['Composition Process',['../md_docs_2_l_i_t_e_r_a_t_e___f_o_r_m_a_t.html#autotoc_md568',1,'']]],
  ['processing_20pipeline_20in_20lime_20c_86',['Processing Pipeline (in &lt;span class=&quot;tt&quot;&gt;lime.c&lt;/span&gt;)',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md89',1,'']]],
  ['profiling_87',['Memory Profiling',['../md_docs_2_e_x_t_e_n_s_i_o_n___p_e_r_f_o_r_m_a_n_c_e.html#autotoc_md395',1,'']]],
  ['project_88',['Integrating Lime in Your Project',['../md_docs_2_i_n_t_e_g_r_a_t_i_o_n.html',1,'']]],
  ['project_20layout_89',['Project Layout',['../index.html#autotoc_md5',1,'']]],
  ['protocol_20examples_20replication_90',['Replication Protocol (&lt;span class=&quot;tt&quot;&gt;examples/replication/&lt;/span&gt;)',['../md_docs_2_e_x_a_m_p_l_e_s.html#autotoc_md70',1,'']]]
];
