/*
** test_pg_grammar.c -- Stress-test the runtime + JIT against the
** full PostgreSQL SQL grammar (~3,842 LR states, ~3,584 rules,
** ~557 terminals, ~145,000 action-table entries, ~1,665 conflicts
** resolved by precedence).
**
** Why this test exists
** --------------------
** Smaller test grammars (the in-tree arithmetic / COBOL examples)
** exercise the common parser paths but only cover at most a few
** hundred LR states.  PG's grammar is 50-100x larger on every
** dimension; running the same code paths through it surfaces
** corner cases that small grammars hide -- most importantly:
**
**   - 16-bit field widths overflowing on real-world action tables
**   - JIT codegen scaling on a 3,842-state x 557-terminal switch
**   - snapshot allocation/deallocation on multi-megabyte payloads
**   - precedence-resolution paths exercised by 1,665 conflicts
**
** When this test passes after a refactor, we know the refactor did
** not break any of those.  When it fails, the alarm fires.
**
** The test deliberately does not try to drive real SQL through the
** grammar -- that would require linking against the PG tokenizer,
** the pg_keyword_lookup table, the entire PG header tree, etc.
** That's a different test (an end-to-end correctness test, future
** work).  This test is a structural-and-dimensional regression test
** against the largest single LR(1) machine Lime is asked to host.
**
** Skip conditions
** ---------------
** This test is built only when the meson option `pg_grammar=true`
** is set.  Without it, the snapshot file (generated from
** examples/pg/gram.lime via lime -n) is not regenerated and the
** binary doesn't link.  Enable with:
**     meson configure builddir -Dpg_grammar=true
**
** Findings to date
** ----------------
**   - The PG snapshot has 3,842 states, 3,584 rules, 557 terminals,
**     and 145,227 action-table entries.
**   - max yy_shift_ofst is 145,227, max yy_reduce_ofst is 141,149.
**     Both exceed INT16_MAX (32,767), so the int16-to-int32 widening
**     of yy_shift_ofst / yy_reduce_ofst in src/snapshot.h is not
**     optional -- without it the runtime engine would silently
**     misroute every shift/reduce on this grammar.  This corner
**     case was invisible in the small test grammars.
**   - lime regenerates the parser tables from gram.lime in ~3.8 s
**     on Apple M1; the snapshot itself is then materialised from
**     static initializers in <1 ms.
**   - lime_jit_compile on the PG grammar completes in ~15 ms with
**     the compact (table-load) codegen path that's enabled above
**     the IR_SIZE_THRESHOLD in jit_codegen.c.  An earlier version
**     used a fully-unrolled state x lookahead switch which produced
**     hundreds of thousands of basic blocks and could not be
**     compiled by LLVM's default<O2> pipeline within reasonable
**     bounds; that path is still used for small grammars where its
**     constant-folding gains outweigh the IR-size cost.
*/

#define _POSIX_C_SOURCE 200809L

#include "parser.h"
#include "parse_context.h"
#include "snapshot.h"
#include "snapshot_build.h"

#include <inttypes.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

/* Provided by examples/pg/gram_snapshot.c (generated by `lime -n`
** from examples/pg/gram.lime).  No %name was given in gram.lime so
** the public symbol is the default Parse* prefix. */
extern ParserSnapshot *ParseBuildSnapshot(void);

static int n_pass = 0, n_fail = 0;

#define CHECK(cond, ...)                                                                           \
    do {                                                                                           \
        if (cond) {                                                                                \
            printf("  [PASS] ");                                                                   \
            printf(__VA_ARGS__);                                                                   \
            printf("\n");                                                                          \
            n_pass++;                                                                              \
        } else {                                                                                   \
            printf("  [FAIL] ");                                                                   \
            printf(__VA_ARGS__);                                                                   \
            printf("\n");                                                                          \
            n_fail++;                                                                              \
        }                                                                                          \
    } while (0)

static double time_diff_ms(struct timespec a, struct timespec b) {
    return (b.tv_sec - a.tv_sec) * 1000.0 + (b.tv_nsec - a.tv_nsec) / 1e6;
}

int main(void) {
    setbuf(stdout, NULL);  /* line-buffer so we see progress in real time */
    printf("Lime PostgreSQL grammar regression test\n");
    printf("=======================================\n\n");

    struct timespec t0, t1;

    /* --- snapshot build --------------------------------------- */
    clock_gettime(CLOCK_MONOTONIC, &t0);
    ParserSnapshot *snap = ParseBuildSnapshot();
    clock_gettime(CLOCK_MONOTONIC, &t1);

    CHECK(snap != NULL, "ParseBuildSnapshot returned a snapshot");
    if (snap == NULL) return 1;

    printf("\n  build time: %.2f ms\n", time_diff_ms(t0, t1));
    printf("  states    : %u\n", snap->nstate);
    printf("  rules     : %u\n", snap->nrule);
    printf("  terminals : %u\n", snap->nterminal);
    printf("  symbols   : %u\n", snap->nsymbol);
    printf("  action tab: %u entries\n\n", snap->action_count);

    /* Order-of-magnitude assertions.  These guard against silent
    ** regressions in the generator that would shrink the table. */
    CHECK(snap->nstate > 1000, "snapshot has > 1000 states (=%u)", snap->nstate);
    CHECK(snap->nrule > 1000, "snapshot has > 1000 rules (=%u)", snap->nrule);
    CHECK(snap->nterminal > 100, "snapshot has > 100 terminals (=%u)", snap->nterminal);
    CHECK(snap->action_count > 50000,
          "action table has > 50000 entries (=%u) -- exercises i32 ofst path",
          snap->action_count);

    /* The fix that motivated this test: yy_shift_ofst entries can
    ** exceed INT16_MAX on grammars this large.  Verify the type
    ** width is wide enough by checking that at least one offset
    ** exceeds 32767 -- if all entries fit in int16_t, the fix
    ** wasn't actually exercised. */
    int32_t max_shift = 0;
    int32_t max_reduce = 0;
    for (uint32_t s = 0; s < snap->nstate; s++) {
        if (snap->yy_shift_ofst[s] > max_shift) max_shift = snap->yy_shift_ofst[s];
        if (snap->yy_reduce_ofst[s] > max_reduce) max_reduce = snap->yy_reduce_ofst[s];
    }
    printf("\n  max yy_shift_ofst : %" PRId32 "\n", max_shift);
    printf("  max yy_reduce_ofst: %" PRId32 "\n\n", max_reduce);
    CHECK(max_shift > 32767 || max_reduce > 32767,
          "at least one ofst entry exceeds INT16_MAX (= int32 width is required)");

    /* --- runtime engine smoke test ---------------------------- */
    ParseContext *ctx = parse_begin(snap);
    CHECK(ctx != NULL, "parse_begin succeeded on PG snapshot");
    if (ctx != NULL) {
        /* Drive an EOF token through the engine.  The PG grammar
        ** rejects empty input, so this should produce a parse
        ** error -- but it should not crash, leak, or assert. */
        int rc = parse_token(ctx, 0, NULL, -1);
        CHECK(rc != 0, "parse_token rejected empty input cleanly (rc=%d)", rc);
        parse_end(ctx);
    }

    /* --- JIT compile ----------------------------------------- */
    /* For small grammars the JIT codegen unrolls the state x
    ** lookahead machine into ~146,000 basic blocks of LLVM IR with
    ** constant-folded action returns, which is fast on tiny grammars
    ** but does not scale to PG-class input.  jit_codegen.c switches
    ** to a compact table-load path above an IR-size threshold; on
    ** the PG grammar that path produces ~30 IR instructions and the
    ** JIT compile completes in tens of milliseconds.
    **
    ** Set LIME_PG_TEST_JIT=0 to skip the JIT half (e.g. when running
    ** under sanitizers that don't play nicely with OrcJIT). */
    if (getenv("LIME_PG_TEST_JIT") != NULL && strcmp(getenv("LIME_PG_TEST_JIT"), "0") == 0) {
        printf("\n--- JIT compile ---\n");
        printf("  [SKIP] LIME_PG_TEST_JIT=0 set -- skipping JIT half.\n");
    } else {
        printf("\n--- JIT compile ---\n");
        clock_gettime(CLOCK_MONOTONIC, &t0);
        int jit_rc = lime_jit_compile(snap);
        clock_gettime(CLOCK_MONOTONIC, &t1);
        if (jit_rc != 0) {
            printf("  [SKIP] lime_jit_compile returned %d (LLVM unavailable?)\n", jit_rc);
        } else {
            printf("  JIT compiled in %.2f ms\n", time_diff_ms(t0, t1));
            CHECK(snap->jit_ctx != NULL, "JIT context attached after compile");

            ctx = parse_begin(snap);
            CHECK(ctx != NULL, "parse_begin succeeded with JIT armed");
            if (ctx != NULL) {
                int rc = parse_token(ctx, 0, NULL, -1);
                CHECK(rc != 0, "JIT path rejects empty input cleanly (rc=%d)", rc);
                parse_end(ctx);
            }
        }
    }

    snapshot_release(snap);

    printf("\n=== Summary === Pass: %d  Fail: %d\n", n_pass, n_fail);
    return n_fail == 0 ? 0 : 1;
}
