#define LBRACE                           1
#define RBRACE                           2
#define LBRACKET                         3
#define RBRACKET                         4
#define COLON                            5
#define COMMA                            6
#define LPAREN                           7
#define RPAREN                           8
#define DOT                              9
#define STRING                          10
#define INT_LIT                         11
#define FLOAT_LIT                       12
#define KW_TRUE                         13
#define KW_FALSE                        14
#define KW_NULL                         15
#define IDENT                           16
#define DOLLAR_IDENT                    17
#define KW_DB                           18
#define KW_FIND                         19
#define KW_UPDATE                       20
#define KW_AGGREGATE                    21
#define KW_OBJECTID                     22
#define OP_EQ                           23
#define OP_NE                           24
#define OP_GT                           25
#define OP_GTE                          26
#define OP_LT                           27
#define OP_LTE                          28
#define OP_IN                           29
#define OP_NIN                          30
#define OP_AND                          31
#define OP_OR                           32
#define OP_NOT                          33
#define OP_NOR                          34
#define OP_EXISTS                       35
#define OP_TYPE                         36
#define OP_REGEX                        37
#define OP_OPTIONS                      38
#define OP_MOD                          39
#define OP_ALL                          40
#define OP_ELEMMATCH                    41
#define OP_SIZE                         42
#define UP_SET                          43
#define UP_UNSET                        44
#define UP_INC                          45
#define UP_MUL                          46
#define UP_RENAME                       47
#define UP_MIN                          48
#define UP_MAX                          49
#define UP_CURRENTDATE                  50
#define UP_SETONINSERT                  51
#define UP_PUSH                         52
#define UP_PULL                         53
#define UP_ADDTOSET                     54
#define UP_POP                          55
#define AGG_MATCH                       56
#define AGG_GROUP                       57
#define AGG_PROJECT                     58
#define AGG_SORT                        59
#define AGG_LIMIT                       60
#define AGG_SKIP                        61
#define AGG_UNWIND                      62
#define AGG_LOOKUP                      63
#define AGG_OUT                         64
#define AGG_COUNT                       65
#define AGG_SUM                         66
#define AGG_AVG                         67
#define AGG_FIRST                       68
#define AGG_LAST                        69
