#define MODE_TYPE_NAME                   1
#define MODE_PLPGSQL_EXPR                2
#define MODE_PLPGSQL_ASSIGN1             3
#define MODE_PLPGSQL_ASSIGN2             4
#define MODE_PLPGSQL_ASSIGN3             5
#define SEMICOLON                        6
#define CONCURRENTLY                     7
#define USING                            8
#define INDEX                            9
#define CASCADE                         10
#define RESTRICT                        11
#define LPAREN                          12
#define RPAREN                          13
#define COMMA                           14
#define FORMAT_LA                       15
#define CALL                            16
#define CREATE                          17
#define ROLE                            18
#define WITH                            19
#define WITH_LA                         20
#define PASSWORD                        21
#define NULL_P                          22
#define ENCRYPTED                       23
#define UNENCRYPTED                     24
#define INHERIT                         25
#define CONNECTION                      26
#define LIMIT                           27
#define VALID                           28
#define UNTIL                           29
#define USER                            30
#define IDENT                           31
#define SYSID                           32
#define ADMIN                           33
#define IN_P                            34
#define GROUP_P                         35
#define ALTER                           36
#define DATABASE                        37
#define ALL                             38
#define DROP                            39
#define IF_P                            40
#define EXISTS                          41
#define ADD_P                           42
#define SCHEMA                          43
#define AUTHORIZATION                   44
#define NOT                             45
#define SET                             46
#define LOCAL                           47
#define SESSION                         48
#define TRANSACTION                     49
#define CHARACTERISTICS                 50
#define AS                              51
#define TO                              52
#define EQ                              53
#define DEFAULT                         54
#define FROM                            55
#define CURRENT_P                       56
#define TIME                            57
#define ZONE                            58
#define CATALOG_P                       59
#define NAMES                           60
#define XML_P                           61
#define OPTION                          62
#define SNAPSHOT                        63
#define DOT                             64
#define READ                            65
#define UNCOMMITTED                     66
#define COMMITTED                       67
#define REPEATABLE                      68
#define SERIALIZABLE                    69
#define TRUE_P                          70
#define FALSE_P                         71
#define ON                              72
#define RESET                           73
#define ISOLATION                       74
#define LEVEL                           75
#define SHOW                            76
#define CONSTRAINTS                     77
#define DEFERRED                        78
#define IMMEDIATE                       79
#define CHECKPOINT                      80
#define DISCARD                         81
#define TEMP                            82
#define TEMPORARY                       83
#define PLANS                           84
#define SEQUENCES                       85
#define TABLE                           86
#define TABLESPACE                      87
#define OWNED                           88
#define BY                              89
#define SEQUENCE                        90
#define VIEW                            91
#define MATERIALIZED                    92
#define FOREIGN                         93
#define PARTITION                       94
#define ATTACH                          95
#define DETACH                          96
#define FINALIZE                        97
#define SPLIT                           98
#define INTO                            99
#define MERGE                          100
#define PARTITIONS                     101
#define COLUMN                         102
#define EXPRESSION                     103
#define STATISTICS                     104
#define GENERATED                      105
#define IDENTITY_P                     106
#define TYPE_P                         107
#define CONSTRAINT                     108
#define VALIDATE                       109
#define WITHOUT                        110
#define OIDS                           111
#define CLUSTER                        112
#define LOGGED                         113
#define UNLOGGED                       114
#define ENABLE_P                       115
#define TRIGGER                        116
#define ALWAYS                         117
#define REPLICA                        118
#define DISABLE_P                      119
#define RULE                           120
#define NO                             121
#define OF                             122
#define OWNER                          123
#define ACCESS                         124
#define METHOD                         125
#define ROW                            126
#define SECURITY                       127
#define FORCE                          128
#define COLLATE                        129
#define NOTHING                        130
#define FULL                           131
#define RESTART                        132
#define FOR                            133
#define VALUES                         134
#define ATTRIBUTE                      135
#define CLOSE                          136
#define COPY                           137
#define PROGRAM                        138
#define STDIN                          139
#define STDOUT                         140
#define BINARY                         141
#define FREEZE                         142
#define DELIMITER                      143
#define CSV                            144
#define JSON                           145
#define HEADER_P                       146
#define QUOTE                          147
#define ESCAPE                         148
#define STAR                           149
#define ENCODING                       150
#define DELIMITERS                     151
#define GLOBAL                         152
#define OPTIONS                        153
#define COMPRESSION                    154
#define STORAGE                        155
#define UNIQUE                         156
#define PRIMARY                        157
#define KEY                            158
#define CHECK                          159
#define REFERENCES                     160
#define NULLS_P                        161
#define DISTINCT                       162
#define STORED                         163
#define VIRTUAL                        164
#define DEFERRABLE                     165
#define INITIALLY                      166
#define ENFORCED                       167
#define LIKE                           168
#define INCLUDING                      169
#define EXCLUDING                      170
#define COMMENTS                       171
#define DEFAULTS                       172
#define INDEXES                        173
#define EXCLUDE                        174
#define OVERLAPS                       175
#define PERIOD                         176
#define INCLUDE                        177
#define MATCH                          178
#define PARTIAL                        179
#define SIMPLE                         180
#define OPERATOR                       181
#define WHERE                          182
#define UPDATE                         183
#define DELETE_P                       184
#define ACTION                         185
#define INHERITS                       186
#define COMMIT                         187
#define ROWS                           188
#define PRESERVE                       189
#define DATA_P                         190
#define REFRESH                        191
#define CACHE                          192
#define CYCLE                          193
#define INCREMENT                      194
#define MAXVALUE                       195
#define MINVALUE                       196
#define NAME_P                         197
#define START                          198
#define FCONST                         199
#define PLUS                           200
#define MINUS                          201
#define LANGUAGE                       202
#define HANDLER                        203
#define TRUSTED                        204
#define INLINE_P                       205
#define VALIDATOR                      206
#define PROCEDURAL                     207
#define LOCATION                       208
#define EXTENSION                      209
#define VERSION_P                      210
#define AGGREGATE                      211
#define CAST                           212
#define DOMAIN_P                       213
#define FUNCTION                       214
#define CLASS                          215
#define FAMILY                         216
#define PROCEDURE                      217
#define ROUTINE                        218
#define TRANSFORM                      219
#define WRAPPER                        220
#define SERVER                         221
#define IMPORT_P                       222
#define EXCEPT                         223
#define MAPPING                        224
#define POLICY                         225
#define SELECT                         226
#define INSERT                         227
#define EXECUTE                        228
#define AFTER                          229
#define EACH                           230
#define BEFORE                         231
#define INSTEAD                        232
#define OR                             233
#define TRUNCATE                       234
#define REFERENCING                    235
#define NEW                            236
#define OLD                            237
#define STATEMENT                      238
#define WHEN                           239
#define EVENT                          240
#define AND                            241
#define SCONST                         242
#define ASSERTION                      243
#define ENUM_P                         244
#define RANGE                          245
#define TEXT_P                         246
#define SEARCH                         247
#define PARSER                         248
#define DICTIONARY                     249
#define TEMPLATE                       250
#define CONFIGURATION                  251
#define COLLATION                      252
#define NONE                           253
#define VALUE_P                        254
#define RENAME                         255
#define ORDER                          256
#define REASSIGN                       257
#define PROPERTY                       258
#define GRAPH                          259
#define CONVERSION_P                   260
#define SUBSCRIPTION                   261
#define PUBLICATION                    262
#define CONTINUE_P                     263
#define COMMENT                        264
#define IS                             265
#define LARGE_P                        266
#define OBJECT_P                       267
#define LABEL                          268
#define FETCH                          269
#define MOVE                           270
#define NEXT                           271
#define PRIOR                          272
#define FIRST_P                        273
#define LAST_P                         274
#define ABSOLUTE_P                     275
#define RELATIVE_P                     276
#define FORWARD                        277
#define BACKWARD                       278
#define GRANT                          279
#define REVOKE                         280
#define PRIVILEGES                     281
#define SYSTEM_P                       282
#define PARAMETER                      283
#define TABLES                         284
#define FUNCTIONS                      285
#define PROCEDURES                     286
#define ROUTINES                       287
#define GRANTED                        288
#define TYPES_P                        289
#define SCHEMAS                        290
#define OBJECTS_P                      291
#define ASC                            292
#define DESC                           293
#define NULLS_LA                       294
#define RETURNS                        295
#define REPLACE                        296
#define OUT_P                          297
#define INOUT                          298
#define VARIADIC                       299
#define PERCENT                        300
#define SETOF                          301
#define CALLED                         302
#define INPUT_P                        303
#define STRICT_P                       304
#define IMMUTABLE                      305
#define STABLE                         306
#define VOLATILE                       307
#define EXTERNAL                       308
#define DEFINER                        309
#define INVOKER                        310
#define LEAKPROOF                      311
#define COST                           312
#define SUPPORT                        313
#define PARALLEL                       314
#define WINDOW                         315
#define RETURN                         316
#define BEGIN_P                        317
#define ATOMIC                         318
#define END_P                          319
#define DO                             320
#define IMPLICIT_P                     321
#define ASSIGNMENT                     322
#define NODE                           323
#define VERTEX                         324
#define EDGE                           325
#define RELATIONSHIP                   326
#define SOURCE                         327
#define DESTINATION                    328
#define PROPERTIES                     329
#define COLUMNS                        330
#define SQL_P                          331
#define REINDEX                        332
#define DEPENDS                        333
#define CURRENT_SCHEMA                 334
#define SKIP                           335
#define ALSO                           336
#define NOTIFY                         337
#define LISTEN                         338
#define UNLISTEN                       339
#define ABORT_P                        340
#define ROLLBACK                       341
#define SAVEPOINT                      342
#define RELEASE                        343
#define PREPARE                        344
#define PREPARED                       345
#define WORK                           346
#define ONLY                           347
#define WRITE                          348
#define CHAIN                          349
#define RECURSIVE                      350
#define CASCADED                       351
#define LOAD                           352
#define REPACK                         353
#define VERBOSE                        354
#define VACUUM                         355
#define ANALYZE                        356
#define ANALYSE                        357
#define EXPLAIN                        358
#define DEALLOCATE                     359
#define OVERRIDING                     360
#define CONFLICT                       361
#define RETURNING                      362
#define LOCK_P                         363
#define MODE                           364
#define SHARE                          365
#define EXCLUSIVE                      366
#define NOWAIT                         367
#define LOCKED                         368
#define THEN                           369
#define MATCHED                        370
#define TARGET                         371
#define DECLARE                        372
#define CURSOR                         373
#define SCROLL                         374
#define ASENSITIVE                     375
#define INSENSITIVE                    376
#define HOLD                           377
#define UMINUS                         378
#define UNION                          379
#define INTERSECT                      380
#define DEPTH                          381
#define BREADTH                        382
#define TIES                           383
#define OFFSET                         384
#define ROLLUP                         385
#define CUBE                           386
#define GROUPING                       387
#define SETS                           388
#define HAVING                         389
#define LATERAL_P                      390
#define GRAPH_TABLE                    391
#define CROSS                          392
#define JOIN                           393
#define NATURAL                        394
#define LEFT                           395
#define RIGHT                          396
#define INNER_P                        397
#define OUTER_P                        398
#define TABLESAMPLE                    399
#define ORDINALITY                     400
#define XMLTABLE                       401
#define XMLNAMESPACES                  402
#define PATH                           403
#define JSON_TABLE                     404
#define NESTED                         405
#define ARRAY                          406
#define LBRACKET                       407
#define RBRACKET                       408
#define INT_P                          409
#define INTEGER                        410
#define SMALLINT                       411
#define BIGINT                         412
#define REAL                           413
#define FLOAT_P                        414
#define DOUBLE_P                       415
#define PRECISION                      416
#define DECIMAL_P                      417
#define DEC                            418
#define NUMERIC                        419
#define BOOLEAN_P                      420
#define BIT                            421
#define CHARACTER                      422
#define CHAR_P                         423
#define VARCHAR                        424
#define NATIONAL                       425
#define NCHAR                          426
#define VARYING                        427
#define TIMESTAMP                      428
#define INTERVAL                       429
#define WITHOUT_LA                     430
#define YEAR_P                         431
#define MONTH_P                        432
#define DAY_P                          433
#define HOUR_P                         434
#define MINUTE_P                       435
#define SECOND_P                       436
#define TYPECAST                       437
#define AT                             438
#define SLASH                          439
#define CARET                          440
#define LT                             441
#define GT                             442
#define LESS_EQUALS                    443
#define GREATER_EQUALS                 444
#define NOT_EQUALS                     445
#define RIGHT_ARROW                    446
#define PIPE                           447
#define OP                             448
#define NOT_LA                         449
#define ILIKE                          450
#define SIMILAR                        451
#define ISNULL                         452
#define NOTNULL                        453
#define UNKNOWN                        454
#define BETWEEN                        455
#define SYMMETRIC                      456
#define DOCUMENT_P                     457
#define NORMALIZED                     458
#define PARAM                          459
#define CURRENT_DATE                   460
#define CURRENT_TIME                   461
#define CURRENT_TIMESTAMP              462
#define LOCALTIME                      463
#define LOCALTIMESTAMP                 464
#define CURRENT_ROLE                   465
#define CURRENT_USER                   466
#define SESSION_USER                   467
#define SYSTEM_USER                    468
#define CURRENT_CATALOG                469
#define EXTRACT                        470
#define NORMALIZE                      471
#define OVERLAY                        472
#define POSITION                       473
#define SUBSTRING                      474
#define TREAT                          475
#define TRIM                           476
#define BOTH                           477
#define LEADING                        478
#define TRAILING                       479
#define NULLIF                         480
#define COALESCE                       481
#define GREATEST                       482
#define LEAST                          483
#define XMLCONCAT                      484
#define XMLELEMENT                     485
#define XMLEXISTS                      486
#define XMLFOREST                      487
#define XMLPARSE                       488
#define XMLPI                          489
#define XMLROOT                        490
#define XMLSERIALIZE                   491
#define JSON_OBJECT                    492
#define JSON_ARRAY                     493
#define JSON_SCALAR                    494
#define JSON_SERIALIZE                 495
#define MERGE_ACTION                   496
#define JSON_QUERY                     497
#define JSON_EXISTS                    498
#define JSON_VALUE                     499
#define STANDALONE_P                   500
#define YES_P                          501
#define XMLATTRIBUTES                  502
#define CONTENT_P                      503
#define INDENT                         504
#define WHITESPACE_P                   505
#define STRIP_P                        506
#define PASSING                        507
#define REF_P                          508
#define WAIT                           509
#define LSN_P                          510
#define WITHIN                         511
#define FILTER                         512
#define IGNORE_P                       513
#define RESPECT_P                      514
#define OVER                           515
#define GROUPS                         516
#define UNBOUNDED                      517
#define PRECEDING                      518
#define FOLLOWING                      519
#define OTHERS                         520
#define ANY                            521
#define SOME                           522
#define COLON_EQUALS                   523
#define EQUALS_GREATER                 524
#define NFC                            525
#define NFD                            526
#define NFKC                           527
#define NFKD                           528
#define PLACING                        529
#define CASE                           530
#define ELSE                           531
#define COLON                          532
#define ASYMMETRIC                     533
#define CONDITIONAL                    534
#define UNCONDITIONAL                  535
#define ERROR_P                        536
#define EMPTY_P                        537
#define KEEP                           538
#define QUOTES                         539
#define SCALAR                         540
#define STRING_P                       541
#define OMIT                           542
#define KEYS                           543
#define ABSENT                         544
#define JSON_OBJECTAGG                 545
#define JSON_ARRAYAGG                  546
#define LBRACE                         547
#define RBRACE                         548
#define BCONST                         549
#define XCONST                         550
#define ICONST                         551
#define FORMAT                         552
#define OFF                            553
#define PLAN                           554
#define UESCAPE                        555
#define VIEWS                          556
