/*
** src/lex/emit_rust_lex.c -- Rust output for the .lex compiler.
**
** Mirror of lex_emit.c's C output but emitting Rust.  The DFA
** tables and per-state accept arrays are emitted as `pub static`
** slices; the runtime is a simple batch tokenizer
** `Lexer::tokenize(input: &str) -> Vec<Token>` rather than the
** streaming push API the C side ships.  Most parser consumers
** want a flat token stream and feed it into the LALR parser
** anyway, so the streaming complexity isn't on the critical
** path for v0.8.x.
**
** What we emit:
**
**   - per-state DFA tables:
**       pub static <STATE>_TRANS:  &[[i16; 256]] = &[...];
**       pub static <STATE>_ACCEPT: &[i16] = &[...];   (rule id or -1)
**   - rule-id constants:
**       pub const RULE_<NAME>: u16 = N;
**   - A `Token` struct: { rule_id, text_start, text_len, line, column }
**   - A `Lexer` struct with tokenize(&self, input: &str) -> Vec<Token>
**     plus per-state state-driven match.
**
** Action body translation: per-rule actions are emitted as
** Rust closures in a dispatch table.  Default action emits the
** token verbatim with the matched text.  Users override per-rule
** via `%rust_lex_action` (sibling to `%rust_action` on the parser
** side; the directive isn't part of v0.8.x and the action body
** gets a default `Token { rule_id, text, ... }` emit when absent).
*/

#include "lex_compile.h"
#include "lex_dfa.h"
#include "lex_ast.h"

#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

extern int g_lime_rust_no_std;

static char *upper_dup_local(const char *s) {
    if (!s) return NULL;
    size_t n = strlen(s);
    char *out = (char *)malloc(n + 1);
    if (!out) return NULL;
    for (size_t i = 0; i < n; i++) {
        out[i] = (char)toupper((unsigned char)s[i]);
    }
    out[n] = '\0';
    return out;
}

static const char *eff_prefix(const char *p) {
    return (p && *p) ? p : "Lex";
}

static void emit_section(FILE *out, const char *title) {
    fprintf(out, "\n// ============================================"
                 "==========================\n");
    fprintf(out, "// %s\n", title);
    fprintf(out, "// ============================================"
                 "==========================\n\n");
}

static void emit_header(FILE *out, const char *prefix, const char *src_path) {
    fprintf(out,
            "// SPDX-License-Identifier: <inherited from input grammar>\n"
            "//\n"
            "// Generated by lime --rustlex -- DO NOT EDIT BY HAND.\n"
            "//\n"
            "// Source grammar: %s\n"
            "// Lexer prefix:   %s\n"
            "// To regenerate:  lime -X --rustlex %s\n"
            "//\n\n"
            "#![allow(dead_code)]\n"
            "#![allow(non_snake_case)]\n"
            "#![allow(non_upper_case_globals)]\n"
            "#![allow(unused_assignments)]\n"
            "#![allow(unused_variables)]\n"
            "#![allow(clippy::all)]\n",
            src_path ? src_path : "(unknown)",
            eff_prefix(prefix),
            src_path ? src_path : "<lex>");
    if (g_lime_rust_no_std) {
        fprintf(out, "extern crate alloc;\n");
        fprintf(out, "use alloc::vec::Vec;\n");
        fprintf(out, "use alloc::string::String;\n\n");
    }
}

/*
** Emit the per-state transition table.  C side uses a flat
** [N][256] int array; Rust side uses &[[i16; 256]] which is
** dense (256 KB for a 1k-state grammar; acceptable).
*/
static void emit_state_dfa(FILE *out, const char *prefix,
                           const LimeLexCompiledState *cs) {
    char *upper_state = upper_dup_local(cs->state_name);
    if (!upper_state) return;

    fprintf(out, "\n/// State %s -- %d DFA states, start = %d\n",
            cs->state_name, cs->dfa->n_states, cs->dfa->start);
    fprintf(out, "pub const %s_%s_START: u16  = %d;\n",
            prefix, upper_state, cs->dfa->start);
    fprintf(out, "pub const %s_%s_NSTATES: u16 = %d;\n\n",
            prefix, upper_state, cs->dfa->n_states);

    /* Transition table */
    fprintf(out, "pub static %s_%s_TRANS: &[[i16; 256]] = &[\n",
            prefix, upper_state);
    for (int s = 0; s < cs->dfa->n_states; s++) {
        fprintf(out, "    [");
        for (int b = 0; b < 256; b++) {
            int t = cs->dfa->states[s].trans[b];
            if (b > 0 && b % 16 == 0) fprintf(out, "\n     ");
            fprintf(out, "%4d,", t);
        }
        fprintf(out, "],\n");
    }
    fprintf(out, "];\n\n");

    /* Accept table */
    fprintf(out, "pub static %s_%s_ACCEPT: &[i16] = &[\n",
            prefix, upper_state);
    for (int s = 0; s < cs->dfa->n_states; s++) {
        const LimeDfaState *st = &cs->dfa->states[s];
        int rule_id = -1;
        if (st->is_accept && st->accept_rule >= 0
            && st->accept_rule < cs->n_rules) {
            rule_id = cs->rule_indices[st->accept_rule];
        }
        if (s > 0 && s % 16 == 0) fprintf(out, "\n   ");
        fprintf(out, " %4d,", rule_id);
    }
    fprintf(out, "\n];\n");
    free(upper_state);
}

/*
** Walk all rules in the spec to emit per-rule constants.
*/
static int collect_rule_count(const LimeLexSpec *spec) {
    int n = 0;
    for (LimeLexRule *r = spec->rules; r; r = r->next) n++;
    for (LimeLexRuleset *rs = spec->rulesets; rs; rs = rs->next) {
        for (LimeLexRule *r = rs->rules; r; r = r->next) n++;
    }
    return n;
}

static void emit_rule_constants(FILE *out, const char *prefix,
                                const LimeLexSpec *spec) {
    emit_section(out, "Rule constants");
    int rule_id = 0;
    for (LimeLexRule *r = spec->rules; r; r = r->next, rule_id++) {
        if (!r->name) continue;
        char *uname = upper_dup_local(r->name);
        if (!uname) continue;
        for (char *p = uname; *p; p++) {
            if (!isalnum((unsigned char)*p) && *p != '_') *p = '_';
        }
        fprintf(out, "pub const %s_RULE_%s: u16 = %d;\n",
                prefix, uname, rule_id);
        free(uname);
    }
    for (LimeLexRuleset *rs = spec->rulesets; rs; rs = rs->next) {
        for (LimeLexRule *r = rs->rules; r; r = r->next, rule_id++) {
            if (!r->name) continue;
            char *uname = upper_dup_local(r->name);
            if (!uname) continue;
            for (char *p = uname; *p; p++) {
                if (!isalnum((unsigned char)*p) && *p != '_') *p = '_';
            }
            fprintf(out, "pub const %s_RULE_%s: u16 = %d;\n",
                    prefix, uname, rule_id);
            free(uname);
        }
    }
    fprintf(out, "\npub const %s_NRULES: u16 = %d;\n", prefix, rule_id);
}

/*
** Emit the public Token type + Lexer struct + tokenize() runtime.
**
** The runtime is a longest-match DFA simulator: walks states for
** each input position, tracks the last accept, returns a token
** when no further transition is possible.
*/
static void emit_lexer_runtime(FILE *out, const char *prefix,
                               const LimeLexCompiled *compiled) {
    emit_section(out, "Tokenizer runtime");

    fprintf(out,
            "/// One token from the input stream.\n"
            "#[derive(Debug, Clone, PartialEq, Eq)]\n"
            "pub struct Token {\n"
            "    /// The rule id that matched.  Compare to %s_RULE_*\n"
            "    /// constants to identify which rule fired.\n"
            "    pub rule_id: u16,\n"
            "    /// Byte offset of the matched text in the input.\n"
            "    pub start: usize,\n"
            "    /// Length of the matched text in bytes.\n"
            "    pub len: usize,\n"
            "    /// 1-based line number of the first byte.\n"
            "    pub line: u32,\n"
            "    /// 1-based column number of the first byte.\n"
            "    pub column: u32,\n"
            "}\n\n",
            prefix);

    fprintf(out,
            "/// Errors returned by the lexer.\n"
            "#[derive(Debug, Clone, PartialEq, Eq)]\n"
            "pub enum LexError {\n"
            "    /// No matching rule at the given offset.  byte is the\n"
            "    /// offending byte; offset is its index.\n"
            "    NoMatch { offset: usize, byte: u8 },\n"
            "    /// Requested state name doesn't exist.\n"
            "    UnknownState,\n"
            "}\n\n");

    fprintf(out,
            "/// Lexer state identifier.  Use the START_STATE_* constants.\n"
            "pub type StateId = u16;\n\n");

    /* Emit a per-state-name -> trans/accept lookup table. */
    fprintf(out, "/// Per-named-state DFA dispatch.\n");
    fprintf(out,
            "fn dfa_trans_for_state(s: StateId) -> &'static [[i16; 256]] {\n");
    fprintf(out, "    match s {\n");
    char *upper_prefix_str = upper_dup_local(prefix);
    if (!upper_prefix_str) return;
    for (int i = 0; i < compiled->n_states; i++) {
        char *us = upper_dup_local(compiled->states[i].state_name);
        if (!us) continue;
        fprintf(out,
                "        %d => %s_%s_TRANS,\n",
                i, upper_prefix_str, us);
        free(us);
    }
    fprintf(out, "        _ => &[],\n");
    fprintf(out, "    }\n");
    fprintf(out, "}\n\n");

    fprintf(out,
            "fn dfa_accept_for_state(s: StateId) -> &'static [i16] {\n");
    fprintf(out, "    match s {\n");
    for (int i = 0; i < compiled->n_states; i++) {
        char *us = upper_dup_local(compiled->states[i].state_name);
        if (!us) continue;
        fprintf(out,
                "        %d => %s_%s_ACCEPT,\n",
                i, upper_prefix_str, us);
        free(us);
    }
    fprintf(out, "        _ => &[],\n");
    fprintf(out, "    }\n");
    fprintf(out, "}\n\n");

    fprintf(out,
            "fn dfa_start_for_state(s: StateId) -> u16 {\n");
    fprintf(out, "    match s {\n");
    for (int i = 0; i < compiled->n_states; i++) {
        char *us = upper_dup_local(compiled->states[i].state_name);
        if (!us) continue;
        fprintf(out,
                "        %d => %s_%s_START,\n",
                i, upper_prefix_str, us);
        free(us);
    }
    fprintf(out, "        _ => 0,\n");
    fprintf(out, "    }\n");
    fprintf(out, "}\n\n");

    /* Public state-name constants to make Lexer::tokenize_in_state
    ** ergonomic. */
    for (int i = 0; i < compiled->n_states; i++) {
        char *us = upper_dup_local(compiled->states[i].state_name);
        if (!us) continue;
        fprintf(out, "pub const STATE_%s: StateId = %d;\n", us, i);
        free(us);
    }
    fprintf(out, "\n");

    /* The Lexer itself */
    fprintf(out,
            "/// Lexer.  Stateless aside from the active state name; the\n"
            "/// caller drives tokenize() with a complete input string and\n"
            "/// receives a Vec<Token>.\n"
            "pub struct Lexer {\n"
            "    state: StateId,\n"
            "}\n\n");

    fprintf(out,
            "impl Lexer {\n"
            "    /// Construct a lexer in the INITIAL state (state 0).\n"
            "    pub fn new() -> Self { Self { state: 0 } }\n\n"
            "    /// Set the active state.  Use STATE_* constants.\n"
            "    pub fn set_state(&mut self, s: StateId) { self.state = s; }\n\n"
            "    /// Get the active state.\n"
            "    pub fn state(&self) -> StateId { self.state }\n\n"
            "    /// Tokenise an input string.  Returns the full token stream\n"
            "    /// when the input is fully consumed; returns Err with the\n"
            "    /// offending offset on no-match.\n"
            "    ///\n"
            "    /// Performance: O(input.len()) with a small per-byte cost\n"
            "    /// (one DFA transition + bookkeeping).  No allocations\n"
            "    /// per token beyond the result Vec.\n"
            "    pub fn tokenize(&mut self, input: &str) -> Result<Vec<Token>, LexError> {\n"
            "        let bytes = input.as_bytes();\n"
            "        let mut out = Vec::new();\n"
            "        let mut pos: usize = 0;\n"
            "        let mut line: u32 = 1;\n"
            "        let mut column: u32 = 1;\n"
            "        while pos < bytes.len() {\n"
            "            let trans = dfa_trans_for_state(self.state);\n"
            "            let accept = dfa_accept_for_state(self.state);\n"
            "            let mut state: i16 = dfa_start_for_state(self.state) as i16;\n"
            "            let mut last_accept: i16 = -1;\n"
            "            let mut last_accept_pos: usize = pos;\n"
            "            let mut p = pos;\n"
            "            // SAFETY: state is in [0, trans.len()) by DFA\n"
            "            // invariant; b is a valid byte (0..256); accept\n"
            "            // and trans share the same length per state.\n"
            "            unsafe {\n"
            "                while p < bytes.len() && state >= 0 {\n"
            "                    let b = *bytes.get_unchecked(p) as usize;\n"
            "                    let next = *trans.get_unchecked(state as usize)\n"
            "                                    .get_unchecked(b);\n"
            "                    if next < 0 { break; }\n"
            "                    state = next;\n"
            "                    let accv = *accept.get_unchecked(state as usize);\n"
            "                    if accv >= 0 {\n"
            "                        last_accept = accv;\n"
            "                        last_accept_pos = p + 1;\n"
            "                    }\n"
            "                    p += 1;\n"
            "                }\n"
            "            }\n"
            "            if last_accept < 0 {\n"
            "                return Err(LexError::NoMatch { offset: pos, byte: bytes[pos] });\n"
            "            }\n"
            "            let tok_start = pos;\n"
            "            let tok_len = last_accept_pos - pos;\n"
            "            let tok_line = line;\n"
            "            let tok_col = column;\n"
            "            // Advance line/column over the matched bytes.\n"
            "            for &b in &bytes[pos..last_accept_pos] {\n"
            "                if b == b'\\n' { line += 1; column = 1; }\n"
            "                else if b != b'\\r' { column += 1; }\n"
            "            }\n"
            "            out.push(Token {\n"
            "                rule_id: last_accept as u16,\n"
            "                start: tok_start,\n"
            "                len: tok_len,\n"
            "                line: tok_line,\n"
            "                column: tok_col,\n"
            "            });\n"
            "            pos = last_accept_pos;\n"
            "        }\n"
            "        Ok(out)\n"
            "    }\n"
            "}\n\n"
            "impl Default for Lexer {\n"
            "    fn default() -> Self { Self::new() }\n"
            "}\n");

    free(upper_prefix_str);
}

int emit_rust_lex(const LimeLexSpec *spec, const LimeLexCompiled *compiled,
                  const char *src_path, const char *out_path, char **error) {
    if (!spec || !compiled || !out_path) {
        if (error) *error = strdup("emit_rust_lex: bad arguments");
        return -1;
    }
    if (error) *error = NULL;

    FILE *out = fopen(out_path, "wb");
    if (!out) {
        if (error) {
            char buf[512];
            snprintf(buf, sizeof(buf),
                     "emit_rust_lex: can't open %s for writing", out_path);
            *error = strdup(buf);
        }
        return -1;
    }

    char *upper_prefix = upper_dup_local(eff_prefix(spec->name_prefix));
    if (!upper_prefix) { fclose(out); return -1; }

    emit_header(out, spec->name_prefix, src_path);

    emit_section(out, "Per-state DFA tables");
    for (int i = 0; i < compiled->n_states; i++) {
        emit_state_dfa(out, upper_prefix, &compiled->states[i]);
    }

    emit_rule_constants(out, upper_prefix, spec);
    emit_lexer_runtime(out, upper_prefix, compiled);

    free(upper_prefix);
    fclose(out);
    return 0;
}
