/*
** src/lex/emit_rust_lex.c -- Rust output for the .lex compiler.
**
** Mirror of lex_emit.c's C output but emitting Rust.  The DFA
** tables and per-state accept arrays are emitted as `pub static`
** slices; the runtime is a simple batch tokenizer
** `Lexer::tokenize(input: &str) -> Vec<Token>` rather than the
** streaming push API the C side ships.  Most parser consumers
** want a flat token stream and feed it into the LALR parser
** anyway, so the streaming complexity isn't on the critical
** path for v0.8.x.
**
** What we emit:
**
**   - per-state DFA tables:
**       pub static <STATE>_TRANS:  &[[i16; 256]] = &[...];
**       pub static <STATE>_ACCEPT: &[i16] = &[...];   (rule id or -1)
**   - rule-id constants:
**       pub const RULE_<NAME>: u16 = N;
**   - A `Token` struct: { rule_id, text_start, text_len, line, column }
**   - A `Lexer` struct with tokenize(&self, input: &str) -> Vec<Token>
**     plus per-state state-driven match.
**
** Action body translation: per-rule actions are emitted as
** Rust closures in a dispatch table.  Default action emits the
** token verbatim with the matched text.  Users override per-rule
** via `%rust_lex_action` (sibling to `%rust_action` on the parser
** side; the directive isn't part of v0.8.x and the action body
** gets a default `Token { rule_id, text, ... }` emit when absent).
*/

#include "lex_compile.h"
#include "lex_dfa.h"
#include "lex_ast.h"

#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

extern int g_lime_rust_no_std;
extern int g_lime_rustlex_memchr_flag;
extern int g_lime_rustlex_simd_flag;
extern int g_lime_per_token_dfa_flag;
extern int g_lime_lex_safe_flag;  /* v0.9.3: 1 = drop unsafe { } in scalar
                                  ** DFA dispatch loops; use [] indexing.
                                  ** 0 = current v0.9.2 behaviour (unsafe +
                                  ** get_unchecked).  Default 1 (set in
                                  ** lime.c).  Categories 2 (SIMD intrinsics)
                                  ** and 3 (#[target_feature] callsites) are
                                  ** unaffected -- they remain unsafe by
                                  ** Rust language rules. */

static char *upper_dup_local(const char *s) {
    if (!s) return NULL;
    size_t n = strlen(s);
    char *out = (char *)malloc(n + 1);
    if (!out) return NULL;
    for (size_t i = 0; i < n; i++) {
        out[i] = (char)toupper((unsigned char)s[i]);
    }
    out[n] = '\0';
    return out;
}

static const char *eff_prefix(const char *p) {
    return (p && *p) ? p : "Lex";
}

static void emit_section(FILE *out, const char *title) {
    fprintf(out, "\n// ============================================"
                 "==========================\n");
    fprintf(out, "// %s\n", title);
    fprintf(out, "// ============================================"
                 "==========================\n\n");
}

static void emit_header(FILE *out, const char *prefix, const char *src_path) {
    fprintf(out,
            "// SPDX-License-Identifier: <inherited from input grammar>\n"
            "//\n"
            "// Generated by lime --rustlex -- DO NOT EDIT BY HAND.\n"
            "//\n"
            "// Source grammar: %s\n"
            "// Lexer prefix:   %s\n"
            "// To regenerate:  lime -X --rustlex %s\n"
            "//\n\n"
            "#![allow(dead_code)]\n"
            "#![allow(non_snake_case)]\n"
            "#![allow(non_upper_case_globals)]\n"
            "#![allow(unused_assignments)]\n"
            "#![allow(unused_variables)]\n"
            "#![allow(clippy::all)]\n",
            src_path ? src_path : "(unknown)",
            eff_prefix(prefix),
            src_path ? src_path : "<lex>");
    if (g_lime_rust_no_std) {
        fprintf(out, "extern crate alloc;\n");
        fprintf(out, "use alloc::vec::Vec;\n");
        fprintf(out, "use alloc::string::String;\n\n");
    }
    if (g_lime_rustlex_memchr_flag) {
        fprintf(out, "// --rustlex-memchr: opt-in memchr crate dependency for\n");
        fprintf(out, "// SIMD-accelerated fast-path scans.  Add to your Cargo.toml:\n");
        fprintf(out, "//   memchr = \"2\"\n");
        fprintf(out, "// (--rustcrate emits this automatically.)\n\n");
    }
}

/*
** Emit the per-state DFA dispatch as a Rust match expression.
**
** v0.8.3 rewrite: instead of emitting a flat &[i16] transition
** table indexed at runtime by trans[state*256+b], we now emit
** a generated `step_<STATE>(state, byte) -> i16` function whose
** body is a giant `match state { 0 => match byte { ... } }`.
**
** LLVM compiles small-arity match expressions into jump tables
** with branch-predicted dispatch; on JSON the win is substantial
** because most states have only 2-4 distinct transitions and
** the jump table fits in I-cache.  See docs/RUST_BENCHMARK.md
** for the v0.8.2 -> v0.8.3 numbers.
**
** Byte-range compression: contiguous bytes with the same target
** state are emitted as `start..=end => target` arms.  E.g. all
** ASCII letters mapping to the same state collapse to one arm
** `97..=122 => N` instead of 26 individual arms.  This keeps
** the generated code small enough for LLVM to optimise well
** even on large DFAs.
**
** Accept table: still emitted as a small &[i16] (NSTATES
** entries).  Accept lookup happens AFTER the step transition
** so it's a single load on a small in-L1 array.
*/
static void emit_state_dfa(FILE *out, const char *prefix,
                           const LimeLexCompiledState *cs) {
    char *upper_state = upper_dup_local(cs->state_name);
    if (!upper_state) return;

    int nstates = cs->dfa->n_states;

    fprintf(out, "\n/// State %s -- %d DFA states, start = %d\n",
            cs->state_name, nstates, cs->dfa->start);
    fprintf(out, "pub const %s_%s_START:    u16 = %d;\n",
            prefix, upper_state, cs->dfa->start);
    fprintf(out, "pub const %s_%s_NSTATES:  u16 = %d;\n\n",
            prefix, upper_state, nstates);

    /* Accept table: NSTATES entries. */
    fprintf(out, "pub static %s_%s_ACCEPT: &[i16] = &[\n",
            prefix, upper_state);
    for (int s = 0; s < nstates; s++) {
        const LimeDfaState *st = &cs->dfa->states[s];
        int rule_id = -1;
        if (st->is_accept && st->accept_rule >= 0
            && st->accept_rule < cs->n_rules) {
            rule_id = cs->rule_indices[st->accept_rule];
        }
        if (s > 0 && s % 16 == 0) fprintf(out, "\n   ");
        fprintf(out, " %4d,", rule_id);
    }
    fprintf(out, "\n];\n\n");

    /* Per-state-group step function: state x byte -> next state. */
    fprintf(out,
            "/// Step the DFA for state group %s.  Returns the\n"
            "/// next state id, or -1 to indicate \"no transition\"\n"
            "/// (caller breaks out of the inner loop).\n",
            cs->state_name);
    fprintf(out,
            "#[inline(always)]\n"
            "fn step_%s(state: u16, b: u8) -> i16 {\n",
            cs->state_name);
    fprintf(out, "    match state {\n");
    for (int s = 0; s < nstates; s++) {
        fprintf(out, "        %d => match b {\n", s);
        /* Compress contiguous-byte runs with same target. */
        const int *tr = cs->dfa->states[s].trans;
        int b = 0;
        while (b < 256) {
            int target = tr[b];
            if (target < 0) { b++; continue; }
            int e = b;
            while (e + 1 < 256 && tr[e + 1] == target) e++;
            if (b == e) {
                fprintf(out, "            %d => %d,\n", b, target);
            } else {
                fprintf(out, "            %d..=%d => %d,\n", b, e, target);
            }
            b = e + 1;
        }
        fprintf(out, "            _ => -1,\n");
        fprintf(out, "        },\n");
    }
    fprintf(out, "        _ => -1,\n");
    fprintf(out, "    }\n");
    fprintf(out, "}\n");

    /* v0.8.3 fast-path emission.  For each state, classify by the
    ** shape of its 256-entry transition row and emit one of two
    ** SIMD-friendly scan helpers when the shape is favourable:
    **
    **   FAST PATH A -- "scan-until-exit" (memchr-style).
    **     Triggered when self-loop covers >= 240 of 256 bytes
    **     and there are <= 8 distinct exit-byte values.  LLVM
    **     compiles the resulting loop to vectorised compare-and-
    **     extract instructions (PCMPISTRI on x86, NEON match on
    **     ARM).  Wins on string body, comment body, identifier
    **     scan, etc.
    **
    **   FAST PATH B -- "scan-while-in-self" (byte-class loop).
    **     Triggered when self-loop covers <= 16 bytes (small
    **     character class).  The loop body becomes a small set
    **     of byte tests that LLVM auto-vectorises into AVX2
    **     compare-and-mask.  Wins on whitespace runs, digit
    **     runs, hex/oct digit runs.
    **
    ** States that match neither pattern fall through to the
    ** standard step dispatch -- still fast, just no SIMD scan.
    */
    fprintf(out,
            "/// Fast-path scan helpers for self-loop-dominant\n"
            "/// states.  Each returns the new value of `p` after\n"
            "/// scanning a run of self-loop bytes.  LLVM\n"
            "/// auto-vectorises these tight loops.\n");
    int *fp_kind = (int *)calloc(nstates, sizeof(int));
    /* fp_kind: 0 = none, 1 = scan-until-exit, 2 = scan-while-self */
    if (!fp_kind) { free(upper_state); return; }
    for (int s = 0; s < nstates; s++) {
        const int *tr = cs->dfa->states[s].trans;
        int self_count = 0;
        int exit_set[8];
        int n_exit = 0;
        int has_too_many_exit = 0;
        int self_set[16];
        int n_self = 0;
        int has_too_many_self = 0;
        for (int b = 0; b < 256; b++) {
            int t = tr[b];
            if (t == s) {
                self_count++;
                if (n_self < 16) self_set[n_self++] = b;
                else has_too_many_self = 1;
            } else if (t >= 0) {
                int found = 0;
                for (int i = 0; i < n_exit; i++)
                    if (exit_set[i] == b) { found = 1; break; }
                if (!found) {
                    if (n_exit >= 8) { has_too_many_exit = 1; }
                    else exit_set[n_exit++] = b;
                }
            }
        }

        /* Pattern A: scan-until-exit.
        **
        ** Two emit modes:
        **
        **   Default (--rustlex): hand-rolled scalar while loop with
        **   unchecked indexing.  Self-contained -- no extra crate
        **   dependency.  ~1 GB/s on x86_64; faster than the bare
        **   step dispatch but ~2x slower than logos's per-token
        **   SIMD on string-heavy workloads.
        **
        **   memchr mode (--rustlex-memchr): emit calls into the
        **   memchr(2) crate (memchr / memchr2 / memchr3 depending
        **   on the exit-set cardinality).  Adds 'memchr = "2"' to
        **   the generated Cargo.toml; SIMD-accelerated
        **   (SSE2/AVX2/NEON internally).  Closes ~50%% of the
        **   lime-vs-logos lexer gap on string-heavy fixtures at
        **   the cost of a runtime crate dependency. */
        if (!has_too_many_exit && self_count >= 240 && n_exit > 0) {
            fp_kind[s] = 1;
            if (g_lime_rustlex_simd_flag) {
                /* In --rustlex-simd mode the per-state scan body lives
                ** as a Scanner trait method (emitted by emit_simd_helpers
                ** with byte literals baked into each impl).  We don't
                ** emit a standalone scan_self_loop_*_g function here --
                ** the dispatcher fast_path_<NAME>_g calls
                ** S::scan_<NAME>_<S> directly. */
                continue;
            }
            fprintf(out,
                    "#[inline(always)]\n"
                    "fn scan_self_loop_%s_%d(bytes: &[u8], p: usize) -> usize {\n",
                    cs->state_name, s);
            if (g_lime_rustlex_memchr_flag) {
                /* memchr crate: call memchr / memchr2 / memchr3
                ** as appropriate for the exit-set size. */
                fprintf(out, "    let tail = &bytes[p..];\n");
                if (n_exit == 1) {
                    fprintf(out,
                            "    p + memchr::memchr(%d, tail).unwrap_or(tail.len())\n",
                            exit_set[0]);
                } else if (n_exit == 2) {
                    fprintf(out,
                            "    p + memchr::memchr2(%d, %d, tail).unwrap_or(tail.len())\n",
                            exit_set[0], exit_set[1]);
                } else if (n_exit == 3) {
                    fprintf(out,
                            "    p + memchr::memchr3(%d, %d, %d, tail).unwrap_or(tail.len())\n",
                            exit_set[0], exit_set[1], exit_set[2]);
                } else {
                    /* memchr_iter: scan for the first occurrence of any
                    ** byte in a 4-8-element exit set.  Slower per-call
                    ** than memchr3 but still SIMD-accelerated for the
                    ** core scan; the per-byte predicate runs only on
                    ** candidate matches. */
                    fprintf(out, "    let mut min_off = tail.len();\n");
                    for (int i = 0; i < n_exit; i++) {
                        fprintf(out,
                                "    if let Some(off) = memchr::memchr(%d, tail) { if off < min_off { min_off = off; } }\n",
                                exit_set[i]);
                    }
                    fprintf(out, "    p + min_off\n");
                }
            } else {
                fprintf(out, "    let n = bytes.len();\n");
                fprintf(out, "    let mut p = p;\n");
                fprintf(out, "    while p < n {\n");
                fprintf(out, "        let b = bytes[p];\n");
                fprintf(out, "        if ");
                for (int i = 0; i < n_exit; i++) {
                    if (i > 0) fprintf(out, " || ");
                    fprintf(out, "b == %d", exit_set[i]);
                }
                fprintf(out, " { break; }\n");
                fprintf(out, "        p += 1;\n");
                fprintf(out, "    }\n");
                fprintf(out, "    p\n");
            }
            fprintf(out, "}\n");
            continue;
        }
        /* Pattern B: scan-while-self.  Currently disabled --
        ** the function-call overhead exceeds the savings on short
        ** self-loop runs (typical JSON whitespace runs are 1-2
        ** bytes).  Worth re-enabling with a length threshold once
        ** we have profile data on a workload with long self-loop
        ** runs (XML text content, source-code indentation, etc.). */
        if (0 && !has_too_many_self && n_self >= 1 && n_self <= 16
            && self_count >= 1) {
            fp_kind[s] = 2;
            fprintf(out,
                    "#[inline(always)]\n"
                    "fn scan_self_loop_%s_%d(bytes: &[u8], mut p: usize) -> usize {\n",
                    cs->state_name, s);
            fprintf(out, "    while p < bytes.len() {\n");
            fprintf(out, "        let b = bytes[p];\n");
            /* compress contiguous self bytes into ranges */
            fprintf(out, "        if !(");
            int j = 0;
            int emitted = 0;
            while (j < n_self) {
                int rs = self_set[j];
                int re = rs;
                while (j + 1 < n_self
                       && self_set[j + 1] == self_set[j] + 1) {
                    re = self_set[j + 1]; j++;
                }
                if (emitted) fprintf(out, " || ");
                if (rs == re) fprintf(out, "b == %d", rs);
                else fprintf(out, "(%d..=%d).contains(&b)", rs, re);
                emitted = 1;
                j++;
            }
            fprintf(out, ") { break; }\n");
            fprintf(out, "        p += 1;\n");
            fprintf(out, "    }\n");
            fprintf(out, "    p\n");
            fprintf(out, "}\n");
        }
    }

    /* Emit a fast-path dispatcher: state -> scan helper or none.
    ** Returns the new `p` (unchanged if no fast path).  Under
    ** --rustlex-simd, the dispatcher is generic over the Scanner
    ** trait so the AVX2/scalar specialisation chosen at the
    ** tokenize() level monomorphises through to the per-state
    ** scan_self_loop_*_g body. */
    if (g_lime_rustlex_simd_flag) {
        fprintf(out,
                "#[inline(always)]\n"
                "fn fast_path_%s_g<S: Scanner>(state: u16, bytes: &[u8], p: usize) -> usize {\n",
                cs->state_name);
    } else {
        fprintf(out,
                "#[inline(always)]\n"
                "fn fast_path_%s(state: u16, bytes: &[u8], p: usize) -> usize {\n",
                cs->state_name);
    }
    fprintf(out, "    match state {\n");
    int any_fast = 0;
    for (int s = 0; s < nstates; s++) {
        if (fp_kind[s] == 0) continue;
        any_fast = 1;
        if (g_lime_rustlex_simd_flag) {
            fprintf(out, "        %d => S::scan_%s_%d(bytes, p),\n",
                    s, cs->state_name, s);
        } else {
            fprintf(out, "        %d => scan_self_loop_%s_%d(bytes, p),\n",
                    s, cs->state_name, s);
        }
    }
    fprintf(out, "        _ => p,\n");
    fprintf(out, "    }\n");
    fprintf(out, "}\n");
    if (!any_fast) {
        fprintf(out, "/* (no fast-path candidates in state group %s) */\n",
                cs->state_name);
    }
    free(fp_kind);

    free(upper_state);
}

/*
** Walk all rules in the spec to emit per-rule constants.
*/
static int collect_rule_count(const LimeLexSpec *spec) {
    int n = 0;
    for (LimeLexRule *r = spec->rules; r; r = r->next) n++;
    for (LimeLexRuleset *rs = spec->rulesets; rs; rs = rs->next) {
        for (LimeLexRule *r = rs->rules; r; r = r->next) n++;
    }
    return n;
}

static void emit_rule_constants(FILE *out, const char *prefix,
                                const LimeLexSpec *spec) {
    emit_section(out, "Rule constants");
    int rule_id = 0;
    for (LimeLexRule *r = spec->rules; r; r = r->next, rule_id++) {
        if (!r->name) continue;
        char *uname = upper_dup_local(r->name);
        if (!uname) continue;
        for (char *p = uname; *p; p++) {
            if (!isalnum((unsigned char)*p) && *p != '_') *p = '_';
        }
        fprintf(out, "pub const %s_RULE_%s: u16 = %d;\n",
                prefix, uname, rule_id);
        free(uname);
    }
    for (LimeLexRuleset *rs = spec->rulesets; rs; rs = rs->next) {
        for (LimeLexRule *r = rs->rules; r; r = r->next, rule_id++) {
            if (!r->name) continue;
            char *uname = upper_dup_local(r->name);
            if (!uname) continue;
            for (char *p = uname; *p; p++) {
                if (!isalnum((unsigned char)*p) && *p != '_') *p = '_';
            }
            fprintf(out, "pub const %s_RULE_%s: u16 = %d;\n",
                    prefix, uname, rule_id);
            free(uname);
        }
    }
    fprintf(out, "\npub const %s_NRULES: u16 = %d;\n", prefix, rule_id);
}

/*
** Emit the public Token type + Lexer struct + tokenize() runtime.
**
** The runtime is a longest-match DFA simulator: walks states for
** each input position, tracks the last accept, returns a token
** when no further transition is possible.
*/

/*
** Emit the multiversion SIMD modules and Scanner trait.  Emitted only
** when --rustlex-simd is set.  Replaces the previous broken design
** which emitted #[target_feature(enable = "avx2")] helpers behind a
** runtime-detected dispatcher -- that design forced every fast-path
** scan to cross a target_feature inlining barrier (the AVX2 body
** could not inline into a non-AVX2 caller), turning each scan into
** an out-of-line function call with cached-atomic-load dispatch.
**
** New design (v0.8.9):
**
**   - tokenize() detects AVX2 once at entry and dispatches into
**     tokenize_avx2() (with #[target_feature(enable = "avx2,bmi2")])
**     or tokenize_scalar().
**
**   - Both wrap a generic tokenize_impl<S: Scanner> that contains
**     the actual lexer body.
**
**   - The Scanner trait has #[inline(always)] methods that delegate
**     to scan_avx2::scan_until_<n> (in AvxScanner) or
**     scan_scalar::scan_until_<n> (in ScalarScanner).
**
**   - When tokenize_avx2() is monomorphised with S = AvxScanner,
**     the AVX2 intrinsics inline directly into the tokenize loop
**     body -- no target_feature inlining barrier, no atomic load
**     per scan, no out-of-line call.
**
** This design measured ~+5% over the scalar baseline on the JSON
** fixture and replaces a -1% regression in the prior emit.  See
** docs/RUST_BENCHMARK.md for the methodology and numbers.
*/
static void emit_simd_helpers(FILE *out, const LimeLexCompiled *compiled) {
    fprintf(out,
            "// =====================================================================\n"
            "// SIMD fast-path helpers (--rustlex-simd, multiversion)\n"
            "// =====================================================================\n\n"
            "// AVX2 module: scan_until_<n>(bytes, start, b1[, b2[, b3]]) finds\n"
            "// the first byte in bytes[start..] equal to any of (b1, ...) and\n"
            "// returns its index, or bytes.len() if none.  These are #[inline\n"
            "// (always)] and carry NO #[target_feature] attribute -- they are\n"
            "// only ever called from a function that has already declared\n"
            "// target_feature(enable = \"avx2\"), so the AVX2 intrinsics\n"
            "// inline into that caller's body without crossing a target_feature\n"
            "// inlining barrier.  Runtime AVX2 detection happens once per\n"
            "// tokenize() call, not once per scan.\n\n");
    fprintf(out,
            "#[cfg(target_arch = \"x86_64\")]\n"
            "mod scan_avx2 {\n"
            "    use std::arch::x86_64::*;\n\n"
            "    #[inline(always)]\n"
            "    pub unsafe fn scan_until_1(bytes: &[u8], start: usize, b1: u8) -> usize {\n"
            "        let n = bytes.len();\n"
            "        let mut p = start;\n"
            "        let v1 = _mm256_set1_epi8(b1 as i8);\n"
            "        while p + 32 <= n {\n"
            "            let chunk = _mm256_loadu_si256(bytes.as_ptr().add(p) as *const __m256i);\n"
            "            let cmp = _mm256_cmpeq_epi8(chunk, v1);\n"
            "            let mask = _mm256_movemask_epi8(cmp) as u32;\n"
            "            if mask != 0 { return p + (mask.trailing_zeros() as usize); }\n"
            "            p += 32;\n"
            "        }\n"
            "        while p < n {\n"
            "            if *bytes.get_unchecked(p) == b1 { return p; }\n"
            "            p += 1;\n"
            "        }\n"
            "        n\n"
            "    }\n\n"
            "    #[inline(always)]\n"
            "    pub unsafe fn scan_until_2(bytes: &[u8], start: usize, b1: u8, b2: u8) -> usize {\n"
            "        let n = bytes.len();\n"
            "        let mut p = start;\n"
            "        let v1 = _mm256_set1_epi8(b1 as i8);\n"
            "        let v2 = _mm256_set1_epi8(b2 as i8);\n"
            "        while p + 32 <= n {\n"
            "            let chunk = _mm256_loadu_si256(bytes.as_ptr().add(p) as *const __m256i);\n"
            "            let cmp1 = _mm256_cmpeq_epi8(chunk, v1);\n"
            "            let cmp2 = _mm256_cmpeq_epi8(chunk, v2);\n"
            "            let cmp = _mm256_or_si256(cmp1, cmp2);\n"
            "            let mask = _mm256_movemask_epi8(cmp) as u32;\n"
            "            if mask != 0 { return p + (mask.trailing_zeros() as usize); }\n"
            "            p += 32;\n"
            "        }\n"
            "        while p < n {\n"
            "            let b = *bytes.get_unchecked(p);\n"
            "            if b == b1 || b == b2 { return p; }\n"
            "            p += 1;\n"
            "        }\n"
            "        n\n"
            "    }\n\n"
            "    #[inline(always)]\n"
            "    pub unsafe fn scan_until_3(bytes: &[u8], start: usize, b1: u8, b2: u8, b3: u8) -> usize {\n"
            "        let n = bytes.len();\n"
            "        let mut p = start;\n"
            "        let v1 = _mm256_set1_epi8(b1 as i8);\n"
            "        let v2 = _mm256_set1_epi8(b2 as i8);\n"
            "        let v3 = _mm256_set1_epi8(b3 as i8);\n"
            "        while p + 32 <= n {\n"
            "            let chunk = _mm256_loadu_si256(bytes.as_ptr().add(p) as *const __m256i);\n"
            "            let cmp1 = _mm256_cmpeq_epi8(chunk, v1);\n"
            "            let cmp2 = _mm256_cmpeq_epi8(chunk, v2);\n"
            "            let cmp3 = _mm256_cmpeq_epi8(chunk, v3);\n"
            "            let cmp = _mm256_or_si256(_mm256_or_si256(cmp1, cmp2), cmp3);\n"
            "            let mask = _mm256_movemask_epi8(cmp) as u32;\n"
            "            if mask != 0 { return p + (mask.trailing_zeros() as usize); }\n"
            "            p += 32;\n"
            "        }\n"
            "        while p < n {\n"
            "            let b = *bytes.get_unchecked(p);\n"
            "            if b == b1 || b == b2 || b == b3 { return p; }\n"
            "            p += 1;\n"
            "        }\n"
            "        n\n"
            "    }\n"
            "}\n\n");
    fprintf(out,
            "// NEON module (aarch64).  NEON is mandatory on aarch64 so we\n"
            "// don't need runtime detection -- the multiversion dispatch\n"
            "// in tokenize() routes all aarch64 callers here directly.\n\n"
            "#[cfg(target_arch = \"aarch64\")]\n"
            "mod scan_neon {\n"
            "    use std::arch::aarch64::*;\n\n"
            "    #[inline(always)]\n"
            "    pub unsafe fn scan_until_1(bytes: &[u8], start: usize, b1: u8) -> usize {\n"
            "        let n = bytes.len();\n"
            "        let mut p = start;\n"
            "        let v1 = vdupq_n_u8(b1);\n"
            "        while p + 16 <= n {\n"
            "            let chunk = vld1q_u8(bytes.as_ptr().add(p));\n"
            "            let cmp = vceqq_u8(chunk, v1);\n"
            "            // Pack 16 lane results into a 64-bit mask: each lane becomes 4 bits.\n"
            "            let mask = vget_lane_u64(\n"
            "                vreinterpret_u64_u8(vshrn_n_u16(vreinterpretq_u16_u8(cmp), 4)), 0);\n"
            "            if mask != 0 { return p + (mask.trailing_zeros() as usize / 4); }\n"
            "            p += 16;\n"
            "        }\n"
            "        while p < n {\n"
            "            if *bytes.get_unchecked(p) == b1 { return p; }\n"
            "            p += 1;\n"
            "        }\n"
            "        n\n"
            "    }\n\n"
            "    #[inline(always)]\n"
            "    pub unsafe fn scan_until_2(bytes: &[u8], start: usize, b1: u8, b2: u8) -> usize {\n"
            "        let n = bytes.len();\n"
            "        let mut p = start;\n"
            "        let v1 = vdupq_n_u8(b1);\n"
            "        let v2 = vdupq_n_u8(b2);\n"
            "        while p + 16 <= n {\n"
            "            let chunk = vld1q_u8(bytes.as_ptr().add(p));\n"
            "            let any = vorrq_u8(vceqq_u8(chunk, v1), vceqq_u8(chunk, v2));\n"
            "            let mask = vget_lane_u64(\n"
            "                vreinterpret_u64_u8(vshrn_n_u16(vreinterpretq_u16_u8(any), 4)), 0);\n"
            "            if mask != 0 { return p + (mask.trailing_zeros() as usize / 4); }\n"
            "            p += 16;\n"
            "        }\n"
            "        while p < n {\n"
            "            let b = *bytes.get_unchecked(p);\n"
            "            if b == b1 || b == b2 { return p; }\n"
            "            p += 1;\n"
            "        }\n"
            "        n\n"
            "    }\n\n"
            "    #[inline(always)]\n"
            "    pub unsafe fn scan_until_3(bytes: &[u8], start: usize, b1: u8, b2: u8, b3: u8) -> usize {\n"
            "        let n = bytes.len();\n"
            "        let mut p = start;\n"
            "        let v1 = vdupq_n_u8(b1);\n"
            "        let v2 = vdupq_n_u8(b2);\n"
            "        let v3 = vdupq_n_u8(b3);\n"
            "        while p + 16 <= n {\n"
            "            let chunk = vld1q_u8(bytes.as_ptr().add(p));\n"
            "            let any = vorrq_u8(\n"
            "                vorrq_u8(vceqq_u8(chunk, v1), vceqq_u8(chunk, v2)),\n"
            "                vceqq_u8(chunk, v3));\n"
            "            let mask = vget_lane_u64(\n"
            "                vreinterpret_u64_u8(vshrn_n_u16(vreinterpretq_u16_u8(any), 4)), 0);\n"
            "            if mask != 0 { return p + (mask.trailing_zeros() as usize / 4); }\n"
            "            p += 16;\n"
            "        }\n"
            "        while p < n {\n"
            "            let b = *bytes.get_unchecked(p);\n"
            "            if b == b1 || b == b2 || b == b3 { return p; }\n"
            "            p += 1;\n"
            "        }\n"
            "        n\n"
            "    }\n"
            "}\n\n");
    fprintf(out,
            "// Scalar fallback module: portable Rust, no platform intrinsics.\n"
            "// Compiled into ScalarScanner; also serves as the fallback for\n"
            "// non-x86_64 / non-aarch64 architectures (RISC-V no-V, etc).\n\n"
            "mod scan_scalar {\n"
            "    #[inline(always)]\n"
            "    pub fn scan_until_1(bytes: &[u8], start: usize, b1: u8) -> usize {\n"
            "        let n = bytes.len();\n"
            "        let mut p = start;\n"
            "        while p < n {\n"
            "            let b = bytes[p];\n"
            "            if b == b1 { return p; }\n"
            "            p += 1;\n"
            "        }\n"
            "        n\n"
            "    }\n\n"
            "    #[inline(always)]\n"
            "    pub fn scan_until_2(bytes: &[u8], start: usize, b1: u8, b2: u8) -> usize {\n"
            "        let n = bytes.len();\n"
            "        let mut p = start;\n"
            "        while p < n {\n"
            "            let b = bytes[p];\n"
            "            if b == b1 || b == b2 { return p; }\n"
            "            p += 1;\n"
            "        }\n"
            "        n\n"
            "    }\n\n"
            "    #[inline(always)]\n"
            "    pub fn scan_until_3(bytes: &[u8], start: usize, b1: u8, b2: u8, b3: u8) -> usize {\n"
            "        let n = bytes.len();\n"
            "        let mut p = start;\n"
            "        while p < n {\n"
            "            let b = bytes[p];\n"
            "            if b == b1 || b == b2 || b == b3 { return p; }\n"
            "            p += 1;\n"
            "        }\n"
            "        n\n"
            "    }\n"
            "}\n\n");
    /* Walk all DFA states across all state groups; classify each
    ** for the "scan-until-exit" fast path; emit a per-state trait
    ** method whose AvxScanner / NeonScanner / ScalarScanner impls
    ** call the underlying scan_avx2 / scan_neon / scan_scalar
    ** scan_until_<n> with the byte literals BAKED IN to each impl
    ** body.  This is the v0.8.9 architectural fix: const-baking
    ** the exit-byte values inside the impl ensures LLVM sees them
    ** as compile-time constants when monomorphising tokenize_impl
    ** through fast_path -> S::scan_<NAME>_<S> -> scan_avx2::scan_until_<n>.
    ** Without this, the byte values were passed through as runtime
    ** u8 args and LLVM didn't const-propagate them through the
    ** indirection chain, costing ~5-7%% on the JSON benchmark. */
    fprintf(out,
            "// Scanner trait: per-fast-path-state methods.  Each method's\n"
            "// AvxScanner / NeonScanner / ScalarScanner impl bakes in the\n"
            "// exit-byte literals from the DFA, so LLVM treats them as\n"
            "// compile-time constants when monomorphising the lexer body.\n\n"
            "trait Scanner {\n");
    /* Forward declarations of the per-state methods. */
    for (int g = 0; g < compiled->n_states; g++) {
        const LimeLexCompiledState *cs = &compiled->states[g];
        if (!cs->dfa) continue;
        for (int s = 0; s < cs->dfa->n_states; s++) {
            const int *tr = cs->dfa->states[s].trans;
            int self_count = 0;
            int exit_set[8];
            int n_exit = 0;
            int has_too_many_exit = 0;
            for (int b = 0; b < 256; b++) {
                int t = tr[b];
                if (t == s) {
                    self_count++;
                } else if (t >= 0) {
                    int found = 0;
                    for (int i = 0; i < n_exit; i++)
                        if (exit_set[i] == b) { found = 1; break; }
                    if (!found) {
                        if (n_exit >= 8) has_too_many_exit = 1;
                        else exit_set[n_exit++] = b;
                    }
                }
            }
            if (has_too_many_exit || self_count < 240 || n_exit == 0) continue;
            fprintf(out,
                    "    fn scan_%s_%d(bytes: &[u8], p: usize) -> usize;\n",
                    cs->state_name, s);
        }
    }
    /* Generic scan_until_<n> trait methods for use by per-token DFA's
    ** per-rule fast-path scans (when --per-token-dfa is also on). */
    fprintf(out,
            "    fn scan_until_1(bytes: &[u8], p: usize, b1: u8) -> usize;\n"
            "    fn scan_until_2(bytes: &[u8], p: usize, b1: u8, b2: u8) -> usize;\n"
            "    fn scan_until_3(bytes: &[u8], p: usize, b1: u8, b2: u8, b3: u8) -> usize;\n");
    fprintf(out, "}\n\n");

    /* Per-arch impls.  AvxScanner (cfg x86_64), NeonScanner (cfg
    ** aarch64), ScalarScanner (always).  Each method body has the
    ** byte literals baked in. */
    const struct {
        const char *cfg;
        const char *struct_name;
        const char *body_prefix;
        const char *body_suffix;
        const char *mod_name;
    } impls[] = {
        { "#[cfg(target_arch = \"x86_64\")]\n", "AvxScanner",
          "        unsafe { scan_avx2::", " }\n", "scan_avx2" },
        { "#[cfg(target_arch = \"aarch64\")]\n", "NeonScanner",
          "        unsafe { scan_neon::", " }\n", "scan_neon" },
        { "", "ScalarScanner",
          "        scan_scalar::", "\n", "scan_scalar" },
    };
    for (int impl_i = 0; impl_i < 3; impl_i++) {
        if (impls[impl_i].cfg[0]) fprintf(out, "%s", impls[impl_i].cfg);
        fprintf(out, "struct %s;\n", impls[impl_i].struct_name);
        if (impls[impl_i].cfg[0]) fprintf(out, "%s", impls[impl_i].cfg);
        fprintf(out, "impl Scanner for %s {\n", impls[impl_i].struct_name);
        for (int g = 0; g < compiled->n_states; g++) {
            const LimeLexCompiledState *cs = &compiled->states[g];
            if (!cs->dfa) continue;
            for (int s = 0; s < cs->dfa->n_states; s++) {
                const int *tr = cs->dfa->states[s].trans;
                int self_count = 0;
                int exit_set[8];
                int n_exit = 0;
                int has_too_many_exit = 0;
                for (int b = 0; b < 256; b++) {
                    int t = tr[b];
                    if (t == s) {
                        self_count++;
                    } else if (t >= 0) {
                        int found = 0;
                        for (int i = 0; i < n_exit; i++)
                            if (exit_set[i] == b) { found = 1; break; }
                        if (!found) {
                            if (n_exit >= 8) has_too_many_exit = 1;
                            else exit_set[n_exit++] = b;
                        }
                    }
                }
                if (has_too_many_exit || self_count < 240 || n_exit == 0) continue;
                int n = n_exit;
                int b1 = exit_set[0];
                int b2 = (n >= 2) ? exit_set[1] : 0;
                int b3 = (n >= 3) ? exit_set[2] : 0;
                fprintf(out,
                        "    #[inline(always)]\n"
                        "    fn scan_%s_%d(bytes: &[u8], p: usize) -> usize {\n",
                        cs->state_name, s);
                if (n == 1) {
                    fprintf(out, "%sscan_until_1(bytes, p, %d)%s",
                            impls[impl_i].body_prefix, b1, impls[impl_i].body_suffix);
                } else if (n == 2) {
                    fprintf(out, "%sscan_until_2(bytes, p, %d, %d)%s",
                            impls[impl_i].body_prefix, b1, b2, impls[impl_i].body_suffix);
                } else {
                    fprintf(out, "%sscan_until_3(bytes, p, %d, %d, %d)%s",
                            impls[impl_i].body_prefix, b1, b2, b3, impls[impl_i].body_suffix);
                }
                fprintf(out, "    }\n");
            }
        }
        /* Emit generic scan_until_<n> trait methods, delegating to
        ** the underlying scan module (avx2/neon/scalar). */
        fprintf(out,
                "    #[inline(always)]\n"
                "    fn scan_until_1(bytes: &[u8], p: usize, b1: u8) -> usize {\n"
                "%sscan_until_1(bytes, p, b1)%s"
                "    }\n"
                "    #[inline(always)]\n"
                "    fn scan_until_2(bytes: &[u8], p: usize, b1: u8, b2: u8) -> usize {\n"
                "%sscan_until_2(bytes, p, b1, b2)%s"
                "    }\n"
                "    #[inline(always)]\n"
                "    fn scan_until_3(bytes: &[u8], p: usize, b1: u8, b2: u8, b3: u8) -> usize {\n"
                "%sscan_until_3(bytes, p, b1, b2, b3)%s"
                "    }\n",
                impls[impl_i].body_prefix, impls[impl_i].body_suffix,
                impls[impl_i].body_prefix, impls[impl_i].body_suffix,
                impls[impl_i].body_prefix, impls[impl_i].body_suffix);
        fprintf(out, "}\n\n");
    }
}

/*
** Per-token DFA emission (--per-token-dfa).  For each non-EOF rule
** in each state group, emits the per-rule minimised DFA tables and
** a walker function that runs the per-rule DFA from start.  Also
** emits a 256-entry leading-byte dispatch table per state group:
**
**   dispatch[byte] >= 0  -> unique rule index in state group
**   dispatch[byte] < 0   -> ambiguous OR no rule; fall back to
**                           unified DFA (or report error if no rule)
**
** Runtime tokenize() in --per-token-dfa mode peeks the leading
** byte, dispatches to the per-rule walker if unambiguous, falls
** through to the unified DFA path otherwise.  Per-rule DFAs are
** typically 2-10 states (vs 30-100 for the unified DFA) so the
** common-case walk is much faster.
*/
static void emit_per_token_tables(FILE *out, const char *prefix,
                                  const LimeLexCompiled *compiled) {
    fprintf(out,
            "// =====================================================================\n"
            "// Per-token DFA dispatch (--per-token-dfa)\n"
            "// =====================================================================\n\n"
            "// Smart leading-byte dispatch.  For each unambiguous leading byte:\n"
            "//\n"
            "//   single-byte rule (e.g. JSON '{', '}'): direct emit, no DFA walk\n"
            "//   fixed-string rule (e.g. \"true\", \"false\"): byte-compare\n"
            "//   general DFA rule (e.g. STR, NUM): walk per-rule DFA inline\n"
            "//\n"
            "// For ambiguous leading bytes or no-rule bytes the dispatcher\n"
            "// returns (0, -1) and the caller falls back to the unified DFA.\n\n");
    /* Emit per-rule DFA tables ONLY for general (non-single-byte,
    ** non-fixed-string) rules.  Single-byte and fixed-string rules
    ** emit direct dispatch without DFA tables. */
    for (int g = 0; g < compiled->n_states; g++) {
        const LimeLexCompiledState *cs = &compiled->states[g];
        if (!cs->per_rule_dfas) continue;
        for (int r = 0; r < cs->n_per_rule_dfas; r++) {
            const LimeDfa *dfa = cs->per_rule_dfas[r];
            if (!dfa) continue;
            if (lime_lex_dfa_single_byte(dfa) >= 0) continue;
            unsigned char fs[256]; int fs_len = 0;
            if (lime_lex_dfa_fixed_string(dfa, fs, &fs_len)) continue;
            /* General rule: emit DFA tables. */
            fprintf(out, "static %s_R%d_TRANS_%s: &[i16] = &[\n",
                    prefix, r, cs->state_name);
            for (int s = 0; s < dfa->n_states; s++) {
                fprintf(out, "    ");
                for (int b = 0; b < 256; b++) {
                    fprintf(out, "%d,", dfa->states[s].trans[b]);
                    if ((b & 31) == 31) fprintf(out, "\n    ");
                }
                fprintf(out, "\n");
            }
            fprintf(out, "];\n\n");
            fprintf(out, "static %s_R%d_ACCEPT_%s: &[u8] = &[",
                    prefix, r, cs->state_name);
            for (int s = 0; s < dfa->n_states; s++) {
                fprintf(out, "%d,", dfa->states[s].is_accept ? 1 : 0);
            }
            fprintf(out, "];\n\n");
            fprintf(out, "const %s_R%d_START_%s: u16 = %d;\n\n",
                    prefix, r, cs->state_name, dfa->start);
        }
    }

    /* For each state group, emit a match_<NAME>(bytes, p) function:
    ** giant match-on-leading-byte.  Each arm contains the inline
    ** dispatch logic for whichever rule the byte uniquely starts.
    ** Returns (consumed_bytes, global_rule_id_or_minus_one). */
    for (int g = 0; g < compiled->n_states; g++) {
        const LimeLexCompiledState *cs = &compiled->states[g];
        if (!cs->per_rule_dfas) continue;
        /* Build per-byte assignment: byte -> (rule_idx_in_state, kind).
        ** kind: 0=single-byte 1=fixed-string 2=general -1=ambig/none */
        int byte_rule[256];
        for (int b = 0; b < 256; b++) byte_rule[b] = -1;
        int *kind = calloc(cs->n_per_rule_dfas, sizeof(int));
        unsigned char (*fixed_str)[256] = calloc(cs->n_per_rule_dfas, sizeof(*fixed_str));
        int *fixed_len = calloc(cs->n_per_rule_dfas, sizeof(int));
        for (int r = 0; r < cs->n_per_rule_dfas; r++) {
            const LimeDfa *dfa = cs->per_rule_dfas[r];
            if (!dfa) { kind[r] = -1; continue; }
            int sb = lime_lex_dfa_single_byte(dfa);
            if (sb >= 0) {
                kind[r] = 0;
                if (byte_rule[sb] == -1) byte_rule[sb] = r;
                else byte_rule[sb] = -2;
                continue;
            }
            int fs_l = 0;
            if (lime_lex_dfa_fixed_string(dfa, fixed_str[r], &fs_l)) {
                kind[r] = 1;
                fixed_len[r] = fs_l;
                int b = fixed_str[r][0];
                if (byte_rule[b] == -1) byte_rule[b] = r;
                else byte_rule[b] = -2;
                continue;
            }
            kind[r] = 2;
            unsigned char bs[256];
            lime_lex_dfa_leading_bytes(dfa, bs);
            for (int b = 0; b < 256; b++) {
                if (!bs[b]) continue;
                if (byte_rule[b] == -1) byte_rule[b] = r;
                else byte_rule[b] = -2;
            }
        }
        /* Emit the match function.  When --rustlex-simd is also
        ** on, make per_token_match generic over Scanner so the
        ** per-rule fast-path scans can use the AVX2/NEON helpers
        ** instead of the scalar while loop.  Without --rustlex-simd,
        ** scalar tight loops still get auto-vectorised by LLVM. */
        if (g_lime_rustlex_simd_flag) {
            fprintf(out,
                    "/// Per-token match for state group %s.  Returns\n"
                    "/// (consumed_bytes, global_rule_id) on match, (0, -1) on\n"
                    "/// fallback (caller runs the unified DFA).\n"
                    "#[inline(always)]\n"
                    "fn per_token_match_%s<S: Scanner>(bytes: &[u8], p: usize) -> (usize, i16) {\n",
                    cs->state_name, cs->state_name);
        } else {
            fprintf(out,
                    "/// Per-token match for state group %s.  Returns\n"
                    "/// (consumed_bytes, global_rule_id) on match, (0, -1) on\n"
                    "/// fallback (caller runs the unified DFA).\n"
                    "#[inline(always)]\n"
                    "fn per_token_match_%s(bytes: &[u8], p: usize) -> (usize, i16) {\n",
                    cs->state_name, cs->state_name);
        }
        fprintf(out, "    if p >= bytes.len() { return (0, -1); }\n");
        /* Lead byte read: the preceding `if p >= bytes.len() { return ... }`
        ** dominates this access, so LLVM elides the bounds check on `bytes[p]`
        ** equivalently to the unsafe form -- safe emit is provably free here. */
        if (g_lime_lex_safe_flag) {
            fprintf(out, "    let lead = bytes[p];\n");
        } else {
            fprintf(out, "    let lead = unsafe { *bytes.get_unchecked(p) };\n");
        }
        fprintf(out, "    match lead {\n");
        /* Group bytes by rule for cleaner emit (e.g. b'0'..=b'9' all
        ** go to one arm).  We emit per-rule arms. */
        char emitted_for_rule[1024] = {0};
        for (int b = 0; b < 256; b++) {
            int r = byte_rule[b];
            if (r < 0) continue;
            if (r >= 1024 || emitted_for_rule[r]) continue;
            emitted_for_rule[r] = 1;
            int gid = cs->rule_indices ? cs->rule_indices[r] : r;
            if (kind[r] == 0) {
                /* Single-byte rule: collect all bytes that map here
                ** (usually 1, but a single-byte DFA accepts only one
                ** byte so byte_rule has only one entry per single-byte
                ** rule).  Emit `b'X' => (1, gid)`. */
                fprintf(out, "        %d => (1, %d),\n", b, gid);
            } else if (kind[r] == 1) {
                /* Fixed-string rule: byte-compare. */
                fprintf(out, "        %d => {\n", (int)fixed_str[r][0]);
                fprintf(out, "            if p + %d <= bytes.len() && &bytes[p..p+%d] == b\"",
                        fixed_len[r], fixed_len[r]);
                for (int j = 0; j < fixed_len[r]; j++) {
                    unsigned char c = fixed_str[r][j];
                    if (c == '\\') fprintf(out, "\\\\");
                    else if (c == '"') fprintf(out, "\\\"");
                    else if (c >= 32 && c < 127) fputc(c, out);
                    else fprintf(out, "\\x%02x", c);
                }
                fprintf(out, "\" {\n");
                fprintf(out, "                (%d, %d)\n", fixed_len[r], gid);
                fprintf(out, "            } else { (0, -1) }\n");
                fprintf(out, "        },\n");
            } else {
                /* General DFA rule: collect all leading bytes, emit
                ** one arm with a pattern OR-ing them, then walk the
                ** per-rule DFA inline.  When a per-rule DFA state is
                ** self-loop-dominant (>=240/256 self-loop bytes, exit
                ** set <=3 distinct bytes -- same threshold as the
                ** unified-DFA fast path), emit an inline scan-until-
                ** exit helper that LLVM auto-vectorises into PCMPEQB
                ** + PMOVMSKB.  Without this, per-rule DFA walks lack
                ** the SIMD treatment the unified DFA gets and lose
                ** ~70%% throughput on prose-heavy content.  This is
                ** Experiment 3 of the per-token DFA work. */
                const LimeDfa *rdfa = cs->per_rule_dfas[r];
                /* Pre-emit per-state fast-path scan helpers as
                ** standalone functions.  These are called from the
                ** walk loop below.  We use simple scalar tight
                ** loops; LLVM auto-vectorises them. */
                int *fp_kind = (int *)calloc(rdfa->n_states, sizeof(int));
                int (*fp_exit)[3] = (int (*)[3])calloc(rdfa->n_states, sizeof(*fp_exit));
                int *fp_nexit = (int *)calloc(rdfa->n_states, sizeof(int));
                /* Pattern B (scan-while-in-range): for states whose
                ** self-loop set is a small contiguous byte range
                ** (e.g. digits '0'..'9' = 10 bytes), emit
                ** while bytes[q] in [lo,hi].  Helps number-heavy
                ** workloads (telemetry, JSON metric values) where
                ** Pattern A's self_count >= 240 threshold doesn't
                ** fire.  v0.8.4 tried this and reverted because
                ** typical short whitespace runs (1-2 bytes) didn't
                ** repay the per-call overhead; the per-rule DFA
                ** architecture lets us apply Pattern B surgically
                ** only to states where it pays. */
                int *fp_lo = (int *)calloc(rdfa->n_states, sizeof(int));
                int *fp_hi = (int *)calloc(rdfa->n_states, sizeof(int));
                if (fp_kind && fp_exit && fp_nexit && fp_lo && fp_hi) {
                    for (int s = 0; s < rdfa->n_states; s++) {
                        const int *tr = rdfa->states[s].trans;
                        int self_count = 0;
                        int exit_set[8]; int n_exit = 0; int too_many = 0;
                        for (int b = 0; b < 256; b++) {
                            int t = tr[b];
                            if (t == s) self_count++;
                            else if (t >= 0) {
                                int found = 0;
                                for (int j = 0; j < n_exit; j++)
                                    if (exit_set[j] == b) { found = 1; break; }
                                if (!found) {
                                    if (n_exit >= 3) too_many = 1;
                                    else exit_set[n_exit++] = b;
                                }
                            }
                        }
                        if (!too_many && self_count >= 240 && n_exit > 0) {
                            fp_kind[s] = 1;
                            fp_nexit[s] = n_exit;
                            for (int j = 0; j < n_exit; j++) fp_exit[s][j] = exit_set[j];
                        } else if (n_exit > 0 && self_count >= 4 && self_count <= 16) {
                            /* Pattern B candidate: check the self-loop
                            ** set forms a contiguous byte range. */
                            int self_lo = -1, self_hi = -1;
                            int contiguous = 1;
                            int seen = 0;
                            for (int b = 0; b < 256; b++) {
                                if (tr[b] == s) {
                                    if (self_lo < 0) self_lo = b;
                                    if (seen && b != self_hi + 1) { contiguous = 0; break; }
                                    self_hi = b;
                                    seen = 1;
                                }
                            }
                            if (contiguous && self_lo >= 0 && self_hi - self_lo + 1 == self_count) {
                                fp_kind[s] = 2;
                                fp_lo[s] = self_lo;
                                fp_hi[s] = self_hi;
                            }
                        }
                    }
                }
                /* Emit one scan helper per fast-path state. */
                for (int s = 0; s < rdfa->n_states; s++) {
                    if (!fp_kind || fp_kind[s] != 1) continue;
                    fprintf(out,
                            "// (per-rule fast-path helper hoisted to module scope)\n");
                    /* Helper definitions are emitted at module scope
                    ** in a separate pass; the walk below references
                    ** them by name as scan_self_loop_R<r>_S<s>. */
                }
                unsigned char bs[256];
                lime_lex_dfa_leading_bytes(cs->per_rule_dfas[r], bs);
                int first = 1;
                fprintf(out, "        ");
                for (int b2 = 0; b2 < 256; b2++) {
                    if (!bs[b2]) continue;
                    if (byte_rule[b2] != r) continue;  /* not unique to r */
                    if (!first) fprintf(out, " | ");
                    fprintf(out, "%d", b2);
                    first = 0;
                }
                fprintf(out, " => {\n");
                fprintf(out,
                        "            let trans = %s_R%d_TRANS_%s;\n"
                        "            let accept = %s_R%d_ACCEPT_%s;\n"
                        "            let mut state: u16 = %s_R%d_START_%s;\n"
                        "            let mut last_accept_pos: usize = 0;\n"
                        "            let n = bytes.len();\n"
                        "            let mut q = p;\n",
                        prefix, r, cs->state_name,
                        prefix, r, cs->state_name,
                        prefix, r, cs->state_name);
                /* v0.9.3 safe-emit: when g_lime_lex_safe_flag is set
                ** (default), drop the `unsafe { ... }` wrapper around
                ** this DFA walk and use safe `[]` indexing.  Categories
                ** 2 (SIMD intrinsics) and 3 (#[target_feature]) are
                ** unaffected -- the AVX2/NEON helpers and the
                ** tokenize_avx2 / tokenize_neon dispatch sites stay
                ** unsafe by Rust language rules.  See unsafe-audit.md
                ** section 2.2 for the full transformation rationale. */
                if (!g_lime_lex_safe_flag) {
                    fprintf(out,
                            "            unsafe {\n"
                            "                if *accept.get_unchecked(state as usize) != 0 {\n"
                            "                    last_accept_pos = q;\n"
                            "                }\n"
                            "                while q < n {\n");
                } else {
                    fprintf(out,
                            "                if accept[state as usize] != 0 {\n"
                            "                    last_accept_pos = q;\n"
                            "                }\n"
                            "                while q < n {\n");
                }
                /* Inline fast-path scan dispatch by state. */
                int any_fp = 0;
                for (int s = 0; s < rdfa->n_states; s++) {
                    if (fp_kind && (fp_kind[s] == 1 || fp_kind[s] == 2)) { any_fp = 1; break; }
                }
                if (any_fp) {
                    fprintf(out,
                            "                    // Per-rule fast-path scan (Pattern A: until-exit, Pattern B: while-in-range).\n"
                            "                    let new_q = match state {\n");
                    for (int s = 0; s < rdfa->n_states; s++) {
                        if (!fp_kind) continue;
                        if (fp_kind[s] == 1) {
                            int n = fp_nexit[s];
                            if (g_lime_rustlex_simd_flag) {
                                if (n == 1) {
                                    fprintf(out,
                                            "                        %d => S::scan_until_1(bytes, q, %d),\n",
                                            s, fp_exit[s][0]);
                                } else if (n == 2) {
                                    fprintf(out,
                                            "                        %d => S::scan_until_2(bytes, q, %d, %d),\n",
                                            s, fp_exit[s][0], fp_exit[s][1]);
                                } else {
                                    fprintf(out,
                                            "                        %d => S::scan_until_3(bytes, q, %d, %d, %d),\n",
                                            s, fp_exit[s][0], fp_exit[s][1], fp_exit[s][2]);
                                }
                            } else {
                                if (n == 1) {
                                    fprintf(out,
                                            g_lime_lex_safe_flag
                                            ? "                        %d => { let mut x = q; while x < n { let bb = bytes[x]; if bb == %d { break; } x += 1; } x },\n"
                                            : "                        %d => { let mut x = q; while x < n { let bb = *bytes.get_unchecked(x); if bb == %d { break; } x += 1; } x },\n",
                                            s, fp_exit[s][0]);
                                } else if (n == 2) {
                                    fprintf(out,
                                            g_lime_lex_safe_flag
                                            ? "                        %d => { let mut x = q; while x < n { let bb = bytes[x]; if bb == %d || bb == %d { break; } x += 1; } x },\n"
                                            : "                        %d => { let mut x = q; while x < n { let bb = *bytes.get_unchecked(x); if bb == %d || bb == %d { break; } x += 1; } x },\n",
                                            s, fp_exit[s][0], fp_exit[s][1]);
                                } else {
                                    fprintf(out,
                                            g_lime_lex_safe_flag
                                            ? "                        %d => { let mut x = q; while x < n { let bb = bytes[x]; if bb == %d || bb == %d || bb == %d { break; } x += 1; } x },\n"
                                            : "                        %d => { let mut x = q; while x < n { let bb = *bytes.get_unchecked(x); if bb == %d || bb == %d || bb == %d { break; } x += 1; } x },\n",
                                            s, fp_exit[s][0], fp_exit[s][1], fp_exit[s][2]);
                                }
                            }
                        } else if (fp_kind[s] == 2) {
                            /* Pattern B: scan-while-in-range.  LLVM
                            ** auto-vectorises this tight loop into
                            ** two vector compares + and + movemask
                            ** on x86_64 / ARM64 with the standard
                            ** loop-vectoriser pass.  Used for digit
                            ** runs in number tokens, identifier
                            ** continuations, etc. */
                            fprintf(out,
                                    g_lime_lex_safe_flag
                                    ? "                        %d => { let mut x = q; while x < n { let bb = bytes[x]; if bb < %d || bb > %d { break; } x += 1; } x },\n"
                                    : "                        %d => { let mut x = q; while x < n { let bb = *bytes.get_unchecked(x); if bb < %d || bb > %d { break; } x += 1; } x },\n",
                                    s, fp_lo[s], fp_hi[s]);
                        }
                    }
                    fprintf(out,
                            g_lime_lex_safe_flag
                            ? "                        _ => q,\n"
                              "                    };\n"
                              "                    if new_q > q {\n"
                              "                        if accept[state as usize] != 0 {\n"
                              "                            last_accept_pos = new_q;\n"
                              "                        }\n"
                              "                        q = new_q;\n"
                              "                        if q >= n { break; }\n"
                              "                    }\n"
                            : "                        _ => q,\n"
                              "                    };\n"
                              "                    if new_q > q {\n"
                              "                        if *accept.get_unchecked(state as usize) != 0 {\n"
                              "                            last_accept_pos = new_q;\n"
                              "                        }\n"
                              "                        q = new_q;\n"
                              "                        if q >= n { break; }\n"
                              "                    }\n");
                }
                if (g_lime_lex_safe_flag) {
                    fprintf(out,
                            "                    let b = bytes[q];\n"
                            "                    let off = (state as usize) * 256 + b as usize;\n"
                            "                    let next = trans[off];\n"
                            "                    if next < 0 { break; }\n"
                            "                    state = next as u16;\n"
                            "                    q += 1;\n"
                            "                    if accept[state as usize] != 0 {\n"
                            "                        last_accept_pos = q;\n"
                            "                    }\n"
                            "                }\n"
                            "            if last_accept_pos > p {\n"
                            "                (last_accept_pos - p, %d)\n"
                            "            } else { (0, -1) }\n"
                            "        },\n",
                            gid);
                } else {
                    fprintf(out,
                            "                    let b = *bytes.get_unchecked(q);\n"
                            "                    let off = (state as usize) * 256 + b as usize;\n"
                            "                    let next = *trans.get_unchecked(off);\n"
                            "                    if next < 0 { break; }\n"
                            "                    state = next as u16;\n"
                            "                    q += 1;\n"
                            "                    if *accept.get_unchecked(state as usize) != 0 {\n"
                            "                        last_accept_pos = q;\n"
                            "                    }\n"
                            "                }\n"
                            "            }\n"
                            "            if last_accept_pos > p {\n"
                            "                (last_accept_pos - p, %d)\n"
                            "            } else { (0, -1) }\n"
                            "        },\n",
                            gid);
                }
                free(fp_kind);
                free(fp_exit);
                free(fp_nexit);
                free(fp_lo);
                free(fp_hi);
            }
        }
        fprintf(out, "        _ => (0, -1),\n");
        fprintf(out, "    }\n}\n\n");
        free(kind);
        free(fixed_str);
        free(fixed_len);
    }

    /* Per-state-group dispatcher: routes self.state to the right
    ** per_token_match_<NAME>.  Generic over Scanner when --rustlex-simd
    ** is on (so the per-rule fast-path scans use AVX2/NEON). */
    if (g_lime_rustlex_simd_flag) {
        fprintf(out,
                "#[inline(always)]\n"
                "fn per_token_match<S: Scanner>(s: StateId, bytes: &[u8], p: usize) -> (usize, i16) {\n"
                "    match s {\n");
        for (int g = 0; g < compiled->n_states; g++) {
            const LimeLexCompiledState *cs = &compiled->states[g];
            if (!cs->per_rule_dfas) continue;
            fprintf(out, "        %d => per_token_match_%s::<S>(bytes, p),\n", g, cs->state_name);
        }
    } else {
        fprintf(out,
                "#[inline(always)]\n"
                "fn per_token_match(s: StateId, bytes: &[u8], p: usize) -> (usize, i16) {\n"
                "    match s {\n");
        for (int g = 0; g < compiled->n_states; g++) {
            const LimeLexCompiledState *cs = &compiled->states[g];
            if (!cs->per_rule_dfas) continue;
            fprintf(out, "        %d => per_token_match_%s(bytes, p),\n", g, cs->state_name);
        }
    }
    fprintf(out, "        _ => (0, -1),\n");
    fprintf(out, "    }\n}\n\n");
}


/*
** Emit the public Token type + Lexer struct + tokenize() runtime.
**
** The runtime is a longest-match DFA simulator: walks states for
** each input position, tracks the last accept, returns a token
** when no further transition is possible.
*/
static void emit_lexer_runtime(FILE *out, const char *prefix,
                               const LimeLexCompiled *compiled) {
    /* Emit shared SIMD helpers up front when --rustlex-simd is set. */
    if (g_lime_rustlex_simd_flag) {
        emit_simd_helpers(out, compiled);
    }
    if (g_lime_per_token_dfa_flag) {
        emit_per_token_tables(out, prefix, compiled);
    }
    emit_section(out, "Tokenizer runtime");

    fprintf(out,
            "/// One token from the input stream.\n"
            "#[derive(Debug, Clone, PartialEq, Eq)]\n"
            "pub struct Token {\n"
            "    /// The rule id that matched.  Compare to %s_RULE_*\n"
            "    /// constants to identify which rule fired.\n"
            "    pub rule_id: u16,\n"
            "    /// Byte offset of the matched text in the input.\n"
            "    pub start: usize,\n"
            "    /// Length of the matched text in bytes.\n"
            "    pub len: usize,\n"
            "    /// 1-based line number of the first byte.\n"
            "    pub line: u32,\n"
            "    /// 1-based column number of the first byte.\n"
            "    pub column: u32,\n"
            "}\n\n",
            prefix);

    fprintf(out,
            "/// Errors returned by the lexer.\n"
            "#[derive(Debug, Clone, PartialEq, Eq)]\n"
            "pub enum LexError {\n"
            "    /// No matching rule at the given offset.  byte is the\n"
            "    /// offending byte; offset is its index.\n"
            "    NoMatch { offset: usize, byte: u8 },\n"
            "    /// Requested state name doesn't exist.\n"
            "    UnknownState,\n"
            "}\n\n");

    fprintf(out,
            "/// Lexer state identifier.  Use the START_STATE_* constants.\n"
            "pub type StateId = u16;\n\n");

    /* Emit a per-state-name -> step-function dispatch.  The
    ** dispatcher inlines: compiler will collapse the match to a
    ** direct call when the StateId is statically known. */
    fprintf(out, "/// Per-named-state DFA dispatch.\n");
    fprintf(out, "/// Calls into the per-state-group step_* function\n");
    fprintf(out, "/// generated by emit_state_dfa (a giant Rust\n");
    fprintf(out, "/// match expression that LLVM lowers to a jump table).\n");
    fprintf(out,
            "#[inline(always)]\n"
            "fn dfa_step_for_state(s: StateId, state: u16, b: u8) -> i16 {\n");
    fprintf(out, "    match s {\n");
    char *upper_prefix_str = upper_dup_local(prefix);
    if (!upper_prefix_str) return;
    for (int i = 0; i < compiled->n_states; i++) {
        const char *sname = compiled->states[i].state_name;
        fprintf(out,
                "        %d => step_%s(state, b),\n",
                i, sname);
    }
    fprintf(out, "        _ => -1,\n");
    fprintf(out, "    }\n");
    fprintf(out, "}\n\n");

    /* Fast-path dispatcher: routes to the per-state-group
    ** fast_path_<NAME> helper which dispatches further on the
    ** active DFA state.  Returns the (possibly-advanced) byte
    ** position after a SIMD-friendly scan over self-loop runs.
    ** Under --rustlex-simd the dispatcher is generic over the
    ** Scanner trait so AVX2 / scalar specialisation propagates
    ** from the tokenize() entry point through every fast-path
    ** call site without an inlining barrier. */
    fprintf(out, "/// Fast-path dispatcher: state group + DFA state\n");
    fprintf(out, "/// -> advanced byte position after SIMD scan.\n");
    if (g_lime_rustlex_simd_flag) {
        fprintf(out,
                "#[inline(always)]\n"
                "fn fast_path_for_state_g<S: Scanner>(s: StateId, state: u16, bytes: &[u8], p: usize) -> usize {\n");
        fprintf(out, "    match s {\n");
        for (int i = 0; i < compiled->n_states; i++) {
            const char *sname = compiled->states[i].state_name;
            fprintf(out,
                    "        %d => fast_path_%s_g::<S>(state, bytes, p),\n",
                    i, sname);
        }
        fprintf(out, "        _ => p,\n");
        fprintf(out, "    }\n");
        fprintf(out, "}\n\n");
    } else {
        fprintf(out,
                "#[inline(always)]\n"
                "fn fast_path_for_state(s: StateId, state: u16, bytes: &[u8], p: usize) -> usize {\n");
        fprintf(out, "    match s {\n");
        for (int i = 0; i < compiled->n_states; i++) {
            const char *sname = compiled->states[i].state_name;
            fprintf(out,
                    "        %d => fast_path_%s(state, bytes, p),\n",
                    i, sname);
        }
        fprintf(out, "        _ => p,\n");
        fprintf(out, "    }\n");
        fprintf(out, "}\n\n");
    }

    fprintf(out,
            "#[inline(always)]\n"
            "fn dfa_accept_for_state(s: StateId) -> &'static [i16] {\n");
    fprintf(out, "    match s {\n");
    for (int i = 0; i < compiled->n_states; i++) {
        char *us = upper_dup_local(compiled->states[i].state_name);
        if (!us) continue;
        fprintf(out,
                "        %d => %s_%s_ACCEPT,\n",
                i, upper_prefix_str, us);
        free(us);
    }
    fprintf(out, "        _ => &[],\n");
    fprintf(out, "    }\n");
    fprintf(out, "}\n\n");

    fprintf(out,
            "#[inline(always)]\n"
            "fn dfa_start_for_state(s: StateId) -> u16 {\n");
    fprintf(out, "    match s {\n");
    for (int i = 0; i < compiled->n_states; i++) {
        char *us = upper_dup_local(compiled->states[i].state_name);
        if (!us) continue;
        fprintf(out,
                "        %d => %s_%s_START,\n",
                i, upper_prefix_str, us);
        free(us);
    }
    fprintf(out, "        _ => 0,\n");
    fprintf(out, "    }\n");
    fprintf(out, "}\n\n");

    /* Public state-name constants to make Lexer::tokenize_in_state
    ** ergonomic. */
    for (int i = 0; i < compiled->n_states; i++) {
        char *us = upper_dup_local(compiled->states[i].state_name);
        if (!us) continue;
        fprintf(out, "pub const STATE_%s: StateId = %d;\n", us, i);
        free(us);
    }
    fprintf(out, "\n");

    /* The Lexer itself */
    fprintf(out,
            "/// Lexer.  Stateless aside from the active state name; the\n"
            "/// caller drives tokenize() with a complete input string and\n"
            "/// receives a Vec<Token>.\n"
            "pub struct Lexer {\n"
            "    state: StateId,\n"
            "}\n\n");

    fprintf(out,
            "impl Lexer {\n"
            "    /// Construct a lexer in the INITIAL state (state 0).\n"
            "    pub fn new() -> Self { Self { state: 0 } }\n\n"
            "    /// Set the active state.  Use STATE_* constants.\n"
            "    pub fn set_state(&mut self, s: StateId) { self.state = s; }\n\n"
            "    /// Get the active state.\n"
            "    pub fn state(&self) -> StateId { self.state }\n\n"
            "    /// Tokenise an input string.  Returns the full token stream\n"
            "    /// when the input is fully consumed; returns Err with the\n"
            "    /// offending offset on no-match.\n"
            "    ///\n"
            "    /// Performance: O(input.len()) with a small per-byte cost\n"
            "    /// (one DFA transition + bookkeeping).  No allocations\n"
            "    /// per token beyond the result Vec.\n");
    if (g_lime_rustlex_simd_flag) {
        /* Multiversion-at-tokenize wrapper.  Detects AVX2 once at
        ** entry; the AVX2 dispatch carries #[target_feature(...)] so
        ** the entire DFA loop monomorphises with AvxScanner whose
        ** intrinsics inline directly into the body.  ScalarScanner
        ** is the fallback. */
        fprintf(out,
            "    pub fn tokenize(&mut self, input: &str) -> Result<Vec<Token>, LexError> {\n"
            "        let bytes = input.as_bytes();\n"
            "        #[cfg(target_arch = \"x86_64\")]\n"
            "        {\n"
            "            if std::arch::is_x86_feature_detected!(\"avx2\") {\n"
            "                return unsafe { self.tokenize_avx2(bytes) };\n"
            "            }\n"
            "        }\n"
            "        #[cfg(target_arch = \"aarch64\")]\n"
            "        {\n"
            "            return unsafe { self.tokenize_neon(bytes) };\n"
            "        }\n"
            "        #[allow(unreachable_code)]\n"
            "        self.tokenize_scalar(bytes)\n"
            "    }\n\n"
            "    #[cfg(target_arch = \"x86_64\")]\n"
            "    #[target_feature(enable = \"avx2,bmi2\")]\n"
            "    unsafe fn tokenize_avx2(&mut self, bytes: &[u8]) -> Result<Vec<Token>, LexError> {\n"
            "        self.tokenize_impl::<AvxScanner>(bytes)\n"
            "    }\n\n"
            "    #[cfg(target_arch = \"aarch64\")]\n"
            "    unsafe fn tokenize_neon(&mut self, bytes: &[u8]) -> Result<Vec<Token>, LexError> {\n"
            "        self.tokenize_impl::<NeonScanner>(bytes)\n"
            "    }\n\n"
            "    fn tokenize_scalar(&mut self, bytes: &[u8]) -> Result<Vec<Token>, LexError> {\n"
            "        self.tokenize_impl::<ScalarScanner>(bytes)\n"
            "    }\n\n"
            "    #[inline(always)]\n"
            "    fn tokenize_impl<S: Scanner>(&mut self, bytes: &[u8]) -> Result<Vec<Token>, LexError> {\n"
            "        let mut out = Vec::new();\n"
            "        let mut pos: usize = 0;\n"
            "        let mut line: u32 = 1;\n"
            "        let mut column: u32 = 1;\n"
            "        while pos < bytes.len() {\n");
        if (g_lime_per_token_dfa_flag) {
            fprintf(out,
                "            // Per-token DFA dispatch (--per-token-dfa).\n"
                "            // No unified-DFA fallback emitted; this build\n"
                "            // assumes unambiguous-leading-byte grammar.\n"
                "            let (consumed, rid) = per_token_match::<S>(self.state, bytes, pos);\n"
                "            if consumed == 0 || rid < 0 {\n"
                "                return Err(LexError::NoMatch { offset: pos, byte: bytes[pos] });\n"
                "            }\n"
                "            let tok_line = line;\n"
                "            let tok_col = column;\n"
                "            for &b in &bytes[pos..pos + consumed] {\n"
                "                if b == b'\\n' { line += 1; column = 1; }\n"
                "                else if b != b'\\r' { column += 1; }\n"
                "            }\n"
                "            out.push(Token { rule_id: rid as u16, start: pos, len: consumed,\n"
                "                             line: tok_line, column: tok_col });\n"
                "            pos += consumed;\n"
                "        }\n"
                "        Ok(out)\n"
                "    }\n"
                "}\n\n"
                "impl Default for Lexer {\n"
                "    fn default() -> Self { Self::new() }\n"
                "}\n");
        } else {
        fprintf(out,
            "            let accept = dfa_accept_for_state(self.state);\n"
            "            let mut state: u16 = dfa_start_for_state(self.state);\n"
            "            let mut last_accept: i16 = -1;\n"
            "            let mut last_accept_pos: usize = pos;\n"
            "            let mut p = pos;\n");
        /* v0.9.3 safe-emit: drop the surrounding `unsafe { ... }`
        ** wrapper and use safe `[]` indexing inside the simd-mode
        ** tokenize_impl loop body.  The unsafe-fn boundary at
        ** tokenize_avx2 / tokenize_neon (Cat 3, #[target_feature])
        ** stays unsafe -- this only sheds the inner Cat-1 unsafe. */
        if (!g_lime_lex_safe_flag) {
            fprintf(out,
            "            unsafe {\n"
            "                while p < bytes.len() {\n"
            "                    let new_p = fast_path_for_state_g::<S>(self.state, state, bytes, p);\n"
            "                    if new_p > p {\n"
            "                        let accv = *accept.get_unchecked(state as usize);\n"
            "                        if accv >= 0 {\n"
            "                            last_accept = accv;\n"
            "                            last_accept_pos = new_p;\n"
            "                        }\n"
            "                        p = new_p;\n"
            "                        if p >= bytes.len() { break; }\n"
            "                    }\n"
            "                    let b = *bytes.get_unchecked(p);\n"
            "                    let next = dfa_step_for_state(self.state, state, b);\n"
            "                    if next < 0 { break; }\n"
            "                    state = next as u16;\n"
            "                    let accv = *accept.get_unchecked(state as usize);\n"
            "                    if accv >= 0 {\n"
            "                        last_accept = accv;\n"
            "                        last_accept_pos = p + 1;\n"
            "                    }\n"
            "                    p += 1;\n"
            "                }\n"
            "            }\n");
        } else {
            fprintf(out,
            "            while p < bytes.len() {\n"
            "                let new_p = fast_path_for_state_g::<S>(self.state, state, bytes, p);\n"
            "                if new_p > p {\n"
            "                    let accv = accept[state as usize];\n"
            "                    if accv >= 0 {\n"
            "                        last_accept = accv;\n"
            "                        last_accept_pos = new_p;\n"
            "                    }\n"
            "                    p = new_p;\n"
            "                    if p >= bytes.len() { break; }\n"
            "                }\n"
            "                let b = bytes[p];\n"
            "                let next = dfa_step_for_state(self.state, state, b);\n"
            "                if next < 0 { break; }\n"
            "                state = next as u16;\n"
            "                let accv = accept[state as usize];\n"
            "                if accv >= 0 {\n"
            "                    last_accept = accv;\n"
            "                    last_accept_pos = p + 1;\n"
            "                }\n"
            "                p += 1;\n"
            "            }\n");
        }
        fprintf(out,
            "            if last_accept < 0 {\n"
            "                return Err(LexError::NoMatch { offset: pos, byte: bytes[pos] });\n"
            "            }\n"
            "            let tok_start = pos;\n"
            "            let tok_len = last_accept_pos - pos;\n"
            "            let tok_line = line;\n"
            "            let tok_col = column;\n"
            "            for &b in &bytes[pos..last_accept_pos] {\n"
            "                if b == b\'\\n\' { line += 1; column = 1; }\n"
            "                else if b != b\'\\r\' { column += 1; }\n"
            "            }\n"
            "            out.push(Token {\n"
            "                rule_id: last_accept as u16,\n"
            "                start: tok_start,\n"
            "                len: tok_len,\n"
            "                line: tok_line,\n"
            "                column: tok_col,\n"
            "            });\n"
            "            pos = last_accept_pos;\n"
            "        }\n"
            "        Ok(out)\n"
            "    }\n"
            "}\n\n"
            "impl Default for Lexer {\n"
            "    fn default() -> Self { Self::new() }\n"
            "}\n");
        } /* end else for !per-token-dfa (simd branch) */
    } else {
        fprintf(out,
            "    pub fn tokenize(&mut self, input: &str) -> Result<Vec<Token>, LexError> {\n"
            "        let bytes = input.as_bytes();\n"
            "        let mut out = Vec::new();\n"
            "        let mut pos: usize = 0;\n"
            "        let mut line: u32 = 1;\n"
            "        let mut column: u32 = 1;\n"
            "        // v0.8.3: step_* match-based dispatch + per-state\n"
            "        // SIMD fast path.  Each iteration first calls\n"
            "        // fast_path_for_state which scans runs of self-loop\n"
            "        // bytes (string body, comment body, identifier\n"
            "        // scan).  LLVM auto-vectorises these scans to\n"
            "        // memchr-equivalent SIMD on x86 / ARM.  After the\n"
            "        // scan we fall through to the standard step\n"
            "        // dispatch which handles the byte that broke the\n"
            "        // self-loop.\n"
            "        while pos < bytes.len() {\n");
        if (g_lime_per_token_dfa_flag) {
            fprintf(out,
                "            // Per-token DFA dispatch (--per-token-dfa).\n"
                "            let (consumed, rid) = per_token_match(self.state, bytes, pos);\n"
                "            if consumed == 0 || rid < 0 {\n"
                "                return Err(LexError::NoMatch { offset: pos, byte: bytes[pos] });\n"
                "            }\n"
                "            let tok_line = line;\n"
                "            let tok_col = column;\n"
                "            for &b in &bytes[pos..pos + consumed] {\n"
                "                if b == b'\\n' { line += 1; column = 1; }\n"
                "                else if b != b'\\r' { column += 1; }\n"
                "            }\n"
                "            out.push(Token { rule_id: rid as u16, start: pos, len: consumed,\n"
                "                             line: tok_line, column: tok_col });\n"
                "            pos += consumed;\n"
                "        }\n"
                "        Ok(out)\n"
                "    }\n"
                "}\n\n"
                "impl Default for Lexer {\n"
                "    fn default() -> Self { Self::new() }\n"
                "}\n");
        } else {
        fprintf(out,
            "            let accept = dfa_accept_for_state(self.state);\n"
            "            let mut state: u16 = dfa_start_for_state(self.state);\n"
            "            let mut last_accept: i16 = -1;\n"
            "            let mut last_accept_pos: usize = pos;\n"
            "            let mut p = pos;\n");
        if (!g_lime_lex_safe_flag) {
            fprintf(out,
            "            unsafe {\n"
            "                while p < bytes.len() {\n"
            "                    // SIMD fast path: scan self-loop run.\n"
            "                    let new_p = fast_path_for_state(self.state, state, bytes, p);\n"
            "                    if new_p > p {\n"
            "                        // We advanced via self-loop scan.\n"
            "                        // For accepting states the longest\n"
            "                        // match extends to new_p.\n"
            "                        let accv = *accept.get_unchecked(state as usize);\n"
            "                        if accv >= 0 {\n"
            "                            last_accept = accv;\n"
            "                            last_accept_pos = new_p;\n"
            "                        }\n"
            "                        p = new_p;\n"
            "                        if p >= bytes.len() { break; }\n"
            "                    }\n"
            "                    let b = *bytes.get_unchecked(p);\n"
            "                    let next = dfa_step_for_state(self.state, state, b);\n"
            "                    if next < 0 { break; }\n"
            "                    state = next as u16;\n"
            "                    let accv = *accept.get_unchecked(state as usize);\n"
            "                    if accv >= 0 {\n"
            "                        last_accept = accv;\n"
            "                        last_accept_pos = p + 1;\n"
            "                    }\n"
            "                    p += 1;\n");
        } else {
            fprintf(out,
            "            while p < bytes.len() {\n"
            "                // SIMD fast path: scan self-loop run.\n"
            "                let new_p = fast_path_for_state(self.state, state, bytes, p);\n"
            "                if new_p > p {\n"
            "                    // We advanced via self-loop scan.\n"
            "                    // For accepting states the longest\n"
            "                    // match extends to new_p.\n"
            "                    let accv = accept[state as usize];\n"
            "                    if accv >= 0 {\n"
            "                        last_accept = accv;\n"
            "                        last_accept_pos = new_p;\n"
            "                    }\n"
            "                    p = new_p;\n"
            "                    if p >= bytes.len() { break; }\n"
            "                }\n"
            "                let b = bytes[p];\n"
            "                let next = dfa_step_for_state(self.state, state, b);\n"
            "                if next < 0 { break; }\n"
            "                state = next as u16;\n"
            "                let accv = accept[state as usize];\n"
            "                if accv >= 0 {\n"
            "                    last_accept = accv;\n"
            "                    last_accept_pos = p + 1;\n"
            "                }\n"
            "                p += 1;\n");
        }
        if (!g_lime_lex_safe_flag) {
            fprintf(out,
            "                }\n"
            "            }\n");
        } else {
            fprintf(out,
            "            }\n");
        }
        fprintf(out,
            "            if last_accept < 0 {\n"
            "                return Err(LexError::NoMatch { offset: pos, byte: bytes[pos] });\n"
            "            }\n"
            "            let tok_start = pos;\n"
            "            let tok_len = last_accept_pos - pos;\n"
            "            let tok_line = line;\n"
            "            let tok_col = column;\n"
            "            // Advance line/column over the matched bytes.\n"
            "            for &b in &bytes[pos..last_accept_pos] {\n"
            "                if b == b\'\\n\' { line += 1; column = 1; }\n"
            "                else if b != b\'\\r\' { column += 1; }\n"
            "            }\n"
            "            out.push(Token {\n"
            "                rule_id: last_accept as u16,\n"
            "                start: tok_start,\n"
            "                len: tok_len,\n"
            "                line: tok_line,\n"
            "                column: tok_col,\n"
            "            });\n"
            "            pos = last_accept_pos;\n"
            "        }\n"
            "        Ok(out)\n"
            "    }\n"
            "}\n\n"
            "impl Default for Lexer {\n"
            "    fn default() -> Self { Self::new() }\n"
            "}\n");
        } /* end else for !per-token-dfa (classic branch) */
    }

    /* Streaming iterator API.  Yields one Token per next() call;
    ** does not allocate a Vec.  Always uses the scalar scan path
    ** because per-token multiversion dispatch would cost more than
    ** it saves; consumers wanting SIMD use the buffered tokenize()
    ** API which dispatches once per call. */
    fprintf(out,
            "\n"
            "/// Streaming token iterator (does NOT allocate a Vec).\n"
            "/// Created via Lexer::iter().  Yields\n"
            "/// Result<Token, LexError> per next() call.  Uses the\n"
            "/// scalar scan path; for SIMD-accelerated bulk parsing\n"
            "/// of large inputs, prefer tokenize() -> Vec<Token>.\n"
            "pub struct TokenIter<'a, 'b> {\n"
            "    lexer: &'a mut Lexer,\n"
            "    bytes: &'b [u8],\n"
            "    pos: usize,\n"
            "    line: u32,\n"
            "    column: u32,\n"
            "}\n\n"
            "impl<'a, 'b> Iterator for TokenIter<'a, 'b> {\n"
            "    type Item = Result<Token, LexError>;\n"
            "    fn next(&mut self) -> Option<Self::Item> {\n"
            "        if self.pos >= self.bytes.len() { return None; }\n"
            "        let accept = dfa_accept_for_state(self.lexer.state);\n"
            "        let mut state: u16 = dfa_start_for_state(self.lexer.state);\n"
            "        let mut last_accept: i16 = -1;\n"
            "        let mut last_accept_pos: usize = self.pos;\n"
            "        let mut p = self.pos;\n");
    /* v0.9.3 safe-emit: TokenIter::next DFA loop -- drop the
    ** `unsafe { ... }` wrapper and use safe `[]` indexing.  The
    ** scalar scan path; no SIMD/target_feature concerns here. */
    if (!g_lime_lex_safe_flag) {
        fprintf(out,
            "        unsafe {\n"
            "            while p < self.bytes.len() {\n"
            "                let b = *self.bytes.get_unchecked(p);\n"
            "                let next = dfa_step_for_state(self.lexer.state, state, b);\n"
            "                if next < 0 { break; }\n"
            "                state = next as u16;\n"
            "                let accv = *accept.get_unchecked(state as usize);\n"
            "                if accv >= 0 {\n"
            "                    last_accept = accv;\n"
            "                    last_accept_pos = p + 1;\n"
            "                }\n"
            "                p += 1;\n"
            "            }\n"
            "        }\n");
    } else {
        fprintf(out,
            "        while p < self.bytes.len() {\n"
            "            let b = self.bytes[p];\n"
            "            let next = dfa_step_for_state(self.lexer.state, state, b);\n"
            "            if next < 0 { break; }\n"
            "            state = next as u16;\n"
            "            let accv = accept[state as usize];\n"
            "            if accv >= 0 {\n"
            "                last_accept = accv;\n"
            "                last_accept_pos = p + 1;\n"
            "            }\n"
            "            p += 1;\n"
            "        }\n");
    }
    fprintf(out,
            "        if last_accept < 0 {\n"
            "            let off = self.pos;\n"
            "            let byte = self.bytes[self.pos];\n"
            "            self.pos = self.bytes.len();\n"
            "            return Some(Err(LexError::NoMatch { offset: off, byte }));\n"
            "        }\n"
            "        let tok = Token {\n"
            "            rule_id: last_accept as u16,\n"
            "            start: self.pos,\n"
            "            len: last_accept_pos - self.pos,\n"
            "            line: self.line,\n"
            "            column: self.column,\n"
            "        };\n"
            "        for &b in &self.bytes[self.pos..last_accept_pos] {\n"
            "            if b == b'\\n' { self.line += 1; self.column = 1; }\n"
            "            else if b != b'\\r' { self.column += 1; }\n"
            "        }\n"
            "        self.pos = last_accept_pos;\n"
            "        Some(Ok(tok))\n"
            "    }\n"
            "}\n\n"
            "impl Lexer {\n"
            "    /// Stream tokens one at a time without allocating a Vec.\n"
            "    /// Useful when input is large or the consumer can process\n"
            "    /// tokens incrementally.  Uses the scalar scan path.\n"
            "    pub fn iter<'a, 'b>(&'a mut self, input: &'b str) -> TokenIter<'a, 'b> {\n"
            "        TokenIter {\n"
            "            lexer: self,\n"
            "            bytes: input.as_bytes(),\n"
            "            pos: 0,\n"
            "            line: 1,\n"
            "            column: 1,\n"
            "        }\n"
            "    }\n"
            "}\n");

    free(upper_prefix_str);
}

int emit_rust_lex(const LimeLexSpec *spec, const LimeLexCompiled *compiled,
                  const char *src_path, const char *out_path, char **error) {
    if (!spec || !compiled || !out_path) {
        if (error) *error = strdup("emit_rust_lex: bad arguments");
        return -1;
    }
    if (error) *error = NULL;

    FILE *out = fopen(out_path, "wb");
    if (!out) {
        if (error) {
            char buf[512];
            snprintf(buf, sizeof(buf),
                     "emit_rust_lex: can't open %s for writing", out_path);
            *error = strdup(buf);
        }
        return -1;
    }

    char *upper_prefix = upper_dup_local(eff_prefix(spec->name_prefix));
    if (!upper_prefix) { fclose(out); return -1; }

    emit_header(out, spec->name_prefix, src_path);

    emit_section(out, "Per-state DFA tables");
    for (int i = 0; i < compiled->n_states; i++) {
        emit_state_dfa(out, upper_prefix, &compiled->states[i]);
    }

    emit_rule_constants(out, upper_prefix, spec);
    emit_lexer_runtime(out, upper_prefix, compiled);

    free(upper_prefix);
    fclose(out);
    return 0;
}
