#define LBRACE                         258
#define RBRACE                         259
#define LBRACKET                       260
#define RBRACKET                       261
#define COLON                          262
#define COMMA                          263
#define STRING                         264
#define NUMBER                         265
#define TRUE                           266
#define FALSE                          267
#define NULL                           268
