#define ATOM                             1
#define VARIABLE                         2
#define UNDERSCORE                       3
#define INTEGER                          4
#define FLOAT                            5
#define STRING                           6
#define KEYWORD                          7
#define LPAREN                           8
#define RPAREN                           9
#define LBRACKET                        10
#define RBRACKET                        11
#define LBRACE                          12
#define RBRACE                          13
#define COMMA                           14
#define DOT                             15
#define PIPE                            16
#define HASH_LBRACE                     17
#define RULE_OP                         18
#define QUERY_OP                        19
#define NOT_OP                          20
#define NEQ_OP                          21
#define EQ_OP                           22
#define LT_OP                           23
#define GT_OP                           24
#define LTE_OP                          25
#define GTE_OP                          26
#define COUNT                           27
#define SUM                             28
#define MIN                             29
#define MAX                             30
#define AVG                             31
#define TRUE_K                          32
#define FALSE_K                         33
#define NIL_K                           34
