#define SLASH                            1
#define DOUBLE_SLASH                     2
#define DOT                              3
#define DOUBLE_DOT                       4
#define AT                               5
#define COMMA                            6
#define COLON_COLON                      7
#define LPAREN                           8
#define RPAREN                           9
#define LBRACKET                        10
#define RBRACKET                        11
#define PLUS                            12
#define MINUS                           13
#define STAR                            14
#define PIPE                            15
#define EQUALS                          16
#define NOT_EQUALS                      17
#define LESS_THAN                       18
#define LESS_EQUAL                      19
#define GREATER_THAN                    20
#define GREATER_EQUAL                   21
#define DOLLAR                          22
#define KW_OR                           23
#define KW_AND                          24
#define KW_DIV                          25
#define KW_MOD                          26
#define AXIS_ANCESTOR                   27
#define AXIS_ANCESTOR_OR_SELF           28
#define AXIS_ATTRIBUTE                  29
#define AXIS_CHILD                      30
#define AXIS_DESCENDANT                 31
#define AXIS_DESCENDANT_OR_SELF         32
#define AXIS_FOLLOWING                  33
#define AXIS_FOLLOWING_SIBLING          34
#define AXIS_NAMESPACE                  35
#define AXIS_PARENT                     36
#define AXIS_PRECEDING                  37
#define AXIS_PRECEDING_SIBLING          38
#define AXIS_SELF                       39
#define NODE_TYPE_COMMENT               40
#define NODE_TYPE_TEXT                  41
#define NODE_TYPE_PI                    42
#define NODE_TYPE_NODE                  43
#define LITERAL                         44
#define NUMBER                          45
#define NAME_TEST                       46
#define FUNCTION_NAME                   47
#define VARIABLE_REF                    48
#define LONE_SLASH                      49
#define UMINUS                          50
