.PHONY: doxygen man clean

doxygen:
	doxygen Doxyfile

man:
	@echo "Man pages are in ../man/"
	@echo "  lime.1          -- lime(1) command reference"
	@echo "  lime_grammar.5  -- lime grammar file format"

clean:
	rm -rf api/
