/*
** src/emit_rust_skin_chumsky.c -- chumsky-API-compatibility skin
** for the Rust output target.
**
** When `lime --target=rust:chumsky` is given (in addition to the
** standard `<stem>.rs`), this module writes a sibling
** `<stem>_chumsky.rs` that adapts lime's generated parser to a
** chumsky-flavoured public API shape.
**
** Design note: chumsky is a combinator library whose entry point is
** a `Parser` value with a `.parse(input)` method returning a
** `Result<O, Vec<Simple<I>>>` (chumsky 0.9 shape) carrying rich
** `Simple` error spans.  lime is LALR and has no combinators; the
** skin presents a single top-level parser value whose `.parse()`
** drives lime's table and returns chumsky's result shape.
**
** The skin emits a self-contained `Simple` error type (a minimal
** subset of `chumsky::error::Simple`) so the generated file compiles
** WITHOUT a chumsky dependency.
**
** Limitations (documented in docs/SKINS.md):
**
**   * Combinator composition is NOT provided; the skin is a single
**     top-level parser, not chumsky's combinator kit.
**   * `Simple` carries the offending token index + an optional
**     "expected" hint; full chumsky `Span` / label support is a
**     v1.5.0 item.
**   * Input is `&[(u16, Value)]` (token code + semantic value),
**     same convention as the nom/pest skins.
*/

#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

struct lime;
extern const char *lime_emit_rust_get_name(const struct lime *lemp);

static char *to_snake_lower(const char *s) {
    if (!s || !*s) return NULL;
    size_t n = strlen(s);
    char *out = (char *)malloc(n + 1);
    if (!out) return NULL;
    size_t j = 0;
    for (size_t i = 0; i < n; i++) {
        unsigned char c = (unsigned char)s[i];
        if (isalnum(c)) out[j++] = (char)tolower(c);
        else if (c == '_') out[j++] = '_';
    }
    out[j] = 0;
    if (j == 0) { out[0] = 'p'; out[1] = 0; }
    return out;
}

static const char *grammar_name(struct lime *lemp) {
    const char *n = lime_emit_rust_get_name(lemp);
    return (n && *n) ? n : "parser";
}

int lime_emit_rust_skin_chumsky(struct lime *lemp,
                                const char *out_path,
                                const char *bare_id) {
    if (!lemp || !out_path || !bare_id) return 1;

    FILE *f = fopen(out_path, "w");
    if (!f) { perror(out_path); return 1; }

    const char *gname = grammar_name(lemp);
    char *fn = to_snake_lower(gname);
    if (!fn) { fclose(f); return 1; }

    fprintf(f,
        "// %s -- chumsky-API-compatibility skin generated by lime.\n"
        "// Do not edit; regenerate with `lime --target=rust:chumsky`.\n"
        "//\n"
        "// Presents a chumsky-flavoured parser value:\n"
        "//\n"
        "//     %s().parse(input) -> Result<Value, Vec<Simple>>\n"
        "//\n"
        "// `Simple` mirrors a minimal subset of chumsky's error type.\n"
        "// See docs/SKINS.md.\n"
        "\n"
        "#![allow(non_snake_case)]\n"
        "#![allow(non_camel_case_types)]\n"
        "#![allow(dead_code)]\n"
        "\n"
        "use super::%s::*;\n"
        "use super::%s::%sParser as InnerParser;\n"
        "\n",
        out_path,
        fn,
        bare_id,
        bare_id, gname);

    fputs(
        "/// Minimal subset of `chumsky::error::Simple`.  Carries the\n"
        "/// index of the offending token (chumsky's span analogue) and\n"
        "/// an optional human hint.  Full Span/label support is v1.5.0.\n"
        "#[derive(Debug, Clone, PartialEq, Eq)]\n"
        "pub struct Simple {\n"
        "    /// Token index at which the parse failed.\n"
        "    pub at: usize,\n"
        "    /// True when failure was end-of-input in a non-accepting\n"
        "    /// state (chumsky's `found: None`).\n"
        "    pub eof: bool,\n"
        "}\n"
        "\n"
        "/// chumsky-shaped parser value.  Construct with the free\n"
        "/// function below; call `.parse(input)`.\n"
        "pub struct Parser;\n"
        "\n"
        "impl Parser {\n"
        "    /// Parse `input` (token-code + value pairs).  Returns the\n"
        "    /// final semantic value on accept, or a Vec of `Simple`\n"
        "    /// errors (chumsky returns all errors; lime is LALR and\n"
        "    /// stops at the first, so the Vec holds exactly one).\n"
        "    pub fn parse(&self, input: &[(u16, Value)])\n"
        "        -> Result<Value, Vec<Simple>>\n"
        "    {\n"
        "        let mut p = InnerParser::new();\n"
        "        let mut i: usize = 0;\n"
        "        while i < input.len() {\n"
        "            let (code, ref value) = input[i];\n"
        "            match p.push(code, value.clone()) {\n"
        "                Ok(true)  => return Ok(p.final_value),\n"
        "                Ok(false) => { i += 1; }\n"
        "                Err(_)    => return Err(vec![Simple { at: i, eof: false }]),\n"
        "            }\n"
        "        }\n"
        "        match p.finalize() {\n"
        "            Ok(_)  => Ok(p.final_value),\n"
        "            Err(_) => Err(vec![Simple { at: input.len(), eof: true }]),\n"
        "        }\n"
        "    }\n"
        "}\n"
        "\n",
        f);

    /* chumsky's idiom is a free function returning the parser value,
    ** e.g. `let p = calc();  p.parse(toks)`. */
    fprintf(f,
        "/// chumsky-idiom constructor: returns the top-level parser.\n"
        "pub fn %s() -> Parser { Parser }\n",
        fn);

    free(fn);
    fclose(f);
    return 0;
}
