/*
** src/emit_rust_skin_nom.c -- nom-API-compatibility skin for the
** Rust output target.
**
** When `lime --target=rust:nom` is given (in addition to the
** standard `<stem>.rs` that --target=rust already emits), this
** module writes a sibling `<stem>_nom.rs` that adapts lime's
** generated parser to a nom-flavoured public API shape.
**
** Design note: nom is a *combinator* library, not a table-driven
** one.  A faithful nom skin cannot expose per-rule combinators
** (lime has no combinators -- it has an LALR table).  What it CAN
** do, and what consumers swapping engines actually want, is a
** top-level entry point with nom's signature and result type so a
** `nom::IResult`-shaped call site keeps compiling:
**
**     fn <name>(input: &[Token]) -> IResult<&[Token], Value>
**
** where `IResult<I, O>` is nom's `Result<(I, O), nom::Err<Error<I>>>`
** and `Error<I>` mirrors nom's default `error::Error`.  On success
** the parser consumes the whole token slice and returns the trailing
** (empty) slice plus the final semantic value -- exactly nom's
** convention of returning the unconsumed remainder.
**
** The skin emits self-contained `IResult` / `Err` / `Error` /
** `ErrorKind` types (a minimal subset of nom's `error` module) so
** the generated file compiles WITHOUT a nom dependency.  Consumers
** who already depend on nom can `use nom::...` instead by deleting
** the emitted shim block; the API shapes are source-compatible.
**
** Limitations (documented in docs/SKINS.md):
**
**   * The input is a `&[Token]` slice, where `Token` is the
**     consumer-defined token type.  lime needs (code: u16, value:
**     Value) per token; the skin requires `Token: Into<(u16, Value)>`
**     via a small `LimeToken` trait the consumer implements.  This
**     keeps the skin free of assumptions about the consumer's token
**     enum (same philosophy as the lalrpop skin's quadruple).
**
**   * Streaming/incremental parsing (nom's `Incomplete`) is not
**     modelled; lime consumes the whole slice eagerly.  EOF in a
**     non-accepting state maps to `Err::Error`.
**
**   * Combinator composition (`alt`, `many0`, etc.) is NOT provided.
**     The skin is a single top-level parser, not a combinator kit.
*/

#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Forward-declare opaque struct lime (defined in lime.c).  Same
** accessor pattern as the lalrpop / bison skins. */
struct lime;
extern const char *lime_emit_rust_get_name(const struct lime *lemp);

/* "calc" -> "calc"; the nom convention is a snake_case free function
** named after the grammar, so we keep the bare name lowercased. */
static char *to_snake_lower(const char *s) {
    if (!s || !*s) return NULL;
    size_t n = strlen(s);
    char *out = (char *)malloc(n + 1);
    if (!out) return NULL;
    size_t j = 0;
    for (size_t i = 0; i < n; i++) {
        unsigned char c = (unsigned char)s[i];
        if (isalnum(c)) out[j++] = (char)tolower(c);
        else if (c == '_') out[j++] = '_';
    }
    out[j] = 0;
    if (j == 0) { out[0] = 'p'; out[1] = 0; }
    return out;
}

static const char *grammar_name(struct lime *lemp) {
    const char *n = lime_emit_rust_get_name(lemp);
    return (n && *n) ? n : "parser";
}

int lime_emit_rust_skin_nom(struct lime *lemp,
                            const char *out_path,
                            const char *bare_id) {
    if (!lemp || !out_path || !bare_id) return 1;

    FILE *f = fopen(out_path, "w");
    if (!f) { perror(out_path); return 1; }

    const char *gname = grammar_name(lemp);
    char *fn = to_snake_lower(gname);
    if (!fn) { fclose(f); return 1; }

    fprintf(f,
        "// %s -- nom-API-compatibility skin generated by lime.\n"
        "// Do not edit; regenerate with `lime --target=rust:nom`.\n"
        "//\n"
        "// Top-level parser with nom's signature + result type:\n"
        "//\n"
        "//     %s(input: &[LimeTok]) -> IResult<&[LimeTok], Value>\n"
        "//\n"
        "// `IResult<I, O>` and the `Error` / `ErrorKind` / `Err` types\n"
        "// below mirror nom's `error` module so call sites that match\n"
        "// on nom errors keep compiling.  See docs/SKINS.md.\n"
        "\n"
        "#![allow(non_snake_case)]\n"
        "#![allow(non_camel_case_types)]\n"
        "#![allow(dead_code)]\n"
        "\n"
        "use super::%s::*;\n"
        "use super::%s::%sParser as InnerParser;\n"
        "\n",
        out_path,
        fn,
        bare_id,
        bare_id, gname);

    /* nom-compatible error / result shim. */
    fputs(
        "/// A lime token as consumed by the nom skin: a terminal token\n"
        "/// code plus its semantic value.  The consumer builds a\n"
        "/// `Vec<LimeTok>` (e.g. from their lexer) and passes a slice.\n"
        "#[derive(Debug, Clone)]\n"
        "pub struct LimeTok {\n"
        "    pub code: u16,\n"
        "    pub value: Value,\n"
        "}\n"
        "\n"
        "/// Subset of `nom::error::ErrorKind` (the variants lime can\n"
        "/// actually produce).  Source-compatible with nom's enum for\n"
        "/// the common match arms.\n"
        "#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n"
        "pub enum ErrorKind {\n"
        "    /// Parser rejected the current token in this state.\n"
        "    Tag,\n"
        "    /// Input ended before the parser reached an accept state.\n"
        "    Eof,\n"
        "}\n"
        "\n"
        "/// Mirrors `nom::error::Error<I>`.\n"
        "#[derive(Debug, Clone)]\n"
        "pub struct Error<I> {\n"
        "    pub input: I,\n"
        "    pub code: ErrorKind,\n"
        "}\n"
        "\n"
        "/// Mirrors `nom::Err<E>`.  lime never produces `Incomplete`\n"
        "/// (it parses eagerly) but the variant is present so callers\n"
        "/// matching all three arms compile.\n"
        "#[derive(Debug, Clone)]\n"
        "pub enum Err<E> {\n"
        "    Incomplete(usize),\n"
        "    Error(E),\n"
        "    Failure(E),\n"
        "}\n"
        "\n"
        "/// Mirrors `nom::IResult<I, O, E>` with the default error type.\n"
        "pub type IResult<I, O> = Result<(I, O), Err<Error<I>>>;\n"
        "\n",
        f);

    /* The top-level parser function. */
    fprintf(f,
        "/// Parse `input` and return `(remainder, value)` on success,\n"
        "/// matching nom's convention of returning the unconsumed\n"
        "/// remainder of the input.  On a full parse the remainder is\n"
        "/// the empty slice.\n"
        "pub fn %s(input: &[LimeTok]) -> IResult<&[LimeTok], Value> {\n"
        "    let mut p = InnerParser::new();\n"
        "    let mut i: usize = 0;\n"
        "    while i < input.len() {\n"
        "        let tok = &input[i];\n"
        "        match p.push(tok.code, tok.value.clone()) {\n"
        "            Ok(true) => {\n"
        "                // Accepted; return the trailing remainder.\n"
        "                return Ok((&input[i + 1..], p.final_value));\n"
        "            }\n"
        "            Ok(false) => { i += 1; }\n"
        "            Err(_) => {\n"
        "                return Err(Err::Error(Error {\n"
        "                    input: &input[i..],\n"
        "                    code: ErrorKind::Tag,\n"
        "                }));\n"
        "            }\n"
        "        }\n"
        "    }\n"
        "    match p.finalize() {\n"
        "        Ok(_) => Ok((&input[input.len()..], p.final_value)),\n"
        "        Err(_) => Err(Err::Error(Error {\n"
        "            input: &input[input.len()..],\n"
        "            code: ErrorKind::Eof,\n"
        "        })),\n"
        "    }\n"
        "}\n",
        fn);

    free(fn);
    fclose(f);
    return 0;
}
