/*
** src/emit_rust.c -- Rust output target for the Lime parser
** generator.  See docs/RUST_OUTPUT.md for the design.
**
** Status: SKELETON.  This file emits enough Rust to verify the
** wiring (CLI flag -> emit dispatch -> output file -> rustc
** compiles), but the real action-table + reduce-callback codegen
** is the work of subsequent commits.
**
** Public entry point:
**
**   int emit_rust_parser(struct lime *lemp, const char *out_path,
**                        char **error);
**
** Returns 0 on success, non-zero on failure.  On failure, *error
** receives a heap-allocated diagnostic the caller free()s.
**
** The Rust output is a self-contained module: no_std-compatible
** for the const-data tables, std-compatible for the parser
** struct + Vec-backed stack.  Generated code does NOT depend on
** any Lime C runtime symbols -- it compiles standalone with
** `rustc --crate-type lib parser.rs`.
*/

#include "snapshot.h"
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Forward declaration -- struct lime is opaque to consumers but
** present in lime.c.  The full definition is in lime.c; this file
** accesses only the fields used by the emitter, all int / pointer
** types so a forward struct declaration is sufficient. */
struct lime;
struct symbol;
struct rule;

/* lime.c exposes these fields on struct lime via accessor patterns
** the C codegen already uses; we mirror that style here.  The
** emitter reads grammar metadata + action tables; it does NOT
** mutate lemp. */
extern int  lime_emit_rust_get_nstate(const struct lime *lemp);
extern int  lime_emit_rust_get_nrule(const struct lime *lemp);
extern int  lime_emit_rust_get_nterminal(const struct lime *lemp);
extern int  lime_emit_rust_get_nsymbol(const struct lime *lemp);
extern int  lime_emit_rust_get_first_token(const struct lime *lemp);
extern const char *lime_emit_rust_get_name(const struct lime *lemp);
extern struct symbol *lime_emit_rust_symbol_at(const struct lime *lemp, int i);
extern const char *lime_emit_rust_symbol_name(const struct symbol *sp);

/*
** Emit a fenced section header to keep the generated file readable
** when a human inspects it after the fact.
*/
static void emit_section(FILE *out, const char *title) {
    fprintf(out, "\n// ============================================"
                 "==========================\n");
    fprintf(out, "// %s\n", title);
    fprintf(out, "// ============================================"
                 "==========================\n\n");
}

/*
** Emit a header comment block describing what this file is and how
** it was produced.  Includes a reproducibility hint so a downstream
** consumer who finds a stray .rs file can find the .y / .lime that
** produced it.
*/
static void emit_header(FILE *out, const struct lime *lemp,
                        const char *grammar_path) {
    const char *name = lime_emit_rust_get_name(lemp);
    fprintf(out,
            "// SPDX-License-Identifier: <inherited from input grammar>\n");
    fprintf(out, "//\n");
    fprintf(out, "// Generated by lime %s -- DO NOT EDIT BY HAND.\n",
            "0.7.0+rust-skeleton");
    fprintf(out, "//\n");
    fprintf(out, "// Source grammar: %s\n",
            grammar_path ? grammar_path : "(unknown)");
    fprintf(out, "// Parser name:    %s\n", name ? name : "Parse");
    fprintf(out, "//\n");
    fprintf(out, "// To regenerate:  lime --rust %s\n",
            grammar_path ? grammar_path : "<grammar>");
    fprintf(out, "//\n");
    fprintf(out, "// This file is a SKELETON.  Subsequent commits on\n");
    fprintf(out, "// the feat/rust-output branch fill in the action-\n");
    fprintf(out, "// table emission, reduce-callback dispatch, and\n");
    fprintf(out, "// snapshot integration.\n");
    fprintf(out, "\n");
    fprintf(out, "#![allow(dead_code)]\n");
    fprintf(out, "#![allow(unused_variables)]\n");
    fprintf(out, "#![allow(non_snake_case)]\n");
    fprintf(out, "#![allow(non_upper_case_globals)]\n");
}

/*
** Emit the per-grammar token-code constants.  Mirrors the
** corresponding .h emit in the C output: each terminal symbol gets
** a `pub const TOKEN_NAME: u16 = N;`.
*/
static void emit_token_constants(FILE *out, const struct lime *lemp) {
    emit_section(out, "Token codes");
    int nterm = lime_emit_rust_get_nterminal(lemp);
    int first_token = lime_emit_rust_get_first_token(lemp);
    fprintf(out, "/// %%first_token directive value.  External token\n");
    fprintf(out, "/// codes are computed as `first_token + internal`.\n");
    fprintf(out, "pub const FIRST_TOKEN: u16 = %d;\n\n", first_token);

    for (int i = 0; i < nterm; i++) {
        struct symbol *sp = lime_emit_rust_symbol_at(lemp, i);
        if (!sp) continue;
        const char *name = lime_emit_rust_symbol_name(sp);
        if (!name || name[0] == '$') continue;
        /* External code = i + first_token.  Skip slot 0 (EOF). */
        if (i == 0) continue;
        fprintf(out, "pub const %s: u16 = %d;\n",
                name, i + first_token);
    }
    fprintf(out, "\n");
}

/*
** Emit placeholder action-table statics.  Real population is the
** work of subsequent commits; the skeleton emits empty arrays and
** marks the spots clearly so the next implementer can find them.
*/
static void emit_action_tables_placeholder(FILE *out, const struct lime *lemp) {
    emit_section(out, "Action tables (PLACEHOLDER -- subsequent "
                      "commits populate)");
    int nstate = lime_emit_rust_get_nstate(lemp);
    int nrule  = lime_emit_rust_get_nrule(lemp);

    fprintf(out, "// TODO(rust-output): populate from lemp->yy_action,\n");
    fprintf(out, "//   yy_lookahead, yy_shift_ofst, yy_reduce_ofst,\n");
    fprintf(out, "//   yy_default, yy_rule_info_lhs, yy_rule_info_nrhs.\n");
    fprintf(out, "//   See src/snapshot_build.c for the C-side\n");
    fprintf(out, "//   population pattern; the Rust emit walks the\n");
    fprintf(out, "//   same lemp fields and writes them as static\n");
    fprintf(out, "//   `&[u16]` slices.\n\n");

    fprintf(out, "pub const NSTATE:    u32 = %d;\n", nstate);
    fprintf(out, "pub const NRULE:     u32 = %d;\n", nrule);
    fprintf(out, "pub const NTERMINAL: u32 = %d;\n",
            lime_emit_rust_get_nterminal(lemp));
    fprintf(out, "pub const NSYMBOL:   u32 = %d;\n\n",
            lime_emit_rust_get_nsymbol(lemp));

    fprintf(out, "pub static YY_ACTION:    &[u16] = &[];  // TODO\n");
    fprintf(out, "pub static YY_LOOKAHEAD: &[u16] = &[];  // TODO\n");
    fprintf(out, "pub static YY_SHIFT_OFST: &[i32] = &[];  // TODO\n");
    fprintf(out, "pub static YY_REDUCE_OFST: &[i32] = &[];  // TODO\n");
    fprintf(out, "pub static YY_DEFAULT:   &[u16] = &[];  // TODO\n");
    fprintf(out, "pub static YY_RULE_LHS:  &[i16] = &[];  // TODO\n");
    fprintf(out, "pub static YY_RULE_NRHS: &[i8]  = &[];  // TODO\n\n");
}

/*
** Emit the public Parser struct + its impl block with a minimal
** API: new / push_token / finalize.  Real implementation is the
** work of subsequent commits; the skeleton returns Err with a
** "not yet implemented" message so callers learn quickly that
** this branch is in-progress.
*/
static void emit_parser_struct(FILE *out, const struct lime *lemp) {
    const char *name = lime_emit_rust_get_name(lemp);
    if (!name) name = "Parse";

    emit_section(out, "Parser API");
    fprintf(out,
            "/// Errors returned by the parser.\n"
            "#[derive(Debug, Clone, PartialEq, Eq)]\n"
            "pub enum ParseError {\n"
            "    /// The token did not match any shift action at the\n"
            "    /// current state.\n"
            "    SyntaxError { token: u16, state: u16 },\n"
            "    /// External token code was outside the\n"
            "    /// `[FIRST_TOKEN, FIRST_TOKEN + NTERMINAL)` range.\n"
            "    OutOfRange { token: u16 },\n"
            "    /// The parser has not yet been implemented for\n"
            "    /// this grammar (skeleton emit).\n"
            "    NotYetImplemented,\n"
            "}\n\n");

    fprintf(out,
            "/// Output of a successful parse.  Real grammars\n"
            "/// substitute their %%type expr {{...}} concrete type\n"
            "/// here once subsequent commits wire the type-table\n"
            "/// translation.\n"
            "pub struct Output;\n\n");

    fprintf(out, "/// %s parser.\n", name);
    fprintf(out, "pub struct %sParser {\n", name);
    fprintf(out, "    state_stack: Vec<u16>,\n");
    fprintf(out, "}\n\n");

    fprintf(out, "impl %sParser {\n", name);
    fprintf(out, "    /// Construct a fresh parser at state 0.\n");
    fprintf(out, "    pub fn new() -> Self {\n");
    fprintf(out, "        Self { state_stack: vec![0] }\n");
    fprintf(out, "    }\n\n");

    fprintf(out, "    /// Feed an external token code.\n");
    fprintf(out, "    /// Returns Ok(()) when the token was\n");
    fprintf(out, "    /// accepted into a state, Err otherwise.\n");
    fprintf(out, "    /// SKELETON: always returns NotYetImplemented.\n");
    fprintf(out, "    pub fn push(&mut self, _token: u16) -> Result<(), ParseError> {\n");
    fprintf(out, "        Err(ParseError::NotYetImplemented)\n");
    fprintf(out, "    }\n\n");

    fprintf(out, "    /// Finalize and produce the parse output.\n");
    fprintf(out, "    /// SKELETON: always returns NotYetImplemented.\n");
    fprintf(out, "    pub fn finalize(self) -> Result<Output, ParseError> {\n");
    fprintf(out, "        Err(ParseError::NotYetImplemented)\n");
    fprintf(out, "    }\n");
    fprintf(out, "}\n\n");

    fprintf(out, "impl Default for %sParser {\n", name);
    fprintf(out, "    fn default() -> Self { Self::new() }\n");
    fprintf(out, "}\n");
}

int emit_rust_parser(struct lime *lemp, const char *out_path,
                     const char *grammar_path, char **error) {
    if (lemp == NULL || out_path == NULL) {
        if (error) *error = strdup("emit_rust_parser: bad arguments");
        return -1;
    }
    if (error) *error = NULL;

    FILE *out = fopen(out_path, "wb");
    if (out == NULL) {
        if (error) {
            char buf[512];
            snprintf(buf, sizeof(buf),
                     "emit_rust_parser: can't open %s for writing", out_path);
            *error = strdup(buf);
        }
        return -1;
    }

    emit_header(out, lemp, grammar_path);
    emit_token_constants(out, lemp);
    emit_action_tables_placeholder(out, lemp);
    emit_parser_struct(out, lemp);

    fclose(out);
    return 0;
}
