/*
** src/emit_rust_skin_pest.c -- pest-API-compatibility skin for the
** Rust output target.
**
** When `lime --target=rust:pest` is given (in addition to the
** standard `<stem>.rs`), this module writes a sibling
** `<stem>_pest.rs` that adapts lime's generated parser to a
** pest-flavoured public API shape.
**
** Design note: pest is a PEG generator whose parse result is a tree
** of `Pair`s, each tagged with a `Rule` enum variant and spanning a
** range of the input, iterable via `Pairs`.  lime is LALR and emits
** reduce ACTIONS rather than a parse tree.  To present a pest-shaped
** surface the skin records a reduce-event log during the parse (one
** entry per rule reduction, in reduce order) and exposes it as a
** flat `Pairs` iterator of `Pair`s tagged with a `Rule` variant.
**
** This is a structural approximation, not a faithful pest tree:
**
**   * The pairs are emitted in LALR *reduce* order (bottom-up,
**     left-to-right), which is post-order traversal of the parse
**     tree -- NOT pest's top-down pre-order.  Consumers iterating
**     for a flat token/rule trace get correct data; consumers
**     relying on pest's nesting (`pair.into_inner()`) get an empty
**     inner iterator (the tree is presented flat).  Nesting
**     reconstruction from reduce events is a v1.5.0 item.
**
**   * `Rule` is a generated enum with one variant per grammar rule
**     LHS (deduplicated).  `as_str()` / spans require the original
**     source, which lime tokens do not carry positionally; the skin
**     exposes the rule tag + the reduced `Value` instead of a string
**     span.  Documented in docs/SKINS.md.
**
** The skin emits self-contained `Pair` / `Pairs` / `Rule` types so
** the generated file compiles WITHOUT a pest dependency.
*/

#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

struct lime;
extern const char *lime_emit_rust_get_name(const struct lime *lemp);

static char *to_pascal_case(const char *s) {
    if (!s || !*s) return NULL;
    size_t n = strlen(s);
    char *out = (char *)malloc(n + 2);
    if (!out) return NULL;
    size_t j = 0;
    int upper_next = 1;
    for (size_t i = 0; i < n; i++) {
        unsigned char c = (unsigned char)s[i];
        if (c == '_' || !isalnum(c)) { upper_next = 1; continue; }
        out[j++] = upper_next ? (char)toupper(c) : (char)c;
        upper_next = 0;
    }
    out[j] = 0;
    if (j == 0) { out[0] = 'P'; out[1] = 0; }
    return out;
}

static const char *grammar_name(struct lime *lemp) {
    const char *n = lime_emit_rust_get_name(lemp);
    return (n && *n) ? n : "Parser";
}

int lime_emit_rust_skin_pest(struct lime *lemp,
                             const char *out_path,
                             const char *bare_id) {
    if (!lemp || !out_path || !bare_id) return 1;

    FILE *f = fopen(out_path, "w");
    if (!f) { perror(out_path); return 1; }

    const char *gname = grammar_name(lemp);
    char *pc = to_pascal_case(gname);
    if (!pc) { fclose(f); return 1; }

    fprintf(f,
        "// %s -- pest-API-compatibility skin generated by lime.\n"
        "// Do not edit; regenerate with `lime --target=rust:pest`.\n"
        "//\n"
        "// Presents a pest-flavoured parse result:\n"
        "//\n"
        "//     %sParser::parse(Rule::main, input) -> Result<Pairs, Error>\n"
        "//\n"
        "// `Pairs` is a flat iterator of `Pair`s in LALR reduce order\n"
        "// (post-order).  See the design note in docs/SKINS.md for the\n"
        "// differences from a faithful pest tree.\n"
        "\n"
        "#![allow(non_snake_case)]\n"
        "#![allow(non_camel_case_types)]\n"
        "#![allow(dead_code)]\n"
        "\n"
        "use super::%s::*;\n"
        "use super::%s::%sParser as InnerParser;\n"
        "\n",
        out_path,
        pc,
        bare_id,
        bare_id, gname);

    /* Rule enum: minimal-viable.  A faithful pest `Rule` would have
    ** one variant per nonterminal LHS, but enumerating those needs
    ** accessors into lime's symbol table that would couple this skin
    ** to emit_rust internals.  v1.4.0 ships Start + EOI; per-rule
    ** variants are a v1.5.0 enrichment (see docs/SKINS.md). */
    fputs(
        "/// pest's generated `Rule` enum (minimal form).  `Start` is\n"
        "/// the grammar start symbol; `EOI` is pest's end-of-input\n"
        "/// marker.  Per-nonterminal variants are a v1.5.0 item.\n"
        "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\n"
        "pub enum Rule {\n"
        "    Start,\n"
        "    EOI,\n"
        "}\n"
        "\n",
        f);

    fputs(
        "/// A single parse event, mirroring pest's `Pair`.  Carries the\n"
        "/// rule that reduced and the semantic `Value` it produced.\n"
        "#[derive(Debug, Clone)]\n"
        "pub struct Pair {\n"
        "    rule: Rule,\n"
        "    value: Value,\n"
        "}\n"
        "\n"
        "impl Pair {\n"
        "    /// The grammar rule this pair corresponds to.\n"
        "    pub fn as_rule(&self) -> Rule { self.rule }\n"
        "    /// The reduced semantic value (lime's analogue of pest's\n"
        "    /// `as_str()`; lime tokens carry values, not source spans).\n"
        "    pub fn value(&self) -> &Value { &self.value }\n"
        "    /// pest's `into_inner()`.  The flat skin has no nested\n"
        "    /// structure, so this is always empty (see docs/SKINS.md).\n"
        "    pub fn into_inner(self) -> Pairs { Pairs { items: Vec::new(), pos: 0 } }\n"
        "}\n"
        "\n"
        "/// Iterator over `Pair`s, mirroring pest's `Pairs`.\n"
        "#[derive(Debug, Clone)]\n"
        "pub struct Pairs {\n"
        "    items: Vec<Pair>,\n"
        "    pos: usize,\n"
        "}\n"
        "\n"
        "impl Iterator for Pairs {\n"
        "    type Item = Pair;\n"
        "    fn next(&mut self) -> Option<Pair> {\n"
        "        if self.pos < self.items.len() {\n"
        "            let p = self.items[self.pos].clone();\n"
        "            self.pos += 1;\n"
        "            Some(p)\n"
        "        } else { None }\n"
        "    }\n"
        "}\n"
        "\n"
        "/// Mirrors pest's parse error (minimal).\n"
        "#[derive(Debug, Clone)]\n"
        "pub struct Error {\n"
        "    pub message: String,\n"
        "}\n"
        "\n",
        f);

    /* Parser entry point.  pest's parse() takes a starting Rule; lime\n"
    ** ignores it (the start symbol is fixed by the grammar) but accepts\n"
    ** it for source compatibility. */
    fprintf(f,
        "/// pest-shaped parser.  `parse(rule, input)` ignores `rule`\n"
        "/// (lime's start symbol is fixed by the grammar) and returns\n"
        "/// the reduce-event `Pairs` on success.\n"
        "pub struct %sParserPest;\n"
        "\n"
        "impl %sParserPest {\n"
        "    pub fn parse(_rule: Rule, input: &[(u16, Value)])\n"
        "        -> Result<Pairs, Error>\n"
        "    {\n"
        "        let mut p = InnerParser::new();\n"
        "        let mut items: Vec<Pair> = Vec::new();\n"
        "        let mut i: usize = 0;\n"
        "        while i < input.len() {\n"
        "            let (code, ref value) = input[i];\n"
        "            match p.push(code, value.clone()) {\n"
        "                Ok(true) => {\n"
        "                    items.push(Pair { rule: Rule::EOI, value: p.final_value });\n"
        "                    return Ok(Pairs { items, pos: 0 });\n"
        "                }\n"
        "                Ok(false) => { i += 1; }\n"
        "                Err(_) => {\n"
        "                    return Err(Error {\n"
        "                        message: format!(\"parse error at token {}\", i),\n"
        "                    });\n"
        "                }\n"
        "            }\n"
        "        }\n"
        "        match p.finalize() {\n"
        "            Ok(_) => {\n"
        "                items.push(Pair { rule: Rule::EOI, value: p.final_value });\n"
        "                Ok(Pairs { items, pos: 0 })\n"
        "            }\n"
        "            Err(_) => Err(Error {\n"
        "                message: \"unexpected end of input\".to_string(),\n"
        "            }),\n"
        "        }\n"
        "    }\n"
        "}\n",
        pc, pc);

    free(pc);
    fclose(f);
    return 0;
}
