/*
** src/emit_rust_skin_lalrpop.c -- lalrpop-API-compatibility skin
** for the Rust output target.
**
** When `lime --target=rust:lalrpop` is given (in addition to the
** standard `<stem>.rs` that --target=rust already emits), this
** module writes a sibling `<stem>_lalrpop.rs` that adapts lime's
** generated parser to lalrpop's public API shape:
**
**   - <PascalName>Parser     wrapper struct (matches lalrpop's typical
**                            `<RuleName>Parser` naming convention)
**   - <PascalName>Parser::new()
**   - <PascalName>Parser::parse(input)  generic over IntoIterator yielding
**                                       (usize, u16, usize, Value)
**   - ParseError<L, T, E> enum mirroring lalrpop_util::ParseError's
**     four variants
**
** Limitations (documented in docs/SKINS.md):
**
**   * The lalrpop-style strongly-typed Token enum is NOT emitted by
**     this skin.  lime represents tokens as u16 codes plus a Value
**     enum holding semantic payloads.  Consumers map their Token
**     enum onto (code, Value) pairs at the iterator boundary.
**
**   * `expected: Vec<String>` is always empty in v1.3.0.  The
**     skin cannot peek the inner parser's current state without
**     a getter that lime does not yet emit; adding that getter is
**     a v1.4.0 task tracked in open-items.md.  Consumers that
**     need expected-token enrichment can import the standard
**     `expected_tokens_in_state(state)` from the sibling module
**     directly.
**
**   * The User error variant of ParseError is exposed but lime
**     never produces it; consumers building their own user-error
**     path construct ParseError::User { error } at the call site.
**
** This is the third Rust skin (after --target=rust:logos for the
** lex side and --target=rust for the standard parser).  It is
** marked experimental in v1.3.0 -- the surface is stable for the
** documented use case but the cross-cutting Spanned<Token> bridge
** is left to the consumer.
*/

#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Forward-declare opaque struct lime (defined in lime.c).  Same
** pattern as src/emit_c_skin_bison.c: skins do not depend on the
** internal layout, only on a pair of accessors. */
struct lime;
extern const char *lime_emit_rust_get_name(const struct lime *lemp);

/* Convert a lowercase / snake_case grammar name to PascalCase.
** "calc" -> "Calc"; "expr_lang" -> "ExprLang".  Caller frees. */
static char *to_pascal_case(const char *s) {
    if (!s || !*s) return NULL;
    size_t n = strlen(s);
    char *out = (char *)malloc(n + 2);
    if (!out) return NULL;
    size_t j = 0;
    int upper_next = 1;
    for (size_t i = 0; i < n; i++) {
        unsigned char c = (unsigned char)s[i];
        if (c == '_' || !isalnum(c)) {
            upper_next = 1;
            continue;
        }
        out[j++] = upper_next ? (char)toupper(c) : (char)c;
        upper_next = 0;
    }
    out[j] = 0;
    if (j == 0) { out[0] = 'P'; out[1] = 0; }
    return out;
}

static const char *grammar_name(struct lime *lemp) {
    const char *n = lime_emit_rust_get_name(lemp);
    return (n && *n) ? n : "Parser";
}

int lime_emit_rust_skin_lalrpop(struct lime *lemp,
                                const char *out_path,
                                const char *bare_id) {
    if (!lemp || !out_path || !bare_id) return 1;

    FILE *f = fopen(out_path, "w");
    if (!f) {
        perror(out_path);
        return 1;
    }

    const char *gname = grammar_name(lemp);
    char *pc = to_pascal_case(gname);
    if (!pc) { fclose(f); return 1; }

    /* File header + imports. */
    fprintf(f,
        "// %s -- lalrpop-API-compatibility skin generated by lime.\n"
        "// Do not edit; regenerate with `lime --target=rust:lalrpop`.\n"
        "//\n"
        "// Wraps the sibling `%s` module's parser in a shape that\n"
        "// mimics lalrpop's `<Name>Parser` API:\n"
        "//\n"
        "//     %sParser::new().parse(tokens)\n"
        "//         -> Result<Value, ParseError<usize, u16, ()>>\n"
        "//\n"
        "// `tokens` is any IntoIterator yielding (start, code, end,\n"
        "// value) quadruples.  See docs/SKINS.md for details.\n"
        "\n"
        "#![allow(non_snake_case)]\n"
        "#![allow(non_camel_case_types)]\n"
        "#![allow(dead_code)]\n"
        "#![allow(clippy::needless_lifetimes)]\n"
        "\n"
        "use super::%s::*;\n"
        "use super::%s::%sParser as InnerParser;\n"
        "\n",
        out_path,         /* path comment */
        bare_id,          /* sibling module reference in comment */
        pc,               /* api shape comment */
        bare_id,          /* use super::<bare>::* */
        bare_id, gname);  /* use super::<bare>::<gname>Parser as InnerParser */

    /* ParseError. */
    fputs(
        "/// Mirrors `lalrpop_util::ParseError<L, T, E>`.  Existing\n"
        "/// match-on-ParseError code in lalrpop-using callers keeps\n"
        "/// compiling against this enum verbatim.  Variants:\n"
        "///\n"
        "/// - `InvalidToken { location }`     :: lexer-side rejection\n"
        "///                                       (caller-constructed).\n"
        "/// - `UnrecognizedEof { ... }`       :: parser hit EOF in a\n"
        "///                                       non-accepting state.\n"
        "/// - `UnrecognizedToken { ... }`     :: parser saw a token\n"
        "///                                       that is not legal\n"
        "///                                       in the current state.\n"
        "/// - `ExtraToken { ... }`            :: lalrpop variant; lime\n"
        "///                                       maps this onto\n"
        "///                                       UnrecognizedToken.\n"
        "/// - `User { error }`                :: caller-supplied error.\n"
        "#[derive(Debug, Clone)]\n"
        "pub enum ParseError<L, T, E> {\n"
        "    InvalidToken      { location: L },\n"
        "    UnrecognizedEof   { location: L, expected: Vec<String> },\n"
        "    UnrecognizedToken { token: (L, T, L), expected: Vec<String> },\n"
        "    ExtraToken        { token: (L, T, L) },\n"
        "    User              { error: E },\n"
        "}\n"
        "\n",
        f);

    /* The wrapper parser. */
    fprintf(f,
        "/// `%sParser` -- lalrpop-shaped wrapper around `%sParser`.\n"
        "/// Owns no state itself; each `parse()` constructs a fresh\n"
        "/// inner parser, so a single instance can drive many\n"
        "/// independent parses.\n"
        "pub struct %sParser;\n"
        "\n"
        "impl %sParser {\n"
        "    /// Construct a new parser-factory.  Cheap; no allocation.\n"
        "    pub fn new() -> Self { %sParser }\n"
        "\n"
        "    /// Parse `input` and return the final semantic value.\n"
        "    ///\n"
        "    /// `input` yields `(start, code, end, value)` quadruples:\n"
        "    /// `start` and `end` are byte offsets; `code` is a TK_*\n"
        "    /// constant from the inner module; `value` is the inner\n"
        "    /// `Value` enum holding the semantic payload.\n"
        "    ///\n"
        "    /// On accept, returns `Ok(parser.final_value)`.  On error,\n"
        "    /// returns `Err(ParseError<usize, u16, ()>)`.\n"
        "    pub fn parse<I>(&self, input: I)\n"
        "        -> Result<Value, ParseError<usize, u16, ()>>\n"
        "    where\n"
        "        I: IntoIterator<Item = (usize, u16, usize, Value)>,\n"
        "    {\n"
        "        let mut p = InnerParser::new();\n"
        "        let mut last_end: usize = 0;\n"
        "        for (start, code, end, value) in input {\n"
        "            last_end = end;\n"
        "            match p.push(code, value) {\n"
        "                Ok(true)  => return Ok(p.final_value),\n"
        "                Ok(false) => continue,\n"
        "                Err(_)    => {\n"
        "                    return Err(ParseError::UnrecognizedToken {\n"
        "                        token: (start, code, end),\n"
        "                        expected: expected_at(&p),\n"
        "                    });\n"
        "                }\n"
        "            }\n"
        "        }\n"
        "        match p.finalize() {\n"
        "            Ok(_)  => Ok(p.final_value),\n"
        "            Err(_) => Err(ParseError::UnrecognizedEof {\n"
        "                location: last_end,\n"
        "                expected: expected_at(&p),\n"
        "            }),\n"
        "        }\n"
        "    }\n"
        "}\n"
        "\n"
        "impl Default for %sParser {\n"
        "    fn default() -> Self { Self::new() }\n"
        "}\n"
        "\n"
        "/// Compute the set of token names that would be accepted in the\n"
        "/// inner parser's current state, for the `expected` field of\n"
        "/// `ParseError`.  Uses the standard introspection API\n"
        "/// (`current_state` + `expected_tokens_in_state` + `token_name`,\n"
        "/// emitted when token-names are enabled, which is the default).\n"
        "fn expected_at(p: &InnerParser) -> Vec<String> {\n"
        "    expected_tokens_in_state(p.current_state())\n"
        "        .into_iter()\n"
        "        .filter_map(|c| token_name(c).map(|s| s.to_string()))\n"
        "        .collect()\n"
        "}\n"
        "\n"
        "/// Strongly-typed token wrapper (lalrpop's `Spanned<Token>`\n"
        "/// analogue).  Provided so consumers can build a typed token\n"
        "/// stream and `.into()` it to the `(start, code, end, value)`\n"
        "/// quadruple `parse()` consumes.  The tuple form keeps working\n"
        "/// (LTS compat); this struct is the forward-compatible shape\n"
        "/// for when extra fields (source-id, etc.) are needed.\n"
        "#[derive(Debug, Clone)]\n"
        "pub struct Token {\n"
        "    pub start: usize,\n"
        "    pub code: u16,\n"
        "    pub end: usize,\n"
        "    pub value: Value,\n"
        "}\n"
        "\n"
        "impl From<Token> for (usize, u16, usize, Value) {\n"
        "    fn from(t: Token) -> Self { (t.start, t.code, t.end, t.value) }\n"
        "}\n"
        "\n"
        "impl From<(usize, u16, usize, Value)> for Token {\n"
        "    fn from(q: (usize, u16, usize, Value)) -> Self {\n"
        "        Token { start: q.0, code: q.1, end: q.2, value: q.3 }\n"
        "    }\n"
        "}\n",
        pc, gname,    /* doc comment header */
        pc,           /* pub struct */
        pc,           /* impl */
        pc,           /* new() body */
        pc);          /* impl Default */

    free(pc);
    fclose(f);
    return 0;
}
