/*
** Snapshot system core implementation.
**
** Provides atomic reference-counted snapshots of parser tables so that
** multiple reader threads can safely share a snapshot while a writer
** thread prepares a new one.
*/
#include "snapshot.h"
#include "parser.h"
#include "jit_context.h"

#include <stdlib.h>
#include <string.h>

/* ------------------------------------------------------------------ */
/*  Internal helpers                                                    */
/* ------------------------------------------------------------------ */

/*
** Free all memory owned by *snap* and then free the snapshot struct
** itself.  This is called only when the reference count reaches zero,
** so no synchronisation is needed here.
*/
static void destroy_snapshot(ParserSnapshot *snap) {
    if (snap == NULL) return;

    /*
    ** The symbols, rules, and states arrays are deep copies owned by
    ** this snapshot.  For now we only free the top-level arrays because
    ** the individual structs are allocated as part of the deep-copy in
    ** create_base_snapshot() (not yet implemented).  When that lands,
    ** the per-element cleanup will be added here as well.
    */
    free(snap->symbols);
    free(snap->rules);
    free(snap->states);

    /* Action tables */
    free(snap->yy_action);
    free(snap->yy_lookahead);
    free(snap->yy_shift_ofst);
    free(snap->yy_reduce_ofst);
    free(snap->yy_default);

    /* JIT context (if any). */
    jit_detach_from_snapshot(snap);

    free(snap);
}

/* ------------------------------------------------------------------ */
/*  Public API                                                         */
/* ------------------------------------------------------------------ */

/*
** Atomically increment the reference count and return *snap* for
** convenience.  Passing NULL is a no-op that returns NULL.
*/
ParserSnapshot *snapshot_acquire(ParserSnapshot *snap) {
    if (snap == NULL) return NULL;
    atomic_fetch_add_explicit(&snap->refcount, 1, memory_order_relaxed);
    return snap;
}

/*
** Atomically decrement the reference count.  If it reaches zero the
** snapshot is destroyed.  Passing NULL is a safe no-op.
**
** The release uses acquire-release ordering: the decrement itself is
** release so that all prior reads/writes in this thread are visible
** before another thread might observe the zero count, and the final
** destroy path uses an acquire fence so that it sees all writes made
** by other threads that previously released their references.
*/
void snapshot_release(ParserSnapshot *snap) {
    if (snap == NULL) return;

    uint_fast32_t prev = atomic_fetch_sub_explicit(
        &snap->refcount, 1, memory_order_release);

    if (prev == 1) {
        /* We were the last holder.  Ensure all prior writes from other
        ** releasers are visible before we read any snapshot data in
        ** destroy_snapshot(). */
        atomic_thread_fence(memory_order_acquire);
        destroy_snapshot(snap);
    }
}

/*
** Stub: create a base snapshot from a grammar file.
**
** Full implementation is generated by Lemon with the -n flag and lives
** in the grammar's *_snapshot.c file.  This weak default is used when
** no generated snapshot file is linked, so the library can still be
** built standalone.
*/
__attribute__((weak))
ParserSnapshot *create_base_snapshot(const char *grammar_file, char **error) {
    (void)grammar_file;  /* unused for now */

    if (error != NULL) {
        const char msg[] =
            "create_base_snapshot: not yet implemented "
            "(requires Lemon dynamic-table support)";
        char *buf = malloc(sizeof(msg));
        if (buf != NULL) {
            memcpy(buf, msg, sizeof(msg));
        }
        *error = buf;
    }
    return NULL;
}

/* ------------------------------------------------------------------ */
/*  Public lemon_snapshot_* wrappers (declared in parser.h)            */
/* ------------------------------------------------------------------ */

ParserSnapshot *lemon_snapshot_acquire(ParserSnapshot *snap) {
    return snapshot_acquire(snap);
}

void lemon_snapshot_release(ParserSnapshot *snap) {
    snapshot_release(snap);
}

ParserSnapshot *lemon_snapshot_create(const char *grammar_file, char **error) {
    return create_base_snapshot(grammar_file, error);
}
