#define SLASH                            1
#define DOUBLE_SLASH                     2
#define DOT                              3
#define DOUBLE_DOT                       4
#define AT                               5
#define COMMA                            6
#define COLON_COLON                      7
#define LPAREN                           8
#define RPAREN                           9
#define LBRACKET                        10
#define RBRACKET                        11
#define PLUS                            12
#define MINUS                           13
#define STAR                            14
#define PIPE                            15
#define EQUALS                          16
#define NOT_EQUALS                      17
#define LESS_THAN                       18
#define LESS_EQUAL                      19
#define GREATER_THAN                    20
#define GREATER_EQUAL                   21
#define SEMICOLON                       22
#define LBRACE                          23
#define RBRACE                          24
#define ASSIGN                          25
#define CONCAT_OP                       26
#define NODE_PRECEDES                   27
#define NODE_FOLLOWS                    28
#define KW_OR                           29
#define KW_AND                          30
#define KW_DIV                          31
#define KW_MOD                          32
#define KW_EQ                           33
#define KW_NE                           34
#define KW_LT                           35
#define KW_LE                           36
#define KW_GT                           37
#define KW_GE                           38
#define KW_FOR                          39
#define KW_LET                          40
#define KW_WHERE                        41
#define KW_ORDER                        42
#define KW_BY                           43
#define KW_RETURN                       44
#define KW_IN                           45
#define KW_AT_WORD                      46
#define KW_IF                           47
#define KW_THEN                         48
#define KW_ELSE                         49
#define KW_SOME                         50
#define KW_EVERY                        51
#define KW_SATISFIES                    52
#define KW_IS                           53
#define KW_TO                           54
#define KW_UNION                        55
#define KW_INTERSECT                    56
#define KW_EXCEPT                       57
#define KW_INSTANCE                     58
#define KW_OF                           59
#define KW_TREAT                        60
#define KW_AS                           61
#define KW_CASTABLE                     62
#define KW_CAST                         63
#define KW_IDIV                         64
#define KW_DECLARE                      65
#define KW_FUNCTION                     66
#define KW_VARIABLE                     67
#define KW_NAMESPACE                    68
#define KW_DEFAULT                      69
#define KW_ELEMENT                      70
#define KW_IMPORT                       71
#define KW_MODULE                       72
#define KW_STABLE                       73
#define KW_ATTRIBUTE                    74
#define KW_DOCUMENT                     75
#define KW_TEXT                         76
#define KW_COMMENT                      77
#define KW_PI                           78
#define KW_ASCENDING                    79
#define KW_DESCENDING                   80
#define KW_TYPESWITCH                   81
#define KW_CASE                         82
#define AXIS_ANCESTOR                   83
#define AXIS_ANCESTOR_OR_SELF           84
#define AXIS_ATTRIBUTE                  85
#define AXIS_CHILD                      86
#define AXIS_DESCENDANT                 87
#define AXIS_DESCENDANT_OR_SELF         88
#define AXIS_FOLLOWING                  89
#define AXIS_FOLLOWING_SIBLING          90
#define AXIS_NAMESPACE                  91
#define AXIS_PARENT                     92
#define AXIS_PRECEDING                  93
#define AXIS_PRECEDING_SIBLING          94
#define AXIS_SELF                       95
#define NODE_TYPE_COMMENT               96
#define NODE_TYPE_TEXT                  97
#define NODE_TYPE_PI                    98
#define NODE_TYPE_NODE                  99
#define LITERAL                        100
#define NUMBER                         101
#define NAME_TEST                      102
#define FUNCTION_NAME                  103
#define VARIABLE_REF                   104
#define LONE_SLASH                     105
#define UMINUS                         106
